---
permalink: sg6000/accessing-and-configuring-santricity-system-manager.html
sidebar: sidebar
keywords: storagegrid, sg6000, storage node, storage appliance, SANtricity System Manager, SANtricity, System Manager, configure, configuring, setup, set up, setting up, access, accessing, E-Series AutoSupport, autosupport 
summary: 'You can use SANtricity System Manager to monitor the status of the storage controllers, storage disks, and other hardware components in the storage controller shelf. You can also configure a proxy for E-Series AutoSupport that enables you to send AutoSupport messages from the appliance without the use of the management port.'
---
= Accessing and Configuring SANtricity System Manager
:icons: font
:imagesdir: ../media/

[.lead]
You can use SANtricity System Manager to monitor the status of the storage controllers, storage disks, and other hardware components in the storage controller shelf. You can also configure a proxy for E-Series AutoSupport that enables you to send AutoSupport messages from the appliance without the use of the management port.

.Steps

* xref:setting-up-and-accessing-santricity-system-manager.adoc[Setting up and Accessing SANtricity System Manager]
* xref:reviewing-hardware-status-in-santricity-system-manager.adoc[Reviewing the hardware status in SANtricity System Manager]
* xref:setting-ip-addresses-for-storage-controllers-using-storagegrid-appliance-installer.adoc[Setting the IP addresses for the storage controllers using the StorageGRID Appliance Installer]
