---
permalink: sg6000/accessing_and_configuring_santricity_system_manager.html
sidebar: sidebar
keywords:
summary: 'You can use SANtricity System Manager to monitor the status of the storage controllers, storage disks, and other hardware components in the storage controller shelf. You can also configure a proxy for E-Series AutoSupport that enables you to send AutoSupport messages from the appliance without the use of the management port.'
---
= Accessing and Configuring SANtricity System Manager
:icons: font
:imagesdir: ../media/

[.lead]
You can use SANtricity System Manager to monitor the status of the storage controllers, storage disks, and other hardware components in the storage controller shelf. You can also configure a proxy for E-Series AutoSupport that enables you to send AutoSupport messages from the appliance without the use of the management port.

.Steps

* xref:setting_up_and_accessing_santricity_system_manager.adoc[Setting up and Accessing SANtricity System Manager]
* xref:reviewing_hardware_status_in_santricity_system_manager.adoc[Reviewing the hardware status in SANtricity System Manager]
* xref:setting_ip_addresses_for_storage_controllers_using_storagegrid_appliance_installer.adoc[Setting the IP addresses for the storage controllers using the StorageGRID Appliance Installer]
