---
permalink: sg6000/automating-configuration-of-storagegrid.html
sidebar: sidebar
keywords: storagegrid, sg6000, storage node, storage appliance, automate, automating, automation, automatic, configuration, configure
summary: 'After deploying the grid nodes, you can automate the configuration of the StorageGRID system.'
---
= Automating the configuration of StorageGRID
:icons: font
:imagesdir: ../media/

[.lead]
After deploying the grid nodes, you can automate the configuration of the StorageGRID system.

.What you'll need

* You know the location of the following files from the installation archive.
+
[options="header"]
|===
| Filename| Description
a|
`configure-storagegrid.py`
a|
Python script used to automate the configuration
a|
`configure-storagegrid.sample.json`
a|
Sample configuration file for use with the script
a|
`configure-storagegrid.blank.json`
a|
Blank configuration file for use with the script
|===

* You have created a `configure-storagegrid.json` configuration file. To create this file, you can modify the sample configuration file (`configure-storagegrid.sample.json`) or the blank configuration file (`configure-storagegrid.blank.json`).

.About this task

You can use the `configure-storagegrid.py` Python script and the `configure-storagegrid.json` configuration file to automate the configuration of your StorageGRID system.

NOTE: You can also configure the system using the Grid Manager or the Installation API.

.Steps

. Log in to the Linux machine you are using to run the Python script.
. Change to the directory where you extracted the installation archive.
+
For example: +
`cd StorageGRID-Webscale-_version/platform_`
+
where `_platform_` is `debs`, `rpms`, or `vsphere`.

. Run the Python script and use the configuration file you created.
+
For example:
+
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----

.After you finish

A Recovery Package `.zip` file is generated during the configuration process, and it is downloaded to the directory where you are running the installation and configuration process. You must back up the Recovery Package file so that you can recover the StorageGRID system if one or more grid nodes fails. For example, copy it to a secure, backed up network location and to a secure cloud storage location.

IMPORTANT: The Recovery Package file must be secured because it contains encryption keys and passwords that can be used to obtain data from the StorageGRID system.

If you specified that random passwords should be generated, you need to extract the `Passwords.txt` file and look for the passwords required to access your StorageGRID system.

----
######################################################################
##### The StorageGRID "recovery package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----

Your StorageGRID system is installed and configured when a confirmation message is displayed.

----
StorageGRID has been configured and installed.
----
