---
permalink: sg6000/configuring_bmc_interface_sg6000.html
sidebar: sidebar
keywords:
summary: 'The user interface for the baseboard management controller \(BMC\) on the SG6000-CN controller provides status information about the hardware and allows you to configure SNMP settings and other options for the SG6000-CN controller.'
---
= Configuring the BMC interface
:icons: font
:imagesdir: ../media/

[.lead]
The user interface for the baseboard management controller (BMC) on the SG6000-CN controller provides status information about the hardware and allows you to configure SNMP settings and other options for the SG6000-CN controller.

.Steps

* xref:changing_root_password_for_bmc_interface_sg6000.adoc[Changing the root password for the BMC interface]
* xref:setting_ip_address_for_bmc_management_port_sg6000.adoc[Setting the IP address for the BMC management port]
* xref:accessing_bmc_interface_sg6000.adoc[Accessing the BMC interface]
* xref:configuring_snmp_settings_for_sg6000_cn_controller.adoc[Configuring SNMP settings for the SG6000-CN controller]
* xref:setting_up_email_notifications_for_alerts.adoc[Setting up email notifications for alerts]
