---
permalink: sg6000/configuring-hardware.html
sidebar: sidebar
keywords: storagegrid, sg6000, storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking
summary: 'After applying power to the appliance, you must configure the network connections that will be used by StorageGRID. You must configure SANtricity System Manager, which is the software you will use to monitor the storage controllers and other hardware in the controller shelf. You must also ensure that you can access the BMC interface for the SG6000-CN controller.'
---
= Configuring the hardware
:icons: font
:imagesdir: ../media/

[.lead]
After applying power to the appliance, you must configure the network connections that will be used by StorageGRID. You must configure SANtricity System Manager, which is the software you will use to monitor the storage controllers and other hardware in the controller shelf. You must also ensure that you can access the BMC interface for the SG6000-CN controller.

.Steps

* xref:configuring-storagegrid-connections.adoc[Configuring StorageGRID connections]
* xref:accessing-and-configuring-santricity-system-manager.adoc[Accessing and Configuring SANtricity System Manager]
* xref:configuring-bmc-interface-sg6000.adoc[Configuring the BMC interface]
* xref:optional-enabling-node-encryption.adoc[Optional: Enabling node encryption]
* xref:optional-changing-raid-mode-sg6000-only.adoc[Optional: Changing the RAID mode (SG6000 only)]
* xref:optional-remapping-network-ports-for-appliance-sg6000.adoc[Optional: Remapping network ports for the appliance]
