---
permalink: sg6000/configuring-storagegrid-connections.html
sidebar: sidebar
keywords: storagegrid, sg6000, storage node, storage appliance, storagegrid connections, connections, configure, setup, set up
summary: 'Before you can deploy a StorageGRID appliance as a Storage Node in a StorageGRID system, you must configure the connections between the appliance and the networks you plan to use. You can configure networking by browsing to the StorageGRID Appliance Installer, which is pre-installed on the SG6000-CN controller \(the compute controller\).'
---
= Configure StorageGRID connections (SG6000)
:icons: font
:imagesdir: ../media/

[.lead]
Before you can deploy a StorageGRID appliance as a Storage Node in a StorageGRID system, you must configure the connections between the appliance and the networks you plan to use. You can configure networking by browsing to the StorageGRID Appliance Installer, which is pre-installed on the SG6000-CN controller (the compute controller).

.Steps

* xref:accessing-storagegrid-appliance-installer-sg6000.adoc[Access StorageGRID Appliance Installer]
* xref:verifying-and-upgrading-storagegrid-appliance-installer-version.adoc[Verify and upgrade StorageGRID Appliance Installer version]
* xref:configuring-network-links-sg6000.adoc[Configure network links (SG6000)]
* xref:configuring-storagegrid-ip-addresses-sg6000.adoc[Configure StorageGRID IP addresses]
* xref:verifying-network-connections.adoc[Verify network connections]
* xref:verifying-port-level-network-connections.adoc[Verify port-level network connections]
