---
permalink: sg6000/connecting_power_cords_and_applying_power_sg6000.html
sidebar: sidebar
keywords:
summary: 'After connecting the network cables, you are ready to apply power to the SG6000-CN controller and to the two storage controllers or optional expansion shelves.'
---
= Connecting power cords and applying power (SG6000)
:icons: font
:imagesdir: ../media/

[.lead]
After connecting the network cables, you are ready to apply power to the SG6000-CN controller and to the two storage controllers or optional expansion shelves.

.Steps

. Confirm that both controllers in the storage controller shelf are off.
+
CAUTION: *Risk of electrical shock* -- Before connecting the power cords, make sure that the power switches for each of the two storage controllers are off.

. If you have expansion shelves, confirm that both of the IOM power switches are off.
+
CAUTION: *Risk of electrical shock* -- Before connecting the power cords, make sure that the two power switches for each of the expansion shelves are off.

. Connect a power cord to each of the two power supply units in the SG6000-CN controller.
. Connect these two power cords to two different power distribution units (PDUs) in the cabinet or rack.
. Connect a power cord to each of the two power supply units in the storage controller shelf.
. If you have expansion shelves, connect a power cord to each of the two power supply units in each expansion shelf.
. Connect the two power cords in each storage shelf (including the optional expansion shelves) to two different PDUs in the cabinet or rack.
. If the power button on the front of the SG6000-CN controller is not currently illuminated blue, press the button to turn on power to the controller.
+
Do not press the power button again during the power-on process.

. Turn on the two power switches on the back of the storage controller shelf. If you have expansion shelves, turn on the two power switches for each shelf.
 ** Do not turn off the power switches during the power-on process.
 ** The fans in the storage controller shelf and optional expansion shelves might be very loud when they first start up. The loud noise during start-up is normal.
. After the components have booted up, check their status.
 ** Check the seven-segment display on the back of each storage controller. Refer to the article about viewing boot-up status codes for more information.
 ** Verify that the power button on the front of the SG6000-CN controller is lit.
. If errors occur, correct any issues.
. Attach the front bezel to the SG6000-CN controller.

.Related information

xref:viewing_boot_up_status_codes_for_sg6000_storage_controllers.adoc[Viewing boot-up status codes for the SG6000 storage controllers]

xref:viewing_status_indicators_and_buttons_on_sg6000_cn_controller.adoc[Viewing status indicators and buttons on the SG6000-CN controller]

xref:reinstalling_sg6000_cn_controller_into_cabinet_or_rack.adoc[Reinstalling the SG6000-CN controller into a cabinet or rack]
