---
permalink: sg6000/gathering_installation_information_sg6000.html
sidebar: sidebar
keywords: StorageGRID
summary: 'As you install and configure the StorageGRID appliance, you must make decisions and gather information about Ethernet switch ports, IP addresses, and port and network bond modes.'
---
= Gathering installation information (SG6000)
:icons: font
:imagesdir: ../media/

[.lead]
As you install and configure the StorageGRID appliance, you must make decisions and gather information about Ethernet switch ports, IP addresses, and port and network bond modes.

You can use the following tables to record the required information for each network you connect to the appliance. These values are required to install and configure the hardware.

|===
| Information needed| Your value for controller A| Your value for controller B
a|
Ethernet switch port you will connect to management port 1 (labeled as P1 on the controller)
a|
 
a|
 
a|
MAC address for management port 1 (printed on a label near port P1)
a|
 
a|
 
a|
DHCP-assigned IP address for management port 1, if available after power on**Note:** If the network you will connect to the storage controller includes a DHCP server, the network administrator can use the MAC address to determine the IP address that was assigned by the DHCP server.

a|
 
a|
 
a|
Static IP address you plan to use for the appliance on the management network
a|
For IPv4:

* IPv4 address:
* Subnet mask:
* Gateway:

For IPv6:

* IPv6 address:
* Routable IP address:
* storage controller router IP address:

a|
For IPv4:

* IPv4 address:
* Subnet mask:
* Gateway:

For IPv6:

* IPv6 address:
* Routable IP address:
* storage controller router IP address:

a|
IP address format
a|
Choose one:

* IPv4
* IPv6

a|
Choose one:

* IPv4
* IPv6

a|
Speed and duplex mode**Note:** You must make sure the Ethernet switch for the SANtricity System Manager management network is set to autonegotiate.

a|
Must be:

* Autonegotiate (default)

a|
Must be:

* Autonegotiate (default)

|===
|===
| Information needed| Your value
a|
Admin Network enabled
a|
Choose one:

* No
* Yes (default)

a|
Network bond mode
a|
Choose one:

* Independent (default)
* Active-Backup

a|
Switch port for the left port in the red circle in the diagram (default active port for Independent network bond mode)
a|
 
a|
Switch port for the right port in the red circle in the diagram (Active-Backup network bond mode only)
a|
 
a|
MAC address for the Admin Network port**Note:** The MAC address label on the front of the SG6000-CN controller lists the MAC address for the BMC management port. To determine the MAC address for the Admin Network port, you must add *2* to the hexadecimal number on the label. For example, if the MAC address on the label ends in *09*, the MAC address for the Admin Port would end in *0B*. If the MAC address on the label ends in *(_y_)FF*, the MAC address for the Admin Port would end in *(_y_+1)01*. You can easily make this calculation by opening Calculator in Windows, setting it to Programmer mode, selecting Hex, typing the MAC address, then typing *+ 2 =*.

a|
 
a|
DHCP-assigned IP address for the Admin Network port, if available after power on *Note:* You can determine the DHCP-assigned IP address by using the MAC address to look up the assigned IP.

a|

* IPv4 address (CIDR):
* Gateway:

a|
Static IP address you plan to use for the appliance Storage Node on the Admin Network**Note:** If your network does not have a gateway, specify the same static IPv4 address for the gateway.

a|

* IPv4 address (CIDR):
* Gateway:

a|
Admin Network subnets (CIDR)
a|
 
|===
|===
| Information needed| Your value
a|
Link speed

a|
Choose one:

* Auto (default)
* 10 GbE
* 25 GbE

a|
Port bond mode

a|
Choose one:

* Fixed (default)
* Aggregate

a|
Switch port for port 1 (Client Network for Fixed mode)

a|
 
a|
Switch port for port 2 (Grid Network for Fixed mode)

a|
 
a|
Switch port for port 3 (Client Network for Fixed mode)

a|
 
a|
Switch port for port 4 (Grid Network for Fixed mode)

a|
 
|===
|===
| Information needed| Your value
a|
Network bond mode
a|
Choose one:

* Active-Backup (default)
* LACP (802.3ad)

a|
VLAN tagging enabled
a|
Choose one:

* No (default)
* Yes

a|
VLAN tag(if VLAN tagging is enabled)

a|
Enter a value between 0 and 4095:
a|
DHCP-assigned IP address for the Grid Network, if available after power on
a|

* IPv4 address (CIDR):
* Gateway:

a|
Static IP address you plan to use for the appliance Storage Node on the Grid Network**Note:** If your network does not have a gateway, specify the same static IPv4 address for the gateway.

a|

* IPv4 address (CIDR):
* Gateway:

a|
Grid Network subnets (CIDRs)
a|
 
|===
|===
| Information needed| Your value
a|
Client Network enabled
a|
Choose one:

* No (default)
* Yes

a|
Network bond mode
a|
Choose one:

* Active-Backup (default)
* LACP (802.3ad)

a|
VLAN tagging enabled
a|
Choose one:

* No (default)
* Yes

a|
VLAN tag(If VLAN tagging is enabled)

a|
Enter a value between 0 and 4095:

a|
DHCP-assigned IP address for the Client Network, if available after power on
a|

* IPv4 address (CIDR):
* Gateway:

a|
Static IP address you plan to use for the appliance Storage Node on the Client Network *Note:* If the Client Network is enabled, the default route on the controller will use the gateway specified here.

a|

* IPv4 address (CIDR):
* Gateway:

|===
|===
| Information needed| Your value
a|
Ethernet switch port you will connect to the BMC management port (circled in the diagram)
a|

a|
DHCP-assigned IP address for the BMC management network, if available after power on
a|

* IPv4 address (CIDR):
* Gateway:

a|
Static IP address you plan to use for the BMC management port
a|

* IPv4 address (CIDR):
* Gateway:

|===
*Related information*

xref:controllers_in_sg6000_appliances.adoc[Controllers in the SG6000 appliances]

xref:reviewing_appliance_network_connections_sg6000.adoc[Reviewing appliance network connections]

xref:port_bond_modes_for_sg6000_cn_controller.adoc[Port bond modes for the SG6000-CN controller]

xref:cabling_appliance_sg6000.adoc[Cabling the appliance (SG6000)]

xref:configuring_storagegrid_ip_addresses_sg6000.adoc[Configuring StorageGRID IP addresses]
