---
permalink: sg6000/index.html
sidebar: sidebar
keywords: storagegrid, sg6000, storage node, storage appliance, overview, models, features 
summary: 'The StorageGRID SG6000 appliances are integrated storage and computing platforms that operate as Storage Nodes in a StorageGRID system. These appliances can be used in a hybrid grid environment that combines appliance Storage Nodes and virtual \(software-based\) Storage Nodes.'
---
= SG6000 appliances: Overview
:icons: font
:imagesdir: ../media/

[.lead]
The StorageGRID SG6000 appliances are integrated storage and computing platforms that operate as Storage Nodes in a StorageGRID system. These appliances can be used in a hybrid grid environment that combines appliance Storage Nodes and virtual (software-based) Storage Nodes.

The SG6000 appliances provide the following features:

* Available in three models:
 ** SG6060, which includes 60 drives, supports expansion shelves, and uses E2800A controllers.
 ** SG6060X, which includes 60 drives, supports expansion shelves, and uses E2800B controllers.
+
NOTE: The SG6060 and SG6060X have identical specifications and function except for the location of the interconnect ports on the storage controllers. 

 ** SGF6024, which offers 24 solid state drives (SSDs).
* Integrate the storage and computing elements for a StorageGRID Storage Node.
* Include the StorageGRID Appliance Installer to simplify Storage Node deployment and configuration.
* Include SANtricity System Manager for managing and monitoring the storage controllers and drives.
* Include a baseboard management controller (BMC) for monitoring and diagnosing the hardware in the compute controller.
* Support up to four 10-GbE or 25-GbE connections to the StorageGRID Grid Network and Client Network.
* Support Federal Information Processing Standard (FIPS) drives. When these drives are used with the Drive Security feature in SANtricity System Manager, unauthorized access to data is prevented.
