---
permalink: sg6000/preparing-site-sg6000.html
sidebar: sidebar
keywords: storagegrid, sg6000, storage node, storage appliance, install, installation, site prep, site preparating, preparing site, site requirements, requirements, site, dimensions, weight, weights, temperature, humidity, altitude, airflow, heat, wiring, power, grounding, facility
summary: 'Before installing the appliance, you must make sure that the site and the cabinet or rack you plan to use meet the specifications for a StorageGRID appliance.'
---
= Preparing the site (SG6000)
:icons: font
:imagesdir: ../media/

[.lead]
Before installing the appliance, you must make sure that the site and the cabinet or rack you plan to use meet the specifications for a StorageGRID appliance.

.Steps

. Confirm that the site meets the requirements for temperature, humidity, altitude range, airflow, heat dissipation, wiring, power, and grounding. See the NetApp Hardware Universe for more information.
. Confirm that your location provides 240-volt AC power for the SG6060 or 120-volt AC power for the SGF6024.
. Obtain a 19-inch (48.3-cm) cabinet or rack to fit shelves of this size (without cables):
+
[options="header"]
|===
| Type of shelf| Height| Width| Depth| Maximum weight
a|
*E2860 controller shelf* for SG6060
a|
6.87 in.

(17.46 cm)
a|
17.66 in.

(44.86 cm)
a|
38.25 in.

(97.16 cm)
a|
250 lb.

(113 kg)
a|
*Optional expansion shelf* for SG6060 (one or two)
a|
6.87 in.

(17.46 cm)
a|
17.66 in.

(44.86 cm)
a|
38.25 in.

(97.16 cm)
a|
250 lb.

(113 kg)
a|
*EF570 controller shelf* for SGF6024
a|
3.35 in.

(8.50 cm)
a|
17.66 in.

(44.86 cm)
a|
19.00 in.

(48.26 cm)
a|
51.74 lb.

(23.47 kg)
a|
*SG6000-CN controller* for each appliance
a|
1.70 in.

(4.32 cm)
a|
17.32 in.

(44.0 cm)
a|
32.0 in.

(81.3 cm)
a|
39 lb.

(17.7 kg)
|===

. Decide where you are going to install the appliance.
+
CAUTION: When installing the E2860 controller shelf or optional expansion shelves, install hardware from the bottom to the top of the rack or cabinet to prevent the equipment from tipping over. To ensure that the heaviest equipment is at the bottom of the cabinet or rack, install the SG6000-CN controller above the E2860 controller shelf and expansion shelves.
+
IMPORTANT: Before committing to the installation, verify that the 0.5m optic cables shipped with the appliance, or cables that you supply, are long enough for the planned layout.

.Related information

https://hwu.netapp.com[NetApp Hardware Universe^]

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]
