---
permalink: sg6000/replacing-hardware-components-in-optional-60-drive-expansion-shelf.html
sidebar: sidebar
keywords: storagegrid, sg6000, storage node, storage appliance, Replacing, replace, hardware, components, remove, removing, removal, install, installing, installation, i/o module, input/output module, power supply, fan, 60-drive expansion shelf, expansion shelf 
summary: 'You might need to replace an input/output module, a power supply, or a fan in the expansion shelf.'
---
= Replacing hardware components in the optional 60-drive expansion shelf
:icons: font
:imagesdir: ../media/

[.lead]
You might need to replace an input/output module, a power supply, or a fan in the expansion shelf.

.What you'll need

* You have the E-Series hardware replacement procedure.
* You have physically located the storage appliance where you are replacing expansion shelf hardware components in the data center.
+
xref:locating-controller-in-data-center.adoc[Locating the controller in a data center]

.About this task

To replace an input/output module (IOM) in a 60-drive expansion shelf, see the instructions in these instructions for replacing a storage controller.

To replace a power supply or a fan in a 60-drive expansion shelf, access the E-Series procedures for maintaining 60-drive hardware.

[options="header"]
|===
| FRU| See E-Series instructions for
a|
Input/output module (IOM)
a|
Replacing an IOM
a|
Power canister
a|
Replace power canister (60-drive)
a|
Fan canister
a|
Replace fan canister (60-drive)
|===
