---
permalink: sg6000/replacing-storage-controller-sg6000.html
sidebar: sidebar
keywords: storagegrid, sg6000, storage node, storage appliance, Replacing, replace, storage controller, e2800, ef570, controller, remove, removing, removal, install, installing, installation
summary: 'You might need to replace an E2800 controller or an EF570 controller if it is not functioning optimally or if it has failed.'
---
= Replace storage controller in the SG6000
:icons: font
:imagesdir: ../media/

[.lead]
You might need to replace an E2800 series controller or an EF570 controller if it is not functioning optimally or if it has failed.

.What you'll need

* You have a replacement controller with the same part number as the controller you are replacing.
* You have labels to identify each cable that is connected to the controller.
* You have an ESD wristband, or you have taken other antistatic precautions.
* You have a #1 Phillips screwdriver.
* You have the E-Series instructions for replacing a controller in duplex configuration.
+
IMPORTANT: Do not rely on the E-Series instructions to replace a controller in the StorageGRID appliance, because the procedures are not the same.

* You have physically located the storage appliance where you are replacing the controller in the data center.
+
xref:locating-controller-in-data-center.adoc[Locate controller in data center]

.About this task

You can determine if you have a failed controller in two ways:

* The Recovery Guru in SANtricity System Manager directs you to replace the controller.
* The amber Attention LED on the controller is on, indicating that the controller has a fault.
+
IMPORTANT: If both controllers in the shelf have their Attention LEDs on, contact technical support for assistance.

If your appliance contains two storage controllers, you can replace one of the controllers while your appliance is powered on and performing read/write operations, as long as the following conditions are true:

* The second controller in the shelf has Optimal status.
* The "`OK to remove`" field in the Details area of the Recovery Guru in SANtricity System Manager displays Yes, indicating that it is safe to remove this component.

IMPORTANT: When possible, place the appliance into maintenance mode for this replacement procedure to minimize the potential impact of unforeseen errors or failures.

IMPORTANT: If the second controller in the shelf does not have Optimal status or if the Recovery Guru indicates that it is not OK to remove the controller, contact technical support.

When you replace a controller, you must remove the battery from the original controller and install it in the replacement controller. In some cases, you might also need to remove the host interface card from the original controller and install it in the replacement controller.

NOTE: The storage controllers in most appliance models do not include host interface cards (HIC).

This task has the following parts: 

. Prepare
. Take controller offline
. Remove controller
. Move battery to new controller
. Move HIC to new controller, if needed
. Replace controller

//For systems with two controllers, both controllers must have the same model number. 

== Prepare
.Steps

. Unpack the new controller, and set it on a flat, static-free surface.
+
Save the packing materials to use when shipping the failed controller.

. Locate the MAC address and FRU part number labels on the back of the replacement controller.

include::../_include/e2800_series_rear.adoc[] 

== Take controller offline
.Steps

. Prepare to remove the controller. You use SANtricity System Manager to perform these steps.
+
.. Confirm that the replacement part number for the failed controller is the same as the FRU part number for the replacement controller.
+
When a controller has a fault and needs to be replaced, the replacement part number is displayed in the Details area of the Recovery Guru. If you need to find this number manually, you can look on the *Base* tab for the controller.
+
IMPORTANT: *Possible loss of data access &#8212;* If the two part numbers are not the same, do not attempt this procedure.

 .. Back up the configuration database.
+
If a problem occurs when you remove a controller, you can use the saved file to restore your configuration.

 .. Collect support data for the appliance.
+
NOTE: Collecting support data before and after replacing a component ensures you can send a full set of logs to technical support in case the replacement does not resolve the problem.

 .. Take the controller you plan to replace offline.
 
include::../_include/remove_controller_e2800.adoc[]
include::../_include/remove_battery_e2800.adoc[]
include::../_include/HIC_replacement.adoc[] 

== Replace controller
.Steps

. Install the replacement controller into the appliance.
 .. Turn the controller over, so that the removable cover faces down.
 .. With the cam handle in the open position, slide the controller all the way into the appliance.
 .. Move the cam handle to the left to lock the controller in place.
 .. Replace the cables and SFPs.
 .. If the original controller used DHCP for the IP address, locate the MAC address on the label on the back of the replacement controller. Ask your network administrator to associate the DNS/network and IP address for the controller you removed with the MAC address for the replacement controller.
+
NOTE: If the original controller did not use DHCP for the IP address, the new controller will adopt the IP address of the controller you removed.
. Bring the controller online using SANtricity System Manager:
 .. Select *Hardware*.
 .. If the graphic shows the drives, select *Show back of shelf*.
 .. Select the controller you want to place online.
 .. Select *Place Online* from the context menu, and confirm that you want to perform the operation.
 .. Verify that the seven-segment display shows a state of `99`.
. Confirm that the new controller is Optimal, and collect support data.

include::../_include/fru-statement.adoc[] 

.Related information

http://mysupport.netapp.com/info/web/ECMP1658252.html[NetApp E-Series Systems Documentation Site^]
