---
permalink: sg6000/replacing-hardware-components-in-storage-controller-shelf.html
sidebar: sidebar
keywords: storagegrid, sg6000, storage node, storage appliance, Replacing, replace, hardware, components, remove, removing, removal, install, installing, installation, storage controller shelf, Battery, Drive, Power canister, power supply, Fan canister, fan, Drive drawer 
summary: 'If a hardware problem occurs, you might need to replace a component in the storage controller shelf.'
---
= Replacing hardware components in the storage controller shelf
:icons: font
:imagesdir: ../media/

[.lead]
If a hardware problem occurs, you might need to replace a component in the storage controller shelf.

.What you'll need

* You have the E-Series hardware replacement procedure.
* You have physically located the storage appliance where you are replacing storage shelf hardware components in the data center.
+
xref:locating-controller-in-data-center.adoc[Locating the controller in a data center]

.About this task

To replace the battery in the storage controller, see the instructions in these instructions for replacing a storage controller. Those instructions describe how to remove a controller from the appliance, remove the battery from the controller, install the battery, and replace the controller.

For instructions for the other field replaceable units (FRUs) in the controller shelves, access the E-Series procedures for system maintenance.

[options="header"]
|===
| FRU| See instructions
a|
Battery
a|
StorageGRID (these instructions): Replacing a storage controller
a|
Drive
a|
E-Series:

* Replace drive (60-drive)
* Replace drive (12-drive or 24-drive)

a|
Power canister
a|
E-Series

* Replace power canister (60-drive)
* Replace power supply (12-drive or 24-drive)

a|
Fan canister (60-drive shelves only)
a|
E-Series: Replace fan canister (60-drive)
a|
Drive drawer (60-drive shelves only)
a|
E-Series: Replace drive drawer (60-drive)
|===
.Related information

http://mysupport.netapp.com/info/web/ECMP1658252.html[NetApp E-Series Systems Documentation Site^]

xref:replacing-storage-controller-sg6000.adoc[Replacing a storage controller]
