---
permalink: sg6000/reviewing-appliance-network-connections-sg6000.html
sidebar: sidebar
keywords: storagegrid, sg6000, storage node, storage appliance, network connections, network connection, network, connection, grid, admin, client, bmc, management, SANtricity System Manager, SANtricity
summary: 'Before installing the StorageGRID appliance, you should understand which networks can be connected to the appliance.'
---
= Reviewing appliance network connections
:icons: font
:imagesdir: ../media/

[.lead]
Before installing the StorageGRID appliance, you should understand which networks can be connected to the appliance.

When you deploy a StorageGRID appliance as a Storage Node in a StorageGRID system, you can connect it to the following networks:

* *Grid Network for StorageGRID*: The Grid Network is used for all internal StorageGRID traffic. It provides connectivity between all nodes in the grid, across all sites and subnets. The Grid Network is required.
* *Admin Network for StorageGRID*: The Admin Network is a closed network used for system administration and maintenance. The Admin Network is typically a private network and does not need to be routable between sites. The Admin Network is optional.
* *Client Network for StorageGRID:* The Client Network is an open network used to provide access to client applications, including S3 and Swift. The Client Network provides client protocol access to the grid, so the Grid Network can be isolated and secured. The Client Network is optional.
* *Management network for SANtricity System Manager*: This network provides access to SANtricity System Manager on the storage controller, allowing you to monitor and manage the hardware components in the storage controller shelf. This management network can be the same as the Admin Network for StorageGRID, or it can be an independent management network.
* *BMC management network for the SG6000-CN controller:* This network provides access to the baseboard management controller in the SG6000-CN, allowing you to monitor and manage the hardware components in the SG6000-CN controller. This management network can be the same as the Admin Network for StorageGRID, or it can be an independent management network.

NOTE: For detailed information about StorageGRID networks, see the _Grid Primer_.

.Related information

xref:gathering-installation-information-sg6000.adoc[Gathering installation information (SG6000)]

xref:cabling-appliance-sg6000.adoc[Cabling the appliance (SG6000)]

xref:port-bond-modes-for-sg6000-cn-controller.adoc[Port bond modes for the SG6000-CN controller]

xref:../network/index.adoc[Network guidelines]
