---
permalink: sg6000/task_replacing_hardware_components_in_the_optional_60_drive_expansion_shelf.html
sidebar: sidebar
keywords: 
summary: 'You might need to replace an input/output module, a power supply, or a fan in the expansion shelf.'
---
= Replacing hardware components in the optional 60-drive expansion shelf
:icons: font
:imagesdir: ../media/

[.lead]
You might need to replace an input/output module, a power supply, or a fan in the expansion shelf.

* You have the E-Series hardware replacement procedure.
* You have physically located the storage appliance where you are replacing expansion shelf hardware components in the data center.
+
xref:task_locating_the_controller_in_a_data_center.adoc[Locating the controller in a data center]

To replace an input/output module (IOM) in a 60-drive expansion shelf, see the instructions in this guide for replacing a storage controller.

To replace a power supply or a fan in a 60-drive expansion shelf, access the E-Series procedures for maintaining 60-drive hardware.

|===
| FRU| See E-Series instructions for
a|
Input/output module (IOM)
a|
Replacing an IOM
a|
Power canister
a|
Replace power canister (60-drive)
a|
Fan canister
a|
Replace fan canister (60-drive)
|===
