---
permalink: sg6000/unable-to-connect-to-appliance.html
sidebar: sidebar
keywords: storagegrid, sg6000, storage node, storage appliance, troubleshoot, troubleshooting, connect, connection, unable to connect, no connection
summary: 'If you cannot connect to the appliance, there might be a network issue, or the hardware installation might not have been completed successfully.'
---
= Unable to connect to the appliance
:icons: font
:imagesdir: ../media/

[.lead]
If you cannot connect to the appliance, there might be a network issue, or the hardware installation might not have been completed successfully.

.Steps

. If you are unable to connect to SANtricity System Manager:
 .. Try to ping the appliance using the IP address for either storage controller on the management network for SANtricity System Manager: +
`*ping _Storage_Controller_IP_*`
 .. If you receive no response from the ping, confirm you are using the correct IP address.
+
Use the IP address for management port 1 on either storage controller.

 .. If the IP address is correct, check appliance cabling and the network setup.
+
If that does not resolve the issue, contact technical support.

 .. If the ping was successful, open a web browser.
 .. Enter the URL for SANtricity System Manager: +
`*https://_Storage_Controller_IP_*`
+
The log in page for SANtricity System Manager appears.
. If you are unable to connect to the SG6000-CN controller:
 .. Try to ping the appliance using the IP address for the SG6000-CN controller: +
`*ping _SG6000-CN_Controller_IP_*`
 .. If you receive no response from the ping, confirm you are using the correct IP address.
+
You can use the IP address of the appliance on the Grid Network, the Admin Network, or the Client Network.

 .. If the IP address is correct, check appliance cabling, SFP transceivers, and the network setup.
+
If that does not resolve the issue, contact technical support.

 .. If the ping was successful, open a web browser.
 .. Enter the URL for the StorageGRID Appliance Installer: +
`*https://_SG6000-CN_Controller_IP_:8443*`
+
The Home page appears.
