---
permalink: sg6000/unable_to_connect_to_appliance.html
sidebar: sidebar
keywords: 
summary: 'If you cannot connect to the appliance, there might be a network issue, or the hardware installation might not have been completed successfully.'
---
= Unable to connect to the appliance
:icons: font
:imagesdir: ../media/

[.lead]
If you cannot connect to the appliance, there might be a network issue, or the hardware installation might not have been completed successfully.

. If you are unable to connect to SANtricity System Manager:
 .. Try to ping the appliance using the IP address for either storage controller on the management network for SANtricity System Manager: `ping Storage_Controller_IP`
 .. If you receive no response from the ping, confirm you are using the correct IP address.
+
Use the IP address for management port 1 on either storage controller.

 .. If the IP address is correct, check appliance cabling and the network setup.
+
If that does not resolve the issue, contact technical support.

 .. If the ping was successful, open a web browser.
 .. Enter the URL for SANtricity System Manager:``+https://Storage_Controller_IP+``
+
The log in page for SANtricity System Manager appears.
. If you are unable to connect to the SG6000-CN controller:
 .. Try to ping the appliance using the IP address for the SG6000-CN controller : `ping SG6000-CN_Controller_IP`
 .. If you receive no response from the ping, confirm you are using the correct IP address.
+
You can use the IP address of the appliance on the Grid Network, the Admin Network, or the Client Network.

 .. If the IP address is correct, check appliance cabling, SFP transceivers, and the network setup.
+
If that does not resolve the issue, contact technical support.

 .. If the ping was successful, open a web browser.
 .. Enter the URL for the StorageGRID Appliance Installer: `+https://SG6000-CN_Controller_IP:8443+`
+
The Home page appears.
