---
permalink: audit/accessing-audit-log-file.html
sidebar: sidebar
keywords: storagegrid, audit, log, log file, access, accessing
summary: 'The audit share contains the active audit.log file and any compressed audit log files. For easy access to audit logs, you can configure client access to audit shares for both NFS and CIFS \(deprecated\). You can also access audit log files directly from the command line of the Admin Node.'
---
= Accessing the audit log file
:icons: font
:imagesdir: ../media/

[.lead]
The audit share contains the active `audit.log` file and any compressed audit log files. For easy access to audit logs, you can configure client access to audit shares for both NFS and CIFS (deprecated). You can also access audit log files directly from the command line of the Admin Node.

.What you'll need

* You must have specific access permissions.
* You must have the `Passwords.txt` file.
* You must know the IP address of an Admin Node.

.Steps

. Log in to an Admin Node:
 .. Enter the following command: `ssh admin@_primary_Admin_Node_IP_`
 .. Enter the password listed in the `Passwords.txt` file.
. Go to the directory containing the audit log files:
+
`cd /var/local/audit/export`
. View the current or a saved audit log file, as required.

.Related information

xref:../admin/index.adoc[Administer StorageGRID]
