---
permalink: audit/arce-archive-object-retrieve-end.html
sidebar: sidebar
keywords: storagegrid, audit, message, ARCE, Archive Object Retrieve End
summary: 'This message is generated when an attempt by the Archive Node to retrieve object data from an external archival storage system completes. If successful, the message indicates that the requested object data has been completely read from the archive location, and was successfully verified. After the object data has been retrieved and verified, it is delivered to the requesting service.'
---
= ARCE: Archive Object Retrieve End
:icons: font
:imagesdir: ../media/

[.lead]
This message is generated when an attempt by the Archive Node to retrieve object data from an external archival storage system completes. If successful, the message indicates that the requested object data has been completely read from the archive location, and was successfully verified. After the object data has been retrieved and verified, it is delivered to the requesting service.

[options="header"]
|===
| Code| Field| Description
a|
CBID
a|
Content Block ID
a|
The unique identifier of the Content Block to be retrieved from the external archival storage system.
a|
VLID
a|
Volume Identifier
a|
The identifier of the volume on which the data was archived.If an archive location for the content is not found, a Volume ID of 0 is returned.

a|
RSLT
a|
Retrieval Result
a|
The completion status of the archive retrieval process:

* SUCS: successful
* VRFL: failed (object verification failure)
* ARUN: failed (external archival storage system unavailable)
* CANC: failed (retrieval operation canceled)
* GERR: failed (general error)

|===
Matching this message with the corresponding ARCB message can indicate the time taken to perform the archive retrieval. This message indicates whether the retrieval was successful, and in the case of failure, the cause of the failure to retrieve the content block.
