---
permalink: audit/cbsb-object-send-begin.html
sidebar: sidebar
keywords: storagegrid, audit, message, CBSB, Object Send Begin
summary: 'During normal system operations, content blocks are continuously transferred between different nodes as data is accessed, replicated and retained. When transfer of a content block from one node to another is initiated, this message is issued by the source entity.'
---
= CBSB: Object Send Begin
:icons: font
:imagesdir: ../media/

[.lead]
During normal system operations, content blocks are continuously transferred between different nodes as data is accessed, replicated and retained. When transfer of a content block from one node to another is initiated, this message is issued by the source entity.

[options="header"]
|===
| Code| Field| Description
a|
CNID
a|
Connection Identifier
a|
The unique identifier of the node-to-node session/connection.
a|
CBID
a|
Content Block Identifier
a|
The unique identifier of the content block being transferred.
a|
CTDR
a|
Transfer Direction
a|
Indicates if the CBID transfer was push-initiated or pull-initiated:

PUSH: The transfer operation was requested by the sending entity.

PULL: The transfer operation was requested by the receiving entity.

a|
CTSR
a|
Source Entity
a|
The node ID of the source (sender) of the CBID transfer.
a|
CTDS
a|
Destination Entity
a|
The node ID of the destination (receiver) of the CBID transfer.
a|
CTSS
a|
Start Sequence Count
a|
Indicates the first sequence count requested. If successful, the transfer begins from this sequence count.
a|
CTES
a|
Expected End Sequence Count
a|
Indicates the last sequence count requested. If successful, the transfer is considered complete when this sequence count has been received.
a|
RSLT
a|
Transfer Start Status
a|
Status at the time the transfer was started:

SUCS: transfer started successfully.

|===
This audit message means a node-to-node data transfer operation was initiated on a single piece of content, as identified by its Content Block Identifier. The operation requests data from "Start Sequence Count" to "Expected End Sequence Count". Sending and receiving nodes are identified by their node IDs. This information can be used to track system data flow, and when combined with storage audit messages, to verify replica counts.
