---
permalink: audit/cbse-object-send-end.html
sidebar: sidebar
keywords: storagegrid, audit, message, CBSE, Object Send End
summary: 'When transfer of a content block from one node to another is completed, this message is issued by the source entity.'
---
= CBSE: Object Send End
:icons: font
:imagesdir: ../media/

[.lead]
When transfer of a content block from one node to another is completed, this message is issued by the source entity.

[options="header"]
|===
| Code| Field| Description
a|
CNID
a|
Connection Identifier
a|
The unique identifier of the node-to-node session/connection.
a|
CBID
a|
Content Block Identifier
a|
The unique identifier of the content block being transferred.
a|
CTDR
a|
Transfer Direction
a|
Indicates if the CBID transfer was push-initiated or pull-initiated:

PUSH: The transfer operation was requested by the sending entity.

PULL: The transfer operation was requested by the receiving entity.

a|
CTSR
a|
Source Entity
a|
The node ID of the source (sender) of the CBID transfer.
a|
CTDS
a|
Destination Entity
a|
The node ID of the destination (receiver) of the CBID transfer.
a|
CTSS
a|
Start Sequence Count
a|
Indicates the sequence count on which the transfer started.
a|
CTAS
a|
Actual End Sequence Count
a|
Indicates the last sequence count successfully transferred. If the Actual End Sequence Count is the same as the Start Sequence Count, and the Transfer Result was not successful, no data was exchanged.
a|
RSLT
a|
Transfer Result
a|
The result of the transfer operation (from the perspective of the sending entity):

SUCS: Transfer successfully completed; all requested sequence counts were sent.

CONL: connection lost during transfer

CTMO: connection timed-out during establishment or transfer

UNRE: destination node ID unreachable

CRPT: transfer ended due to reception of corrupt or invalid data (might indicate tampering)

|===
This audit message means a node-to-node data transfer operation was completed. If the Transfer Result was successful, the operation transferred data from "Start Sequence Count" to "Actual End Sequence Count". Sending and receiving nodes are identified by their node IDs. This information can be used to track system data flow and to locate, tabulate, and analyze errors. When combined with storage audit messages, it can also be used to verify replica counts.
