---
permalink: audit/example-s3-object-ingest.html
sidebar: sidebar
keywords: storagegrid, audit, example, S3, object ingest
summary: 'The series of audit messages below is an example of the audit messages generated and saved to the audit log when an S3 client ingests an object to a Storage Node \(LDR service\).'
---
= Example: S3 object ingest
:icons: font
:imagesdir: ../media/

[.lead]
The series of audit messages below is an example of the audit messages generated and saved to the audit log when an S3 client ingests an object to a Storage Node (LDR service).

In this example, the active ILM policy includes the stock ILM rule, Make 2 Copies.

NOTE: Not all audit messages generated during a transaction are listed in the example below. Only those related to the S3 ingest transaction (SPUT) are listed.

This example assumes that an S3 bucket has been previously created.

== SPUT: S3 PUT

The SPUT message is generated to indicate that an S3 PUT transaction has been issued to create an object in a specific bucket.

[source]
[subs="specialcharacters,quotes"]
----
2017-07-17T21:17:58.959669[AUDT:[RSLT(FC32):SUCS][TIME(UI64):25771][SAIP(IPAD):"10.96.112.29"][S3AI(CSTR):"70899244468554783528"][SACC(CSTR):"test"][S3AK(CSTR):"SGKHyalRU_5cLflqajtaFmxJn946lAWRJfBF33gAOg=="][SUSR(CSTR):"urn:sgws:identity::70899244468554783528:root"][SBAI(CSTR):"70899244468554783528"][SBAC(CSTR):"test"][S3BK(CSTR):"example"][S3KY(CSTR):"testobject-0-3"][*CBID\(UI64\):0x8EF52DF8025E63A8*][CSIZ(UI64):30720][AVER(UI32):10][ATIM(UI64):150032627859669][*ATYP\(FC32\):SPUT*][ANID(UI32):12086324][AMID(FC32):S3RQ][ATID(UI64):14399932238768197038]]
----

== ORLM: Object Rules Met

The ORLM message indicates that the ILM policy has been satisfied for this object. The message includes the object's CBID and the name of the ILM rule that was applied.

For replicated objects, the LOCS field includes the LDR node ID and volume ID of the object locations.

[source]
[subs="specialcharacters,quotes"]
----
2019-07-17T21:18:31.230669[AUDT:[*CBID\(UI64\):0x50C4F7AC2BC8EDF7*][RULE(CSTR):"Make 2 Copies"][STAT(FC32):DONE][CSIZ(UI64):0][UUID(CSTR):"0B344E18-98ED-4F22-A6C8-A93ED68F8D3F"][LOCS(CSTR):"*CLDI 12828634 2148730112*, *CLDI 12745543 2147552014*"][RSLT(FC32):SUCS][AVER(UI32):10][*ATYP\(FC32\):ORLM*][ATIM(UI64):1563398230669][ATID(UI64):15494889725796157557][ANID(UI32):13100453][AMID(FC32):BCMS]]
----

For erasure-coded objects, the LOCS field includes the Erasure Coding profile ID and the Erasure Coding group ID

[source]
[subs="specialcharacters,quotes"]
----
2019-02-23T01:52:54.647537 [AUDT:[CBID(UI64):0xFA8ABE5B5001F7E2][RULE(CSTR):"EC_2_plus_1"][STAT(FC32):DONE][CSIZ(UI64):10000][UUID(CSTR):"E291E456-D11A-4701-8F51-D2F7CC9AFECA"][LOCS(CSTR):"*CLEC 1 A471E45D-A400-47C7-86AC-12E77F229831*"][RSLT(FC32):SUCS][AVER(UI32):10][ATIM(UI64):1550929974537]*\[ATYP\(FC32\):ORLM\]*[ANID(UI32):12355278][AMID(FC32):ILMX][ATID(UI64):4168559046473725560]]
----

The PATH field includes S3 bucket and key information or Swift container and object information, depending on which API was used.

----
2019-09-15.txt:2018-01-24T13:52:54.131559 [AUDT:[CBID(UI64):0x82704DFA4C9674F4][RULE(CSTR):"Make 2 Copies"][STAT(FC32):DONE][CSIZ(UI64):3145729][UUID(CSTR):"8C1C9CAC-22BB-4880-9115-CE604F8CE687"][PATH(CSTR):"frisbee_Bucket1/GridDataTests151683676324774_1_1vf9d"][LOCS(CSTR):"CLDI 12525468, CLDI 12222978"][RSLT(FC32):SUCS][AVER(UI32):10][ATIM(UI64):1568555574559][ATYP(FC32):ORLM][ANID(UI32):12525468][AMID(FC32):OBDI][ATID(UI64):344833886538369336]]
----
