---
permalink: audit/gnrg-gnds-registration.html
sidebar: sidebar
keywords: storagegrid, audi, message, GNRG, GNDS Registration
summary: 'The CMN service generates this audit message when a service has updated or registered information about itself in the StorageGRID system.'
---
= GNRG: GNDS Registration
:icons: font
:imagesdir: ../media/

[.lead]
The CMN service generates this audit message when a service has updated or registered information about itself in the StorageGRID system.

[options="header"]
|===
| Code| Field| Description
a|
RSLT
a|
Result
a|
The result of the update request:

* SUCS: Successful
* SUNV: Service Unavailable
* GERR: Other failure

a|
GNID
a|
Node ID
a|
The node ID of the service that initiated the update request.
a|
GNTP
a|
Device Type
a|
The grid node's device type (for example, BLDR for an LDR service).
a|
GNDV
a|
Device Model version
a|
The string identifying the grid node's device model version in the DMDL bundle.
a|
GNGP
a|
Group
a|
The group to which the grid node belongs (in the context of link costs and service-query ranking).
a|
GNIA
a|
IP Address
a|
The grid node's IP address.
|===
This message is generated whenever a grid node updates its entry in the Grid Nodes Bundle.
