---
permalink: audit/gted-grid-task-ended.html
sidebar: sidebar
keywords: storagegrid, audit, message, GTED, Grid Task Ended
summary: 'This audit message indicates that the CMN service has finished processing the specified grid task and has moved the task to the Historical table. If the result is SUCS, ABRT, or ROLF, there will be a corresponding Grid Task Started audit message. The other results indicate that processing of this grid task never started.'
---
= GTED: Grid Task Ended
:icons: font
:imagesdir: ../media/

[.lead]
This audit message indicates that the CMN service has finished processing the specified grid task and has moved the task to the Historical table. If the result is SUCS, ABRT, or ROLF, there will be a corresponding Grid Task Started audit message. The other results indicate that processing of this grid task never started.

[options="header"]
|===
| Code| Field| Description
a|
TSID
a|
Task ID
a|
This field uniquely identifies a generated grid task and allows the grid task to be managed over its lifecycle.

*Note:* The Task ID is assigned at the time that a grid task is generated, not the time that it is submitted. It is possible for a given grid task to be submitted multiple times, and in this case the Task ID field is not sufficient to uniquely link the Submitted, Started, and Ended audit messages.

a|
RSLT
a|
Result
a|
The final status result of the grid task:

* SUCS: The grid task completed successfully.
* ABRT: The grid task was aborted without a rollback error.
* ROLF: The grid task was aborted and was unable to complete the rollback process.
* CANC: The grid task was canceled by the user before it was started.
* EXPR: The grid task expired before it was started.
* IVLD: The grid task was invalid.
* AUTH: The grid task was unauthorized.
* DUPL: The grid task was rejected as a duplicate.

|===
