---
permalink: audit/gtst-grid-task-started.html
sidebar: sidebar
keywords: storagegrid, audit, message, GTST, Grid Task Started
summary: 'This audit message indicates that the CMN service has started to process the specified grid task. The audit message immediately follows the Grid Task Submitted message for grid tasks initiated by the internal Grid Task Submission service and selected for automatic activation. For grid tasks submitted into the Pending table, this message is generated when the user starts the grid task.'
---
= GTST: Grid Task Started
:icons: font
:imagesdir: ../media/

[.lead]
This audit message indicates that the CMN service has started to process the specified grid task. The audit message immediately follows the Grid Task Submitted message for grid tasks initiated by the internal Grid Task Submission service and selected for automatic activation. For grid tasks submitted into the Pending table, this message is generated when the user starts the grid task.

[options="header"]
|===
| Code| Field| Description
a|
TSID
a|
Task ID
a|
This field uniquely identifies a generated grid task and allows the task to be managed over its lifecycle.

*Note:* The Task ID is assigned at the time that a grid task is generated, not the time that it is submitted. It is possible for a given grid task to be submitted multiple times, and in this case the Task ID field is not sufficient to uniquely link the Submitted, Started, and Ended audit messages.

a|
RSLT
a|
Result
a|
The result. This field has only one value:

* SUCS: The grid task was started successfully.

|===
