---
permalink: audit/gtsu-grid-task-submitted.html
sidebar: sidebar
keywords: storagegrid, audit, message, GTSU, Grid Task Submitted
summary: 'This audit message indicates that a grid task has been submitted to the CMN service.'
---
= GTSU: Grid Task Submitted
:icons: font
:imagesdir: ../media/

[.lead]
This audit message indicates that a grid task has been submitted to the CMN service.

[options="header"]
|===
| Code| Field| Description
a|
TSID
a|
Task ID
a|
Uniquely identifies a generated grid task and allows the task to be managed over its lifecycle.

*Note:* The Task ID is assigned at the time that a grid task is generated, not the time that it is submitted. It is possible for a given grid task to be submitted multiple times, and in this case the Task ID field is not sufficient to uniquely link the Submitted, Started, and Ended audit messages.

a|
TTYP
a|
Task Type
a|
The type of grid task.
a|
TVER
a|
Task Version
a|
A number indicating the version of the grid task.
a|
TDSC
a|
Task Description
a|
A human-readable description of the grid task.
a|
VATS
a|
Valid After Timestamp
a|
The earliest time (UINT64 microseconds from January 1, 1970 - UNIX time) at which the grid task is valid.
a|
VBTS
a|
Valid Before Timestamp
a|
The latest time (UINT64 microseconds from January 1, 1970 - UNIX time) at which the grid task is valid.
a|
TSRC
a|
Source
a|
The source of the task:

* TXTB: The grid task was submitted through the StorageGRID system as a signed text block.
* GRID: The grid task was submitted through the internal Grid Task Submission Service.

a|
ACTV
a|
Activation Type
a|
The type of activation:

* AUTO: The grid task was submitted for automatic activation.
* PEND: The grid task was submitted into the pending table. This is the only possibility for the TXTB source.

a|
RSLT
a|
Result
a|
The result of the submission:

* SUCS: The grid task was submitted successfully.
* FAIL: The task has been moved directly to the historical table.

|===
