---
permalink: audit/index.html
sidebar: sidebar
keywords: storagegrid, audit, message, log, structure, content
summary: 'These instructions contain information about the structure and content of StorageGRID audit messages and audit logs. You can use this information to read and analyze the audit trail of system activity.'
---
= Review audit logs: Overview
:icons: font
:imagesdir: ../media/

[.lead]
These instructions contain information about the structure and content of StorageGRID audit messages and audit logs. You can use this information to read and analyze the audit trail of system activity.

These instructions are for administrators responsible for producing reports of system activity and usage that require analysis of the StorageGRID system's audit messages.

To use the text log file, you must have access to the configured audit share on the Admin Node.

For information on configuring audit message levels and using an external syslog server, see xref:../monitor/configure-audit-messages.adoc[Configure audit messages and log destinations].

.Related information

* xref:../admin/index.adoc[Administer StorageGRID]
