---
permalink: audit/lkcu-overwritten-object-cleanup.html
sidebar: sidebar
keywords: storagegrid, audit, message, LKCU, Overwritten Object Cleanup
summary: 'This message is generated when StorageGRID removes an overwritten object that previously required cleanup to free up storage space. An object is overwritten when an S3 or Swift client writes an object to a path already containing a object. The removal process occurs automatically and in the background.'
---
= LKCU: Overwritten Object Cleanup
:icons: font
:imagesdir: ../media/

[.lead]
This message is generated when StorageGRID removes an overwritten object that previously required cleanup to free up storage space. An object is overwritten when an S3 or Swift client writes an object to a path already containing a object. The removal process occurs automatically and in the background.

[options="header"]
|===
| Code| Field| Description
a|
CSIZ
a|
Content size
a|
The size of the object in bytes.
a|
LTYP
a|
Type of cleanup
a|
_Internal use only._
a|
LUID
a|
Removed Object UUID
a|
The identifier of the object that was removed.
a|
PATH
a|
S3 Bucket/Key or Swift Container/Object ID
a|
The S3 bucket name and S3 key name, or the Swift container name and Swift object identifier.
a|
SEGC
a|
Container UUID
a|
UUID of the container for the segmented object. This value is available only if the object is segmented.
a|
UUID
a|
Universally Unique Identifier
a|
The identifier of the object that still exists. This value is available only if the object has not been deleted.
|===
