---
permalink: audit/mgau-management-audit-message.html
sidebar: sidebar
keywords: storagegrid, audit, message, MGAU, Management audit message
summary: 'The Management category logs user requests to the Management API. Every request that is not a GET or HEAD request to the API logs a response with the username, IP, and type of request to the API.'
---
= MGAU: Management audit message
:icons: font
:imagesdir: ../media/

[.lead]
The Management category logs user requests to the Management API. Every request that is not a GET or HEAD request to the API logs a response with the username, IP, and type of request to the API.

[options="header"]
|===
| Code| Field| Description
a|
MDIP
a|
Destination IP Address
a|
The server (destination) IP address.
a|
MDNA
a|
Domain name
a|
The host domain name.
a|
MPAT
a|
Request PATH
a|
The request path.
a|
MPQP
a|
Request query parameters
a|
The query parameters for the request.
a|
MRBD
a|
Request body
a|
The content of the request body. While the response body is logged by default, the request body is logged in certain cases when the response body is empty. Because the following information is not available in the response body, it is taken from the request body for the following POST methods:

* Username and account ID in *POST authorize*
* New subnets configuration in *POST /grid/grid-networks/update*
* New NTP servers in *POST /grid/ntp-servers/update*
* Decommissioned server IDs in *POST /grid/servers/decommission*

*Note:* Sensitive information is either deleted (for example, an S3 access key) or masked with asterisks (for example, a password).

a|
MRMD
a|
Request method
a|
The HTTP request method:

* POST
* PUT
* DELETE
* PATCH

a|
MRSC
a|
Response code
a|
The response code.
a|
MRSP
a|
Response body
a|
The content of the response (the response body) is logged by default.

*Note:* Sensitive information is either deleted (for example, an S3 access key) or masked with asterisks (for example, a password).

a|
MSIP
a|
Source IP address
a|
The client (source) IP address.
a|
MUUN
a|
User URN
a|
The URN (uniform resource name) of the user who sent the request.
a|
RSLT
a|
Result
a|
Returns successful (SUCS) or the error reported by the backend.
|===
