---
permalink: audit/olst-system-detected-lost-object.html
sidebar: sidebar
keywords: storagegrid, audit, message, OLST, System Detected Lost Object
summary: 'This message is generated when the DDS service cannot locate any copies of an object within the StorageGRID system.'
---
= OLST: System Detected Lost Object
:icons: font
:imagesdir: ../media/

[.lead]
This message is generated when the DDS service cannot locate any copies of an object within the StorageGRID system.

[options="header"]
|===
| Code| Field| Description
a|
CBID
a|
Content Block Identifier
a|
The CBID of the lost object.
a|
NOID
a|
Node ID
a|
If available, the last known direct or nearline location of the lost object. It is possible to have just the Node ID without a Volume ID if the volume information is not available.
a|
PATH
a|
S3 Bucket/Key or Swift Container/Object ID
a|
If available, the S3 bucket name and S3 key name, or the Swift container name and Swift object identifier.
a|
RSLT
a|
Result
a|
This field has the value NONE. RSLT is a mandatory message field, but is not relevant for this message. NONE is used rather than SUCS so that this message is not filtered.
a|
UUID
a|
Universally Unique ID
a|
The identifier of the lost object within the StorageGRID system.
a|
VOLI
a|
Volume ID
a|
If available, the Volume ID of the Storage Node or Archive Node for the last known location of the lost object.
|===
