---
permalink: audit/ovwr-object-overwrite.html
sidebar: sidebar
keywords: storagegrid, audit, message, OVWR, Object Overwrite
summary: 'This message is generated when an external \(client-requested\) operation causes one object to be overwritten by another object.'
---
= OVWR: Object Overwrite
:icons: font
:imagesdir: ../media/

[.lead]
This message is generated when an external (client-requested) operation causes one object to be overwritten by another object.

[options="header"]
|===
| Code| Field| Description
a|
CBID
a|
Content Block Identifier (new)
a|
The CBID for the new object.
a|
CSIZ
a|
Previous Object Size
a|
The size, in bytes, of the object being overwritten.
a|
OCBD
a|
Content Block Identifier (previous)
a|
The CBID for the previous object.
a|
UUID
a|
Universally Unique ID (new)
a|
The identifier of the new object within the StorageGRID system.
a|
OUID
a|
Universally Unique ID (previous)
a|
The identifier for the previous object within the StorageGRID system.
a|
PATH
a|
S3 or Swift Object Path
a|
The S3 or Swift object path used for both the previous and new object
a|
RSLT
a|
Result Code
a|
Result of the Object Overwrite transaction. Result is always:

SUCS: Successful

|===
