---
permalink: audit/sdel-s3-delete.html
sidebar: sidebar
keywords: storagegrid, audit, message, SDEL, S3 DELETE
summary: 'When an S3 client issues a DELETE transaction, a request is made to remove the specified object or bucket. This message is issued by the server if the transaction is successful.'
---
= SDEL: S3 DELETE
:icons: font
:imagesdir: ../media/

[.lead]
When an S3 client issues a DELETE transaction, a request is made to remove the specified object or bucket. This message is issued by the server if the transaction is successful.

[options="header"]
|===
| Code| Field| Description
a|
CBID
a|
Content Block Identifier
a|
The unique identifier of the content block requested. If the CBID is unknown, this field is set to 0. Operations on buckets do not include this field.
a|
CNCH
a|
Consistency Control Header
a|
The value of the Consistency-Control HTTP request header, if present in the request.
a|
CNID
a|
Connection Identifier
a|
The unique system identifier for the TCP/IP connection.
a|
CSIZ
a|
Content Size
a|
The size of the deleted object in bytes. Operations on buckets do not include this field.
a|
DMRK
a|
Delete Marker Version ID
a|
The version ID of the delete marker created when deleting an object from a versioned bucket. Operations on buckets do not include this field.
a|
HTRH
a|
HTTP Request Header
a|
List of logged HTTP request header names and values as selected during configuration.

*Note:* `X-Forwarded-For` is automatically included if it is present in the request and if the `X-Forwarded-For` value is different from the request sender IP address (SAIP audit field).

a|
MTME
a|
Last Modified Time
a|
The Unix timestamp, in microseconds, indicating when the object was last modified.
a|
RSLT
a|
Result Code
a|
Result of the DELETE transaction. Result is always:

SUCS: Successful

a|
S3AI
a|
S3 tenant account ID (request sender)
a|
The tenant account ID of the user who sent the request. An empty value indicates anonymous access.
a|
S3AK
a|
S3 Access Key ID (request sender)
a|
The hashed S3 access key ID for the user that sent the request. An empty value indicates anonymous access.
a|
S3BK
a|
S3 Bucket
a|
The S3 bucket name.
a|
S3KY
a|
S3 Key
a|
The S3 key name, not including the bucket name. Operations on buckets do not include this field.
a|
S3SR
a|
S3 Subresource
a|
The bucket or object subresource being operated on, if applicable.
a|
SACC
a|
S3 tenant account name (request sender)
a|
The name of the tenant account for the user who sent the request. Empty for anonymous requests.
a|
SAIP
a|
IP address (request sender)
a|
The IP address of the client application that made the request.
a|
SBAC
a|
S3 tenant account name (bucket owner)
a|
The tenant account name for the bucket owner. Used to identify cross-account or anonymous access.
a|
SBAI
a|
S3 tenant account ID (bucket owner)
a|
The tenant account ID of the owner of the target bucket. Used to identify cross-account or anonymous access.
a|
SUSR
a|
S3 User URN (request sender)
a|
The tenant account ID and the user name of the user making the request. The user can either be a local user or an LDAP user. For example: `urn:sgws:identity::03393893651506583485:root`

Empty for anonymous requests.

a|
TIME
a|
Time
a|
Total processing time for the request in microseconds.
a|
TLIP
a|
Trusted Load Balancer IP Address
a|
If the request was routed by a trusted Layer 7 load balancer, the IP address of the load balancer.
a|
UUID
a|
Universally Unique Identifier
a|
The identifier of the object within the StorageGRID system.
a|
VSID
a|
Version ID
a|
The version ID of the specific version of an object that was deleted. Operations on buckets and objects in unversioned buckets do not include this field.
|===
