---
permalink: audit/svrf-object-store-verify-fail.html
sidebar: sidebar
keywords: storagegrid, audit, message, SVRF, Object Store Verify Fail
summary: 'This message is issued whenever a content block fails the verification process. Each time replicated object data is read from or written to disk, several verification and integrity checks are performed to ensure the data sent to the requesting user is identical to the data originally ingested into the system. If any of these checks fail, the system automatically quarantines the corrupt replicated object data to prevent it from being retrieved again.'
---
= SVRF: Object Store Verify Fail
:icons: font
:imagesdir: ../media/

[.lead]
This message is issued whenever a content block fails the verification process. Each time replicated object data is read from or written to disk, several verification and integrity checks are performed to ensure the data sent to the requesting user is identical to the data originally ingested into the system. If any of these checks fail, the system automatically quarantines the corrupt replicated object data to prevent it from being retrieved again.

[options="header"]
|===
| Code| Field| Description
a|
CBID
a|
Content Block Identifier
a|
The unique identifier of the content block which failed verification.
a|
RSLT
a|
Result Code
a|
Verification failure type:

CRCF: Cyclic redundancy check (CRC) failed.

HMAC: Hash-based message authentication code (HMAC) check failed.

EHSH: Unexpected encrypted content hash.

PHSH: Unexpected original content hash.

SEQC: Incorrect data sequence on disk.

PERR: Invalid structure of disk file.

DERR: Disk error.

FNAM: Bad file name.

|===
*Note:* This message should be monitored closely. Content verification failures can indicate attempts to tamper with content or impending hardware failures.

To determine what operation triggered the message, see the value of the AMID (Module ID) field. For example, an SVFY value indicates that the message was generated by the Storage Verifier module, that is, background verification, and STOR indicates that the message was triggered by content retrieval.
