---
permalink: audit/system_audit_messages.html
sidebar: sidebar
keywords: storagegrid, audit, message, messages, system, ECOC, ETAF, GNRG, GNUR, GTED, GTST, GTSU, IDEL, LKCU, LLST, OLST, ORLM, SADD, SADE, SVRF, SVRU, SYSD, SYST, SYSU, VLST
summary: 'You should be familiar with audit messages belonging to the system audit category. These are events related to the auditing system itself, grid node states, system-wide task activity \(grid tasks\), and service backup operations, so that you can address potential issues.'
---
= System audit messages
:icons: font
:imagesdir: ../media/

[.lead]
You should be familiar with audit messages belonging to the system audit category. These are events related to the auditing system itself, grid node states, system-wide task activity (grid tasks), and service backup operations, so that you can address potential issues.

[options="header"]
|===
| Code| Message title and description| See
a|
ECOC
a|
Corrupt Erasure Coded Data Fragment: Indicates that a corrupt erasure coded data fragment has been detected.
a|
xref:ecoc_corrupt_erasure_coded_data_fragment.adoc[ECOC: Corrupt Erasure Coded Data Fragment]
a|
ETAF
a|
Security Authentication Failed: A connection attempt using Transport Layer Security (TLS) failed.
a|
xref:etaf_security_authentication_failed.adoc[ETAF: Security Authentication Failed]
a|
GNRG
a|
GNDS Registration: A service updated or registered information about itself in the StorageGRID system.
a|
xref:gnrg_gnds_registration.adoc[GNRG: GNDS Registration]
a|
GNUR
a|
GNDS Unregistration: A service has unregistered itself from the StorageGRID system.
a|
xref:gnur_gnds_unregistration.adoc[GNUR: GNDS Unregistration]
a|
GTED
a|
Grid Task Ended: The CMN service finished processing the grid task.
a|
xref:gted_grid_task_ended.adoc[GTED: Grid Task Ended]
a|
GTST
a|
Grid Task Started: The CMN service started to process the grid task.
a|
xref:gtst_grid_task_started.adoc[GTST: Grid Task Started]
a|
GTSU
a|
Grid Task Submitted: A grid task was submitted to the CMN service.
a|
xref:gtsu_grid_task_submitted.adoc[GTSU: Grid Task Submitted]
a|
IDEL
a|
ILM Initiated Delete: This audit message is generated when ILM starts the process of deleting an object.
a|
xref:idel_ilm_initiated_delete.adoc[IDEL: ILM Initiated Delete]
a|
LKCU
a|
Overwritten Object Cleanup. This audit message is generated when an overwritten object is automatically removed to free up storage space.
a|
xref:lkcu_overwritten_object_cleanup.adoc[LKCU: Overwritten Object Cleanup]
a|
LLST
a|
Location Lost: This audit message is generated when a location is lost.
a|
xref:llst_location_lost.adoc[LLST: Location Lost]
a|
OLST
a|
Object Lost: A requested object cannot be located within the StorageGRID system.
a|
xref:olst_system_detected_lost_object.adoc[OLST: System Detected Lost Object]
a|
ORLM
a|
Object Rules Met: Object data is stored as specified by the ILM rules.
a|
xref:orlm_object_rules_met.adoc[ORLM: Object Rules Met]
a|
SADD
a|
Security Audit Disable: Audit message logging was turned off.
a|
xref:sadd_security_audit_disable.adoc[SADD: Security Audit Disable]
a|
SADE
a|
Security Audit Enable: Audit message logging has been restored.
a|
xref:sade_security_audit_enable.adoc[SADE: Security Audit Enable]
a|
SVRF
a|
Object Store Verify Fail: A content block failed verification checks.
a|
xref:svrf_object_store_verify_fail.adoc[SVRF: Object Store Verify Fail]
a|
SVRU
a|
Object Store Verify Unknown: Unexpected object data detected in the object store.
a|
xref:svru_object_store_verify_unknown.adoc[SVRU: Object Store Verify Unknown]
a|
SYSD
a|
Node Stop: A shutdown was requested.
a|
xref:sysd_node_stop.adoc[SYSD: Node Stop]
a|
SYST
a|
Node Stopping: A service initiated a graceful stop.
a|
xref:syst_node_stopping.adoc[SYST: Node Stopping]
a|
SYSU
a|
Node Start: A service started; the nature of the previous shutdown is indicated in the message.
a|
xref:sysu_node_start.adoc[SYSU: Node Start]
a|
VLST
a|
User Initiated Volume Lost: The `/proc/CMSI/Volume_Lost` command was run.
a|
xref:vlst_user_initiated_volume_lost.adoc[VLST: User Initiated Volume Lost]
|===

.Related information

xref:lkcu_overwritten_object_cleanup.adoc[LKCU: Overwritten Object Cleanup]
