---
permalink: audit/sysu-node-start.html
sidebar: sidebar
keywords: storagegrid, audit, message, SYSU, Node Start
summary: 'When a service is restarted, this message is generated to indicate if the previous shutdown was clean \(commanded\) or disorderly \(unexpected\).'
---
= SYSU: Node Start
:icons: font
:imagesdir: ../media/

[.lead]
When a service is restarted, this message is generated to indicate if the previous shutdown was clean (commanded) or disorderly (unexpected).

[options="header"]
|===
| Code| Field| Description
a|
RSLT
a|
Clean Shutdown
a|
The nature of the shutdown:

SUCS: System was cleanly shut down.

DSDN: System was not cleanly shut down.

VRGN: System was started for the first time after server installation (or re-installation).

|===
The message does not indicate if the host server was started, only the reporting service. This message can be used to:

* Detect discontinuity in the audit trail.
* Determine if a service is failing during operation (as the distributed nature of the StorageGRID system can mask these failures). Server Manager restarts a failed service automatically.
