---
permalink: audit/wdel-swift-delete.html
sidebar: sidebar
keywords: storagegrid, audit, message, WDEL, Swift DELETE
summary: 'When a Swift client issues a DELETE transaction, a request is made to remove the specified object or container. This message is issued by the server if the transaction is successful.'
---
= WDEL: Swift DELETE
:icons: font
:imagesdir: ../media/

[.lead]
When a Swift client issues a DELETE transaction, a request is made to remove the specified object or container. This message is issued by the server if the transaction is successful.

[options="header"]
|===
| Code| Field| Description
a|
CBID
a|
Content Block Identifier
a|
The unique identifier of the content block requested. If the CBID is unknown, this field is set to 0. Operations on containers do not include this field.
a|
CSIZ
a|
Content Size
a|
The size of the deleted object in bytes. Operations on containers do not include this field.
a|
HTRH
a|
HTTP Request Header
a|
List of logged HTTP request header names and values as selected during configuration.

*Note:* `X-Forwarded-For` is automatically included if it is present in the request and if the `X-Forwarded-For` value is different from the request sender IP address (SAIP audit field).

a|
MTME
a|
Last Modified Time
a|
The Unix timestamp, in microseconds, indicating when the object was last modified.
a|
RSLT
a|
Result Code
a|
Result of the DELETE transaction. Result is always:

SUCS: Successful

a|
SAIP
a|
IP address of requesting client
a|
The IP address of the client application that made the request.
a|
TIME
a|
Time
a|
Total processing time for the request in microseconds.
a|
TLIP
a|
Trusted Load Balancer IP Address
a|
If the request was routed by a trusted Layer 7 load balancer, the IP address of the load balancer.
a|
UUID
a|
Universally Unique Identifier
a|
The identifier of the object within the StorageGRID system.
a|
WACC
a|
Swift Account ID
a|
The unique account ID as specified by the StorageGRID system.
a|
WCON
a|
Swift Container
a|
The Swift container name.
a|
WOBJ
a|
Swift Object
a|
The Swift object identifier. Operations on containers do not include this field.
a|
WUSR
a|
Swift Account User
a|
The Swift account username that uniquely identifies the client performing the transaction.
|===
