---
permalink: audit/wdel-swift-delete.html
sidebar: sidebar
keywords: storagegrid, audit, message, WDEL, Swift DELETE
summary: 'When a Swift client issues a DELETE transaction, a request is made to remove the specified object or container. This message is issued by the server if the transaction is successful.'
---
= WDEL: Swift DELETE
:icons: font
:imagesdir: ../media/

[.lead]
When a Swift client issues a DELETE transaction, a request is made to remove the specified object or container. This message is issued by the server if the transaction is successful.

[cols="1a,1a,4a" options="header"]
|===
| Code| Field| Description
|
CBID
|
Content Block Identifier
|
The unique identifier of the content block requested. If the CBID is unknown, this field is set to 0. Operations on containers do not include this field.
|
CSIZ
|
Content Size
|
The size of the deleted object in bytes. Operations on containers do not include this field.
|
HTRH
|
HTTP Request Header
|
List of logged HTTP request header names and values as selected during configuration.

*Note:* `X-Forwarded-For` is automatically included if it is present in the request and if the `X-Forwarded-For` value is different from the request sender IP address (SAIP audit field).

|
MTME
|
Last Modified Time
|
The Unix timestamp, in microseconds, indicating when the object was last modified.
|
RSLT
|
Result Code
|
Result of the DELETE transaction. Result is always:

SUCS: Successful

|
SAIP
|
IP address of requesting client
|
The IP address of the client application that made the request.

|SGRP
|Site (Group)
|If present, the object was deleted at the site specified, which is not the site where the object was ingested.

|
TIME
|
Time
|
Total processing time for the request in microseconds.
|
TLIP
|
Trusted Load Balancer IP Address
|
If the request was routed by a trusted Layer 7 load balancer, the IP address of the load balancer.
|
UUID
|
Universally Unique Identifier
|
The identifier of the object within the StorageGRID system.
|
WACC
|
Swift Account ID
|
The unique account ID as specified by the StorageGRID system.
|
WCON
|
Swift Container
|
The Swift container name.
|
WOBJ
|
Swift Object
|
The Swift object identifier. Operations on containers do not include this field.
|
WUSR
|
Swift Account User
|
The Swift account username that uniquely identifies the client performing the transaction.
|===
