sidebar:
  entries:
    - title: StorageGRID 11.5 Docs
      url: /index.html
    - section: release-notes
    - section: primer
    - section: network
    - section: sg100-1000
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
    - section: tenant
    - section: s3
    - section: swift
    - section: monitor
    - section: expand
    - section: maintain
    - section: audit
    - title: Earlier versions
      url: /earlier-versions.html
    - title: Legal notices
      url: /legal-notices.html


homepage:
  tiles:
    - title: Get started
      links:
      - title: Release notes
        url: /release-notes/index.html
      - title: What's new
        url: /upgrade/whats_new.html
      - title: Grid primer
        url: /primer/index.html
      - title: Network guidelines
        url: /network/index.html
    - title: Install & maintain hardware
      links:
      - title: SG100 & SG1000 services appliances
        url: /sg100-1000/index.html
      - title: SG6000 storage appliances
        url: /sg6000/index.html
      - title: SG5700 storage appliances
        url: /sg5700/index.html
      - title: SG5600 storage appliances
        url: /sg5600/index.html
    - title: Install & upgrade software
      links:
      - title: Install Red Hat Enterprise Linux or CentOS
        url: /rhel/index.html
      - title: Install Ubuntu or Debian
        url: /ubuntu/index.html
      - title: Install VMware
        url: /vmware/index.html
      - title: Upgrade software
        url: /upgrade/index.html
    - title: Configure the grid
      links:
      - title: Administer StorageGRID
        url: /admin/index.html
      - title: Manage objects with ILM
        url: /ilm/index.html
      - title: System hardening
        url: /harden/index.html
      - title: Configure StorageGRID for FabricPool
        url: /fabricpool/index.html
    - title: Manage objects
      links:
      - title: Use a tenant account
        url: /tenant/index.html
      - title: Use S3
        url: /s3/index.html
      - title: Use Swift
        url: /swift/index.html
    - title: Monitor & maintain
      links:
      - title: Monitor & troubleshoot
        url: /monitor/index.html
      - title: Expand your grid
        url: /expand/index.html
      - title: Maintain & recover
        url: /maintain/index.html
      - title: Review audit logs
        url: /audit/index.html
    - title: Demos & tutorials
      links:
      - title: StorageGRID video library
        url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7nh2wGRA65iulXhtXwLiqrY
      - title: NetApp learning services
        url: https://www.netapp.com/support-and-training/netapp-university/
    - title: More resources
      links:
      - title: StorageGRID support page
        url: https://mysupport.netapp.com/site/products/all/details/5d9f1107e01d9c0001ee50f6/downloads-tab
      - title: NetApp Interoperability Matrix Tool (IMT)
        url: https://mysupport.netapp.com/matrix
      - title: StorageGRID knowledge base
        url: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID
      - title: NetApp blog
        url: https://netapp.com/blog/
      - title: NetApp community
        url: https://community.netapp.com/
    - title: Earlier versions
      links:
      - title: StorageGRID 11.4 documentation
        url: https://docs.netapp.com/sgws-114/index.jsp
      - title: StorageGRID 11.3 documentation
        url: https://docs.netapp.com/sgws-113/index.jsp
      - title: StorageGRID 11.2 documentation
        url: https://docs.netapp.com/sgws-112/index.jsp
