---
settings:
  name: StorageGRID
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: true
    lipi_enabled: false
#  versions:
    # Current repo stanza comes first
#    - name: StorageGRID
#      url: /storagegrid-116
#      version-number: "11.6"
    # Additional releases newest to oldest
    # Release in GitHub (typical)
#    - name: StorageGRID
#      url: /storagegrid-115
#      version-number: "11.5"
    # Release not in GitHub
#    - name: StorageGRID
#      url: https://mysupport.netapp.com/documentation/docweb/index.html?productID=63374&language=en-US
#      version-number: "11.4"
    # Release not in GitHub
#    - name: StorageGRID
#      url: https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61023&archive=true
#      version-number: "11.3"
sidebar:
  entries:
    - title: StorageGRID 11.6 Docs
      url: /index.html
    - section: release-notes
    - title: Get started
      entries:
      - section: primer
      - section: network
    - title: Install and maintain appliance hardware
      entries:
      - section: sg100-1000
      - section: sg6000
      - section: sg5700
      - section: sg5600
    - title: Install and upgrade software
      entries:
      - section: upgrade
      - section: rhel
      - section: ubuntu
      - section: vmware
    - title: Perform system administration
      entries:  
      - section: admin
      - section: ilm
      - section: harden
      - section: fabricpool
    - title: Use StorageGRID
      entries: 
      - section: tenant
      - section: s3
      - section: swift
    - title: Monitor and maintain StorageGRID
      entries:  
      - section: monitor
      - section: expand
      - section: maintain
      - section: audit
    - title: Enable StorageGRID
      url: /storagegrid-enable.html
    - title: Earlier versions
      url: /earlier-versions.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family