---
sidebar: sidebar
permalink: storagegrid-enable.html
keywords: storagegrid, how to enable, third-party solutions, tools, applications, examples
summary: "Learn how to enable applications and tools in your environment and test features with StorageGRID."
---
= How to enable StorageGRID in your environment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Go to https://docs.netapp.com/us-en/storagegrid-enable/index.html[How to enable StorageGRID in your environment^] to learn how to enable applications and tools in your environment and test features with StorageGRID. 

The *storagegrid-enable* documentation site provides examples and cookbooks that expand upon the product documentation in this site, and it describes some next steps in evaluating and integrating with StorageGRID.

Some of the information included:

* Lists of validated third-party solutions for past and current StorageGRID releases.
* Product feature guides. For example, these guides provide all the information you need to create Cloud Storage Pools.
* Tool and application guides.
* API examples for using StorageGRID features such as S3 encryption and S3 Object Lock.



