---
permalink: upgrade/checking_systems_condition_before_upgrading_software.html
sidebar: sidebar
keywords:
summary: 'Before upgrading a StorageGRID system, you must verify the system is ready to accommodate the upgrade. You must ensure that the system is running normally and that all grid nodes are operational.'
---
= Checking the system's condition before upgrading software
:icons: font
:imagesdir: ../media/

[.lead]
Before upgrading a StorageGRID system, you must verify the system is ready to accommodate the upgrade. You must ensure that the system is running normally and that all grid nodes are operational.

.Steps
. Sign in to the Grid Manager using a supported browser.
. Check for and resolve any active alerts.
+
For information about specific alerts, see the monitoring and troubleshooting instructions.

. Confirm that no conflicting grid tasks are active or pending.
 .. Select *Support* > *Tools* > *Grid Topology*.
 .. Select *site* > *_primary Admin Node_* > *CMN* > *Grid Tasks* > *Configuration*.
+
Information lifecycle management evaluation (ILME) tasks are the only grid tasks that can run concurrently with the software upgrade.

 .. If any other grid tasks are active or pending, wait for them to finish or release their lock.
+
NOTE: Contact technical support if a task does not finish or release its lock.
. Refer to the lists of internal and external ports in the 11.5 version of the networking guidelines, and ensure that all required ports are opened before you upgrade.
+
IMPORTANT: If you have opened any custom firewall ports, you are notified during the upgrade precheck. You must contact technical support before proceeding with the upgrade.

.Related information

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-troubleshooting/home.html[Monitoring and troubleshooting StorageGRID]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-admin/home.html[Administering StorageGRID]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-maint/home.html[Recovery and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-network/home.html[StorageGRID networking guidelines]
