---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html
sidebar: sidebar
keywords: upgrade, grid tasks, firewall, ports
summary: 'Before upgrading a StorageGRID system, you must verify the system is ready to accommodate the upgrade. You must ensure that the system is running normally and that all grid nodes are operational.'
---
= Check the system's condition
:icons: font
:imagesdir: ../media/

[.lead]
Before upgrading a StorageGRID system, you must verify the system is ready to accommodate the upgrade. You must ensure that the system is running normally and that all grid nodes are operational.

.Steps
. Sign in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
. Check for and resolve any active alerts.
+
For information about specific alerts, see the xref:../monitor/alerts-reference.adoc[Alerts reference].

. Confirm that no conflicting grid tasks are active or pending.
 .. Select *SUPPORT* > *Tools* > *Grid topology*.
 .. Select *_site_* > *_primary Admin Node_* > *CMN* > *Grid Tasks* > *Configuration*.
+
Information lifecycle management evaluation (ILME) tasks are the only grid tasks that can run concurrently with the software upgrade.

 .. If any other grid tasks are active or pending, wait for them to finish or release their lock.
+
NOTE: Contact technical support if a task does not finish or release its lock.

. Refer to xref:../network/internal-grid-node-communications.adoc[Internal grid node communications] and xref:../network/external-communications.adoc[External communications] to ensure that all required ports for StorageGRID 11.6 are opened before you upgrade.
+
IMPORTANT: If you have opened any custom firewall ports, you are notified during the upgrade precheck. You must contact technical support before proceeding with the upgrade.