---
permalink: upgrade/estimating-time-to-complete-upgrade.html
sidebar: sidebar
keywords: upgrade, time estimate, duration, cassandra upgrade
summary: 'When planning an upgrade to StorageGRID 11.6, you must consider when to upgrade, based on how long the upgrade might take. You must also be aware of which operations you can and cannot perform during each stage of the upgrade.'
---
= Estimate the time to complete an upgrade
:icons: font
:imagesdir: ../media/

[.lead]
When planning an upgrade to StorageGRID 11.6, you must consider when to upgrade, based on how long the upgrade might take. You must also be aware of which operations you can and cannot perform during each stage of the upgrade.

.About this task
The time required to complete a StorageGRID upgrade depends on a variety of factors such as client load and hardware performance.

The table summarizes the main upgrade tasks and lists the approximate time required for each task. The steps after the table provide instructions you can use to estimate the upgrade time for your system.

[cols="1a,1a,1a,a" options="header"]
|===
| Upgrade task| Description| Approximate time required| During this task

|Start Upgrade Service
|Upgrade prechecks are run, the software file is distributed, and the upgrade service is started.
|3 minutes per grid node, unless validation errors are reported
|As required, you can run the upgrade prechecks manually before the scheduled upgrade maintenance window.


|Upgrade Grid Nodes (primary Admin Node)
|The primary Admin Node is stopped, upgraded, and restarted.
|30 minutes to 1 hour, with SG100 and SG1000 appliance nodes requiring the most time.
|You cannot access the primary Admin Node. Connection errors are reported, which you can ignore.

|Upgrade Grid Nodes (all other nodes)
|The software on all other grid nodes is upgraded, in the order in which you approve the nodes. Every node in your system will be brought down one at a time for several minutes each.
|15 minutes to 1 hour per node, with appliance nodes requiring the most time

*Note:* For appliance nodes, the StorageGRID Appliance Installer is automatically updated to the latest release.

|
* Do not change the grid configuration.
* Do not change the audit level configuration.
* Do not update the ILM configuration.
* You are prevented from performing other maintenance procedures, such as hotfix, decommission, or expansion.
+
*Note:* If you need to perform a recovery, contact technical support.

|Enable Features
|The new features for the new version are enabled.
|Less than 5 minutes
|
* Do not change the grid configuration.
* Do not change the audit level configuration.
* Do not update the ILM configuration.
* You cannot perform another maintenance procedure.

|Upgrade Database
|The upgrade process checks each node to verify that the Cassandra database does not need to be updated.
|10 seconds per node or a few minutes for the entire grid
|The upgrade from StorageGRID 11.5 to 11.6 does not require a Cassandra database upgrade; however, the Cassandra service will be stopped and restarted on each Storage Node. 

For future StorageGRID feature releases, the Cassandra database update step might take several days to complete.

|Final Upgrade Steps
|Temporary files are removed and the upgrade to the new release completes.
|5 minutes
|When the *Final Upgrade Steps* task completes, you can perform all maintenance procedures.

|===

.Steps

. Estimate the time required to upgrade all grid nodes.
 .. Multiply the number of nodes in your StorageGRID system by 1 hour/node.
+
As a general rule, appliance nodes take longer to upgrade than software-based nodes.
 
 .. Add 1 hour to this time to account for the time required to download the `.upgrade` file, run precheck validations, and complete the final upgrade steps.
. If you have Linux nodes, add 15 minutes for each node to account for the time required to download and install the RPM or DEB package.
. Calculate the total estimated time for the upgrade by adding the results of steps 1 and 2.

== Example: Estimated time to upgrade to StorageGRID 11.6

Suppose your system has 14 grid nodes, of which 8 are Linux nodes.

. Multiply 14 by 1 hour/node.

. Add 1 hour to account for the download, precheck, and final steps.
+
The estimated time to upgrade all nodes is 15 hours.

. Multiply 8 by 15 minutes/node to account for the time to install the RPM or DEB package on the Linux nodes.
+
The estimated time for this step is 2 hours.

. Add the values together.
+
You should allow up to 17 hours to complete the upgrade of your system to StorageGRID 11.6.0.