---
permalink: upgrade/index.html
sidebar: sidebar
keywords: storagegrid software upgrade
summary: 'Use these instructions to upgrade a StorageGRID system to a new release.'
---
= Upgrade StorageGRID software: Overview
:icons: font
:imagesdir: ../media/

[.lead]
Use these instructions to upgrade a StorageGRID system to a new release.

== About these instructions
These instructions describe what's new in StorageGRID 11.6 and provide step-by-step instructions for upgrading all nodes in your StorageGRID system to the new release.  

== Before you begin
Review these topics to learn about the new features and enhancements in StorageGRID 11.6, determine whether any features have been deprecated or removed, and find out about changes to StorageGRID APIs.

* xref:whats-new.adoc[What's new in StorageGRID 11.6]
* xref:removed-or-deprecated-features.adoc[Removed or deprecated features]
* xref:changes-to-grid-management-api.adoc[Changes to the Grid Management API]
* xref:changes-to-tenant-management-api.adoc[Changes to the Tenant Management API]
