---
permalink: upgrade/obtaining-required-materials-for-software-upgrade.html
sidebar: sidebar
keywords: upgrade, requirements, rhel, red hat, linux, centOS, ubuntu, debian
summary: 'Before you begin the software upgrade, you must obtain all required materials so you can complete the upgrade successfully.'
---
= Obtaining the required materials for a software upgrade
:icons: font
:imagesdir: ../media/

[.lead]
Before you begin the software upgrade, you must obtain all required materials so you can complete the upgrade successfully.

[cols="1a,3a" options="header"]
|===
| Item| Notes
a|
StorageGRID upgrade files
a|
You must download the required files to your service laptop:

* *All platforms*: `.upgrade` file
* *Any node on Red Hat Enterprise Linux or CentOS*: `.upgrade` file and RPM file (`.zip` or `.tgz`)
* *Any node on Ubuntu or Debian*: `.upgrade` file and DEB file (`.zip` or `.tgz`)

a|
Service laptop
a|
The service laptop must have:

* Network port
* SSH client (for example, PuTTY)

a|
Supported web browser
a|
You must confirm that the web browser on the service laptop is supported for use with StorageGRID 11.6.

xref:../admin/web-browser-requirements.adoc[Web browser requirements]

*Note:* Browser support has changed for StorageGRID 11.6. Confirm you are using a supported version.

a|
Recovery Package (`.zip`) file
a|
Before upgrading, you should download the most recent Recovery Package file in case any problems occur during the upgrade.

After you upgrade the primary Admin Node, you must download a new copy of the Recovery Package file and save it in a safe location. The updated Recovery Package file allows you to restore the system if a failure occurs.

xref:downloading-recovery-package.adoc[Downloading the Recovery Package]

a|
`Passwords.txt` file
a|
This file is included in the SAID package, which is part of the Recovery Package `.zip` file. You must obtain the latest version of the Recovery Package.
a|
Provisioning passphrase
a|
The passphrase is created and documented when the StorageGRID system is first installed. The provisioning passphrase is not listed in the `Passwords.txt` file.
a|
Related documentation
a|

* Release notes for StorageGRID 11.6. Be sure to read these carefully before starting the upgrade.
* Instructions for administering StorageGRID
* If you are upgrading a Linux deployment, the StorageGRID installation instructions for your Linux platform.
* Other StorageGRID documentation, as required.

|===
.Related information

xref:../admin/web-browser-requirements.adoc[Web browser requirements]

xref:../admin/index.adoc[Administer StorageGRID]

xref:../rhel/index.adoc[Install Red Hat Enterprise Linux or CentOS]

xref:../ubuntu/index.adoc[Install Ubuntu or Debian]

xref:../vmware/index.adoc[Install VMware]

xref:downloading-storagegrid-upgrade-files.adoc[Downloading the StorageGRID upgrade files]

xref:downloading-recovery-package.adoc[Downloading the Recovery Package]

xref:../release-notes/index.adoc[Release notes]
