---
permalink: upgrade/performing-upgrade.html
sidebar: sidebar
keywords: upgrade, software upgrade
summary: 'The Software Upgrade page guides you through the process of uploading the required file and upgrading all of the grid nodes in your StorageGRID system.'
---
= Performing the upgrade
:icons: font
:imagesdir: ../media/

[.lead]
The Software Upgrade page guides you through the process of uploading the required file and upgrading all of the grid nodes in your StorageGRID system.

.What you'll need

You are aware of the following:

* You must upgrade all grid nodes for all data center sites from the primary Admin Node, using the Grid Manager.
* To detect and resolve issues, you can manually run the upgrade prechecks before starting the actual upgrade. The same prechecks are performed when you start the upgrade. Precheck failures will stop the upgrade process and might require technical support involvement to resolve.
* When you start the upgrade, the primary Admin Node is upgraded automatically.
* After the primary Admin Node has been upgraded, you can select which grid nodes to upgrade next.
* You must upgrade all grid nodes in your StorageGRID system to complete the upgrade, but you can upgrade individual grid nodes in any order. You can select individual grid nodes, groups of grid nodes, or all grid nodes. You can repeat the process of selecting grid nodes as many times as necessary, until all grid nodes at all sites are upgraded.
* When the upgrade starts on a grid node, the services on that node are stopped. Later, the grid node is rebooted. Do not approve the upgrade for a grid node unless you are sure that node is ready to be stopped and rebooted.
* When all grid nodes have been upgraded, new features are enabled and you can resume operations; however, you must wait to perform a decommission or expansion procedure until the background *Upgrade Database* task and the *Final Upgrade Steps* task have completed.
* You must complete the upgrade on the same hypervisor platform you started with.

.Steps
. xref:linux-installing-rpm-or-deb-package-on-all-hosts.adoc[Linux: Installing the RPM or DEB package on all hosts]
. xref:starting-upgrade.adoc[Starting the upgrade]
. xref:upgrading-grid-nodes-and-completing-upgrade.adoc[Upgrading grid nodes and completing the upgrade]
. xref:increasing-metadata-reserved-space-setting.adoc[Increasing the Metadata Reserved Space setting]

.Related information

xref:../admin/index.adoc[Administer StorageGRID]

xref:estimating-time-to-complete-upgrade.adoc[Estimating the time to complete an upgrade]
