---
permalink: upgrade/troubleshooting-user-interface-issues.html
sidebar: sidebar
keywords: grid manager, tenant manager, error, browser
summary: 'You might see issues with the Grid Manager or the Tenant Manager after upgrading to a new version of StorageGRID software.'
---
= Troubleshoot user interface issues
:icons: font
:imagesdir: ../media/

[.lead]
You might see issues with the Grid Manager or the Tenant Manager after upgrading to a new version of StorageGRID software.

== Web interface does not respond as expected

The Grid Manager or the Tenant Manager might not respond as expected after StorageGRID software is upgraded.

If you experience issues with the web interface:

* Make sure you are using a xref:../admin/web-browser-requirements.adoc[supported web browser].
+
NOTE: Browser support typically changes for each StorageGRID release.
* Clear your web browser cache.
+
Clearing the cache removes outdated resources used by the previous version of StorageGRID software, and permits the user interface to operate correctly again. For instructions, see the documentation for your web browser.