---
permalink: upgrade/troubleshooting-upgrade-issues.html
sidebar: sidebar
keywords: upgrade, troubleshoot, troubleshooting, errors, upgrade precheck
summary: 'If the upgrade does not complete successfully, you might able to resolve the issue yourself. If you cannot resolve an issue, you should gather the required information before contacting technical support.'
---
= Troubleshooting upgrade issues
:icons: font
:imagesdir: ../media/

[.lead]
If the upgrade does not complete successfully, you might able to resolve the issue yourself. If you cannot resolve an issue, you should gather the required information before contacting technical support.

The following sections describe how to recover from situations where the upgrade has partially failed. Contact technical support if you cannot resolve an upgrade issue.

== Upgrade precheck errors

To detect and resolve issues, you can manually run the upgrade prechecks before starting the actual upgrade. Most precheck errors provide information about how to resolve the issue. If you need help, contact technical support.

== Provisioning failures

If the automatic provisioning process fails, contact technical support.

== Grid node crashes or fails to start

If a grid node crashes during the upgrade process or fails to start successfully after the upgrade finishes, contact technical support to investigate and to correct any underlying issues.

== Ingest or data retrieval is interrupted

If data ingest or retrieval is unexpectedly interrupted when you are not upgrading a grid node, contact technical support.

== Database upgrade errors

If the database upgrade fails with an error, retry the upgrade. If it fails again, contact technical support.

.Related information

xref:checking-systems-condition-before-upgrading-software.adoc[Checking the system's condition before upgrading software]
