---
permalink: upgrade/whats-new.html
sidebar: sidebar
keywords: what is new in StorageGRID 11.6
summary: 'StorageGRID 11.6 introduces multi VLAN support, support for S3 Select, syslog transfer, ability to change SSH passwords, and user interface enhancements to the Grid Manager.'
---
= What's new in StorageGRID 11.6
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID 11.6 introduces multi VLAN support, support for S3 Select, syslog transfer, ability to change SSH passwords, and usability enhancements to the Grid Manager.

== Kathy's what's new changes

=== Support for multiple VLAN interfaces
You can now configure VLAN interfaces from the Grid Manager (*CONFIGURATION* > *Network* > *VLAN interfaces*).

.Learn more
* xref:../admin/index.adoc[Administer StorageGRID]

=== Updates to high availability (HA) groups
The user interface for creating an HA group was revised.

A new optional field, *Gateway CIDR*, allows you to specify a subnet IP address and prefix length for each HA group. All virtual IP (VIP) addresses must belong to this subnet. The new field removes these previous limitations for HA groups:

* Interfaces can now be configured with DHCP. They no longer need to be configured with fixed (static) IP addresses. 

* Interfaces no longer need to belong to the Grid Network (eth0) or the Client Network (eth2). They can now belong to completely different subnets, including the Admin Network or a virtual LAN (VLAN).

=== Updates to load balancer endpoints

The user interface for creating a load balancer endpoint was revised.

=== New upgrade process

//more text goes here//

A new *Check for software updates* check box was added to the AutoSupport page (*SUPPORT* > *Tools* > *AutoSupport*). By default, StorageGRID contacts NetApp to determine if software updates are available for your system, but you can disable the check box as required. 

.Learn more
* xref:../admin/configure-autosupport-grid-manager.adoc[Configure AutoSupport]

=== Usability enhancements 
The Grid Manager user interface has been redesigned.

* New sidebar
* New menu structure. CONFIGURATION menu reorganized with new section for Security.
* New Nodes page
* New wizards guide you through complex configurations, including creating a tenant, configuring load balancer endpoints, and configuring high availability (HA) groups.

=== New alerts

The following new alerts were added for StorageGRID 11.6:

* Audit logs are being added to the in-memory queue
* Cassandra table corruption
* EC rebalance failure
* EC repair failure
* External syslog CA certificate expiration
* External syslog client certificate expiration
* External syslog server certificate expiration
* External syslog server forwarding error
* Identity federation synchronization failure for a tenant
* Logs are being added to the on-disk queue
* Low read-only watermark override
* Object existence check failed
* Object existence check stalled

.Learn more
* xref:../monitor/index.adoc[Monitor and troubleshoot]

=== Changes to the audit messages
* A new *BUID* field was added to the ORLM: Object Rules Met audit message. The *BUID* field shows the bucket ID, which is used for internal operations. The new field appears only if the message status is PRGD.

* A new *SGRP* field was added to the following audit messages. The *SGRP*  field is present only if an object was deleted at a different site than where it was ingested.
** IDEL: ILM Initiated Delete
** OVWR: Object Overwrite
** SDEL: S3 DELETE
** WDEL: Swift DELETE

.Learn more
* xref:../audit/index.adoc[Review audit logs]

=== Storage volume watermarks now optimized

In previous releases, the settings for the *Storage Volume Soft Read-Only Watermark*, *Storage Volume Hard Read-Only Watermark*, and *Storage Volume Read-Write Watermark* applied to every storage volume on every Storage Node. Starting in StorageGRID 11.6, StorageGRID can optimize these watermarks for each storage volume, based on the size of the Storage Node and the relative capacity of the volume. The optimized watermarks will be larger than the previous default settings.

Optimized watermarks are automatically applied to all new and most upgraded StorageGRID 11.6 systems, unless either of the following is true:

* More than 90% of Storage Nodes would become read-only if optimized watermarks were applied. StorageGRID will not change watermark settings if doing so would make the system unable to accept new data.

* A storage volume watermark is set to a custom value (*CONFIGURATION* > *System* > *Storage options*). StorageGRID will not override custom watermark settings with optimized values. 

If you use custom watermarks, the *Low read-only watermark override* alert might be triggered after you upgrade. This alert lets you know if your custom watermark settings are too small. See xref:../upgrade/resolve-low-watermark-alert.adoc[Resolve Low read-only watermark override alerts] for details. 

As part of this change, two Prometheus metrics were added:

* `storagegrid_storage_volume_minimum_optimized_soft_readonly_watermark`
* `storagegrid_storage_volume_maximum_optimized_soft_readonly_watermark`

.Learn more
* xref:../admin/what-storage-volume-watermarks-are.adoc[What are storage volume watermarks?]

== Changes to S3 REST API support

=== GET object and HEAD object support for multipart objects

Previously, StorageGRID did not support the `partNumber` request parameter in GET Object or HEAD Object requests. Starting in StorageGRID 11.6, you can now issue GET and HEAD requests to retrieve a specific part of a multipart object. GET and HEAD Object also support the `x-amz-mp-parts-count` response element to indicate how many parts an object has.

.Learn more
* xref:../s3/index.adoc[Use S3]

=== Updates to Tenant Accounts permission
Admin users who belong to a group with the Tenant Accounts permission can now view existing traffic classification policies. Previously, users were required to have Root Access permission to view these metrics.

=== New "Estimated time to completion" chart for EC rebalance and EC repair jobs
You can now view the estimated time to completion and the completion percentage for a current EC rebalance or EC repair job. Select *SUPPORT* > *Tools* > *Metrics*. Then, select *EC Overview* in the Grafana section. Look at the *Grid EC Job Estimated Time to Completion* and *Grid EC Job Percentage Completed* dashboards.

=== Diagnostics page sorted by severity
The results on the Diagnostics page (*SUPPORT* > *Tools* > *Diagnostics*) are now sorted by severity (Caution, Attention, and then Normal). Within each severity, the results are sorted alphabetically.

=== Prometheus storage no longer limited to 31 days
Previously, Prometheus metrics were stored on Admin Nodes for 31 days. Now, metrics are stored until the space reserved for Prometheus data is full, which can significantly increase how long historical metrics are available.

When the `/var/local/mysql_ibdata/` volume reaches capacity, the oldest metrics are deleted first.

=== New option for replicated data repairs

You can now add the `show-replicated-repair-status` option to the `repair-data` command to see an estimated percent completion for a replicated repair. 

IMPORTANT: The `show-replicated-repair-status` option is available for technical preview in StorageGRID 11.6. This feature is under development, and the value returned might be incorrect or delayed. To determine if a repair is complete, continue to use *Awaiting – All*, *Repairs Attempted (XRPA*), and *Scan Period — Estimated (XSCM)* as described in the recovery procedures.

=== Parallel S3 multipart downloads 
//get information from Raptor team

== Kevin's what's new changes

=== Available consistency control now includes GET operations

The Available consistency control behaves the same as the “read-after-new-write” consistency level, but provides eventual consistency for HEAD and GET operations. The Available consistency control offers higher availability for HEAD and GET operations than “read-after-new-write” if Storage Nodes are unavailable. Differs from Amazon S3 consistency guarantees for HEAD and GET operations.

.Learn more
* xref:../s3/index.adoc[Use S3]

=== Access security certificates from single location

Security certificate information and access has been consolidated in a single location in the Grid Manager at *CONFIGURATON* > *Security* > *Certificates*.

.Learn more
* xref:../admin/using-storagegrid-security-certificates.adoc[About security certificates] 

=== Default bucket retention period for S3 Object Lock

If the S3 Object Lock default retention mode is enabled for a bucket, you can specify a default retention period for each object that you add to the bucket.

.Learn more
* xref:../s3/using-s3-object-lock.adoc[Using S3 Object Lock] 

=== Google Cloud Platform (GCP) support

You can now use the Google Cloud Platform (GCP) as an endpoint for Cloud Storage Pools and the CloudMirror platform service.

.Learn more
* xref:../tenant/specifying-urn-for-platform-services-endpoint.adoc[Specify the URN for a platform services endpoint]
* xref:../ilm/creating-cloud-storage-pool.adoc[Create a Cloud Storage Pool] 

=== AWS Commercial Cloud Services (C2S) support for CloudMirror

You can now use AWS Commercial Cloud Services (C2S) endpoints for CloudMirror replication.

.Learn more
* xref:../tenant/creating-platform-services-endpoint.adoc[Create a platform services endpoint]


== Lisa's what's new changes

=== Object existence check added to maintenance tasks
The foreground verification feature has been renamed to object existence check. This feature has been redesigned to reduce runtime by at least three times. The redesign also allows for ease of use without technical support intervention. Object existence check is available from the Grid Manager at *MAINTENANCE > Object existence check*.

=== Enhancements to the Grid Manager 
The appearance and organization of the Grid Manager user interface has been completely redesigned to improve user experience.

The Nodes page has been redesigned to include a summary page that contains a tabular list of all sites and nodes in the grid. The table includes summary information, such as object data used and object metadata used. An alert icon is displayed next to any node that has an active alert.

.Learn more
* xref:../admin/index.adoc[Administer StorageGRID]

== Object metadata allowed space increased
If you are installing or upgrading to StorageGRID 11.6, the maximum allowed metadata space for Storage Nodes will be increased to 3.96 TB (from 2.64 TB) for higher capacity nodes, which are nodes with an actual reserved space for metadata of more than 4 TB. This new value might allow more object metadata to be stored on each Storage Node if allowed by your xref:../admin/managing-object-metadata-storage.adoc#metadata-reserved-space-setting[Metadata Reserved Space setting].

NOTE: If you have not already done so, and if your Storage Nodes have enough RAM and sufficient space on volume 0, you can xref:../upgrade/increasing-metadata-reserved-space-setting.adoc[manually increase the Metadata Reserved Space setting] up to 8 TB after you install or upgrade.

== S3 Select feature added

S3 tenants can now use S3 Select to issue SelectObjectContent requests to individual objects. This feature provides an efficient way to search through large amounts of data without having to deploy a database and associated resources to enable searches. It also reduces the cost and latency of retrieving data. Only certain tenant accounts can use S3 Select, and the grid administrator must enable this feature for a tenant.

xref:../monitor/reviewing-support-metrics.adoc[Grafana charts] for S3 Select operations have also been added.

Learn more:

xref:../admin/manage-s3-select-for-tenant-accounts.adoc[Manage S3 Select for tenant accounts]

xref:../s3/use-s3-select.adoc[Use S3 Select]

== Paul's what's new changes

=== Ability to change node console passwords
You now can use the Grid Manager to change the node console passwords. These passwords are used to log in to a node as “admin” using SSH, or to the root user on a VM/physical console connection. (*CONFIGURATION* > *Access control* > *Grid passwords*). 

.Learn more
* xref:../admin/change-node-console-password.adoc[Change node console passwords]

=== Add an external syslog server and change log destinations
You now can use the Grid Manager to add an external syslog server to store and manage system logs, security logs and application logs collected from the nodes in your grid. Additionally, you can configure StorageGRID to send test messages to a newly configured external syslog server to help you validate your log collection infrastructure. You also can now change the destinations of your audit information. (*CONFIGURATION* > *Monitoring* > *Audit and syslog server*). 

.Learn more
* xref:../monitor/configure-audit-messages.adoc[Configure audit messages and log destinations]

=== Ability to pause the SANtricity upgrade process and skip some nodes
While you are performing a SANtricity OS upgrade, you can now pause the upgrade and skip upgrading some nodes so you can finish the upgrade at a later time. (*MAINTENANCE* > *System* > *Software update*). 

.Learn more
* xref:../sg5600/upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg5700.adoc[Upgrading SANtricity OS on storage controllers using the grid manager (SG5600)]
* xref:../sg5700/upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg5700.adoc[Upgrading SANtricity OS on storage controllers using the grid manager (SG5700)]
* xref:../sg6000/upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg5700.adoc[Upgrading SANtricity OS on storage controllers using the grid manager (SG6000]

== StorageGRID documentation changes

* The documentation center has been migrated to a GitHub site.
