---
permalink: upgrade/whats-new.html
sidebar: sidebar
keywords: new features, 11.6
summary: 'StorageGRID 11.6 introduces a new user interface, VLAN support, ability to change SSH password, support for new SSO providers, and more.'
---
= What's new in StorageGRID 11.6
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID 11.6 introduces a new user interface, VLAN support, ability to change SSH password, support for new SSO providers, and more.

== Kathy's what's new changes

* Updates to the user interface for creating a load balancer endpoint.

.Learn more
* xref:../admin/index.adoc[Administer StorageGRID]

=== New alerts added

The following new alerts were added for StorageGRID 11.6:

* EC rebalance failure
* EC repair failure
* Identity federation synchronization failure for a tenant

.Learn more
* xref:../monitor/index.adoc[Monitor & troubleshoot]


== Kevin's what's new changes

=== Available consistency control now includes GET operations

The Available consistency control behaves the same as the “read-after-new-write” consistency level, but provides eventual consistency for HEAD and GET operations. The Available consistency control offers higher availability for HEAD and GET operations than “read-after-new-write” if Storage Nodes are unavailable. Differs from Amazon S3 consistency guarantees for HEAD and GET operations.

.Learn more
* xref:../s3/index.adoc[Use S3]

== Lisa's what's new changes


.Learn more
* xref:../admin/index.adoc[Administer StorageGRID]

== Paul's what's new changes

.Learn more
* xref:../admin/index.adoc[Administer StorageGRID]





== StorageGRID documentation changes

* The documentation center has been migrated to a GitHub site.
