---
permalink: upgrade/whats-new.html
sidebar: sidebar
keywords: what is new in StorageGRID 11.6
summary: 'StorageGRID 11.6 introduces multi VLAN support, support for S3 Select, syslog transfer, ability to change SSH passwords, and user interface enhancements to the Grid Manager.'
---
= What's new in StorageGRID 11.6
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID 11.6 introduces multi VLAN support, support for S3 Select, syslog transfer, ability to change SSH passwords, and usability enhancements to the Grid Manager.

== Kathy's what's new changes

=== Support for multiple VLAN interfaces
You can now configure VLAN interfaces from the Grid Manager (*CONFIGURATION* > *VLAN interfaces*).

.Learn more
* xref:../admin/index.adoc[Administer StorageGRID]

=== Updates to HA groups
The user interface for creating an HA group was revised.

A new optional field, *Gateway CIDR*, allows you to specify a subnet IP address and prefix length for each HA group. All virtual IP (VIP) addresses must belong to this subnet. The new field removes these previous limitations for HA groups:

* Interfaces can now be configured with DHCP. They no longer need to be configured with fixed (static) IP addresses. 

* Interfaces no longer need to belong to the Grid Network (eth0) or the Client Network (eth2). They can now belong to completely different subnets, including the Admin Network or a virtual LAN (VLAN).

=== Updates to load balance endpoints

The user interface for creating a load balancer endpoint was revised.

=== New upgrade process

//more text goes here//

A new *Check for software updates* check box was added to the AutoSupport page (*SUPPORT* > *Tools* > *AutoSupport*). By default, StorageGRID contacts NetApp to determine if software updates are available for your system, but you can disable the check box as required. 

.Learn more
* xref:../admin/configure-autosupport-grid-manager.adoc[Configure AutoSupport]

=== Usability enhancements 
The Grid Manager user interface has been redesigned.

* New sidebar
* New menu structure
* New Nodes page
* New wizards guide you through complex configurations, including creating a tenant, configuring load balancer endpoints, and configuring HA groups.

=== New alerts

The following new alerts were added for StorageGRID 11.6:

* EC rebalance failure
* EC repair failure
* Identity federation synchronization failure for a tenant

.Learn more
* xref:../monitor/index.adoc[Monitor & troubleshoot]

=== Changes to the ORLM audit message
A new BUID field was added to the *ORLM: Object Rules Met* audit message. The BUID field shows the bucket ID, which is used for internal operations. The new field appears only if the message status is PRGD.

.Learn more
* xref:../audit/index.adoc[Review audit logs]

== Changes to S3 REST API support

=== GET object and HEAD object support for multipart objects

Previously, StorageGRID did not support the `partNumber` request parameter in GET Object or HEAD Object requests. Starting in StorageGRID 11.6, you can now issue GET and HEAD requests to retrieve a specific part of a multipart object. GET and HEAD Object also support the `x-amz-mp-parts-count` response element to indicate how many parts an object has.

.Learn more
* xref:../s3/index.adoc[Use S3]

== Kevin's what's new changes

=== Available consistency control now includes GET operations

The Available consistency control behaves the same as the “read-after-new-write” consistency level, but provides eventual consistency for HEAD and GET operations. The Available consistency control offers higher availability for HEAD and GET operations than “read-after-new-write” if Storage Nodes are unavailable. Differs from Amazon S3 consistency guarantees for HEAD and GET operations.

.Learn more
* xref:../s3/index.adoc[Use S3]

== Lisa's what's new changes


.Learn more
* xref:../admin/index.adoc[Administer StorageGRID]

== Paul's what's new changes

.Learn more
* xref:../admin/index.adoc[Administer StorageGRID]





== StorageGRID documentation changes

* The documentation center has been migrated to a GitHub site.
