---
permalink: upgrade/whats-new.html
sidebar: sidebar
keywords: new features, 11.6
summary: 'StorageGRID 11.6 introduces a new user interface, VLAN support, ability to change SSH password, support for new SSO providers, and more.'
---
= What's new in StorageGRID 11.6
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID 11.6 introduces a new user interface, VLAN support, ability to change SSH password, support for new SSO providers, and more.

== Kathy's what's new changes

* Updates to the user interface for creating a load balancer endpoint.

.Learn more
* xref:../admin/index.adoc[Administer StorageGRID]

=== New alerts added

The following new alerts were added for StorageGRID 11.6:

* EC rebalance failure
* EC repair failure
* Identity federation synchronization failure for a tenant

.Learn more
* xref:../monitor/index.adoc[Monitor & troubleshoot]


== Kevin's what's new changes

=== Available consistency control now includes GET operations

The Available consistency control behaves the same as the “read-after-new-write” consistency level, but provides eventual consistency for HEAD and GET operations. The Available consistency control offers higher availability for HEAD and GET operations than “read-after-new-write” if Storage Nodes are unavailable. Differs from Amazon S3 consistency guarantees for HEAD and GET operations.

.Learn more
* xref:../s3/index.adoc[Use S3]

== Lisa's what's new changes

=== Object existence check added to maintenance tasks
The foreground verification feature was renamed to object existence check. This feature has been redesigned and is now available from the Grid Manager at *MAINTENANCE > Object existence check*.

=== Enhancements to the Grid Manager 
The appearance and organization of the Grid Manager user interface has been completely redesigned to improve user experience.

* The Nodes page has been redesigned to display a list of all sites and nodes in the grid. The list includes summary information, such as object data used and object metadata used.

* For any node that has an active alert, the Nodes summary page displays an alert icon next to the node name.

.Learn more
* xref:../admin/index.adoc[Administer StorageGRID]

== Paul's what's new changes

.Learn more
* xref:../admin/index.adoc[Administer StorageGRID]





== StorageGRID documentation changes

* The documentation center has been migrated to a GitHub site.
