---
permalink: sg100-1000/configuring-snmp-settings-for-sg1000.html
sidebar: sidebar
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, SNMP, configure, setup, set up 
summary: 'If you are familiar with configuring SNMP for hardware, you can use the BMC interface to configure the SNMP settings for the services appliance. You can provide secure community strings, enable SNMP Trap, and specify up to five SNMP destinations.'
---
= Configuring SNMP settings for the services appliance
:icons: font
:imagesdir: ../media/

[.lead]
If you are familiar with configuring SNMP for hardware, you can use the BMC interface to configure the SNMP settings for the services appliance. You can provide secure community strings, enable SNMP Trap, and specify up to five SNMP destinations.

.What you'll need

* You know how to access the BMC dashboard.
* You have experience in configuring SNMP settings for SNMPv1-v2c equipment.

.Steps

. From the BMC dashboard, select *Settings* > *SNMP Settings*.
. On the SNMP Settings page, select *Enable SNMP V1/V2*, and then provide a Read-Only Community String and a Read-Write Community String.
+
The Read-Only Community String is like a user ID or password. You should change this value to prevent intruders from getting information about your network setup. The Read-Write Community String protects the device against unauthorized changes.

. Optionally, select *Enable Trap*, and enter the required information.
+
IMPORTANT: Enter the Destination IP for each SNMP trap using an IP address. Fully qualified domain names are not supported.
+
Enable traps if you want the services appliance to send immediate notifications to an SNMP console when it is in an unusual state. Traps might indicate link up/down conditions, temperatures exceeding certain thresholds, or high traffic.

. Optionally, click *Send Test Trap* to test your settings.
. If the settings are correct, click *Save*.
