---
permalink: sg100-1000/installation_and_deployment_overview.html
sidebar: sidebar
keywords: 
summary: 'You can install one or more StorageGRID services appliances when you first deploy StorageGRID, or you can add services appliance nodes later as part of an expansion.'
---
= Installation and deployment overview
:icons: font
:imagesdir: ../media/

[.lead]
You can install one or more StorageGRID services appliances when you first deploy StorageGRID, or you can add services appliance nodes later as part of an expansion.

== Before you begin

Your StorageGRID system is using the required version of StorageGRID software.

|===
| Appliance| Required StorageGRID version
a|
SG100
a|
11.4 or later (latest hotfix recommended)
a|
SG1000
a|
11.3 or later (latest hotfix recommended)
|===

== Installation and deployment tasks

Preparing and adding a StorageGRID appliance to the grid includes two primary phases.

== 1. Installing and configuring appliance hardware

Installing and configuring the StorageGRID appliance hardware includes the following steps:

. Preparing for installation:
 ** Preparing the installation site
 ** Unpacking the boxes and checking the contents
 ** Obtaining additional equipment and tools
 ** Verifying network configuration
 ** Optional: Configuring an external key management server (KMS) if you plan to encrypt all appliance data. See details about external key management in the instructions for administering StorageGRID.
. Installing the hardware:
 ** Registering the hardware
 ** Installing the appliance into a cabinet or rack
 ** Cabling the appliance
 ** Connecting the power cord and applying power
 ** Viewing boot-up status codes
. Configuring the hardware:
 ** Accessing StorageGRID Appliance Installer and configuring the link and network IP settings required to connect to StorageGRID networks
 ** Accessing the baseboard management controller (BMC) interface on the appliance.
 ** Optional: Enabling node encryption if you plan to use an external KMS to encrypt appliance data.

== 2. Deploying an appliance Gateway or Admin Node

After the appliance hardware has been installed and configured, you can deploy the appliance as a Gateway Node and an Admin Node in a StorageGRID system. Both the SG100 and the SG1000 appliances can operate as Gateway Nodes and Admin Nodes (primary and non-primary) at the same time.

|===
| Task| Instructions
a|
Deploying an appliance Gateway or Admin Node in a new StorageGRID system
a|
xref:deploying_services_appliance_node.adoc[Deploying a services appliance node]
a|
Adding an appliance Gateway or Admin Node to an existing StorageGRID system
a|
Instructions for expanding a StorageGRID system
a|
Deploying an appliance Gateway or Admin Node as part of a node recovery operation
a|
Instructions for recovery and maintenance
|===
*Related information*

xref:preparing_for_installation_sg100_and_sg1000.adoc[Preparing for installation]

xref:installing_hardware_sg100_and_sg1000.adoc[Installing the hardware]

xref:configuring_storagegrid_connections_sg100_and_sg1000.adoc[Configuring StorageGRID connections]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-expansion/home.html[Expanding a StorageGRID system]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-maint/home.html[Recovery and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-admin/home.html[Administering StorageGRID]
