---
permalink: sg100-1000/overview-of-installation-rest-apis.html
sidebar: sidebar
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, installation REST API, REST API, installation REST APIs, REST APIs, Appliance Installer API, Appliance Installer APIs, Install API, Install APIs, Installer API, Installer APIs, Installation API, Installation APIs, api, apis
summary: 'StorageGRID provides two REST APIs for performing installation tasks: the StorageGRID Installation API and the StorageGRID Appliance Installer API.'
---
= Overview of installation REST APIs
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID provides two REST APIs for performing installation tasks: the StorageGRID Installation API and the StorageGRID Appliance Installer API.

Both APIs use the Swagger open source API platform to provide the API documentation. Swagger allows both developers and non-developers to interact with the API in a user interface that illustrates how the API responds to parameters and options. This documentation assumes that you are familiar with standard web technologies and the JSON (JavaScript Object Notation) data format.

IMPORTANT: Any API operations you perform using the API Docs webpage are live operations. Be careful not to create, update, or delete configuration data or other data by mistake.

Each REST API command includes the API's URL, an HTTP action, any required or optional URL parameters, and an expected API response.

== StorageGRID Installation API

The StorageGRID Installation API is only available when you are initially configuring your StorageGRID system, and in the event that you need to perform a primary Admin Node recovery. The Installation API can be accessed over HTTPS from the Grid Manager.

To access the API documentation, go to the installation web page on the primary Admin Node and select *Help* > *API Documentation* from the menu bar.

The StorageGRID Installation API includes the following sections:

* *config* -- Operations related to the product release and versions of the API. You can list the product release version and the major versions of the API supported by that release.
* *grid* -- Grid-level configuration operations. You can get and update grid settings, including grid details, Grid Network subnets, grid passwords, and NTP and DNS server IP addresses.
* *nodes* -- Node-level configuration operations. You can retrieve a list of grid nodes, delete a grid node, configure a grid node, view a grid node, and reset a grid node's configuration.
* *provision* -- Provisioning operations. You can start the provisioning operation and view the status of the provisioning operation.
* *recovery* -- Primary Admin Node recovery operations. You can reset information, upload the Recover Package, start the recovery, and view the status of the recovery operation.
* *recovery-package* -- Operations to download the Recovery Package.
* *sites* -- Site-level configuration operations. You can create, view, delete, and modify a site.

== StorageGRID Appliance Installer API

The StorageGRID Appliance Installer API can be accessed over HTTPS from  `_Controller_IP_:8443`.

To access the API documentation, go to the StorageGRID Appliance Installer on the appliance and select *Help* > *API Docs* from the menu bar.

The StorageGRID Appliance Installer API includes the following sections:

* *clone* -- Operations to configure and control node cloning.
* *encryption* -- Operations to manage encryption and view encryption status.
* *hardware configuration* -- Operations to configure system settings on attached hardware.
* *installation* -- Operations for starting the appliance installation and for monitoring installation status.
* *networking* -- Operations related to the Grid, Admin, and Client Network configuration for a StorageGRID appliance and appliance port settings.
* *setup* -- Operations to help with initial appliance installation setup including requests to get information about the system and update the primary Admin Node IP.
* *support* -- Operations for rebooting the controller and getting logs.
* *upgrade* -- Operations related to upgrading appliance firmware.
* *uploadsg* -- Operations for uploading StorageGRID installation files.
