---
permalink: sg100-1000/preparing_for_installation_sg100_and_sg1000.html
sidebar: sidebar
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, install, installation, preparation, get ready, prepare
summary: 'Preparing to install a StorageGRID appliance entails preparing the site and obtaining all required hardware, cables, and tools. You should also gather IP addresses and network information.'
---
= Preparing for installation
:icons: font
:imagesdir: ../media/

[.lead]
Preparing to install a StorageGRID appliance entails preparing the site and obtaining all required hardware, cables, and tools. You should also gather IP addresses and network information.

.Steps

* xref:preparing_site_sg100_and_sg1000.adoc[Preparing the site (SG100 and SG1000)]
* xref:unpacking_boxes_sg100_and_sg1000.adoc[Unpacking the boxes (SG100 and SG1000)]
* xref:obtaining_additional_equipment_and_tools_sg100_and_sg1000.adoc[Obtaining additional equipment and tools (SG100 and SG1000)]
* xref:../admin/web_browser_requirements.adoc[Web browswer requirements]
* xref:reviewing_appliance_network_connections_sg100_and_sg1000.adoc[Reviewing appliance network connections]
* xref:gathering_installation_information_sg100_and_sg1000.adoc[Gathering installation information (SG100 and SG1000)]
