---
permalink: sg100-1000/preparing-site-sg100-and-sg1000.html
sidebar: sidebar
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, install, installation, site prep, site preparating, preparing site, site requirements, requirements, site, dimensions, weight, weights, temperature, humidity, altitude, airflow, heat, wiring, power, grounding, facility
summary: 'Before installing the appliance, you must make sure that the site and the cabinet or rack you plan to use meet the specifications for a StorageGRID appliance.'
---
= Preparing the site (SG100 and SG1000)
:icons: font
:imagesdir: ../media/

[.lead]
Before installing the appliance, you must make sure that the site and the cabinet or rack you plan to use meet the specifications for a StorageGRID appliance.

.Steps

. Confirm that the site meets the requirements for temperature, humidity, altitude range, airflow, heat dissipation, wiring, power, and grounding. See the NetApp Hardware Universe for more information.
. Confirm that your location provides the correct voltage of AC power (in the range of 120 to 240 volts AC).
. Obtain a 19-inch (48.3-cm) cabinet or rack to fit shelves of this size (without cables):
+
[options="header"]
|===
| Height| Width| Depth| Maximum weight
a|
1.70 in.

(4.32 cm)
a|
17.32 in.

(44.0 cm)
a|
32.0 in.

(81.3 cm)
a|
39 lb.

(17.7 kg)

|===

. Decide where you are going to install the appliance.

.Related information

https://hwu.netapp.com[NetApp Hardware Universe^]

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]
