---
permalink: sg100-1000/preparing-for-installation-sg100-and-sg1000.html
sidebar: sidebar
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, install, installation, preparation, get ready, prepare
summary: 'Preparing to install a StorageGRID appliance entails preparing the site and obtaining all required hardware, cables, and tools. You should also gather IP addresses and network information.'
---
= Preparing for installation
:icons: font
:imagesdir: ../media/

[.lead]
Preparing to install a StorageGRID appliance entails preparing the site and obtaining all required hardware, cables, and tools. You should also gather IP addresses and network information.

.Steps

* xref:preparing-site-sg100-and-sg1000.adoc[Preparing the site (SG100 and SG1000)]
* xref:unpacking-boxes-sg100-and-sg1000.adoc[Unpacking the boxes (SG100 and SG1000)]
* xref:obtaining-additional-equipment-and-tools-sg100-and-sg1000.adoc[Obtaining additional equipment and tools (SG100 and SG1000)]
* xref:../admin/web-browser-requirements.adoc[Web browser requirements]
* xref:reviewing-appliance-network-connections-sg100-and-sg1000.adoc[Reviewing appliance network connections (SG100 and SG1000)]
* xref:gathering-installation-information-sg100-and-sg1000.adoc[Gathering installation information (SG100 and SG1000)]
