---
permalink: sg100-1000/replacing_services_appliance.html
sidebar: sidebar
keywords: 
summary: 'You might need to replace the appliance if it is not functioning optimally or if it has failed.'
---
= Replacing the services appliance
:icons: font
:imagesdir: ../media/

[.lead]
You might need to replace the appliance if it is not functioning optimally or if it has failed.

.What you'll need

* You have a replacement appliance with the same part number as the appliance you are replacing.
* You have labels to identify each cable that is connected to the appliance.
* You have physically located the appliance that you are replacing in the data center.
+
xref:locating_controller_in_data_center.adoc[Locating the controller in a data center]

* The appliance has been placed maintenance mode.
+
xref:placing_appliance_into_maintenance_mode.adoc[Placing an appliance into maintenance mode]

.About this task

The StorageGRID node will not be accessible while you replace the appliance. If the appliance is functioning sufficiently, you can perform a controlled shutdown at the start of this procedure.

NOTE: If you are replacing the appliance before installing StorageGRID software, you might not be able to access the StorageGRID Appliance Installer immediately after completing this procedure. While you can access the StorageGRID Appliance Installer from other hosts on the same subnet as the appliance, you cannot access it from hosts on other subnets. This condition should resolve itself within 15 minutes (when any ARP cache entries for the original appliance time out), or you can clear the condition immediately by purging any old ARP cache entries manually from the local router or gateway.

.Steps

. When the appliance has been placed maintenance mode, shut down the appliance.
 .. Log in to the grid node:
  ... Enter the following command: `ssh admin@grid_node_IP`
  ... Enter the password listed in the `Passwords.txt` file.
  ... Enter the following command to switch to root: `su -`
  ... Enter the password listed in the `Passwords.txt` file.
When you are logged in as root, the prompt changes from `$` to `#`.
 .. Shut down the appliance:``shutdown -h now``
. Use one of two methods to verify that the power for the appliance is off:
 ** The power indicator LED on the front of the appliance is off.
 ** The Power Control page of the BMC interface indicates that the appliance is off.
. If the StorageGRID networks attached to the appliance use DHCP servers, update DNS/network and IP address settings.
 .. Locate the MAC address label on the front of the appliance, and determine the MAC address for the Admin Network port.
+
NOTE: The MAC address label lists the MAC address for the BMC management port.
+
To determine the MAC address for the Admin Network port, you must add *2* to the hexadecimal number on the label. For example, if the MAC address on the label ends in *09*, the MAC address for the Admin Port would end in *0B*. If the MAC address on the label ends in *(_y_)FF*, the MAC address for the Admin Port would end in *(_y_+1)01*. You can easily make this calculation by opening Calculator in Windows, setting it to Programmer mode, selecting Hex, typing the MAC address, then typing *+ 2 =*.

 .. Ask your network administrator to associate the DNS/network and IP address for the appliance you removed with the MAC address for the replacement appliance.
+
IMPORTANT: You must ensure that all IP addresses for the original appliance have been updated before you apply power to the replacement appliance. Otherwise, the appliance will obtain new DHCP IP addresses when it boots up and might not be able to reconnect to StorageGRID. This step applies to all StorageGRID networks that are attached to the appliance.
+
NOTE: If the original appliance used static IP address, the new appliance will automatically adopt the IP addresses of the appliance you removed.
. Remove and replace the appliance:
 .. Label the cables and then disconnect the cables and any network transceivers.
+
IMPORTANT: To prevent degraded performance, do not twist, fold, pinch, or step on the cables.

 .. Remove the failed appliance from the cabinet or rack.
 .. Transfer the two power supplies, eight cooling fans, and two SSDs from the failed appliance to the replacement appliance.
+
Follow the instructions provided for replacing these components.

 .. Install the replacement appliance into the cabinet or rack.
 .. Replace the cables and any optical transceivers.
 .. Power on the appliance and monitor the appliance LEDs and boot-up codes.
+
Use the BMC interface to monitor boot-up status.
. Confirm that the appliance node appears in the Grid Manager and that no alerts appear.

.Related information

xref:installing_appliance_in_cabinet_or_rack_sg100_and_sg1000.adoc[Installing the appliance into a cabinet or rack (SG100 and SG1000)]

xref:viewing_status_indicators_on_sg100_and_sg1000_appliances.adoc[Viewing status indicators on the SG100 and SG1000 appliances]

xref:viewing_boot_up_codes_for_appliance_sg100_and_sg1000.adoc[Viewing boot-up codes for the appliance]
