---
permalink: sg100-1000/sg100-and-sg1000-applications.html
sidebar: sidebar
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, applications, how to use, services
summary: 'You can configure the StorageGRID services appliances in various ways to provide gateway services as well as redundancy of some grid administration services.'
---
= SG100 and SG1000 applications
:icons: font
:imagesdir: ../media/

[.lead]
You can configure the StorageGRID services appliances in various ways to provide gateway services as well as redundancy of some grid administration services.

Appliances can be deployed in the following ways:

* Add to a new or existing grid as a Gateway Node
* Add to a new grid as a primary or non-primary Admin Node, or to an existing grid as a non-primary Admin Node
* Operate as a Gateway Node and Admin Node (primary or non-primary) at the same time

The appliance facilitates the use of high availability (HA) groups and intelligent load balancing for S3 or Swift data path connections.

The following examples describe how you can maximize the capabilities of the appliance:

* Use two SG100 or two SG1000 appliances to provide gateway services by configuring them as Gateway Nodes.
+
IMPORTANT: Do not deploy the SG100 and SG1000 service appliances in the same site. Unpredictable performance might result.

* Use two SG100 or two SG1000 appliances to provide redundancy of some grid administration services. Do this by configuring each appliance as Admin Nodes.
* Use two SG100 or two SG1000 appliances to provide highly available load balancing and traffic shaping services accessed through one or more virtual IP addresses. Do this by configuring the appliances as any combination of Admin Nodes or Gateway Nodes and adding both nodes to the same HA group.
+
IMPORTANT: If you use Admin Nodes and Gateway Nodes in the same HA group, CLB (Connection Load Balancer) ports and Admin Node-only ports will not fail over. For instructions for configuring HA groups, see the instructions for administering StorageGRID.
+
NOTE: The CLB service is deprecated.

When used with StorageGRID storage appliances, both the SG100 and the SG1000 services appliances enable deployment of appliance-only grids with no dependencies on external hypervisors or compute hardware.

.Related information

xref:../admin/index.adoc[Administer StorageGRID]
