---
permalink: sg100-1000/task_connecting_power_cords_and_applying_power_sg100_and_sg1000.html
sidebar: sidebar
keywords: 
summary: 'After connecting the network cables, you are ready to apply power to the appliance.'
---
= Connecting power cords and applying power (SG100 and SG1000)
:icons: font
:imagesdir: ../media/

[.lead]
After connecting the network cables, you are ready to apply power to the appliance.

. Connect a power cord to each of the two power supply units in the appliance.
. Connect these two power cords to two different power distribution units (PDUs) in the cabinet or rack.
. If the power button on the front of the appliance is not currently illuminated blue, press the button to turn on power to the appliance.
+
Do not press the power button again during the power-on process.

. If errors occur, correct any issues.
. Attach the front bezel to the appliance.

*Related information*

xref:reference_viewing_status_indicators_on_the_sg100_and_sg1000_appliances.adoc[Viewing status indicators on the SG100 and SG1000 appliances]
