---
permalink: ubuntu/downloading-and-extracting-storagegrid-installation-files.html
sidebar: sidebar
keywords: how to download ubuntu or debian installation files
summary: 'You must download the StorageGRID installation archive and extract the required files.'
---
= Download and extract the StorageGRID installation files
:icons: font
:imagesdir: ../media/

[.lead]
You must download the StorageGRID installation archive and extract the required files.

.Steps

. Go to the https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads page for StorageGRID^].
. Select the button for downloading the latest release, or select another version from the drop-down menu and select *Go*.
. Sign in with the username and password for your NetApp account.
. If a Caution/MustRead statement appears, read it and select the check box.
+
IMPORTANT: You must apply any required hotfixes after you install the StorageGRID release. For more information, see the xref:../maintain/storagegrid-hotfix-procedure.adoc[hotfix procedure in the recovery and maintenance instructions]

. Read the End User License Agreement, select the check box, and then select *Accept & Continue*.
+
The downloads page for the version you selected appears. The page contains three columns:

. In the *Install StorageGRID* column, select the .tgz or .zip file for Ubuntu or Debian.
+
NOTE: Select the `.zip` file if you are running Windows on the service laptop.

. Save and extract the archive file.
. Choose the files you need from the following list.
+
The set of files you need depends on your planned grid topology and how you will deploy your StorageGRID grid.
+
NOTE: The paths listed in the table are relative to the top-level directory installed by the extracted installation archive.

include::../_include/installation-files-ubuntu.adoc[]

.Related information

xref:../maintain/index.adoc[Recover and maintain]
