---
permalink: ubuntu/downloading-and-extracting-storagegrid-installation-files.html
sidebar: sidebar
keywords: storagegrid, ubuntu, debian, download installation files, downloading installation files
summary: 'You must download the StorageGRID installation archive and extract the required files.'
---
= Downloading and extracting the StorageGRID installation files
:icons: font
:imagesdir: ../media/

[.lead]
You must download the StorageGRID installation archive and extract the required files.

.Steps

. Go to the NetApp Downloads page for StorageGRID.
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads: StorageGRID^]

. Select the button for downloading the latest release, or select another version from the drop-down menu and select *Go*.
. Sign in with the username and password for your NetApp account.
. If a Caution/MustRead statement appears, read it and select the check box.
+
You must apply any required hotfixes after you install the StorageGRID release. For more information, see the hotfix procedure in the recovery and maintenance instructions.

. Read the End User License Agreement, select the check box, and then select *Accept & Continue*.
+
The downloads page for the version you selected appears. The page contains three columns:

. In the *Install StorageGRID* column, select the appropriate software.
+
Select the `.tgz` or `.zip` archive file for your platform.

 ** `StorageGRID-Webscale-version-DEB-uniqueID.zip`
 ** `StorageGRID-Webscale-version-DEB-uniqueID.tgz`

+
The compressed files contain the DEB files and scripts for Ubuntu or Debian.

+
NOTE: Use the `.zip` file if you are running Windows on the service laptop.

. Save and extract the archive file.
. Choose the files you need from the following list.
+
The set of files you need depends on your planned grid topology and how you will deploy your StorageGRID grid.
+
NOTE: The paths listed in the table are relative to the top-level directory installed by the extracted installation archive.

[cols="1a,2a" options="header"]
|===
| Path and file name| Description
m|./debs/README
|A text file that describes all of the files contained in the StorageGRID download file.

m|./debs/NLF000000.txt
|A non-production NetApp License File that you can use for testing and proof of concept deployments.

m|./debs/storagegrid-webscale-images-version-SHA.deb
|DEB package for installing the StorageGRID node images on Ubuntu or Debian hosts.

m|./debs/storagegrid-webscale-images-version-SHA.deb.md5
|MD5 checksum for the file `/debs/storagegrid-webscale-images-version-SHA.deb`.

m|./debs/storagegrid-webscale-service-version-SHA.deb
|DEB package for installing the StorageGRID host service on Ubuntu or Debian hosts.

|*Deployment scripting tool* |*Description*

m|./debs/configure-storagegrid.py
|A Python script used to automate the configuration of a StorageGRID system.

m|./debs/configure-sga.py
|A Python script used to automate the configuration of StorageGRID appliances.

m|./debs/storagegrid-ssoauth.py
|An example Python script that you can use to sign in to the Grid Management API when single sign-on is enabled.

m|./debs/configure-storagegrid.sample.json
|A sample configuration file for use with the `configure-storagegrid.py` script.

m|./debs/configure-storagegrid.blank.json
|A blank configuration file for use with the `configure-storagegrid.py` script.

m|./debs/extras/ansible
|Example Ansible role and playbook for configuring Ubuntu or Debian hosts for StorageGRID container deployment. You can customize the role or playbook as necessary.
|===

.Related information

xref:../maintain/index.adoc[Maintain & recover]
