---
permalink: ubuntu/installing-storagegrid-webscale-host-services.html
sidebar: sidebar
keywords:
summary: 'You use the StorageGRID DEB package to install the StorageGRID host services.'
---
= Installing StorageGRID host services
:icons: font
:imagesdir: ../media/

[.lead]
You use the StorageGRID DEB package to install the StorageGRID host services.

.About this task

These instructions describe how to install the host services from the DEB packages. As an alternative, you can use the APT repository metadata included in the installation archive to install the DEB packages remotely. See the APT repository instructions for your Linux operating system.

.Steps

. Copy the StorageGRID DEB packages to each of your hosts, or make them available on shared storage.
+
For example, place them in the `/tmp` directory, so you can use the example command in the next step.

. Log in to each host as root or using an account with sudo permission, and run the following commands.
+
You must install the `images` package first, and the `service` package second. If you placed the packages in a directory other than `/tmp`, modify the command to reflect the path you used.
+
----
sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb
----
+
----
sudo dpkg --install /tmp/storagegrid-webscale-service-version-SHA.deb
----
+
IMPORTANT: Python 2.7 must already be installed before the StorageGRID packages can be installed. The `sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb` command will fail until you have done so.
