---
permalink: ubuntu/required-materials.html
sidebar: sidebar
keywords: installation materials ubuntu debian
summary: 'Before you install StorageGRID, you must gather and prepare required materials.'
---
= Required materials
:icons: font
:imagesdir: ../media/

[.lead]
Before you install StorageGRID, you must gather and prepare required materials.

[options="header"]
|===
| Item| Notes
a|
NetApp StorageGRID license
a|
You must have a valid, digitally signed NetApp license.

*Note*: A non-production license, which can be used for testing and proof of concept grids, is included in the StorageGRID installation archive.

a|StorageGRID installation archive
a|You must xref:downloading-and-extracting-storagegrid-installation-files.adoc[download the StorageGRID installation archive and extract the files].

a|Service laptop
a|The StorageGRID system is installed through a service laptop.

The service laptop must have:

* Network port
* SSH client (for example, PuTTY)
* xref:../admin/web-browser-requirements.adoc[Supported web browser]

a|StorageGRID documentation
a|
* xref:../release-notes/index.adoc[Release notes]
* xref:../admin/index.adoc[Instructions for administering StorageGRID]
|===

.Related information

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]