---
permalink: harden/hardening-guidelines-for-software-upgrades.html
sidebar: sidebar
keywords: Hardening guidelines, upgrades
summary: 'You must keep your StorageGRID system and related services up to date to defend against attacks.'
---
= Hardening guidelines for software upgrades
:icons: font
:imagesdir: ../media/

[.lead]
You must keep your StorageGRID system and related services up to date to defend against attacks.

== Upgrades to StorageGRID software

Whenever possible, you should upgrade StorageGRID software to the most recent major release or to the previous major release. Keeping StorageGRID up to date helps reduce the amount of time that known vulnerabilities are active and reduces the overall attack surface area. In addition, the most recent releases of StorageGRID often contain security hardening features that are not included in earlier releases.

When a hotfix is required, NetApp prioritizes creating updates for the most recent releases. Some patches might not be compatible with earlier releases.

To download the most recent StorageGRID releases and hotfixes, go to the StorageGRID software download page. For step-by-step instructions for upgrading StorageGRID software, see the instructions for upgrading StorageGRID. For instructions on applying a hotfix, see the recovery and maintenance instructions.

== Upgrades to external services

External services can have vulnerabilities that affect StorageGRID indirectly. You should ensure that the services that StorageGRID depends on are kept up to date. These services include LDAP, KMS (or KMIP server), DNS, and NTP.

Use the NetApp Interoperability Matrix Tool to get a list of supported versions.

== Upgrades to hypervisors

If your StorageGRID nodes are running on VMware or another hypervisor, you must ensure that the hypervisor software and firmware are up to date.

Use the NetApp Interoperability Matrix Tool to get a list of supported versions.

== *Upgrade to Linux nodes*

If your StorageGRID nodes are using Linux host platforms, you must ensure that security updates and kernel updates are applied to the host OS. Additionally, you must apply firmware updates to vulnerable hardware when these updates become available.

Use the NetApp Interoperability Matrix Tool to get a list of supported versions.

.Related information

https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads: StorageGRID^]

xref:../upgrade/index.adoc[Upgrade software]

xref:../maintain/index.adoc[Maintain & recover]

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]
