---
permalink: swift/container-operations.html
sidebar: sidebar
keywords:
summary: 'StorageGRID supports a maximum of 1,000 containers per Swift account. The following Swift API operations are performed on containers.'
---
= Container operations
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID supports a maximum of 1,000 containers per Swift account. The following Swift API operations are performed on containers.

== DELETE container

This operation removes an empty container from a Swift account in a StorageGRID system.

The following request parameters are required:

* `Account`
* `Container`

The following request header is required:

* `X-Auth-Token`

A successful execution returns the following headers with an "HTTP/1.1 204 No Content" response:

* `Content-Length`
* `Content-Type`
* `Date`
* `X-Trans-Id`

== GET container

This operation retrieves the object list associated with the container along with container statistics and metadata in a StorageGRID system.

The following request parameters are required:

* `Account`
* `Container`

The following request header is required:

* `X-Auth-Token`

The following supported request query parameters are optional:

* `Delimiter`
* `End_marker`
* `Format`
* `Limit`
* `Marker`
* `Path`
* `Prefix`

A successful execution returns the following headers with an "HTTP/1.1 200 Success" or a "HTTP/1.1 204 No Content" response:

* `Accept-Ranges`
* `Content-Length`
* `Content-Type`
* `Date`
* `X-Container-Bytes-Used`
* `X-Container-Object-Count`
* `X-Timestamp`
* `X-Trans-Id`

== HEAD container

This operation retrieves container statistics and metadata from a StorageGRID system.

The following request parameters are required:

* `Account`
* `Container`

The following request header is required:

* `X-Auth-Token`

A successful execution returns the following headers with an "HTTP/1.1 204 No Content" response:

* `Accept-Ranges`
* `Content-Length`
* `Date`
* `X-Container-Bytes-Used`
* `X-Container-Object-Count`
* `X-Timestamp`
* `X-Trans-Id`

== PUT container

This operation creates a container for an account in a StorageGRID system.

The following request parameters are required:

* `Account`
* `Container`

The following request header is required:

* `X-Auth-Token`

A successful execution returns the following headers with an "HTTP/1.1 201 Created" or "HTTP/1.1 202 Accepted" (if the container already exists under this account) response:

* `Content-Length`
* `Date`
* `X-Timestamp`
* `X-Trans-Id`

A container name must be unique in the StorageGRID namespace. If the container exists under another account, the following header is returned: "HTTP/1.1 409 Conflict."

.Related information

xref:monitoring-and-auditing-operations.adoc[Swift operations tracked in the audit logs]
