---
permalink: swift/error-responses-to-swift-api-operations.html
sidebar: sidebar
keywords: 
summary: 'Understanding the possible error responses can help you troubleshoot operations.'
---
= Error responses to Swift API operations
:icons: font
:imagesdir: ../media/

[.lead]
Understanding the possible error responses can help you troubleshoot operations.

The following HTTP status codes might be returned when errors occur during an operation:

[options="header"]
|===
| Swift error name| HTTP status
a|
AccountNameTooLong, ContainerNameTooLong, HeaderTooBig, InvalidContainerName, InvalidRequest, InvalidURI, MetadataNameTooLong, MetadataValueTooBig, MissingSecurityHeader, ObjectNameTooLong, TooManyContainers, TooManyMetadataItems, TotalMetadataTooLarge

a|
400 Bad Request
a|
AccessDenied
a|
403 Forbidden
a|
ContainerNotEmpty, ContainerAlreadyExists
a|
409 Conflict
a|
InternalError
a|
500 Internal Server Error
a|
InvalidRange
a|
416 Requested Range Not Satisfiable
a|
MethodNotAllowed
a|
405 Method Not Allowed
a|
MissingContentLength
a|
411 Length Required
a|
NotFound
a|
404 Not Found
a|
NotImplemented
a|
501 Not Implemented
a|
PreconditionFailed
a|
412 Precondition Failed
a|
ResourceNotFound
a|
404 Not Found
a|
Unauthorized
a|
401 Unauthorized
a|
UnprocessableEntity
a|
422 Unprocessable Entity
|===
