---
permalink: swift/history-of-swift-api-support-in-storagegrid.html
sidebar: sidebar
keywords: 
summary: 'You should be aware of changes to the StorageGRID system’s support for the Swift REST API.'
---
= History of Swift API support in StorageGRID
:icons: font
:imagesdir: ../media/

[.lead]
You should be aware of changes to the StorageGRID system's support for the Swift REST API.

[options="header"]
|===
| Release| Comments
a|
11.5
a|
Removed Weak consistency control. The Available consistency level will be used instead.
a|
11.4
a|
Added support for TLS 1.3 and updated list of supported TLS cipher suites. CLB is deprecated. Added description of interrelationship between ILM and consistency setting.
a|
11.3
a|
Updated PUT Object operations to describe the impact of ILM rules that use synchronous placement at ingest (the Balanced and Strict options for Ingest Behavior). Added description of client connections that use load balancer endpoints or high availability groups. Updated list of supported TLS cipher suites. TLS 1.1 ciphers are no longer supported.
a|
11.2
a|
Minor editorial changes to document.
a|
11.1
a|
Added support for using HTTP for Swift client connections to grid nodes. Updated the definitions of consistency controls.
a|
11.0
a|
Added support for 1,000 containers for each tenant account.
a|
10.3
a|
Administrative updates and corrections to the document. Removed sections for configuring custom server certificates.
a|
10.2
a|
Initial support of the Swift API by the StorageGRID system. The currently supported version is OpenStack Swift Object Storage API v1.

|===
