---
permalink: swift/options-request.html
sidebar: sidebar
keywords: 
summary: 'The OPTIONS request checks the availability of an individual Swift service. The OPTIONS request is processed by the Storage Node or Gateway Node specified in the URL.'
---
= OPTIONS request
:icons: font
:imagesdir: ../media/

[.lead]
The OPTIONS request checks the availability of an individual Swift service. The OPTIONS request is processed by the Storage Node or Gateway Node specified in the URL.

== OPTIONS method

For example, client applications can issue an OPTIONS request to the Swift port on a Storage Node, without providing Swift authentication credentials, to determine whether the Storage Node is available. You can use this request for monitoring or to allow external load balancers to identify when a Storage Node is down.

When used with the info URL or the storage URL, the OPTIONS method returns a list of supported verbs for the given URL (for example, HEAD, GET, OPTIONS, and PUT). The OPTIONS method cannot be used with the auth URL.

The following request parameter is required:

* `Account`

The following request parameters are optional:

* `Container`
* `Object`

A successful execution returns the following headers with an "`HTTP/1.1 204 No Content`" response. The OPTIONS request to the storage URL does not require that the target exists.

* `Allow` (a list of supported verbs for the given URL, for example, HEAD, GET, OPTIONS, and PUT)
* `Content-Length`
* `Content-Type`
* `Date`
* `X-Trans-Id`

.Related information

xref:supported-swift-api-endpoints.adoc[Supported Swift API endpoints]
