---
permalink: swift/swift_rest_api_supported_operations.html
sidebar: sidebar
keywords: 
summary: 'The StorageGRID system supports most operations in the OpenStack Swift API. Before integrating Swift REST API clients with StorageGRID, review the implementation details for account, container, and object operations.'
---
= Swift REST API supported operations
:icons: font
:imagesdir: ../media/

[.lead]
The StorageGRID system supports most operations in the OpenStack Swift API. Before integrating Swift REST API clients with StorageGRID, review the implementation details for account, container, and object operations.

== Operations supported in StorageGRID

The following Swift API operations are supported:

* xref:account_operations.adoc[Account operations]
* xref:container_operations.adoc[Container operations]
* xref:object_operations.adoc[Object operations]

== Common response headers for all operations

The StorageGRID system implements all common headers for supported operations as defined by the OpenStack Swift Object Storage API v1.

.Related information

http://docs.openstack.org/developer/swift/api/object_api_v1_overview.html[OpenStack: Object Storage API]
