---
permalink: network/appliance-nodes.html
sidebar: sidebar
keywords:
summary: 'You can configure the network ports on StorageGRID appliances to use the port bond modes that meet your requirements for throughput, redundancy, and failover.'
---
= Appliance nodes
:icons: font
:imagesdir: ../media/

[.lead]
You can configure the network ports on StorageGRID appliances to use the port bond modes that meet your requirements for throughput, redundancy, and failover.

The 10/25-GbE ports on the StorageGRID appliances can be configured in Fixed or Aggregate bond mode for connections to the Grid Network and Client Network.

The 1-GbE Admin Network ports can be configured in Independent or Active-Backup mode for connections to the Admin Network.

See the information about port bond modes in the installation and maintenance instructions for your appliance.

.Related information

xref:../sg100-1000/index.adoc[SG100 & SG1000 services appliances]

xref:../sg6000/index.adoc[SG6000 storage appliances]

xref:../sg5700/index.adoc[SG5700 storage appliances]

xref:../sg5600/index.adoc[SG5600 storage appliances]
