---
permalink: network/host-network-configuration-for-docker-deployments.html
sidebar: sidebar
keywords:
summary: 'Before starting your StorageGRID deployment on a Docker container platform, determine which networks \(Grid, Admin, Client\) each node will use. You must ensure that each node’s network interface is configured on the correct virtual or physical host interface, and that each network has sufficient bandwidth.'
---
= Host network configuration for Docker deployments
:icons: font
:imagesdir: ../media/

[.lead]
Before starting your StorageGRID deployment on a Docker container platform, determine which networks (Grid, Admin, Client) each node will use. You must ensure that each node's network interface is configured on the correct virtual or physical host interface, and that each network has sufficient bandwidth.

== Physical hosts

If you are using physical hosts to support grid nodes:

* Make sure all hosts use the same host interface for each node interface. This strategy simplifies host configuration and enables future node migration.
* Obtain an IP address for the physical host itself.
+
NOTE: A physical interface on the host can be used by the host itself and one or more nodes running on the host. Any IP addresses assigned to the host or nodes using this interface must be unique. The host and the node cannot share IP addresses.

* Open the required ports to the host.

== Minimum bandwidth recommendations

The following table provides the minimum bandwidth recommendations for each type of StorageGRID node and each type of network. You must provision each physical or virtual host with sufficient network bandwidth to meet the aggregate minimum bandwidth requirements for the total number and type of StorageGRID nodes you plan to run on that host.

[options="header"]
|===
a| Type of node 3+|Type of network

a| |Grid |Admin |Client
a|Admin |10 Gbps |1 Gbps |1 Gbps
a|Gateway |10 Gbps |1 Gbps |10 Gbps
a|Storage |10 Gbps |1 Gbps |10 Gbps
a|Archive |10 Gbps |1 Gbps |10 Gbps
|===

NOTE: This table does not include SAN bandwidth, which is required for access to shared storage. If you are using shared storage accessed over Ethernet (iSCSI or FCoE), you should provision separate physical interfaces on each host to provide sufficient SAN bandwidth. To avoid introducing a bottleneck, SAN bandwidth for a given host should roughly match the aggregate Storage Node network bandwidth for all Storage Nodes running on that host.

Use the table to determine the minimum number of network interfaces to provision on each host, based on the number and type of StorageGRID nodes you plan to run on that host.

For example, to run one Admin Node, one Gateway Node, and one Storage Node on a single host:

* Connect the Grid and Admin Networks on the Admin Node (requires 10 + 1 = 11 Gbps)
* Connect the Grid and Client Networks on the Gateway Node (requires 10 + 10 = 20 Gbps)
* Connect the Grid Network on the Storage Node (requires 10 Gbps)

In this scenario, you should provide a minimum of 11 + 20 + 10 = 41 Gbps of network bandwidth, which could be met by two 40 Gbps interfaces or five 10 Gbps interfaces, potentially aggregated into trunks and then shared by the three or more VLANs carrying the Grid, Admin, and Client subnets local to the physical data center containing the host.

For some recommended ways of configuring physical and network resources on the hosts in your StorageGRID cluster to prepare for your StorageGRID deployment, see the information about configuring the host network in the installation instructions for your Linux platform.

.Related information

xref:../rhel/index.adoc[Install Red Hat Enterprise Linux or CentOS]

xref:../ubuntu/index.adoc[Install Ubuntu or Debian]
