---
permalink: network/linux-deployments.html
sidebar: sidebar
keywords:
summary: 'For efficiency, reliability, and security, the StorageGRID system runs on Linux as a collection of Docker containers. Docker-related network configuration is not required in a StorageGRID system.'
---
= Linux deployments
:icons: font
:imagesdir: ../media/

[.lead]
For efficiency, reliability, and security, the StorageGRID system runs on Linux as a collection of Docker containers. Docker-related network configuration is not required in a StorageGRID system.

Use a non-bond device, such as a VLAN or virtual Ethernet (veth) pair, for the container network interface. Specify this device as the network interface in the node configuration file.

IMPORTANT: Do not use bond or bridge devices directly as the container network interface. Doing so could prevent node start-up because of a kernel issue with the use of macvlan with bond and bridge devices in the container namespace.

See the installation instructions for Red Hat Enterprise Linux/CentOS or Ubuntu/Debian deployments.

.Related information

xref:../rhel/index.adoc[Install Red Hat Enterprise Linux or CentOS]

xref:../ubuntu/index.adoc[Install Ubuntu or Debian]
