---
permalink: network/networking-and-ports-for-platform-services-and-cloud-storage-pools.html
sidebar: sidebar
keywords: networking for platform services, networking for cloud storage pools
summary: 'If you plan to use StorageGRID platform services or Cloud Storage Pools, you must configure grid networking and firewalls to ensure that the destination endpoints can be reached.'
---
= Networking and ports for platform services and Cloud Storage Pools
:icons: font
:imagesdir: ../media/

[.lead]
If you plan to use StorageGRID platform services or Cloud Storage Pools, you must configure grid networking and firewalls to ensure that the destination endpoints can be reached. 

== Networking for platform services

As described in xref:../admin/manage-platform-services-for-tenants.adoc[Manage platform services for tenants] and xref:../tenant/what-platform-services-are.adoc[What are platform services], platform services include external services that provide search integration, event notification, and CloudMirror replication.

Platform services require access from Storage Nodes that host the StorageGRID ADC service to the external service endpoints. Examples for providing access include:

* On the Storage Nodes with ADC services, configure unique Admin Networks with AESL entries that route to the target endpoints.
* Rely on the default route provided by a Client Network. If you use the default route, you can use the xref:../admin/managing-untrusted-client-networks.adoc[untrusted Client Network feature] to restrict inbound connections.

== Networking for Cloud Storage Pools

Cloud Storage Pools also require access from Storage Nodes to the endpoints provided by the external service used, such as Amazon S3 Glacier or Microsoft Azure Blob storage. For information, see xref:../ilm/what-cloud-storage-pool-is.adoc[What a Cloud Storage Pool is].

== Ports for platform services and Cloud Storage Pools

By default, platform services and Cloud Storage Pool communications use the following ports:

* *80*: For endpoint URIs that begin with `http`
* *443*: For endpoint URIs that begin with `https`

A different port can be specified when the endpoint is created or edited. See xref:network-port-reference.adoc[Network port reference].

If you use a non-transparent proxy server, you must also xref:../admin/configuring-storage-proxy-settings.adoc[configure storage proxy settings] to allow messages to be sent to external endpoints, such as an endpoint on the internet. 

== VLANs and platform services and Cloud Storage Pools
You cannot use VLAN networks for platform services or Cloud Storage Pools. The destination endpoints must be reachable over the Grid, Admin, or Client Network.
