---
permalink: network/network-installation-and-provisioning.html
sidebar: sidebar
keywords:
summary: 'You must understand how the Grid Network and the optional Admin and Client Networks are used during node deployment and grid configuration.'
---
= Network installation and provisioning
:icons: font
:imagesdir: ../media/

[.lead]
You must understand how the Grid Network and the optional Admin and Client Networks are used during node deployment and grid configuration.

== Initial deployment of a node

When you first deploy a node, you must attach the node to the Grid Network and ensure it has access to the primary Admin Node. If the Grid Network is isolated, you can configure the Admin Network on the primary Admin Node for configuration and installation access from outside the Grid Network.

A Grid Network with a gateway configured becomes the default gateway for a node during deployment. The default gateway allows grid nodes on separate subnets to communicate with the primary Admin Node before the grid has been configured.

If necessary, subnets containing NTP servers or requiring access to the Grid Manager or API can also be configured as grid subnets.

== Automatic node registration with primary Admin Node

After the nodes are deployed, they register themselves with the primary Admin Node using the Grid Network. You can then use the Grid Manager, the `configure-storagegrid.py` Python script, or the Installation API to configure the grid and approve the registered nodes. During grid configuration, you can configure multiple grid subnets. Static routes to these subnets through the Grid Network gateway will be created on each node when you complete grid configuration.

== Disabling the Admin Network or Client Network

If you want to disable the Admin Network or Client Network, you can remove the configuration from them during the node approval process, or you can use the Change IP tool after installation is complete. See the information about network maintenance procedures in the recovery and maintenance instructions.

.Related information

xref:../maintain/index.adoc[Maintain & recover]
