---
permalink: network/post_installation_guidelines.html
sidebar: sidebar
keywords:
summary: 'After completing grid node deployment and configuration, follow these guidelines for DHCP addressing and network configuration changes.'
---
= Post-installation guidelines
:icons: font
:imagesdir: ../media/

[.lead]
After completing grid node deployment and configuration, follow these guidelines for DHCP addressing and network configuration changes.

* If DHCP was used to assign IP addresses, configure a DHCP reservation for each IP address on the networks being used.
+
You can only set up DHCP during the deployment phase. You cannot set up DHCP during configuration.
+
IMPORTANT: Nodes reboot when their IP addresses change, which can cause outages if a DHCP address change affects multiple nodes at the same time.

* You must use the Change IP procedures if you want to change IP addresses, subnet masks, and default gateways for a grid node. See the information about configuring IP addresses in the recovery and maintenance instructions.
* If you make networking configuration changes, including routing and gateway changes, client connectivity to the primary Admin Node and other grid nodes might be lost. Depending on the networking changes applied, you might need to re-establish these connections.

.Related information

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-install-rhel/home.html[Red Hat Enterprise Linux or CentOS installation]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-install-ub/home.html[Ubuntu or Debian installation]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-install-vmw/home.html[VMware installation]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sga-install-sg1000/home.html[SG100 and SG1000 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sga-install-sg6000/home.html[SG6000 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sga-install-sg5700/home.html[SG5700 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-app-install/home.html[SG5600 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-maint/home.html[Recovery and maintenance]
