---
permalink: network/storagegrid_networking_overview.html
sidebar: sidebar
keywords:
summary: 'Configuring the networking for a StorageGRID system requires a high level of experience with Ethernet switching, TCP/IP networking, subnets, network routing, and firewalls.'
---
= StorageGRID networking overview
:icons: font
:imagesdir: ../media/

[.lead]
Configuring the networking for a StorageGRID system requires a high level of experience with Ethernet switching, TCP/IP networking, subnets, network routing, and firewalls.

Before you configure networking, become familiar with StorageGRID architecture as described in the _Grid primer_.

Before you deploy and configure StorageGRID, you must configure the networking infrastructure. Communication needs to occur among all the nodes in the grid and between the grid and external clients and services.

External clients and external services need to connect to StorageGRID networks to perform functions such as the following:

* Store and retrieve object data
* Receive email notifications
* Access the StorageGRID management interface (the Grid Manager and Tenant Manager)
* Access the audit share (optional)
* Provide services such as:
 ** Network Time Protocol (NTP)
 ** Domain Name System (DNS)
 ** Key Management Server (KMS)

StorageGRID networking must be configured appropriately to handle the traffic for these functions and more.

After you determine which of the three StorageGRID networks you want to use and how those networks will be configured, you can install and configure the StorageGRID nodes by following the appropriate instructions.

.Related information

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-primer/home.html[Grid primer]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-admin/home.html[Administering StorageGRID]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-rn/home.html[StorageGRID release notes]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-install-rhel/home.html[Red Hat Enterprise Linux or CentOS installation]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-install-ub/home.html[Ubuntu or Debian installation]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-install-vmw/home.html[VMware installation]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sga-install-sg1000/home.html[SG100 and SG1000 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sga-install-sg6000/home.html[SG6000 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sga-install-sg5700/home.html[SG5700 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-app-install/home.html[SG5600 appliance installation and maintenance]
