---
permalink: sg5600/configuring-autosupport.html
sidebar: sidebar
keywords: storagegrid, sg5600, storage node, storage appliance, configure, configuring, set up, setup, autosupport, auto support
summary: 'The AutoSupport tool collects data in a customer support bundle from the appliance and automatically sends the data to technical support. Configuring AutoSupport assists technical support with remote troubleshooting and problem analysis.'
---
= Configuring AutoSupport
:icons: font
:imagesdir: ../media/

[.lead]
The AutoSupport tool collects data in a customer support bundle from the appliance and automatically sends the data to technical support. Configuring AutoSupport assists technical support with remote troubleshooting and problem analysis.

.What you'll need

* The AutoSupport feature must be enabled and activated on the appliance.
+
The AutoSupport feature is activated and deactivated globally on a storage management station.

* The Storage Manager Event Monitor must be running on at least one machine with access to the appliance and, preferably, on no more than one machine.

.About this task

All of the data is compressed into a single compressed archive file format (.7z) at the location you specify.

AutoSupport provides the following types of messages:

[options="header"]
|===
| Message types| Description
a|
Event messages
a|

* Sent when a support event on the managed appliance occurs
* Include system configuration and diagnostic information

a|
Daily messages
a|

* Sent once every day during a user configurable time interval in the local time of the appliance
* Include the current system event logs and performance data

a|
Weekly messages
a|

* Sent once every week during a user configurable time interval in the local time of the appliance
* Include configuration and system state information

|===

.Steps

. From the Enterprise Management Window in SANtricity Storage Manager, select the *Devices* tab, and then select *Discovered Storage Arrays*.
. Select *Tools* > *AutoSupport* > *Configuration*.
. Use SANtricity Storage Manager online help, if needed, to complete the task.

.Related information

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61197[NetApp Documentation: SANtricity Storage Manager^]
