---
permalink: sg5600/connecting-ac-power-cords-sg5600.html
sidebar: sidebar
keywords: storagegrid, sg5600, storage node, storage appliance, wire, wiring, cabling, cable, Connecting, connect, power cords, power, ac, ac power
summary: 'You must connect the AC power cords to the external power source and to the AC power connector on each controller. After you have connected the power cords, you can turn the power on.'
---
= Connecting the AC power cords (SG5600)
:icons: font
:imagesdir: ../media/

[.lead]
You must connect the AC power cords to the external power source and to the AC power connector on each controller. After you have connected the power cords, you can turn the power on.

.What you'll need

Both appliance power switches must be off before connecting power.

CAUTION: *Risk of electrical shock* -- Before connecting the power cords, make sure that the two power switches on the appliance are off.

.About this task

* You should use separate power sources for each power supply.
+
Connecting to independent power sources maintains power redundancy.

* You can use the power cords shipped with the controller with typical outlets used in the destination country, such as wall receptacles of an uninterrupted power supply (UPS).
+
However, these power cords are not intended for use in most EIA-compliant cabinets.

.Steps

. Turn off the power switches in the enclosure or chassis.
. Turn off the power switches on the controllers.
. Connect the primary power cords from the cabinet to the external power sources.
. Connect the power cords to the AC power connector on each controller.
