---
permalink: sg5600/gathering-installation-information-sg5600.html
sidebar: sidebar
keywords: storagegrid, sg5600, storage node, storage appliance, install, information, site, pre-install, preparing, prepare, preinstall, info, preparation
summary: 'As you install and configure the StorageGRID appliance, you must make decisions and gather information about Ethernet switch ports, IP addresses, and port and network bond modes.'
---
= Gathering installation information (SG5600)
:icons: font
:imagesdir: ../media/

[.lead]
As you install and configure the StorageGRID appliance, you must make decisions and gather information about Ethernet switch ports, IP addresses, and port and network bond modes.

.About this task

You can use the following tables to record information for each network you connect to the appliance. These values are required to install and configure the hardware.

== Information needed to connect the E2700 controller to SANtricity Storage Manager

You must connect the E2700 controller to the management network you will use for SANtricity Storage Manager.

[options="header"]
|===
| Information needed| Your value
a|
Ethernet switch port you will connect to management port 1
a|

a|
MAC address for management port 1 (printed on a label near port P1)
a|

a|
DHCP-assigned IP address for management port 1, if available after power on

*Note:* If the network you will connect to the E2700 controller includes a DHCP server, the network administrator can use the MAC address to determine the IP address that was assigned by the DHCP server.

a|

a|
Speed and duplex mode

*Note:* You must make sure the Ethernet switch for the SANtricity Storage Manager management network is set to autonegotiate.

a|
Must be:

* Autonegotiate (default)

a|
IP address format
a|
Choose one:

* IPv4
* IPv6

a|
Static IP address you plan to use for the appliance on the management network
a|
For IPv4:

* IPv4 address:
* Subnet mask:
* Gateway:

For IPv6:

* IPv6 address:
* Routable IP address:
* E2700 controller router IP address:
|===

== Information needed to connect the E5600SG controller to the Admin Network

The Admin Network for StorageGRID is an optional network, used for system administration and maintenance. The appliance connects to the Admin Network using the 1-GbE management ports on the E5600SG controller.

[options="header"]
|===
| Information needed| Your value
a|
Admin Network enabled
a|
Choose one:

* No
* Yes (default)

a|
Network bond mode
a|
Choose one:

* Independent
* Active-Backup

a|
Switch port for management port 1 (P1)
a|

a|
Switch port for management port 2 (P2; Active-Backup network bond mode only)
a|

a|
MAC address for management port 1 (printed on a label near port P1)
a|

a|
DHCP-assigned IP address for management port 1, if available after power on

*Note:* If the Admin Network includes a DHCP server, the E5600SG controller displays the DHCP-assigned IP address on its seven-segment display after it boots up. You can also determine the DHCP-assigned IP address by using the MAC address to look up the assigned IP.

a|

* IPv4 address (CIDR):
* Gateway:

a|
Static IP address you plan to use for the appliance Storage Node on the Admin Network

*Note:* If your network does not have a gateway, specify the same static IPv4 address for the gateway.

a|

* IPv4 address (CIDR):
* Gateway:

a|
Admin Network subnets (CIDR)
a|

|===

== Information needed to connect and configure the 10-GbE ports on the E5600SG controller

The four 10-GbE ports on the E5600SG controller connect to the StorageGRID Grid Network and Client Network.

NOTE: See "10-GbE port connections for the E5600SG controller" for more information about the options for these
ports.

[options="header"]
|===
| Information needed| Your value
a|
Port bond mode

a|
Choose one:

* Fixed (default)
* Aggregate

a|
Switch port for port 1 (Client Network for Fixed mode)

a|

a|
Switch port for port 2 (Grid Network for Fixed mode)

a|

a|
Switch port for port 3 (Client Network for Fixed mode)

a|

a|
Switch port for port 4 (Grid Network for Fixed mode)

a|

|===

== Information needed to connect the E5600SG controller to the Grid Network

The Grid Network for StorageGRID is a required network, used for all internal StorageGRID traffic. The appliance connects to the Grid Network using the 10-GbE ports on the E5600SG controller.

NOTE: See "10-GbE port connections for the E5600SG controller" for more information about the options for these
ports.

[options="header"]
|===
| Information needed| Your value
a|
Network bond mode
a|
Choose one:

* Active-Backup (default)
* LACP (802.3ad)

a|
VLAN tagging enabled
a|
Choose one:

* No (default)
* Yes

a|
VLAN tag(if VLAN tagging is enabled)

a|
Enter a value between 0 and 4095:
a|
DHCP-assigned IP address for the Grid Network, if available after power on

*Note:* If the Grid Network includes a DHCP server, the E5600SG controller displays the DHCP-assigned IP address for the Grid Network on its seven-segment display after it boots up.

a|

* IPv4 address (CIDR):
* Gateway:

a|
Static IP address you plan to use for the appliance Storage Node on the Grid Network

*Note:* If your network does not have a gateway, specify the same static IPv4 address for the gateway.

a|

* IPv4 address (CIDR):
* Gateway:

a|
Grid Network subnets (CIDR)

*Note:* If the Client Network is not enabled, the default route on the controller will use the gateway specified here.

a|

|===

== Information needed to connect the E5600SG controller to the Client Network

The Client Network for StorageGRID is an optional network, used to provides client protocol access to the grid. The appliance connects to the Client Network using the 10-GbE ports on the E5600SG controller.

NOTE: See "10-GbE port connections for the E5600SG controller" for more information about the options for these
ports.

[options="header"]
|===
| Information needed| Your value
a|
Client Network enabled
a|
Choose one:

* No (default)
* Yes

a|
Network bond mode
a|
Choose one:

* Active-Backup (default)
* LACP (802.3ad)

a|
VLAN tagging enabled
a|
Choose one:

* No (default)
* Yes

a|
VLAN tag(if VLAN tagging is enabled)

a|
Enter a value between 0 and 4095:
a|
DHCP-assigned IP address for the Client Network, if available after power on
a|

* IPv4 address (CIDR):
* Gateway:

a|
Static IP address you plan to use for the appliance Storage Node on the Client Network

*Note:* If the Client Network is enabled, the default route on the controller will use the gateway specified here.

a|

* IPv4 address (CIDR):
* Gateway:

|===

.Related information

xref:reviewing-appliance-network-connections-sg5600.adoc[Reviewing appliance network connections]

xref:configuring-hardware.adoc[Configuring the hardware]

xref:port-bond-modes-for-e5600sg-controller-ports.adoc[Port bond modes for the E5600SG controller ports]
