---
permalink: sg5600/preparing-for-installation.html
sidebar: sidebar
keywords: storagegrid, sg5600, storage node, storage appliance, install, installation, preparation, get ready, prepare
summary: 'Preparing to install a StorageGRID appliance entails preparing the site and obtaining all required hardware, cables, and tools. You should also gather IP addresses and network information.'
---
= Preparing for installation (SG5600)
:icons: font
:imagesdir: ../media/

[.lead]
Preparing to install a StorageGRID appliance entails preparing the site and obtaining all required hardware, cables, and tools. You should also gather IP addresses and network information.

.Steps

* xref:preparing-site-sg5600.adoc[Preparing the site (SG5600)]
* xref:unpacking-boxes-sg5600.adoc[Unpacking the boxes (SG5600)]
* xref:obtaining-additional-equipment-and-tools-sg5600.adoc[Obtaining additional equipment and tools (SG5600)]
* xref:service-laptop-requirements-sg5600.adoc[Service laptop requirements]
* xref:../admin/web-browser-requirements.adoc[Web browser requirements]
* xref:reviewing-appliance-network-connections-sg5600.adoc[Reviewing appliance network connections (SG5600)]
* xref:gathering-installation-information-sg5600.adoc[Gathering installation information (SG5600)]
