---
permalink: sg5600/preparing_for_installation.html
sidebar: sidebar
keywords:
summary: 'Preparing to install a StorageGRID appliance entails preparing the site and obtaining all required hardware, cables, and tools. You should also gather IP addresses and network information.'
---
= Preparing for installation
:icons: font
:imagesdir: ../media/

[.lead]
Preparing to install a StorageGRID appliance entails preparing the site and obtaining all required hardware, cables, and tools. You should also gather IP addresses and network information.

.Steps

* xref:preparing_site_sg5600.adoc[Preparing the site (SG5600)]
* xref:unpacking_boxes_sg5600.adoc[Unpacking the boxes (SG5600)]
* xref:obtaining_additional_equipment_and_tools_sg5600.adoc[Obtaining additional equipment and tools (SG5600)]
* xref:service_laptop_requirements_sg5600.adoc[Service laptop requirements]
* xref:web_browser_requirements.adoc[Web browser requirements]
* xref:reviewing_appliance_network_connections_sg5600.adoc[Reviewing appliance network connections]
* xref:gathering_installation_information_sg5600.adoc[Gathering installation information (SG5600)]
