---
permalink: sg5600/preparing-site-sg5600.html
sidebar: sidebar
keywords: storagegrid, sg5600, storage node, storage appliance, install, installation, site prep, site preparating, preparing site, site requirements, requirements, site, dimensions, weight, weights, temperature, humidity, altitude, airflow, heat, wiring, power, grounding, facility
summary: 'Before installing the appliance, you must make sure that the site and the cabinet or rack you plan to use meet the specifications for a StorageGRID appliance.'
---
= Preparing the site (SG5600)
:icons: font
:imagesdir: ../media/

[.lead]
Before installing the appliance, you must make sure that the site and the cabinet or rack you plan to use meet the specifications for a StorageGRID appliance.

.Steps

. Confirm that the site meets the requirements for temperature, humidity, altitude range, airflow, heat dissipation, wiring, power, and grounding. See the NetApp Hardware Universe for more information.
. Obtain a 19-inch (48.3-cm) cabinet or rack to fit shelves of this size (without cables):
+
[options="header"]
|===
| Appliance model| Height| Width| Depth| Maximum weight
a|
SG5612

(12 drives)
a|
3.40 in.

(8.64 cm)
a|
19.0 in.

(48.26 cm)
a|
21.75 in.

(55.25 cm)
a|
59.5 lb

(27 kg)
a|
SG5660

(60 drives)
a|
7.00 in.

(17.78 cm)
a|
17.75 in.

(45.08 cm)
a|
32.50 in.

(82.55 cm)
a|
236.2 lb.

(107.1 kg)

|===

. Install any required network switches. See the NetApp Interoperability Matrix Tool for compatibility information.

.Related information

https://hwu.netapp.com[NetApp Hardware Universe^]

https://mysupport.netapp.com/NOW/products/interoperability[NetApp Interoperability^]
