---
permalink: sg5600/reference_hardware_setup_progress_appears_to_hang.html
sidebar: sidebar
keywords: 
summary: 'The StorageGRID Appliance Installer might not be available if hardware faults or cabling errors prevent the E5600SG controller from completing its boot-up processing.'
---
= Hardware setup appears to hang
:icons: font
:imagesdir: ../media/

[.lead]
The StorageGRID Appliance Installer might not be available if hardware faults or cabling errors prevent the E5600SG controller from completing its boot-up processing.

. Check the Needs Attention LED on either controller and look for a flashing error code.
+
During power up, the Service Action Allowed and Service Action Required LEDs are turned on while the hardware is initializing. The upper decimal point of the lower digit, called the diagnostic LED, also illuminates. The seven-segment display runs through a sequence of codes that are common for both controllers. This is normal and is not an indication of an error. When the hardware boots successfully, the Service Action LEDs are turned off, and the displays are driven by the firmware.

. Review the codes on the seven-segment display for the E5600SG controller.
+
NOTE: The installation and provisioning take time. Some installation phases do not report updates to the StorageGRID Appliance Installer for several minutes.
+
If an error occurs, the seven-segment display flashes a sequence, such as HE.

. To understand what these codes mean, see the following resources:
+
|===
| Controller| Reference
a|
E5600SG controller
a|

 ** "`HE error: Error synchronizing with SANtricity OS Software`"
 ** "`E5600SG controller seven-segment display codes`"

a|
E2700 controller
a|
E-Series documentation    *Note:* The codes described for the E-Series E5600 controller do not apply to the E5600SG controller in the appliance.
+
|===

. If this does not resolve the issue, contact technical support.

*Related information*

xref:reference_e5600sg_controller_seven_segment_display_codes.adoc[E5600SG controller seven-segment display codes]

xref:task_he_error_error_synchronizing_with_santricity_os_software.adoc[HE error: Error synchronizing with SANtricity OS Software]

https://library.netapp.com/ecm/ecm_download_file/ECMLP2344477[E2700 Controller-Drive Tray and Related Drive Trays Installation Guide]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61765[NetApp Documentation: E2700 Series]
