---
permalink: sg5600/reference_unable_to_connect_to_storagegrid_appliance_over_the_network.html
sidebar: sidebar
keywords: 
summary: ''
---
= Unable to connect to StorageGRID appliance over the network
:icons: font
:imagesdir: ../media/

* *Issue*
+
You cannot connect to the appliance.

* *Cause*
+
This could occur if there is a network issue or the hardware installation did not complete successfully.

* *Corrective action*
 .. Ping the appliance: `ping <E5600_controller_IP\>`
 .. Access the StorageGRID Appliance Installer by opening a browser and entering the following: `https://<Management_Port_IP\>:8443`
+
For Management_Port_IP, enter the IP address for management port 1 on the E5600SG controller (provisioned during the physical installation).

 .. Click *Configure Admin network*, and check the IP.
 .. If you receive a response from the ping, check that port 8443 is open in the firewalls.
 .. Reboot the appliance.
 .. Refresh the installation web page.
 .. If this does not resolve the connection issue, contact technical support from the NetApp Support Site at http://mysupport.netapp.com/[mysupport.netapp.com].

*Related information*

xref:reference_e5600sg_controller_seven_segment_display_codes.adoc[E5600SG controller seven-segment display codes]
