---
permalink: sg5600/replacing-e5600sg-controller.html
sidebar: sidebar
keywords: storagegrid, sg5600, storage node, storage appliance, hardware, Replacing, replace, E5600sg, controller, remove, removing, removal, install, installing, installation
summary: 'You might need to replace the E5600SG controller.'
---
= Replacing the E5600SG controller
:icons: font
:imagesdir: ../media/

[.lead]
You might need to replace the E5600SG controller.

.What you'll need

You must have access to the following resources:

* E-Series hardware replacement information on the NetApp Support Site at +
http://mysupport.netapp.com/[mysupport.netapp.com^]
* E5600 documentation on the Support Site
* The appliance has been placed maintenance mode.
+
xref:placing-appliance-into-maintenance-mode.adoc[Placing an appliance into maintenance mode]

.About this task

If both controllers are functioning sufficiently to allow for a controlled shutdown, you can shut down the E5600SG controller first to interrupt the connectivity to the E2700 controller.

NOTE: If you are replacing the controller before installing StorageGRID software, you might not be able to access the StorageGRID Appliance Installer immediately after completing this procedure. While you can access the StorageGRID Appliance Installer from other hosts on the same subnet as the appliance, you cannot access it from hosts on other subnets. This condition should resolve itself within 15 minutes (when any ARP cache entries for the original controller time out), or you can clear the condition immediately by purging any old ARP cache entries manually from the local router or gateway.

.Steps

. Use antistatic protection.
. Label each cable that is attached to the E5600SG controller, so you can reconnect the cables correctly.
+
IMPORTANT: To prevent degraded performance, do not twist, fold, pinch, or step on the cables. Do not bend the cables tighter than a 5-cm (2-in) radius.

. When the appliance has been placed maintenance mode, shut down the E5600SG controller.
 .. Log in to the grid node:
  ... Enter the following command: `ssh admin@_grid_node_IP_`
  ... Enter the password listed in the `Passwords.txt` file.
  ... Enter the following command to switch to root: `su -`
  ... Enter the password listed in the `Passwords.txt` file.
+
When you are logged in as root, the prompt changes from `$` to `#`.
 .. Shut down the E5600SG controller: +
`*shutdown -h now*`
. Turn off the power to the enclosure, and wait until all LED and seven-segment display activity on the rear of the controller has stopped.
. Remove the cables.
. Remove the controller, as described in the E5600SG controller documentation.
. Insert the new controller, as described in the E5600SG controller documentation.
. Replace all cables.
. Turn the power back on to the enclosure.
. Monitor the seven-segment codes.
 ** E2700 controller:
+
The final LED state is `99`.

 ** E5600SG controller:
+
The final LED state is `HA`.
. Monitor the status of the appliance Storage Node in the Grid Manager.
+
Verify that the appliance Storage Nodes returns to the expected status.

.Related information

https://mysupport.netapp.com/info/web/ECMP11751516.html[NetApp E-Series and EF-Series Hardware Replacement Procedures^]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61893[NetApp Documentation: E5600 Series^]
