---
permalink: sg5600/storagegrid-appliance-features.html
sidebar: sidebar
keywords: storagegrid, sg5600, storage node, storage appliance, features 
summary: 'The StorageGRID SG5600 appliance provides an integrated storage solution for creating a new StorageGRID system or for expanding the capacity of an existing system.'
---
= StorageGRID appliance features
:icons: font
:imagesdir: ../media/

[.lead]
The StorageGRID SG5600 appliance provides an integrated storage solution for creating a new StorageGRID system or for expanding the capacity of an existing system.

The StorageGRID appliance provides the following features:

* Combines the StorageGRID Storage Node computing and storage elements into a single, efficient, integrated solution
* Simplifies the installation and configuration of a Storage Node, automating most of the process required
* Provides a high-density storage solution with two enclosure options: one that is 2U and one that is 4U
* Uses 10-GbE IP interfaces directly to the Storage Node, without the need for intermediate storage interfaces such as FC or iSCSI
* Can be used in a hybrid grid environment that uses StorageGRID appliances and virtual (software-based) Storage Nodes
* Includes preconfigured storage and comes preloaded with the StorageGRID Appliance Installer (on the E5600SG controller) for field-ready software deployment and integration
