---
permalink: sg5600/turning-power-on-sg5600.html
sidebar: sidebar
keywords: storagegrid, sg5600, storage node, storage appliance, power on, power, start 
summary: 'Powering on the enclosure provides power to both controllers.'
---
= Turning power on (SG5600)
:icons: font
:imagesdir: ../media/

[.lead]
Powering on the enclosure provides power to both controllers.

.Steps

. Turn on the two power supply switches at the rear of the enclosure.
+
While the power is being applied, the LEDs on the controllers go on and off intermittently.
+
The power-on process can take up to ten minutes to complete. The controllers reboot several times during the initial startup sequence, which causes the fans to ramp up and down and the LEDs to flash.

. Check the Power LED and the Host Link Active LEDs on each controller to verify that the power was turned on.
. Wait for all drives to show a persistent green LED, indicating that they have come online.
. Check for green LEDs on the front and rear of the enclosure.
+
If you see any amber LEDs, make a note of their locations.

. Look at the seven-segment display for the E5600SG controller.
+
This display shows *HO*, followed by a repeating sequence of two digits.
+
----
HO -- IP address for Admin Network -- IP address for Grid Network HO
----
+
In the sequence, the first set of numbers is the DHCP-assigned IP address for the controller's management port 1. This address is used to connect the controller to the Admin Network for StorageGRID. The second set of numbers is the DHCP-assigned IP address used to connect the appliance to the Grid Network for StorageGRID.
+
NOTE: If an IP address could not be assigned using DHCP, 0.0.0.0 is displayed.
