---
permalink: sg5600/viewing-boot-up-status-and-reviewing-error-codes-on-sg5600-controllers.html
sidebar: sidebar
keywords: storagegrid, sg5600, storage node, storage appliance, status, boot codes, boot, error codes, error, code, start, startup, start up, start-up, progress, e5600sg
summary: 'The seven-segment display on each controller shows status and error codes when the appliance powers up, while the hardware is initializing, and when the hardware fails and must back out of the initialization. If you are monitoring the progress or troubleshooting, you should watch the sequence of the codes as they appear.'
---
= Viewing boot-up status and reviewing error codes on the SG5600 controllers
:icons: font
:imagesdir: ../media/

[.lead]
The seven-segment display on each controller shows status and error codes when the appliance powers up, while the hardware is initializing, and when the hardware fails and must back out of the initialization. If you are monitoring the progress or troubleshooting, you should watch the sequence of the codes as they appear.

.About this task

The status and error codes for the E5600SG controller are not the same as those for the E2700 controller.

.Steps

. During boot-up, view the codes shown on the seven-segment displays to monitor progress.
. To review error codes for the E5600SG controller, see the seven-segment display status and error code information.
. To review error codes for the E2700 controller, see the E2700 controller documentation on the Support Site.

.Related information

xref:e5600sg-controller-seven-segment-display-codes.adoc[E5600SG controller seven-segment display codes]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61765[NetApp Documentation: E2700 Series^]
