---
permalink: sg5600/viewing_boot_up_status_and_reviewing_error_codes_on_sg5600_controllers.html
sidebar: sidebar
keywords: 
summary: 'The seven-segment display on each controller shows status and error codes when the appliance powers up, while the hardware is initializing, and when the hardware fails and must back out of the initialization. If you are monitoring the progress or troubleshooting, you should watch the sequence of the codes as they appear.'
---
= Viewing boot-up status and reviewing error codes on the SG5600 controllers
:icons: font
:imagesdir: ../media/

[.lead]
The seven-segment display on each controller shows status and error codes when the appliance powers up, while the hardware is initializing, and when the hardware fails and must back out of the initialization. If you are monitoring the progress or troubleshooting, you should watch the sequence of the codes as they appear.

The status and error codes for the E5600SG controller are not the same as those for the E2700 controller.

. During boot-up, view the codes shown on the seven-segment displays to monitor progress.
. To review error codes for the E5600SG controller, see the seven-segment display status and error code information.
. To review error codes for the E2700 controller, see the E2700 controller documentation on the Support Site.

*Related information*

xref:e5600sg_controller_seven_segment_display_codes.adoc[E5600SG controller seven-segment display codes]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61765[NetApp Documentation: E2700 Series]
