---
permalink: tenant/changing-consistency-level.html
sidebar: sidebar
keywords: how to change tenant consistency level, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global
summary: 'If you are using an S3 tenant, you can use the Tenant Manager or the Tenant Management API to change the consistency control for operations performed on the objects in S3 buckets.'
---
= Change the consistency level
:icons: font
:imagesdir: ../media/

[.lead]
If you are using an S3 tenant, you can use the Tenant Manager or the Tenant Management API to change the consistency control for operations performed on the objects in S3 buckets.

.What you'll need
* You must be signed in to the Tenant Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You must belong to a user group that has the Manage All Buckets or the Root Access permission. These permissions override the permissions settings in group or bucket policies. See xref:tenant-management-permissions.adoc[Tenant management permissions].

.About this task

Consistency level provides a balance between the availability of the objects and the consistency of those objects across different Storage Nodes and sites. In general, you should use the *Read-after-new-write* consistency level for your buckets.

If the *Read-after-new-write* consistency level does not meet the client application's requirements, you can change the consistency level by setting the bucket consistency level or by using the `Consistency-Control` header. The `Consistency-Control` header overrides the bucket consistency level.

NOTE: When you change a bucket's consistency level, only those objects that are ingested after the change are guaranteed to meet the revised level.

.Steps
. Select *STORAGE (S3)* > *Buckets*.
. Select the bucket name from the list.
+
The bucket details page appears.

. Select *Bucket options* > *Consistency level*.

. Select a consistency level for operations performed on the objects in this bucket.
+
* *All*: Provides the highest level of consistency. All nodes receive the data immediately, or the request will fail.

* *Strong-global*: Guarantees read-after-write consistency for all client requests across all sites.

* *Strong-site*: Guarantees read-after-write consistency for all client requests within a site.

* *Read-after-new-write* (default): Provides read-after-write consistency for new objects and eventual consistency for object updates. Offers high availability and data protection guarantees. Recommended for most cases.

* *Available*: Provides eventual consistency for both new objects and object updates. For S3 buckets, use only as required (for example, for a bucket that contains log values that are rarely read, or for HEAD or GET operations on keys that do not exist). Not supported for S3 FabricPool buckets.

. Select *Save changes*.