---
permalink: tenant/considerations-for-using-platform-services.html
sidebar: sidebar
keywords: storagegrid, tenant, platform services considerations, cloudmirror considerations
summary: 'Before implementing platform services, review the recommendations and considerations for using these services.'
---
= Considerations for using platform services
:icons: font
:imagesdir: ../media/

[.lead]
Before implementing platform services, review the recommendations and considerations for using these services.

== Considerations for using platform services

[cols="1a,3a" options="header"]
|===
| Consideration| Details
a|
Destination endpoint monitoring

a|
You must monitor the availability of each destination endpoint. If connectivity to the destination endpoint is lost for an extended period of time and a large backlog of requests exists, additional client requests (such as PUT requests) to StorageGRID will fail. You must retry these failed requests when the endpoint becomes reachable.

a|
Destination endpoint throttling

a|
StorageGRID software might throttle incoming S3 requests for a bucket if the rate at which the requests are being sent exceeds the rate at which the destination endpoint can receive the requests. Throttling only occurs when there is a backlog of requests waiting to be sent to the destination endpoint.

The only visible effect is that the incoming S3 requests will take longer to execute. If you start to detect significantly slower performance, you should reduce the ingest rate or use an endpoint with higher capacity. If the backlog of requests continues to grow, client S3 operations (such as PUT requests) will eventually fail.

CloudMirror requests are more likely to be affected by the performance of the destination endpoint because these requests typically involve more data transfer than search integration or event notification requests.

a|
Ordering guarantees

a|
StorageGRID guarantees ordering of operations on an object within a site. As long as all operations against an object are within the same site, the final object state (for replication) will always equal the state in StorageGRID.

StorageGRID makes a best effort attempt to order requests when operations are made across StorageGRID sites. For example, if you write an object initially to site A and then later overwrite the same object at site B, the final object replicated by CloudMirror to the destination bucket is not guaranteed to be the newer object.

a|
ILM-driven object deletions

a|
To match the deletion behavior of the AWS CRR and SNS services, CloudMirror and event notification requests are not sent when an object in the source bucket is deleted because of StorageGRID ILM rules. For example, no CloudMirror or event notifications requests are sent if an ILM rule deletes an object after 14 days.

In contrast, search integration requests are sent when objects are deleted because of ILM.

[cols="1a,3a" options="header"]
|===

== Considerations for using the CloudMirror replication service

|===
| Consideration| Details
a|
Replication status

a|
StorageGRID does not support the `x-amz-replication-status` header.

a|
Object size

a|
The maximum size for objects that can be replicated to a destination bucket by the CloudMirror replication service is 5 TB, which is the same as the maximum object size supported by StorageGRID.

a|
Bucket versioning and version IDs

a|
If the source S3 bucket in StorageGRID has versioning enabled, you should also enable versioning for the destination bucket.

When using versioning, note that the ordering of object versions in the destination bucket is best effort and not guaranteed by the CloudMirror service, due to limitations in the S3 protocol.

*Note*: Version IDs for the source bucket in StorageGRID are not related to the version IDs for the destination bucket.

a|
Tagging for object versions

a|
The CloudMirror service does not replicate any PUT Object tagging or DELETE Object tagging requests that supply a version ID, due to limitations in the S3 protocol. Because version IDs for the source and destination are not related, there is no way to ensure that a tag update to a specific version ID will be replicated.

In contrast, the CloudMirror service does replicate PUT Object tagging requests or DELETE Object tagging requests that do not specify a version ID. These requests update the tags for the latest key (or the latest version if the bucket is versioned). Normal ingests with tags (not tagging updates) are also replicated.

a|
Multipart uploads and `ETag` values
a|
When mirroring objects that were uploaded using a multipart upload, the CloudMirror service does not preserve the parts. As a result, the `ETag` value for the mirrored object will be different than the `ETag` value of the original object.

a|
Objects encrypted with SSE-C (server-side encryption with customer-provided keys)
a|
The CloudMirror service does not support objects that are encrypted with SSE-C. If you attempt to ingest an object into the source bucket for CloudMirror replication and the request includes the SSE-C request headers, the operation fails.

a|
Bucket with S3 Object Lock enabled
a|
If the destination S3 bucket for CloudMirror replication has S3 Object Lock enabled, the replication operation will fail with an AccessDenied error.

|===
.Related information

xref:../s3/index.adoc[Use S3]
