---
permalink: tenant/disabling_identity_federation.html
sidebar: sidebar
keywords:
summary: 'If you configured an identity federation service for this tenant, you can temporarily or permanently disable identity federation for tenant groups and users. When identity federation is disabled, there is no communication between the StorageGRID system and the identity source. However, any settings you have configured are retained, allowing you to easily re-enable identity federation in the future.'
---
= Disabling identity federation
:icons: font
:imagesdir: ../media/

[.lead]
If you configured an identity federation service for this tenant, you can temporarily or permanently disable identity federation for tenant groups and users. When identity federation is disabled, there is no communication between the StorageGRID system and the identity source. However, any settings you have configured are retained, allowing you to easily re-enable identity federation in the future.

.What you'll need
* You must be signed in to the Tenant Manager using a supported browser.
* You must have specific access permissions.

.About this task
Before you disable identity federation, you should be aware of the following:

* Federated users will be unable to sign in.
* Federated users who are currently signed in will retain access to the tenant account until their session expires, but they will be unable to sign in after their session expires.
* Synchronization between the StorageGRID system and the identity source will not occur.

.Steps
. Select *ACCESS MANAGEMENT* > *Identity federation*.
. Deselect the *Enable identity federation* check box.
. Select *Save*.

.Related information

xref:tenant_management_permissions.adoc[Tenant management permissions]
