---
permalink: tenant/forcing_synchronization_with_identity_source.html
sidebar: sidebar
keywords: 
summary: 'The StorageGRID system periodically synchronizes federated groups and users from the identity source. You can force synchronization to start if you want to enable or restrict user permissions as quickly as possible.'
---
= Forcing synchronization with the identity source
:icons: font
:imagesdir: ../media/

[.lead]
The StorageGRID system periodically synchronizes federated groups and users from the identity source. You can force synchronization to start if you want to enable or restrict user permissions as quickly as possible.

* You must be signed in to the Tenant Manager using a supported browser.
* You must have specific access permissions.
* The saved identity source must be enabled.

. Select *ACCESS MANAGEMENT* > *Identity federation*.
+
The Identity federation page appears. The *Sync server* button is at the top right of the page.
+
NOTE: If the saved identity source is not enabled, the *Sync server* button will not be active.

. Select *Sync server*.
+
A confirmation message is displayed indicating that synchronization started successfully.

*Related information*

xref:tenant_management_permissions.adoc[Tenant management permissions]
