---
permalink: tenant/specifying-urn-for-platform-services-endpoint.html
sidebar: sidebar
keywords: storagegrid, tenant, platform services urn, urn
summary: 'When you create a platform services endpoint, you must specify a Unique Resource Name \(URN\). You will use the URN to reference the endpoint when you create configuration XML for the platform service. The URN for each endpoint must be unique.'
---
= Specifying the URN for a platform services endpoint
:icons: font
:imagesdir: ../media/

[.lead]
When you create a platform services endpoint, you must specify a Unique Resource Name (URN). You will use the URN to reference the endpoint when you create configuration XML for the platform service. The URN for each endpoint must be unique.

StorageGRID validates platform services endpoints as you create them. Before you create a platform services endpoint, confirm that the resource specified in the endpoint exists and that it can be reached.

== URN elements

The URN for a platform services endpoint must start with either `arn:aws` or `urn:mysite`, as follows:

* If the service is hosted on AWS, use `arn:aws`.
* If the service is hosted locally, use `urn:mysite`

For example, if you are specifying the URN for a CloudMirror endpoint hosted on StorageGRID, the URN might begin with `urn:sgws`.

The next element of the URN specifies the type of platform service, as follows:

[cols="2a,1a" options="header"]
|===
|Service |Type
|CloudMirror replication
m|s3

|Notifications
m|sns

|Search integration
m|es
|===
For example, to continue specifying the URN for a CloudMirror endpoint hosted on StorageGRID, you would add `s3` to get `urn:sgws:s3`.

The final element of the URN identifies the specific target resource at the destination URI.

[cols="1a,2a" options="header"]
|===
| Service| Specific resource
a|CloudMirror replication
m|bucket-name

a|Notifications
m|sns-topic-name

|Search integration
|`domain-name/index-name/type-name`

*Note:* If the Elasticsearch cluster is *not* configured to create indexes automatically, you must create the index manually before you create the endpoint.

|===

== URNs for services hosted on AWS

For AWS entities, the complete URN is a valid AWS ARN. For example:

* CloudMirror replication:
+
----
arn:aws:s3:::bucket-name
----

* Notifications:
+
----
arn:aws:sns:region:account-id:topic-name
----

* Search integration:
+
----
arn:aws:es:region:account-id:domain/domain-name/index-name/type-name
----
+
NOTE: For an AWS search integration endpoint, the `domain-name` must include the literal string `domain/`, as shown here.

== URNs for locally-hosted services

When using locally-hosted services instead of cloud services, you can specify the URN in any way that creates a valid and unique URN, as long as the URN includes the required elements in the third and final positions. You can leave the elements indicated by optional blank, or you can specify them in any way that helps you identify the resource and make the URN unique. For example:

* CloudMirror replication:
+
----
urn:mysite:s3:optional:optional:bucket-name
----
+
For a CloudMirror endpoint hosted on StorageGRID, you can specify a valid URN that begins with `urn:sgws`:
+
----
urn:sgws:s3:optional:optional:bucket-name
----

* Notifications:
+
----
urn:mysite:sns:optional:optional:sns-topic-name
----

* Search integration:
+
----
urn:mysite:es:optional:optional:domain-name/index-name/type-name
----
+
NOTE: For locally-hosted search integration endpoints, the `domain-name` element can be any string as long as the URN of the endpoint is unique.
