---
permalink: tenant/understanding-notifications-for-buckets.html
sidebar: sidebar
keywords: StorageGRID, tenant, s3 bucket, event notification, supported notifications, supported messages, sequencer key
summary: 'You can enable event notification for an S3 bucket if you want StorageGRID to send notifications about specified events to a destination Amazon Simple Notification Service \(SNS\).'
---
= Understanding notifications for buckets
:icons: font
:imagesdir: ../media/

[.lead]
You can enable event notification for an S3 bucket if you want StorageGRID to send notifications about specified events to a destination Amazon Simple Notification Service (SNS).

You can configure event notifications by associating notification configuration XML with a source bucket. The notification configuration XML follows S3 conventions for configuring bucket notifications, with the destination SNS topic specified as the URN of an endpoint.

Event notifications are created at the source bucket as specified in the notification configuration and are delivered to the destination. If an event associated with an object succeeds, a notification about that event is created and queued for delivery.

The uniqueness and ordering of notifications are not guaranteed. More than one notification of an event might be delivered to the destination as a result of operations taken to guarantee delivery success. And because delivery is asynchronous, the time ordering of notifications at the destination is not guaranteed to match the ordering of events on the source bucket, particularly for operations that originate from different StorageGRID sites. You can use the `sequencer` key in the event message to determine the order of events for a particular object, as described in Amazon S3 documentation.

== Supported notifications and messages

StorageGRID event notification follows the Amazon S3 API with the following limitations:

* You cannot configure a notification for the following event types. These event types are *not* supported.
 ** `s3:ReducedRedundancyLostObject`
 ** `s3:ObjectRestore:Completed`
* Event notifications sent from StorageGRID use the standard JSON format except that they do not include some keys and use specific values for others, as shown in the table:

[cols="1a,2a" options="header"]
|===
| Key name| StorageGRID value
a|
eventSource
a|
`sgws:s3`
a|
awsRegion
a|
not included
a|
x-amz-id-2
a|
not included
a|
arn
a|
`urn:sgws:s3:::bucket_name`
|===

.Related information

xref:configuring-event-notifications.adoc[Configuring event notifications]
