---
permalink: tenant/using_search_integration_service.html
sidebar: sidebar
keywords:
summary: 'The search integration service is one of the three StorageGRID platform services. You can enable this service to send object metadata to a destination search index whenever an object is created, deleted, or its metadata or tags are updated.'
---
= Using the search integration service
:icons: font
:imagesdir: ../media/

[.lead]
The search integration service is one of the three StorageGRID platform services. You can enable this service to send object metadata to a destination search index whenever an object is created, deleted, or its metadata or tags are updated.

You can configure search integration by using the Tenant Manager to apply custom StorageGRID configuration XML to a bucket.

NOTE: Because the search integration service causes object metadata to be sent to a destination, its configuration XML is referred to as _metadata notification configuration XML_. This configuration XML is different than the _notification configuration XML_ used to enable event notifications.

See the instructions for implementing S3 client applications for details about the following custom StorageGRID S3 REST API operations:

* DELETE Bucket metadata notification configuration request
* GET Bucket metadata notification configuration request
* PUT Bucket metadata notification configuration request

.Related information

xref:configuration_xml_for_search_configuration.adoc[Configuration XML for search integration]

xref:object_metadata_included_in_metadata_notifications.adoc[Object metadata included in metadata notifications]

xref:json_generated_by_search_integration_service.adoc[JSON generated by the search integration service]

xref:configuring_search_integration_service.adoc[Configuring the search integration service]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-s3/home.html[Implementing S3 client applications]
