---
permalink: vmware/automating_grid_node_deployment_in_vmware_vsphere.html
sidebar: sidebar
keywords: 
summary: 'You can automate the deployment of StorageGRID grid nodes in VMware vSphere.'
---
= Automating grid node deployment in VMware vSphere
:icons: font
:imagesdir: ../media/

[.lead]
You can automate the deployment of StorageGRID grid nodes in VMware vSphere.

* You have access to a Linux/Unix system with Bash 3.2 or later.
* You have VMware OVF Tool 4.1 installed and correctly configured.
* You know the username and password required to access VMware vSphere using the OVF Tool.
* You know the virtual infrastructure (VI) URL for the location in vSphere where you want to deploy the StorageGRID virtual machines. This URL will typically be a vApp, or Resource Pool. For example: vi://vcenter.example.com/vi/sgws
+
NOTE: You can use the VMware `ovftool` utility to determine this value (see the `ovftool` documentation for details).
+
NOTE: If you are deploying to a vApp, the virtual machines will not start automatically the first time, and you must power them on manually.

* You have collected all the required information for the configuration file. See "`Collecting information about your deployment environment`" for information.
* You have access to the following files from the VMware installation archive for StorageGRID:
+
|===
| Filename| Description
a|
NetApp-SG-version-SHA.vmdk
a|
The virtual machine disk file that is used as a template for creating grid node virtual machines.    *Note:* This file must be in the same folder as the .ovf and .mf files.
a|
    vsphere-primary-admin.ovf
+
vsphere-primary-admin.mf
a|
The Open Virtualization Format template file (.ovf) and manifest file (.mf) for deploying the primary Admin Node.
a|
    vsphere-non-primary-admin.ovf
+
vsphere-non-primary-admin.mf
a|
The template file (.ovf) and manifest file (.mf) for deploying non-primary Admin Nodes.
a|
    vsphere-archive.ovf
+
vsphere-archive.mf
a|
The template file (.ovf) and manifest file (.mf) for deploying Archive Nodes.
a|
    vsphere-gateway.ovf
+
vsphere-gateway.mf
a|
The template file (.ovf) and manifest file (.mf) for deploying Gateway Nodes.
a|
    vsphere-storage.ovf
+
vsphere-storage.mf
a|
The template file (.ovf) and manifest file (.mf) for deploying virtual machine-based Storage Nodes.
a|
deploy-vsphere-ovftool.sh
a|
The Bash shell script used to automate the deployment of virtual grid nodes.
a|
deploy-vsphere-ovftool-sample.ini
a|
The sample configuration file for use with the deploy-vsphere-ovftool.sh script.
|===

.Related information

xref:collecting_information_about_your_deployment_environment.adoc[Collecting information about your deployment environment]
