---
permalink: vmware/automating-grid-node-deployment-in-vmware-vsphere.html
sidebar: sidebar
keywords:
summary: 'You can automate the deployment of StorageGRID grid nodes in VMware vSphere.'
---
= Automating grid node deployment in VMware vSphere
:icons: font
:imagesdir: ../media/

[.lead]
You can automate the deployment of StorageGRID grid nodes in VMware vSphere.

.What you'll need

* You have access to a Linux/Unix system with Bash 3.2 or later.
* You have VMware OVF Tool 4.1 installed and correctly configured.
* You know the username and password required to access VMware vSphere using the OVF Tool.
* You know the virtual infrastructure (VI) URL for the location in vSphere where you want to deploy the StorageGRID virtual machines. This URL will typically be a vApp, or Resource Pool. For example: `vi://vcenter.example.com/vi/sgws`
+
NOTE: You can use the VMware `ovftool` utility to determine this value (see the `ovftool` documentation for details).
+
NOTE: If you are deploying to a vApp, the virtual machines will not start automatically the first time, and you must power them on manually.

* You have collected all the required information for the configuration file. See xref:collecting-information-about-your-deployment-environment.adoc[Collecting information about your deployment environment] for information.
* You have access to the following files from the VMware installation archive for StorageGRID:

[cols="1a,1a" options="header"]
|===
| Filename| Description
m|NetApp-SG-version-SHA.vmdk
|The virtual machine disk file that is used as a template for creating grid node virtual machines.

*Note:* This file must be in the same folder as the `.ovf` and `.mf` files.

m|vsphere-primary-admin.ovf

vsphere-primary-admin.mf
|The Open Virtualization Format template file (`.ovf`) and manifest file (`.mf`) for deploying the primary Admin Node.

m|vsphere-non-primary-admin.ovf

vsphere-non-primary-admin.mf
|The template file (`.ovf`) and manifest file (`.mf`) for deploying non-primary Admin Nodes.

m|vsphere-archive.ovf

vsphere-archive.mf
|The template file (`.ovf`) and manifest file (`.mf`) for deploying Archive Nodes.

m|vsphere-gateway.ovf

vsphere-gateway.mf
|The template file (`.ovf`) and manifest file (`.mf`) for deploying Gateway Nodes.

m|vsphere-storage.ovf

vsphere-storage.mf
|The template file (`.ovf`) and manifest file (`.mf`) for deploying virtual machine-based Storage Nodes.

m|deploy-vsphere-ovftool.sh
|The Bash shell script used to automate the deployment of virtual grid nodes.

m|deploy-vsphere-ovftool-sample.ini
|The sample configuration file for use with the `deploy-vsphere-ovftool.sh` script.
|===
