---
permalink: vmware/collecting-information-about-your-deployment-environment.html
sidebar: sidebar
keywords: how to collect information about your deployment environment
summary: 'Before deploying grid nodes, you must collect information about your network configuration and VMware environment.'
---
= Collect information about your deployment environment
:icons: font
:imagesdir: ../media/

[.lead]
Before deploying grid nodes, you must collect information about your network configuration and VMware environment.

IMPORTANT: It is more efficient to perform one single installation of all the nodes, rather than installing some nodes now and some nodes later.

== VMware information

You must access the deployment environment and collect information about the VMware environment; the networks that were created for the Grid, Admin, and Client Networks; and the storage volume types you plan to use for Storage Nodes.

You must collect information about your VMware environment, including the following:

* The username and password for a VMware vSphere account that has appropriate permissions to complete the deployment.
* Host, datastore, and network configuration information for each StorageGRID grid node virtual machine.

IMPORTANT: VMware live vMotion causes the virtual machine clock time to jump and is not supported for grid nodes of any type. Though rare, incorrect clock times can result in loss of data or configuration updates.

== Grid Network information

You must collect information about the VMware network created for the StorageGRID Grid Network (required), including:

* The network name.
* If you are not using DHCP, the required networking details for each grid node (IP address, gateway, and network mask).
* If you are not using DHCP, the IP address of the primary Admin Node on the Grid Network. See "`How grid nodes discover the primary Admin Node`" for more information.

== Admin Network information

For nodes that will be connected to the optional StorageGRID Admin Network, you must collect information about the VMware network created for this network, including:

* The network name.
* The method used to assign IP addresses, either static or DHCP.
* If you are using static IP addresses, the required networking details for each grid node (IP address, gateway, network mask).
* The external subnet list (ESL) for the Admin Network.

== Client Network information

For nodes that will be connected to the optional StorageGRID Client Network, you must collect information about the VMware network created for this network, including:

* The network name.
* The method used to assign IP addresses, either static or DHCP.
* If you are using static IP addresses, the required networking details for each grid node (IP address, gateway, network mask).

== Information about additional interfaces
You can optionally add trunk or access interfaces to the VM in vCenter after you install the node. For example, you might want to add a trunk interface to an Admin or Gateway Node, so you can use VLAN interfaces to segregate the traffic belonging to different applications or tenants. Or, you might want to add an access interface to use in a high availability (HA) group.

The interfaces you add are displayed on the VLAN interfaces page and on the HA groups page in the Grid Manager.

* If you add a trunk interface, configure one or more VLAN interfaces for each new parent interface. See xref:../admin/configure-vlan-interfaces.html[configure VLAN interfaces]. 

* If you add an access interface, you must add it directly to HA groups. See xref:../admin/configure-high-availability-group.html[configure high availability groups].


== Storage volumes for virtual Storage Nodes

You must collect the following information for virtual machine-based Storage Nodes:

* The number and size of storage volumes (storage LUNs) you plan to add. See "`Storage and performance requirements.`"

== Grid configuration information

You must collect information to configure your grid:

* Grid license
* Network Time Protocol (NTP) server IP addresses
* Domain Name System (DNS) server IP addresses

.Related information

xref:how-grid-nodes-discover-primary-admin-node.adoc[How grid nodes discover the primary Admin Node]

xref:storage-and-performance-requirements.adoc[Storage and performance requirements]
