---
permalink: vmware/defining-configuration-file-for-your-deployment.html
sidebar: sidebar
keywords:
summary: 'You specify the information needed to deploy virtual grid nodes for StorageGRID in a configuration file, which is used by the deploy-vsphere-ovftool.sh Bash script. You can modify a sample configuration file, so that you do not have to create the file from scratch.'
---
= Defining the configuration file for your deployment
:icons: font
:imagesdir: ../media/

[.lead]
You specify the information needed to deploy virtual grid nodes for StorageGRID in a configuration file, which is used by the `deploy-vsphere-ovftool.sh` Bash script. You can modify a sample configuration file, so that you do not have to create the file from scratch.

.Steps

. Make a copy of the sample configuration file (`deploy-vsphere-ovftool.sample.ini`). Save the new file as `deploy-vsphere-ovftool.ini` in the same directory as `deploy-vsphere-ovftool.sh`.
. Open `deploy-vsphere-ovftool.ini`.
. Enter all of the information required to deploy VMware virtual grid nodes.
+
See xref:configuration-file-settings.adoc[Configuration file settings] for information.

. When you have entered and verified all of the necessary information, save and close the file.
