---
permalink: vmware/deploying_virtual_machine_grid_nodes_in_vmware_vsphere_web_client.html
sidebar: sidebar
keywords:
summary: 'You use VMware vSphere Web Client to deploy each grid node as a virtual machine. During deployment, each grid node is created and connected to one or more networks. If you need to deploy any StorageGRID appliance Storage Nodes, see the installation and maintenance instructions for the appliance after you have deployed all virtual machine grid nodes.'
---
= Deploying virtual machine grid nodes in VMware vSphere Web Client
:icons: font
:imagesdir: ../media/

[.lead]
You use VMware vSphere Web Client to deploy each grid node as a virtual machine. During deployment, each grid node is created and connected to one or more networks. If you need to deploy any StorageGRID appliance Storage Nodes, see the installation and maintenance instructions for the appliance after you have deployed all virtual machine grid nodes.

* xref:collecting_information_about_your_deployment_environment.adoc[Collecting information about your deployment environment]
* xref:how_grid_nodes_discover_primary_admin_node.adoc[How grid nodes discover the primary Admin Node]
* xref:deploying_storagegrid_node_as_virtual_machine.adoc[Deploying a StorageGRID node as a virtual machine]

.Related information

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sga-install-sg1000/home.html[SG100 and SG1000 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-app-install/home.html[SG5600 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sga-install-sg5700/home.html[SG5700 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sga-install-sg6000/home.html[SG6000 appliance installation and maintenance]
