---
permalink: vmware/downloading_and_extracting_storagegrid_installation_files.html
sidebar: sidebar
keywords: 
summary: 'You must download the StorageGRID installation archives and extract the files..'
---
= Downloading and extracting the StorageGRID installation files
:icons: font
:imagesdir: ../media/

[.lead]
You must download the StorageGRID installation archives and extract the files..

. Go to the NetApp Downloads page for StorageGRID.
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads: StorageGRID]

. Select the button for downloading the latest release, or select another version from the drop-down menu and select *Go*.
. Sign in with the username and password for your NetApp account.
. If a Caution/MustRead statement appears, read it and select the check box.
+
You must apply any required hotfixes after you install the StorageGRID release. For more information, see the hotfix procedure in the recovery and maintenance instructions.

. Read the End User License Agreement, select the check box, and then select *Accept & Continue*.
. In the *Install StorageGRID* column, select the appropriate software.
+
Download the .tgz or .zip archive file for your platform.

 ** StorageGRID-Webscale-version-VMware-uniqueID.zip
 ** StorageGRID-Webscale-version-VMware-uniqueID.tgz
*Note:* Use the .zip file if you are running Windows on the service laptop.

. Save and extract the archive file.
. Choose the files you need from the following list.
+
The files you need depend on your planned grid topology and how you will deploy your StorageGRID system.
+
NOTE: The paths listed in the table are relative to the top-level directory installed by the extracted installation archive.
+
|===
| Path and file name| Description
a|
./vsphere/README
a|
A text file that describes all of the files contained in the StorageGRID download file.
a|
./vsphere/NLF000000.txt
a|
A free license that does not provide any support entitlement for the product.
a|
./vsphere/NetApp-SG-version-SHA.vmdk
a|
The virtual machine disk file that is used as a template for creating grid node virtual machines.
a|
    ./vsphere/vsphere-primary-admin.ovf
+
./vsphere/vsphere-primary-admin.mf
a|
The Open Virtualization Format template file (.ovf) and manifest file (.mf) for deploying the primary Admin Node.
a|
    ./vsphere/vsphere-non-primary-admin.ovf
+
./vsphere/vsphere-non-primary-admin.mf
a|
The template file (.ovf) and manifest file (.mf) for deploying non-primary Admin Nodes.
a|
    ./vsphere/vsphere-archive.ovf
+
./vsphere/vsphere-archive.mf
a|
The template file (.ovf) and manifest file (.mf) for deploying Archive Nodes.
a|
    ./vsphere/vsphere-gateway.ovf
+
./vsphere/vsphere-gateway.mf
a|
The template file (.ovf) and manifest file (.mf) for deploying Gateway Nodes.
a|
    ./vsphere/vsphere-storage.ovf
+
./vsphere/vsphere-storage.mf
a|
The template file (.ovf) and manifest file (.mf) for deploying virtual machine-based Storage Nodes.
a|
*Deployment scripting tool*
a|
*Description*
a|
./vsphere/deploy-vsphere-ovftool.sh
a|
A Bash shell script used to automate the deployment of virtual grid nodes.
a|
./vsphere/deploy-vsphere-ovftool-sample.ini
a|
A sample configuration file for use with the deploy-vsphere-ovftool.sh script.
a|
./vsphere/configure-storagegrid.py
a|
A Python script used to automate the configuration of a StorageGRID system.
a|
./vsphere/configure-sga.py
a|
A Python script used to automate the configuration of StorageGRID appliances.
a|
./vsphere/storagegrid-ssoauth.py
a|
An example Python script that you can use to sign in to the Grid Management API when single sign-on is enabled.
a|
./vsphere/configure-storagegrid.sample.json
a|
A sample configuration file for use with the configure-storagegrid.py script.
a|
./vsphere/configure-storagegrid.blank.json
a|
A blank configuration file for use with the configure-storagegrid.py script.
|===

*Related information*

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-maint/home.html[Recovery and maintenance]
