---
permalink: vmware/installation_overview.html
sidebar: sidebar
keywords: 
summary: 'Installing a StorageGRID system in a VMware environment includes three primary steps.'
---
= Installation overview
:icons: font
:imagesdir: ../media/

[.lead]
Installing a StorageGRID system in a VMware environment includes three primary steps.

. *Preparation*: During planning and preparation, you perform the following tasks:
 ** Learn about the hardware, software, virtual machine, storage, and performance requirements for StorageGRID.
 ** Learn about the specifics of StorageGRID networking so you can configure your network appropriately. For more information, see the StorageGRID networking guidelines.
 ** Identify and prepare the physical servers you plan to use to host your StorageGRID grid nodes.
 ** On the servers you have prepared:
  *** Install VMware vSphere Hypervisor
  *** Configure the ESX hosts
  *** Install and configure VMware vSphere and vCenter
. *Deployment*: Deploy grid nodes using the VMware vSphere Web Client. When you deploy grid nodes, they are created as part of the StorageGRID system and connected to one or more networks.
 .. Use the VMware vSphere Web Client, a .vmdk file, and a set of .ovf file templates to deploy the software-based nodes as virtual machines (VMs) on the servers you prepared in step 1.
 .. Use the StorageGRID Appliance Installer to deploy StorageGRID appliance nodes.
+
NOTE: Hardware-specific installation and integration instructions are not included in the StorageGRID installation procedure. To learn how to install StorageGRID appliances, see the installation and maintenance instructions for your appliance.
. *Configuration*: When all nodes have been deployed, use the StorageGRIDGrid Manager to configure the grid and complete the installation.

These instructions recommend a standard approach for deploying and configuring a StorageGRID system in a VMware environment. See also the information about the following alternative approaches:

* Use the deploy-vsphere-ovftool.sh Bash script (available from the installation archive) to deploy grid nodes in VMware vSphere.
* Automate the deployment and configuration of the StorageGRID system using a Python configuration script (provided in the installation archive).
* Automate the deployment and configuration of appliance grid nodes with a Python configuration script (available from the installation archive or from the StorageGRID Appliance Installer).
* If you are an advanced developer of StorageGRID deployments, use the installation REST APIs to automate the installation of StorageGRID grid nodes.

.Related information

xref:planning_and_preparation.adoc[Planning and preparation]

xref:deploying_virtual_machine_grid_nodes_in_vmware_vsphere_web_client.adoc[Deploying virtual machine grid nodes in VMware vSphere Web Client]

xref:configuring_grid_and_completing_installation.adoc[Configuring the grid and completing installation]

xref:automating_installation.adoc[Automating the installation]

xref:overview_of_installation_rest_api.adoc[Overview of the installation REST API]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-network/home.html[StorageGRID networking guidelines]
