---
permalink: vmware/planning-and-preparation.html
sidebar: sidebar
keywords: how to plan before installation
summary: 'Before deploying grid nodes and configuring the StorageGRID grid, you must be familiar with the steps and requirements for completing the procedure.'
---
= Before you install (VMware)
:icons: font
:imagesdir: ../media/

[.lead]
Before deploying grid nodes and configuring the StorageGRID grid, you must be familiar with the steps and requirements for completing the procedure.

The StorageGRID deployment and configuration procedures assume that you are familiar with the architecture and operational functionality of the StorageGRID system.

You can deploy a single site or multiple sites at one time; however, all sites must meet the minimum requirement of having at least three Storage Nodes.

IMPORTANT: StorageGRID does not support the use of virtual storage area networks (vSANs), because the underlying disk protection is not hardware
RAID.

Before starting the node deployment and grid configuration procedure, you must:

* Plan the StorageGRID deployment.
* Install, connect, and configure all required hardware, including any StorageGRID appliances, to specifications.
+
NOTE: Hardware-specific installation and integration instructions are not included in the StorageGRID installation procedure. To learn how to install StorageGRID appliances, see the installation and maintenance instructions for your appliance.

* Understand the xref:../network/index.adoc[available network options and how each network option should be implemented on grid nodes].
* Gather all networking information in advance. Unless you are using DHCP, gather the IP addresses to assign to each grid node, and the IP addresses of the domain name system (DNS) and network time protocol (NTP) servers that will be used.
* Decide which of the available deployment and configuration tools you want to use.

.Related information

xref:../sg100-1000/index.adoc[SG100 and SG1000 services appliances]

xref:../sg6000/index.adoc[SG6000 storage appliances]

xref:../sg5700/index.adoc[SG5700 storage appliances]

xref:../sg5600/index.adoc[SG5600 storage appliances]
