---
permalink: vmware/running-bash-script.html
sidebar: sidebar
keywords:
summary: 'You can use the deploy-vsphere-ovftool.sh Bash script and the deploy-vsphere-ovftool.ini configuration file you modified to automate the deployment of StorageGRID grid nodes in VMware vSphere.'
---
= Running the Bash script
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `deploy-vsphere-ovftool.sh` Bash script and the deploy-vsphere-ovftool.ini configuration file you modified to automate the deployment of StorageGRID grid nodes in VMware vSphere.

.What you'll need

* You have created a deploy-vsphere-ovftool.ini configuration file for your environment.

You can use the help available with the Bash script by entering the help commands (`-h/--help`). For example:

----
./deploy-vsphere-ovftool.sh -h
----

or

----
./deploy-vsphere-ovftool.sh --help
----

.Steps

. Log in to the Linux machine you are using to run the Bash script.
. Change to the directory where you extracted the installation archive.
+
For example:
+
----
cd StorageGRID-Webscale-version/vsphere
----

. To deploy all grid nodes, run the Bash script with the appropriate options for your environment.
+
For example:
+
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd ./deploy-vsphere-ovftool.ini
----

. If a grid node failed to deploy because of an error, resolve the error and rerun the Bash script for only that node.
+
For example:
+
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd --single-node="DC1-S3" ./deploy-vsphere-ovftool.ini
----

The deployment is complete when the status for each node is "`Passed.`"

----
Deployment Summary
+-----------------------------+----------+----------------------+
| node                        | attempts | status               |
+-----------------------------+----------+----------------------+
| DC1-ADM1                    |        1 | Passed               |
| DC1-G1                      |        1 | Passed               |
| DC1-S1                      |        1 | Passed               |
| DC1-S2                      |        1 | Passed               |
| DC1-S3                      |        1 | Passed               |
+-----------------------------+----------+----------------------+
----
