---
permalink: vmware/software-requirements.html
sidebar: sidebar
keywords:
summary: 'You can use a virtual machine to host any type of StorageGRID grid node. One virtual machine is required for each grid node installed on the VMware server.'
---
= Software requirements
:icons: font
:imagesdir: ../media/

[.lead]
You can use a virtual machine to host any type of StorageGRID grid node. One virtual machine is required for each grid node installed on the VMware server.

== VMware vSphere Hypervisor

You must install VMware vSphere Hypervisor on a prepared physical server. The hardware must be configured correctly (including firmware versions and BIOS settings) before you install VMware software.

* Configure networking in the hypervisor as required to support networking for the StorageGRID system you are installing.
+
xref:../network/index.adoc[Networking guidelines]

* Ensure that the datastore is large enough for the virtual machines and virtual disks that are required to host the grid nodes.
* If you create more than one datastore, name each datastore so that you can easily identify which datastore to use for each grid node when you create virtual machines.

== ESX host configuration requirements

CAUTION: You must properly configure the network time protocol (NTP) on each ESX host. If the host time is incorrect, negative effects, including data loss, could occur.

== VMware configuration requirements

You must install and configure VMware vSphere and vCenter before deploying StorageGRID grid nodes.

For supported versions of VMware vSphere Hypervisor and VMware vCenter Server software, see the Interoperability Matrix.

For the steps required to install these VMware products, see the VMware documentation.

.Related information

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]
