---
permalink: vmware/troubleshooting-installation-issues.html
sidebar: sidebar
keywords: how to troubleshoot installation issues
summary: 'If any problems occur while installing your StorageGRID system, you can access the installation log files.'
---
= Troubleshoot installation issues
:icons: font
:imagesdir: ../media/

[.lead]
If any problems occur while installing your StorageGRID system, you can access the installation log files.

The following are the main installation log files, which technical support might need to resolve issues.

* `/var/local/log/install.log` (found on all grid nodes)
* `/var/local/log/gdu-server.log` (found on the primary Admin Node)

To learn how to access the log files, see the xref:../monitor/index.adoc[instructions for monitoring and troubleshooting StorageGRID]. For help troubleshooting appliance installation issues, see the installation and maintenance instructions for your appliances. If you need additional help, contact technical support.

xref:../sg100-1000/index.adoc[SG100 and SG1000 services appliances]

xref:../sg6000/index.adoc[SG6000 storage appliances]

xref:../sg5700/index.adoc[SG5700 storage appliances]

xref:../sg5600/index.adoc[SG5600 storage appliances]

https://mysupport.netapp.com/site/global/dashboard[NetApp Support^]

== Virtual machine resource reservation requires adjustment

OVF files include a resource reservation designed to ensure that each grid node has sufficient RAM and CPU to operate efficiently. If you create virtual machines by deploying these OVF files on VMware and the predefined number of resources are not available, the virtual machines will not start.

.About this task

If you are certain that the VM host has sufficient resources for each grid node, manually adjust the resources allocated for each virtual machine, and then try starting the virtual machines.

.Steps

. In the VMware vSphere Hypervisor client tree, select the virtual machine that is not started.
. Right‐click the virtual machine, and select *Edit Settings*.
. From the Virtual Machines Properties window, select the *Resources* tab.
. Adjust the resources allocated to the virtual machine:
 .. Select *CPU*, and then use the Reservation slider to adjust the MHz reserved for this virtual machine.
 .. Select *Memory*, and then use the Reservation slider to adjust the MB reserved for this virtual machine.
. Click *OK*.
. Repeat as required for other virtual machines hosted on the same VM host.