---
permalink: vmware/troubleshooting-installation-issues.html
sidebar: sidebar
keywords: storagegrid, vmware, troubleshoot installation, troubleshooting installation
summary: 'If any problems occur while installing your StorageGRID system, you can access the installation log files.'
---
= Troubleshooting installation issues
:icons: font
:imagesdir: ../media/

[.lead]
If any problems occur while installing your StorageGRID system, you can access the installation log files.

The following are the main installation log files, which technical support might need to resolve issues.

* `/var/local/log/install.log` (found on all grid nodes)
* `/var/local/log/gdu-server.log` (found on the primary Admin Node)

To learn how to access the log files, see the instructions for monitoring and troubleshooting StorageGRID. For help troubleshooting appliance installation issues, see the installation and maintenance instructions for your appliances. If you need additional help, contact technical support.

.Related information

xref:../monitor/index.adoc[Monitor & troubleshoot]

xref:../sg100-1000/index.adoc[SG100 & SG1000 services appliances]

xref:../sg6000/index.adoc[SG6000 storage appliances]

xref:../sg5700/index.adoc[SG5700 storage appliances]

xref:../sg5600/index.adoc[SG5600 storage appliances]

https://mysupport.netapp.com/site/global/dashboard[NetApp Support^]
