---
permalink: vmware/virtual-machine-resource-reservation-requires-adjustment.html
sidebar: sidebar
keywords:
summary: 'OVF files include a resource reservation designed to ensure that each grid node has sufficient RAM and CPU to operate efficiently. If you create virtual machines by deploying these OVF files on VMware and the predefined number of resources are not available, the virtual machines will not start.'
---
= Virtual machine resource reservation requires adjustment
:icons: font
:imagesdir: ../media/

[.lead]
OVF files include a resource reservation designed to ensure that each grid node has sufficient RAM and CPU to operate efficiently. If you create virtual machines by deploying these OVF files on VMware and the predefined number of resources are not available, the virtual machines will not start.

.About this task

If you are certain that the VM host has sufficient resources for each grid node, manually adjust the resources allocated for each virtual machine, and then try starting the virtual machines.

.Steps

. In the VMware vSphere Hypervisor client tree, select the virtual machine that is not started.
. Right‐click the virtual machine, and select *Edit Settings*.
. From the Virtual Machines Properties window, select the *Resources* tab.
. Adjust the resources allocated to the virtual machine:
 .. Select *CPU*, and then use the Reservation slider to adjust the MHz reserved for this virtual machine.
 .. Select *Memory*, and then use the Reservation slider to adjust the MB reserved for this virtual machine.
. Click *OK*.
. Repeat as required for other virtual machines hosted on the same VM host.
