---
permalink: rhel/configuring-docker-storage-volume.html
sidebar: sidebar
keywords: how to configure container engine storage volume, Docker, Podman
summary: 'Before installing the container engine (Docker or Podman), you might need to format the storage volume and mount it.'
---
= Configure container engine storage volume
:icons: font
:imagesdir: ../media/

[.lead]
Before installing the container engine (Docker or Podman), you might need to format the storage volume and mount it.

.About this task

You can skip these steps if you plan to use local storage for the Docker or Podman storage volume and have sufficient space available on the host partition containing `/var/lib/docker` for Docker and `/var/lib/containers` for Podman.

NOTE: Podman is supported only on Red Hat Enterprise Linux (RHEL).

.Steps

. Create a file system on the container engine storage volume:
+
----
sudo mkfs.ext4 container-engine-storage-volume-device
----

. Mount the container engine storage volume:

* For Docker: 
+
----
sudo mkdir -p /var/lib/docker
sudo mount container-storage-volume-device /var/lib/docker
----
* For Podman: 
+
----
sudo mkdir -p /var/lib/containers
sudo mount container-storage-volume-device /var/lib/containers
----

. Add an entry for container-storage-volume-device to /etc/fstab.
+
This step ensures that the storage volume will remount automatically after host reboots.

== Install Docker

The StorageGRID system runs on Red Hat Enterprise Linux or CentOS as a collection of containers. If you have chosen to use the Docker container engine, follow these steps to install Docker. Otherwise, <<Install Podman,install Podman>>.

.Steps

. Install Docker by following the instructions for your Linux distribution.
+
NOTE: If Docker is not included with your Linux distribution, you can download it from the Docker website.

. Ensure Docker has been enabled and started by running the following two commands:
+
----
sudo systemctl enable docker
----
+
----
sudo systemctl start docker
----

. Confirm you have installed the expected version of Docker by entering the following:
+
----
sudo docker version
----
+
The Client and Server versions must be 1.11.0 or later.

== Install Podman

The StorageGRID system runs on Red Hat Enterprise Linux as a collection of containers. If you have chosen to use the Podman container engine, follow these steps to install Podman. Otherwise, <<Install Docker,install Docker>>.

NOTE: Podman is supported only on Red Hat Enterprise Linux (RHEL).

.Steps

. Install Podman and Podman-Docker by following the instructions for your Linux distribution.

+
NOTE: You must also install the Podman-Docker package when you install Podman.

. Confirm you have installed the expected version of Podman and Podman-Docker by entering the following:
+
----
sudo docker version
----
NOTE: The Podman-Docker package allows you to use Docker commands.
+
The Client and Server versions must be 3.2.3 or later.
+
----
Version: 3.2.3
API Version: 3.2.3
Go Version: go1.15.7
Built: Tue Jul 27 03:29:39 2021
OS/Arch: linux/amd64
----