---
permalink: rhel/configuring-docker-storage-volume.html
sidebar: sidebar
keywords:
summary: 'Before installing Docker or Podman, you might need to format the storage volume and mount it.'
---
= Configure the Docker or Podman storage volume
:icons: font
:imagesdir: ../media/

[.lead]
Before installing the container engine (Docker or Podman), you might need to format the storage volume and mount it.

.About this task

You can skip these steps if you plan to use local storage for the Docker or Podman storage volume and have sufficient space available on the host partition containing `/var/lib/docker` for Docker and `/var/lib/containers` for Podman.

NOTE: Podman is only supported on Red Hat Enterprise Linux (RHEL).

.Steps

. Create a file system on the container engine storage volume:
+
----
sudo mkfs.ext4 container-engine-storage-volume-device
----

. Mount the container engine storage volume:

* For Docker: 
+
----
sudo mkdir -p /var/lib/docker
sudo mount container-storage-volume-device /var/lib/docker
----
* For Podman: 
+
----
sudo mkdir -p /var/lib/containers
sudo mount container-storage-volume-device /var/lib/containers
----

. Add an entry for container-storage-volume-device to /etc/fstab.
+
This step ensures that the storage volume will remount automatically after host reboots.
