---
permalink: rhel/deployment-tools.html
sidebar: sidebar
keywords: 
summary: 'You might benefit from automating all or part of the StorageGRID installation.'
---
= Deployment tools
:icons: font
:imagesdir: ../media/

[.lead]
You might benefit from automating all or part of the StorageGRID installation.

Automating the deployment might be useful in any of the following cases:

* You already use a standard orchestration framework, such as Ansible, Puppet, or Chef, to deploy and configure physical or virtual hosts.
* You intend to deploy multiple StorageGRID instances.
* You are deploying a large, complex StorageGRID instance.

The StorageGRID host service is installed by a package and driven by configuration files that can be created interactively during a manual installation, or prepared ahead of time (or programmatically) to enable automated installation using standard orchestration frameworks. StorageGRID provides optional Python scripts for automating the configuration of StorageGRID appliances, and the whole StorageGRID system (the "`grid`"). You can use these scripts directly, or you can inspect them to learn how to use the StorageGRID Installation REST API in grid deployment and configuration tools you develop yourself.

If you are interested in automating all or part of your StorageGRID deployment, review "`Automating the installation`" before beginning the installation process.

.Related information

xref:overview-of-installation-rest-api.adoc[Overview of the installation REST API]

xref:automating-installation.adoc[Automating the installation]
