---
permalink: rhel/deploying_virtual_grid_nodes.html
sidebar: sidebar
keywords:
summary: 'To deploy virtual grid nodes on Red Hat Enterprise Linux or CentOS hosts, you create node configuration files for all nodes, validate the files, and start the StorageGRID host service, which starts the nodes. If you need to deploy any StorageGRID appliance Storage Nodes, see the installation and maintenance instructions for the appliance after you have deployed all virtual nodes.'
---
= Deploying virtual grid nodes
:icons: font
:imagesdir: ../media/

[.lead]
To deploy virtual grid nodes on Red Hat Enterprise Linux or CentOS hosts, you create node configuration files for all nodes, validate the files, and start the StorageGRID host service, which starts the nodes. If you need to deploy any StorageGRID appliance Storage Nodes, see the installation and maintenance instructions for the appliance after you have deployed all virtual nodes.

* xref:creating_node_configuration_files.adoc[Creating node configuration files]
* xref:validating_storagegrid_configuration.adoc[Validating the StorageGRID configuration]
* xref:starting_storagegrid_host_service.adoc[Starting the StorageGRID host service]

.Related information

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sga-install-sg1000/home.html[SG100 and SG1000 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-app-install/home.html[SG5600 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sga-install-sg5700/home.html[SG5700 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sga-install-sg6000/home.html[SG6000 appliance installation and maintenance]
