---
permalink: rhel/index.html
sidebar: sidebar
keywords: red hat enterprise linux, rhel, centos linux
summary: 'Installing a StorageGRID system in a Red Hat Enterprise Linux (RHEL) or CentOS Linux environment includes three primary steps.'
---
= Install Red Hat Enterprise Linux or CentOS: Overview
:icons: font
:imagesdir: ../media/

[.lead]
Installing a StorageGRID system in a Red Hat Enterprise Linux (RHEL) or CentOS Linux environment includes three primary steps.

. *Preparation*: During planning and preparation, you perform the following tasks:
 ** Learn about the hardware and storage requirements for StorageGRID.
 ** Learn about the specifics of xref:../network/index.adoc[StorageGRID networking] so you can configure your network appropriately.
 ** Identify and prepare the physical or virtual servers you plan to use to host your StorageGRID grid nodes.
 ** On the servers you have prepared:
  *** Install Linux
  *** Configure the host network
  *** Configure host storage
  *** Install container engine
  *** Install the StorageGRID host services
. *Deployment*: Deploy grid nodes using the appropriate user interface. When you deploy grid nodes, they are created as part of the StorageGRID system and connected to one or more networks.
 .. Use the Linux command line and node configuration files to deploy software-based grid nodes on the hosts you prepared in step 1.
 .. Use the StorageGRID Appliance Installer to deploy StorageGRID appliance nodes.
+
NOTE: Hardware-specific installation and integration instructions are not included in the StorageGRID installation procedure. To learn how to install StorageGRID appliances, see the installation and maintenance instructions for your appliance.
. *Configuration*: When all nodes have been deployed, use the Grid Manager to configure the grid and complete the installation.

These instructions recommend a standard approach for deploying and configuring a StorageGRID system. See also the information about the following alternative approaches:

* Use a standard orchestration framework such as Ansible, Puppet, or Chef to install RHEL or CentOS, configure networking and storage, install the container engine and the StorageGRID host service, and deploy virtual grid nodes.
* Automate the deployment and configuration of the StorageGRID system using a Python configuration script (provided in the installation archive).
* Automate the deployment and configuration of appliance grid nodes with a Python configuration script (available from the installation archive or from the StorageGRID Appliance Installer).
* If you are an advanced developer of StorageGRID deployments, use the installation REST APIs to automate the installation of StorageGRID grid nodes.

