---
permalink: rhel/overview-of-installation-rest-api.html
sidebar: sidebar
keywords: storagegrid, rhel, redhat, redhat linux, installation REST API
summary: 'StorageGRID provides the StorageGRID Installation API for performing installation tasks.'
---
= Overview of the installation REST API
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID provides the StorageGRID Installation API for performing installation tasks.

The API uses the Swagger open source API platform to provide the API documentation. Swagger allows both developers and non-developers to interact with the API in a user interface that illustrates how the API responds to parameters and options. This documentation assumes that you are familiar with standard web technologies and the JSON (JavaScript Object Notation) data format.

IMPORTANT: Any API operations you perform using the API Docs webpage are live operations. Be careful not to create, update, or delete configuration data or other data by mistake.

Each REST API command includes the API's URL, an HTTP action, any required or optional URL parameters, and an expected API response.

== StorageGRID Installation API

The StorageGRID Installation API is only available when you are initially configuring your StorageGRID system, and in the event that you need to perform a primary Admin Node recovery. The Installation API can be accessed over HTTPS from the Grid Manager.

To access the API documentation, go to the installation web page on the primary Admin Node and select *Help* > *API Documentation* from the menu bar.

The StorageGRID Installation API includes the following sections:

* *config* -- Operations related to the product release and versions of the API. You can list the product release version and the major versions of the API supported by that release.
* *grid* -- Grid-level configuration operations. You can get and update grid settings, including grid details, Grid Network subnets, grid passwords, and NTP and DNS server IP addresses.
* *nodes* -- Node-level configuration operations. You can retrieve a list of grid nodes, delete a grid node, configure a grid node, view a grid node, and reset a grid node's configuration.
* *provision* -- Provisioning operations. You can start the provisioning operation and view the status of the provisioning operation.
* *recovery* -- Primary Admin Node recovery operations. You can reset information, upload the Recover Package, start the recovery, and view the status of the recovery operation.
* *recovery-package* -- Operations to download the Recovery Package.
* *sites* -- Site-level configuration operations. You can create, view, delete, and modify a site.
