---
permalink: rhel/planning-and-preparation.html
sidebar: sidebar
keywords: storagegrid, redhat installation planning, rhel installation planning
summary: 'Before deploying grid nodes and configuring the StorageGRID grid, you must be familiar with the steps and requirements for completing the procedure.'
---
= Planning and preparation
:icons: font
:imagesdir: ../media/

[.lead]
Before deploying grid nodes and configuring the StorageGRID grid, you must be familiar with the steps and requirements for completing the procedure.

The StorageGRID deployment and configuration procedures assume that you are familiar with the architecture and operation of the StorageGRID system.

You can deploy a single site or multiple sites at one time; however, all sites must meet the minimum requirement of having at least three Storage Nodes.

Before starting a StorageGRID installation, you must:

* Understand StorageGRID's compute requirements, including the minimum CPU and RAM requirements for each node.
* Understand how StorageGRID supports multiple networks for traffic separation, security, and administrative convenience, and have a plan for which networks you intend to attach to each StorageGRID node.
+
See the StorageGRID networking guidelines.

* Understand the storage and performance requirements of each type of grid node.
* Identify a set of servers (physical, virtual, or both) that, in aggregate, provide sufficient resources to support the number and type of StorageGRID nodes you plan to deploy.
* Understand the requirements for node migration, if you want to perform scheduled maintenance on physical hosts without any service interruption.
* Gather all networking information in advance. Unless you are using DHCP, gather the IP addresses to assign to each grid node, and the IP addresses of the domain name system (DNS) and network time protocol (NTP) servers that will be used.
* Install, connect, and configure all required hardware, including any StorageGRID appliances, to specifications.
+
NOTE: Hardware-specific installation and integration instructions are not included in the StorageGRID installation procedure. To learn how to install StorageGRID appliances, see the installation and maintenance instructions for your appliance.

* Decide which of the available deployment and configuration tools you want to use.

.Related information

xref:../network/index.adoc[Network guidelines]

xref:../sg100-1000/index.adoc[SG100 & SG1000 services appliances]

xref:../sg6000/index.adoc[SG6000 storage appliances]

xref:../sg5700/index.adoc[SG5700 storage appliances]

xref:../sg5600/index.adoc[SG5600 storage appliances]
