---
permalink: rhel/required_materials.html
sidebar: sidebar
keywords: 
summary: 'Before you install StorageGRID, you must gather and prepare required materials.'
---
= Required materials
:icons: font
:imagesdir: ../media/

[.lead]
Before you install StorageGRID, you must gather and prepare required materials.

[options="header"]
|===
| Item| Notes
a|
NetApp StorageGRID license
a|
You must have a valid, digitally signed NetApp license.

NOTE: A non-production license, which can be used for testing and proof of concept grids, is included in the StorageGRID installation archive.

a|
StorageGRID installation archive

a|
You must download the StorageGRID installation archive and extract the files.

a|
Service laptop
a|
The StorageGRID system is installed through a service laptop.

The service laptop must have:

* Network port
* SSH client (for example, PuTTY)
* Supported web browser

a|
StorageGRID documentation
a|

* Release Notes
* Instructions for administering StorageGRID

|===
.Related information

xref:downloading_and_extracting_storagegrid_installation_files.adoc[Downloading and extracting the StorageGRID installation files]

xref:web_browser_requirements.adoc[Web browser requirements]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-admin/home.html[Administering StorageGRID]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-rn/home.html[StorageGRID release notes]
