---
permalink: rhel/task_downloading_and_extracting_the_storagegrid_installation_files.html
sidebar: sidebar
keywords: 
summary: 'You must download the StorageGRID installation archive and extract the required files.'
---
= Downloading and extracting the StorageGRID installation files
:icons: font
:imagesdir: ../media/

[.lead]
You must download the StorageGRID installation archive and extract the required files.

. Go to the NetApp Downloads page for StorageGRID.
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads: StorageGRID]

. Select the button for downloading the latest release, or select another version from the drop-down menu and select *Go*.
. Sign in with the username and password for your NetApp account.
. If a Caution/MustRead statement appears, read it and select the check box.
+
You must apply any required hotfixes after you install the StorageGRID release. For more information, see the hotfix procedure in the recovery and maintenance instructions.

. Read the End User License Agreement, select the check box, and then select *Accept & Continue*.
. In the *Install StorageGRID* column, select the appropriate software.
+
Download the .tgz or .zip archive file for your platform.
+
The compressed files contain the RPM files and scripts for Red Hat Enterprise Linux or CentOS.
+
NOTE: Use the .zip file if you are running Windows on the service laptop.

. Save and extract the archive file.
. Choose the files you need from the following list.
+
The files you need depend on your planned grid topology and how you will deploy your StorageGRID system.
+
NOTE: The paths listed in the table are relative to the top-level directory installed by the extracted installation archive
+
|===
| Path and file name| Description
a|
./rpms/README
a|
A text file that describes all of the files contained in the StorageGRID download file.
a|
./rpms/NLF000000.txt
a|
A free license that does not provide any support entitlement for the product.
a|
./rpms/StorageGRID-Webscale-Images-version-SHA.rpm
a|
RPM package for installing the StorageGRID node images on your RHEL or CentOS hosts.
a|
./rpms/StorageGRID-Webscale-Service-version-SHA.rpm
a|
RPM package for installing the StorageGRID host service on your RHEL or CentOS hosts.
a|
*Deployment scripting tool*
a|
*Description*
a|
./rpms/configure-storagegrid.py
a|
A Python script used to automate the configuration of a StorageGRID system.
a|
./rpms/configure-sga.py
a|
A Python script used to automate the configuration of StorageGRID appliances.
a|
./rpms/configure-storagegrid.sample.json
a|
A sample configuration file for use with the configure-storagegrid.py script.
a|
./rpms/storagegrid-ssoauth.py
a|
An example Python script that you can use to sign in to the Grid Management API when single sign-on is enabled.
a|
./rpms/configure-storagegrid.blank.json
a|
A blank configuration file for use with the configure-storagegrid.py script.
a|
./rpms/extras/ansible
a|
Example Ansible role and playbook for configuring RHEL or CentOS hosts for StorageGRID container deployment. You can customize the role or playbook as necessary.
|===

*Related information*

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-maint/home.html[Recovery and maintenance]
