---
permalink: rhel/where-to-go-next.html
sidebar: sidebar
keywords: 
summary: 'After completing an installation, you must perform a series of integration and configuration steps. Some steps are required; others are optional.'
---
= Where to go next
:icons: font
:imagesdir: ../media/

[.lead]
After completing an installation, you must perform a series of integration and configuration steps. Some steps are required; others are optional.

== Required tasks

* Create a tenant account for each client protocol (Swift or S3) that will be used to store objects on your StorageGRID system.
* Control system access by configuring groups and user accounts. Optionally, you can configure a federated identity source (such as Active Directory or OpenLDAP), so you can import administration groups and users. Or, you can create local groups and users.
* Integrate and test the S3 or Swift API client applications you will use to upload objects to your StorageGRID system.
* When you are ready, configure the information lifecycle management (ILM) rules and ILM policy you want to use to protect object data.
+
NOTE: When you install StorageGRID, the default ILM policy, Baseline 2 Copies Policy, is active. This policy includes the stock ILM rule (Make 2 Copies), and it applies if no other policy has been activated.

* If your installation includes appliance Storage Nodes, use SANtricity software to complete the following tasks:
 ** Connect to each StorageGRID appliance.
 ** Verify receipt of AutoSupport data.
* If your StorageGRID system includes any Archive Nodes, configure the Archive Node's connection to the target external archival storage system.

NOTE: If any Archive Nodes will use Tivoli Storage Manager as the external archival storage system, you must also configure Tivoli Storage Manager.

* Review and follow the StorageGRID system hardening guidelines to eliminate security risks.
* Configure email notifications for system alerts.

== Optional tasks

* If you want to receive notifications from the (legacy) alarm system, configure mailing lists and email notifications for alarms.
* Update grid node IP addresses if they have changed since you planned your deployment and generated the Recovery Package. See information about changing IP addresses in the recovery and maintenance instructions.
* Configure storage encryption, if required.
* Configure storage compression to reduce the size of stored objects, if required.
* Configure audit client access. You can configure access to the system for auditing purposes through an NFS or a CIFS file share. See the instructions for administering StorageGRID.

NOTE: Audit export through CIFS/Samba has been deprecated and will be removed in a future StorageGRID release.

.Related information

xref:../admin/index.adoc[Administer StorageGRID]

xref:../s3/index.adoc[Use S3]

xref:../swift/index.adoc[Use Swift]

xref:../ilm/index.adoc[Manage objects with ILM]

xref:../monitor/index.adoc[Monitor & troubleshoot]

xref:../maintain/index.adoc[Maintain & recover]

xref:../sg100-1000/index.adoc[SG100 & SG1000 services appliances]

xref:../sg5600/index.adoc[SG5600 storage appliances]

xref:../sg5700/index.adoc[SG5700 storage appliances]

xref:../sg6000/index.adoc[SG6000 storage appliances]

xref:../release-notes/index.adoc[Release notes]

xref:../harden/index.adoc[System hardening]

xref:../audit/index.adoc[Review audit logs]

xref:../upgrade/index.adoc[Upgrade software]
