---
permalink: admin/administering-storagegrid-system.html
sidebar: sidebar
keywords:
summary: 'Use these instructions to configure and administer a StorageGRID system.'
---
= Administering a StorageGRID system
:icons: font
:imagesdir: ../media/

[.lead]
Use these instructions to configure and administer a StorageGRID system.

These instructions describe how to use the Grid Manager to set up groups and users, create tenant accounts to allow S3 and Swift client applications to store and retrieve objects, configure and manage StorageGRID networks, configure AutoSupport, manage node settings, and more.

[NOTE]
====
The instructions for managing objects with information lifecycle management (ILM) rules and policies have been moved to
xref:../ilm/index.adoc[Manage objects with ILM].
====

These instructions are for technical personnel who will be configuring, administering, and supporting a StorageGRID system after it has been installed.

.What you'll need
* You have a general understanding of the StorageGRID system.
* You have fairly detailed knowledge of Linux command shells, networking, and server hardware setup and configuration.
