---
permalink: admin/archiving-to-tape-through-tsm-middleware.html
sidebar: sidebar
keywords: 
summary: 'You can configure an Archive Node to target a Tivoli Storage Manager \(TSM\) server that provides a logical interface for storing and retrieving object data to random or sequential access storage devices, including tape libraries.'
---
= Archiving to tape through TSM middleware
:icons: font
:imagesdir: ../media/

[.lead]
You can configure an Archive Node to target a Tivoli Storage Manager (TSM) server that provides a logical interface for storing and retrieving object data to random or sequential access storage devices, including tape libraries.

The Archive Node's ARC service acts as a client to the TSM server, using Tivoli Storage Manager as middleware for communicating with the archival storage system.

== TSM management classes

Management classes defined by the TSM middleware outline how the TSMʹs backup and archive operations function, and can be used to specify rules for content that are applied by the TSM server. Such rules operate independently of the StorageGRID system's ILM policy, and must be consistent with the StorageGRID system's requirement that objects are stored permanently and are always available for retrieval by the Archive Node. After object data is sent to a TSM server by the Archive Node, the TSM lifecycle and retention rules are applied while the object data is stored to tape managed by the TSM server.

The TSM management class is used by the TSM server to apply rules for data location or retention after objects are sent to the TSM server by the Archive Node. For example, objects identified as database backups (temporary content that can be overwritten with newer data) could be treated differently than application data (fixed content that must be retained indefinitely).
