---
permalink: admin/changing-your-password.html
sidebar: sidebar
keywords: change password, grid manager password
summary: 'If you are a local user of the Grid Manager, you can change your own password.'
---
= Change your password
:icons: font
:imagesdir: ../media/

[.lead]
If you are a local user of the Grid Manager, you can change your own password.

.What you'll need

You are signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].

.About this task

If you sign in to StorageGRID as a federated user or if single sign-on (SSO) is enabled, you cannot change your password in Grid Manager. Instead, you must change your password in the external identity source, for example, Active Directory or OpenLDAP.

.Steps

. From the Grid Manager header, select *_your name_* > *Change password*.
. Enter your current password.
. Type a new password.
+
Your password must contain at least 8 and no more than 32 characters. Passwords are case-sensitive.

. Re-enter the new password.
. Select *Save*.
