---
permalink: admin/change-node-console-password.html
sidebar: sidebar
keywords: node console password, console password, change password, password
summary: 'Each node in your grid has a unique node console password, which you need to log in to the node. Use these steps to change the node console password for each node in your grid. The passwords are stored in the recovery package.'
---
= Change node console passwords
:icons: font
:imagesdir: ../media/

[.lead]
Each node in your grid has a unique node console password, which you need to log in to the node. Use these steps to change each unique node console password for each node in your grid.

.What you'll need

* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have the Maintenance or Root access permission.
* You have the current provisioning passphrase.

.About this task

Use the node console password to log in to a node as “admin” using SSH, or to the root user on a VM/physical console connection. The change node console password process creates new passwords for each node in your grid and stores the passwords in an updated `Passwords.txt` file in the Recovery Package. The passwords are listed in the Password column in the `Passwords.txt` file. 

NOTE: There are separate SSH access passwords for the SSH keys used for communication between nodes. The SSH access passwords are not changed by this procedure.

== Access the wizard

.Steps
. Select *CONFIGURATION* > *Access control* > *Grid passwords*.

. Under *Change node console passwords*, select *Make a change*.

== Enter the provisioning passphrase

.Steps

. Enter the provisioning passphrase for your grid.

. Select *Continue*.

== [[download-current]]Download the current Recovery Package

Before changing node console passwords, download the current Recovery Package. You can use the passwords in this file if the password change process fails for any node.

.Steps

. Select *Download recovery package*.

. Copy the Recovery Package file (`.zip`) to two safe, secure, and separate locations.
+
CAUTION: The Recovery Package file must be secured because it contains encryption keys and passwords that can be used to obtain data from the StorageGRID system.

. Select *Continue*.

. When the confirmation dialog appears, select *Yes* if you are ready to start changing the node console passwords.
+
You can't cancel this process after it starts.

== Change node console passwords

When the node console password process starts, a new Recovery Package is generated that includes the new passwords. Then, the passwords are updated on each node.

.Steps

. Wait for the new Recovery Package to be generated, which might take a few minutes.

. Select *Download new recovery package*. 

. When the download completes:

.. Open the `.zip` file.
.. Confirm that you can access the contents, including the `Passwords.txt` file, which contains the new node console passwords.
.. Copy the new Recovery Package file (`.zip`) to two safe, secure, and separate locations.
+
CAUTION: Do not overwrite the old Recovery Package.
+
The Recovery Package file must be secured because it contains encryption keys and passwords that can be used to obtain data from the StorageGRID system.

. Select the check box to indicate you have downloaded the new Recovery Package and verified the content.

. Select *Change node console passwords* and wait for all nodes to be updated with the new passwords. This might take a few minutes.
+
If passwords are changed for all nodes, a green success banner appears. Go to the next step.
+
If there is an error during the update process, a banner message lists the number of nodes that failed to have their passwords changed. The system will automatically retry the process on any node that failed to have its password changed. If the process ends with some nodes still not having a changed password, the *Retry* button appears.
+
If the password update failed for one or more nodes: 

.. Review the error messages listed in the table.
.. Resolve the issues.
.. Select *Retry*.
+
NOTE: Retrying only changes the node console passwords on the nodes that failed during previous password change attempts. 

. After node console passwords have been changed for all nodes, delete the <<download-current,first Recovery Package you downloaded>>.

. Optionally, use the *Recovery package* link to download an additional copy of the new Recovery Package.
