---
permalink: admin/completing_archive_node_setup.html
sidebar: sidebar
keywords: 
summary: 'The Archive Node is not functional after you complete the installation process. Before the StorageGRID system can save objects to the TSM Archive Node, you must complete the installation and configuration of the TSM server and configure the Archive Node to communicate with the TSM server.'
---
= Completing the Archive Node setup
:icons: font
:imagesdir: ../media/

[.lead]
The Archive Node is not functional after you complete the installation process. Before the StorageGRID system can save objects to the TSM Archive Node, you must complete the installation and configuration of the TSM server and configure the Archive Node to communicate with the TSM server.

For more information about optimizing TSM retrieval and store sessions, see information about managing archival storage.

Refer to the following IBM documentation, as necessary, as you prepare your TSM server for integration with the Archive Node in a StorageGRID system:

* _IBM Tape Device Drivers Installation and User's Guide_
+
http://www.ibm.com/support/docview.wss?rs=577&uid=ssg1S7002972

* _IBM Tape Device Drivers Programming Reference_
+
http://www.ibm.com/support/docview.wss?rs=577&uid=ssg1S7003032

*Related information*

xref:managing_archive_nodes.adoc[Managing Archive Nodes]
