---
permalink: admin/concept_administering_storagegrid_system.html
sidebar: sidebar
keywords: 
summary: 'This guide provides instructions and information for configuring and administering a StorageGRID system.'
---
= Administering a StorageGRID system
:icons: font
:imagesdir: ../media/

[.lead]
This guide provides instructions and information for configuring and administering a StorageGRID system.

== About this guide

This guide describes how to use the Grid Manager to set up groups and users, create tenant accounts to allow S3 and Swift client applications to store and retrieve objects, configure and manage StorageGRID networks, configure AutoSupport, manage node settings, and more.

NOTE: Information about managing objects with information lifecycle management (ILM) rules and policies is no longer in the _Administrator Guide_. The instructions for ILM have been moved to a new document.

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-ilm/home.html[Managing objects with information lifecycle management]

== Audience for this guide

This guide is for technical personnel who will be configuring, administering, and supporting a StorageGRID system after it has been installed.

This guide assumes a general understanding of the StorageGRID system. A fairly detailed level of computer literacy is assumed, including knowledge of Linux command shells, networking, and server hardware setup and configuration.
