---
permalink: admin/concept_how_ha_groups_are_used.html
sidebar: sidebar
keywords: 
summary: 'You might want to use high availability \(HA\) groups for several reasons.'
---
= How HA groups are used
:icons: font
:imagesdir: ../media/

[.lead]
You might want to use high availability (HA) groups for several reasons.

* An HA group can provide highly available administrative connections to the Grid Manager or the Tenant Manager.
* An HA group can provide highly available data connections for S3 and Swift clients.
* An HA group that contains only one interface allows you to provide many VIP addresses and to explicitly set IPv6 addresses.

An HA group can provide high availability only if all nodes included in the group provide the same services. When you create an HA group, add interfaces from the types of nodes that provide the services you require.

* *Admin Nodes*: Include the Load Balancer service and enable access to the Grid Manager or the Tenant Manager.
* *Gateway Nodes*: Include the Load Balancer service and the CLB service (deprecated).

|===
| Purpose of HA group| Add nodes of this type to the HA group
a|
Access to Grid Manager
a|

* Primary Admin Node (*preferred Master*)
* Non-primary Admin Nodes

NOTE: The primary Admin Node must be the preferred Master. Some maintenance procedures can only be performed from the primary Admin Node.

a|
Access to Tenant Manager only
a|

* Primary or non-primary Admin Nodes

a|
S3 or Swift client access -- Load Balancer service
a|

* Admin Nodes
* Gateway Nodes

a|
S3 or Swift client access -- CLB service**Note:** The CLB service is deprecated.

a|

* Gateway Nodes

|===

== Limitations of using HA groups with Grid Manager or Tenant Manager

The failure of services for the Grid Manager or the Tenant Manager does not trigger failover within the HA group.

If you are signed in to the Grid Manager or the Tenant Manager when failover occurs, you are signed out and must sign in again to resume your task.

Some maintenance procedures cannot be performed when the primary Admin Node is unavailable. During failover, you can use the Grid Manager to monitor your StorageGRID system.

== Limitations of using HA groups with the CLB service

The failure of the CLB service does not trigger failover within the HA group.

NOTE: The CLB service is deprecated.
