---
permalink: admin/confirming_capacity_of_storagegrid_system.html
sidebar: sidebar
keywords: 
summary: 'Before migrating large amounts of data into the StorageGRID system, confirm that the StorageGRID system has the disk capacity to handle the anticipated volume.'
---
= Confirming capacity of the StorageGRID system
:icons: font
:imagesdir: ../media/

[.lead]
Before migrating large amounts of data into the StorageGRID system, confirm that the StorageGRID system has the disk capacity to handle the anticipated volume.

If the StorageGRID system includes an Archive Node and a copy of migrated objects has been saved to nearline storage (such as tape), ensure that the Archive Node's storage has sufficient capacity for the anticipated volume of migrated data.

As part of the capacity assessment, look at the data profile of the objects you plan to migrate and calculate the amount of disk capacity required. For details about monitoring the disk capacity of your StorageGRID system, see the instructions for monitoring and troubleshooting StorageGRID.

*Related information*

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-troubleshooting/home.html[Monitoring and troubleshooting StorageGRID]

xref:managing_storage_nodes.adoc[Managing Storage Nodes]
