---
permalink: admin/configuring-sso.html
sidebar: sidebar
keywords:
summary: 'When single sign-on \(SSO\) is enabled, users can only access the Grid Manager, the Tenant Manager, the Grid Management API, or the Tenant Management API if their credentials are authorized using the SSO sign-in process implemented by your organization.'
---
= Configuring single sign-on
:icons: font
:imagesdir: ../media/

[.lead]
When single sign-on (SSO) is enabled, users can only access the Grid Manager, the Tenant Manager, the Grid Management API, or the Tenant Management API if their credentials are authorized using the SSO sign-in process implemented by your organization.

* xref:confirming-federated-users-can-sign-in.adoc[Confirming federated users can sign in]
* xref:using-sandbox-mode.adoc[Using sandbox mode]
* xref:creating-relying-party-trusts-in-ad-fs.adoc[Creating relying party trusts in AD FS]
* xref:testing-relying-party-trusts.adoc[Testing relying party trusts]
* xref:enabling-single-sign-on.adoc[Enabling single sign-on]
* xref:disabling-single-sign-on.adoc[Disabling single sign-on]
* xref:temporarily-disabling-and-reenabling-sso-for-admin-node.adoc[Temporarily disabling and reenabling single sign-on for one Admin Node]
