---
permalink: admin/configuring-sso.html
sidebar: sidebar
keywords:
summary: 'When single sign-on \(SSO\) is enabled, users can only access the Grid Manager, the Tenant Manager, the Grid Management API, or the Tenant Management API if their credentials are authorized using the SSO sign-in process implemented by your organization.'
---
= Configure single sign-on
:icons: font
:imagesdir: ../media/

[.lead]
When single sign-on (SSO) is enabled, users can only access the Grid Manager, the Tenant Manager, the Grid Management API, or the Tenant Management API if their credentials are authorized using the SSO sign-in process implemented by your organization.

* xref:confirming-federated-users-can-sign-in.adoc[Confirm federated users can sign in]
* xref:using-sandbox-mode.adoc[Use sandbox mode]
* xref:creating-relying-party-trusts-in-ad-fs.adoc[Create relying party trusts in AD FS]
* xref:creating-enterprise-application-azure.adoc[Create enterprise applications in Azure]
* xref:creating-sp-connection-ping.adoc[Create service provider connections in PingFederate]
* xref:disabling-single-sign-on.adoc[Disable single sign-on]
* xref:temporarily-disabling-and-reenabling-sso-for-admin-node.adoc[Temporarily disable and reenable single sign-on for one Admin Node]
