---
permalink: admin/configuring-tsm-server.html
sidebar: sidebar
keywords: 
summary: 'This section includes sample instructions for preparing a TSM server following TSM best practices.'
---
= Configuring the TSM server
:icons: font
:imagesdir: ../media/

[.lead]
This section includes sample instructions for preparing a TSM server following TSM best practices.

The following instructions guide you through the process of:

* Defining a disk storage pool, and a tape storage pool (if required) on the TSM server
* Defining a domain policy that uses the TSM management class for the data saved from the Archive Node, and registering a node to use this domain policy

These instructions are provided for your guidance only; they are not intended to replace TSM documentation, or to provide complete and comprehensive instructions suitable for all configurations. Deployment specific instructions should be provided by a TSM administrator who is familiar both with your detailed requirements, and with the complete set of TSM Server documentation.
