---
permalink: admin/configuring-audit-client-access.html
sidebar: sidebar
keywords: 
summary: 'The Admin Node, through the Audit Management System \(AMS\) service, logs all audited system events to a log file available through the audit share, which is added to each Admin Node at installation. For easy access to audit logs, you can configure client access to audit shares for both CIFS and NFS.'
---
= Configuring audit client access
:icons: font
:imagesdir: ../media/

[.lead]
The Admin Node, through the Audit Management System (AMS) service, logs all audited system events to a log file available through the audit share, which is added to each Admin Node at installation. For easy access to audit logs, you can configure client access to audit shares for both CIFS and NFS.

The StorageGRID system uses positive acknowledgment to prevent loss of audit messages before they are written to the log file. A message remains queued at a service until the AMS service or an intermediate audit relay service has acknowledged control of it.

For more information, see the instructions for understanding audit messages.

NOTE: If you have the option to use CIFS or NFS, choose NFS.

NOTE: Audit export through CIFS/Samba has been deprecated and will be removed in a future StorageGRID release.

.Related information

xref:what-admin-node-is.adoc[What an Admin Node is]

xref:../audit/index.adoc[Review audit logs]

xref:../upgrade/index.adoc[Upgrade software]
