---
permalink: admin/confirming-capacity-of-storagegrid-system.html
sidebar: sidebar
keywords: data migration, data capacity for migration
summary: 'Before migrating large amounts of data into the StorageGRID system, confirm that the StorageGRID system has the disk capacity to handle the anticipated volume.'
---
= Confirm capacity of the StorageGRID system
:icons: font
:imagesdir: ../media/

[.lead]
Before migrating large amounts of data into the StorageGRID system, confirm that the StorageGRID system has the disk capacity to handle the anticipated volume.

If the StorageGRID system includes an Archive Node and a copy of migrated objects has been saved to nearline storage (such as tape), ensure that the Archive Node's storage has sufficient capacity for the anticipated volume of migrated data.

As part of the capacity assessment, look at the data profile of the objects you plan to migrate and calculate the amount of disk capacity required. For details about monitoring the disk capacity of your StorageGRID system, see xref:managing-storage-nodes.adoc[Manage Storage Nodes] and xref:../monitor/index.adoc[Monitor and troubleshoot].



