---
permalink: admin/configuring_sso.html
sidebar: sidebar
keywords:
summary: 'When single sign-on \(SSO\) is enabled, users can only access the Grid Manager, the Tenant Manager, the Grid Management API, or the Tenant Management API if their credentials are authorized using the SSO sign-in process implemented by your organization.'
---
= Configuring single sign-on
:icons: font
:imagesdir: ../media/

[.lead]
When single sign-on (SSO) is enabled, users can only access the Grid Manager, the Tenant Manager, the Grid Management API, or the Tenant Management API if their credentials are authorized using the SSO sign-in process implemented by your organization.

* xref:confirming_federated_users_can_sign_in.adoc[Confirming federated users can sign in]
* xref:using_sandbox_mode.adoc[Using sandbox mode]
* xref:creating_relying_party_trusts_in_ad_fs.adoc[Creating relying party trusts in AD FS]
* xref:testing_relying_party_trusts.adoc[Testing relying party trusts]
* xref:enabling_single_sign_on.adoc[Enabling single sign-on]
* xref:disabling_single_sign_on.adoc[Disabling single sign-on]
* xref:temporarily_disabling_and_reenabling_sso_for_admin_node.adoc[Temporarily disabling and reenabling single sign-on for one Admin Node]
