---
permalink: admin/configuring_server_certificates.html
sidebar: sidebar
keywords: 
summary: 'You can customize the server certificates used by the StorageGRID system.'
---
= Configuring server certificates
:icons: font
:imagesdir: ../media/

[.lead]
You can customize the server certificates used by the StorageGRID system.

The StorageGRID system uses security certificates for multiple distinct purposes:

* Management Interface Server Certificates: Used to secure access to the Grid Manager, the Tenant Manager, the Grid Management API, and the Tenant Management API.
* Storage API Server Certificates: Used to secure access to the Storage Nodes and Gateway Nodes, which API client applications use to upload and download object data.

You can use the default certificates created during installation, or you can replace either, or both, of these default types of certificates with your own custom certificates.

== Supported types of custom server certificate

The StorageGRID system supports custom server certificates encrypted with RSA or ECDSA (Elliptic Curve Digital Signature Algorithm).

For more information on how StorageGRID secures client connections for the REST API, see the S3 or Swift implementation guides.

== Certificates for load balancer endpoints

StorageGRID manages the certificates used for load balancer endpoints separately. To configure load balancer certificates, see the instructions for configuring load balancer endpoints.

*Related information*

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-s3/home.html[Implementing S3 client applications]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-swift/home.html[Implementing Swift client applications]

link:configuring_load_balancer_endpoints.md#[Creating load balancer endpoints]
