---
permalink: admin/configuring-storagegrid-certificates-for-fabricpool.html
sidebar: sidebar
keywords: fabricpool, ONTAP certificates
summary: 'For S3 clients that perform strict hostname validation and do not support disabling strict hostname validation, such as ONTAP clients using FabricPool, you can generate or upload a server certificate when you configure the load balancer endpoint.'
---
= Configure StorageGRID certificates for FabricPool
:icons: font
:imagesdir: ../media/

[.lead]
For S3 clients that perform strict hostname validation and do not support disabling strict hostname validation, such as ONTAP clients using FabricPool, you can generate or upload a server certificate when you configure the load balancer endpoint.

.What you'll need

* You have specific access permissions.
* You are signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].

.About this task

When you create a load balancer endpoint, you can generate a self-signed server certificate or upload a certificate that is signed by a known certificate authority (CA). In production environments, you should use a certificate that is signed by a known CA. Certificates signed by a CA can be rotated non-disruptively. They are also more secure because they provide better protection against man-in-the-middle attacks.

The following steps provide general guidelines for S3 clients that use FabricPool. For more detailed information and procedures, see xref:../fabricpool/index.adoc[Configure StorageGRID for FabricPool].

NOTE: The separate Connection Load Balancer (CLB) service on Gateway Nodes is deprecated and not recommended for use with FabricPool.

.Steps

. Optionally, configure a high availability (HA) group for FabricPool to use.
. Create an S3 load balancer endpoint for FabricPool to use.
+
When you create an HTTPS load balancer endpoint, you are prompted to upload your server certificate, certificate private key, and optional CA bundle.

. Attach StorageGRID as a cloud tier in ONTAP.
+
Specify the load balancer endpoint port and the fully qualified domain name used in the CA certificate you uploaded. Then, provide the CA certificate.
+
NOTE: If an intermediate CA issued the StorageGRID certificate, you must provide the intermediate CA certificate. If the StorageGRID certificate was issued directly by the Root CA, you must provide the Root CA certificate.


