---
permalink: admin/controlling-administrator-access-to-storagegrid.html
sidebar: sidebar
keywords:
summary: 'You can control access to the StorageGRID system by opening or closing firewall ports, managing admin groups and users, configuring single sign-on \(SSO\), and providing certificates to allow secure external access to StorageGRID metrics.'
---
= Controlling access to StorageGRID
:icons: font
:imagesdir: ../media/

[.lead]
You can control access to the StorageGRID system by opening or closing firewall ports, managing admin groups and users, configuring single sign-on (SSO), and providing certificates to allow secure external access to StorageGRID metrics.

* xref:controlling-access-through-firewalls.adoc[Controlling access through firewalls]
* xref:using-storagegrid-security-certificates.adoc[Use security certificates]
* xref:using-identity-federation.adoc[Using identity federation]
* xref:managing-admin-groups.adoc[Managing admin groups]
* xref:managing-local-users.adoc[Managing local users]
* xref:using-single-sign-on.adoc[Using single sign-on (SSO) for StorageGRID]
* xref:configuring-administrator-client-certificates.adoc[Configuring administrator client certificates]
