---
permalink: admin/controlling_administrator_access_to_storagegrid.html
sidebar: sidebar
keywords:
summary: 'You can control access to the StorageGRID system by opening or closing firewall ports, managing admin groups and users, configuring single sign-on \(SSO\), and providing certificates to allow secure external access to StorageGRID metrics.'
---
= Controlling access to StorageGRID
:icons: font
:imagesdir: ../media/

[.lead]
You can control access to the StorageGRID system by opening or closing firewall ports, managing admin groups and users, configuring single sign-on (SSO), and providing certificates to allow secure external access to StorageGRID metrics.

* xref:controlling_access_through_firewalls.adoc[Controlling access through firewalls]
* xref:using_storagegrid_security_certificates.adoc[Use security certificates]
* xref:using_identity_federation.adoc[Using identity federation]
* xref:managing_admin_groups.adoc[Managing admin groups]
* xref:managing_local_users.adoc[Managing local users]
* xref:using_single_sign_on.adoc[Using single sign-on (SSO) for StorageGRID]
* xref:configuring_administrator_client_certificates.adoc[Configuring administrator client certificates]
