---
permalink: admin/creating-and-activating-domain-policy.html
sidebar: sidebar
keywords:
summary: 'You must create a domain policy and then activate it to configure the TSM server to save data sent from the Archive Node.'
---
= Creating and activating the domain policy
:icons: font
:imagesdir: ../media/

[.lead]
You must create a domain policy and then activate it to configure the TSM server to save data sent from the Archive Node.

.Steps

. Create a domain policy.
+
`copy domain standard tsm-domain`

. If you are not using an existing management class, enter one of the following:
+
`define policyset tsm-domain standard`
+
`define mgmtclass tsm-domain standard _default_`
+
`_default_` is the default management class for the deployment.

. Create a copygroup to the appropriate storage pool. Enter (on one line):
+
`define copygroup tsm-domain standard _default_ type=archive destination=SGWSDiskPool retinit=event retmin=0 retver=0`
+
`_default_` is the default Management Class for the Archive Node. The values of `retinit`, `retmin`, and `retver` have been chosen to reflect the retention behavior currently used by the Archive Node
+
NOTE: Do not set `retinit` to `retinit=create`. Setting `retinit=create` blocks the Archive Node from deleting content since retention events are used to remove content from the TSM server.

. Assign the management class to be the default.
+
`assign defmgmtclass _tsm-domain_ standard _default_`

. Set the new policy set as active.
+
`activate policyset tsm-domain standard`
+
Ignore the "`no backup copy group`" warning that appears when you enter the activate command.

. Register a node to use the new policy set on the TSM server. On the TSM server, enter (on one line):
+
`register node arc-user arc-password passexp=0 domain=tsm-domain MAXNUMMP=number-of-sessions`
+
arc-user and arc-password are same client node name and password as you define on the Archive Node, and the value of MAXNUMMP is set to the number of tape drives reserved for Archive Node store sessions.
+
NOTE: By default, registering a node creates an administrative user ID with client owner authority, with the password defined for the node.
