---
permalink: admin/creating-custom-notifications-for-migration-alarms.html
sidebar: sidebar
keywords: 
summary: 'You might want StorageGRID to send alert notifications or alarm \(legacy system\) notifications to the system administrator responsible for monitoring migration if certain values exceed recommended thresholds.'
---
= Creating custom notifications for migration alarms
:icons: font
:imagesdir: ../media/

[.lead]
You might want StorageGRID to send alert notifications or alarm (legacy system) notifications to the system administrator responsible for monitoring migration if certain values exceed recommended thresholds.

.What you'll need

* You must be signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You must have specific access permissions.
* You must have configured email settings for alert (or alarm) notifications.

.Steps

. Create a custom alert rule or a Global Custom alarm for each Prometheus metric or StorageGRID attribute you want to monitor during data migration.
+
Alerts are triggered based on Prometheus metric values. Alarms are triggered based on attribute values. See the instructions for monitoring and troubleshooting StorageGRID for more information.

. Disable the custom alert rule or the Global Custom alarm after data migration is complete.
+
Note that Global Custom alarms override Default alarms.

.Related information

xref:../monitor/index.adoc[Monitor & troubleshoot]
