---
permalink: admin/defining-tsm-tape-and-disk-storage-pools.html
sidebar: sidebar
keywords:
summary: 'The Archive Node writes to a disk storage pool. To archive content to tape, you must configure the disk storage pool to move content to a tape storage pool.'
---
= Defining TSM tape and disk storage pools
:icons: font
:imagesdir: ../media/

[.lead]
The Archive Node writes to a disk storage pool. To archive content to tape, you must configure the disk storage pool to move content to a tape storage pool.

.About this task
For a TSM server, you must define a tape storage pool and a disk storage pool within Tivoli Storage Manager. After the disk pool is defined, create a disk volume and assign it to the disk pool. A tape pool is not required if your TSM server uses disk‐only storage.

You must complete a number of steps on your TSM server before you can create a tape storage pool. (Create a tape library and at least one drive in the tape library. Define a path from the server to the library and from the server to the drives, and then define a device class for the drives.) The details of these steps can vary depending upon the hardware configuration and storage requirements of the site. For more information, see the TSM documentation.

The following set of instructions illustrates the process. You should be aware that the requirements for your site could be different depending on the requirements of your deployment. For configuration details and for instructions, see the TSM documentation.

NOTE: You must log onto the server with administrative privileges and use the dsmadmc tool to execute the following commands.

.Steps

. Create a tape library.
+
`define library _tapelibrary_ libtype=_scsi_`
+
Where `_tapelibrary_` is an arbitrary name chosen for the tape library, and the value of `libtype` can vary depending upon the type of tape library.

. Define a path from the server to the tape library.
+
`define path _servername tapelibrary_ srctype=server desttype=library device=_lib-devicename_`

 *  `_servername_` is the name of the TSM server
 *  `_tapelibrary_` is the tape library name you defined
 *  `_lib-devicename_` is the device name for the tape library

. Define a drive for the library.
+
`define drive _tapelibrary_ _drivename_`

 * `_drivename_` is the name you want to specify for the drive
 * `_tapelibrary_` is the tape library name you defined
+
You might want to configure an additional drive or drives, depending upon your hardware configuration. (For example, if the TSM server is connected to a Fibre Channel switch that has two inputs from a tape library, you might want to define a drive for each input.)

. Define a path from the server to the drive you defined.
+
`define path _servername_ drivename srctype=server desttype=drive library=_tapelibrary_ device=_drive-dname_`

 ** `_drive-dname_` is the device name for the drive
 ** `_tapelibrary_` is the tape library name you defined
+
Repeat for each drive that you have defined for the tape library, using a separate `_drivename_` and `_drive-dname_` for each drive.

. Define a device class for the drives.
+
`define devclass _DeviceClassName_ devtype=_lto_ library=_tapelibrary_ format=_tapetype_`

 * `_DeviceClassName_` is the name of the device class
 * `_lto_` is the type of drive connected to the server
 * `_tapelibrary_` is the tape library name you defined
 * `_tapetype_` is the tape type; for example, ultrium3

. Add tape volumes to the inventory for the library.
+
`checkin libvolume _tapelibrary_`
+
`_tapelibrary_` is the tape library name you defined.

. Create the primary tape storage pool.
+
`define stgpool _SGWSTapePool_ _DeviceClassName_ description=_description_ _collocate=filespace_ maxscratch=_XX_`

 * `_SGWSTapePool_` is the name of the Archive Node's tape storage pool. You can select any name for the tape storage pool (as long as the name uses the syntax conventions expected by the TSM server).
 * `_DeviceClassName_` is the name of the device class name for the tape library.
 * `_description_` is a description of the storage pool that can be displayed on the TSM server using the `query stgpool` command. For example: "`Tape storage pool for the Archive Node.`"
 * `_collocate=filespace_` specifies that the TSM server should write objects from the same file space into a single tape.
 * `XX` is one of the following:
  ** The number of empty tapes in the tape library (in the case that the Archive Node is the only application using the library).
  ** The number of tapes allocated for use by the StorageGRID system (in instances where the tape library is shared).

. On a TSM server, create a disk storage pool. At the TSM server's administrative console, enter
+
`define stgpool _SGWSDiskPool_ disk description=_description_ maxsize=_maximum_file_size nextstgpool=SGWSTapePool_ highmig=_percent_high_ lowmig=_percent_low_`

 * `_SGWSDiskPool_` is the name of the Archive Node's disk pool. You can select any name for the disk storage pool (as long as the name uses the syntax conventions expected by the TSM).
 * `_description_` is a description of the storage pool that can be displayed on the TSM server using the `query stgpool` command. For example, "`Disk storage pool for the Archive Node.`"
 * `_maximum_file_size_` forces objects larger than this size to be written directly to tape, rather than being cached in the disk pool. It is recommended to set `_maximum_file_size_` to 10 GB.
 * `_nextstgpool=SGWSTapePool_` refers the disk storage pool to the tape storage pool defined for the Archive Node.
 * `_percent_high_` sets the value at which the disk pool begins to migrate its contents to the tape pool. It is recommended to set `_percent_high_` to 0 so that data migration begins immediately
 * `_percent_low_` sets the value at which migration to the tape pool stops. It is recommended to set `_percent_low_` to 0 to clear out the disk pool.

. On a TSM server, create a disk volume (or volumes) and assign it to the disk pool.
+
`define volume _SGWSDiskPool_ _volume_name_ formatsize=_size_`

 * `_SGWSDiskPool_` is the disk pool name.
 * `_volume_name_` is the full path to the location of the volume (for example, `/var/local/arc/stage6.dsm`) on the TSM server where it writes the contents of the disk pool in preparation for transfer to tape.
 * `_size_` is the size, in MB, of the disk volume.
+
For example, to create a single disk volume such that the contents of a disk pool fill a single tape, set the value of size to 200000 when the tape volume has a capacity of 200 GB.
+
However, it might be desirable to create multiple disk volumes of a smaller size, as the TSM server can write to each volume in the disk pool. For example, if the tape size is 250 GB, create 25 disk volumes with a size of 10 GB (10000) each.
+
The TSM server preallocates space in the directory for the disk volume. This can take some time to complete (more than three hours for a 200 GB disk volume).
