---
permalink: admin/deleting-tenant-account.html
sidebar: sidebar
keywords: 
summary: 'You can delete a tenant account if you want to permanently remove the tenant’s access to the system.'
---
= Deleting a tenant account
:icons: font
:imagesdir: ../media/

[.lead]
You can delete a tenant account if you want to permanently remove the tenant's access to the system.

.What you'll need

* You must be signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You must have specific access permissions (see xref:using-storagegrid-security-certificates.adoc[About security certificates]).
* You must have removed all buckets (S3), containers (Swift), and objects associated with the tenant account.

.Steps

. Select *Tenants*.
. Select the tenant account you want to delete.
+
If your system includes more than 20 items, you can specify how many rows are shown on each page at one time. Use the search box to search for a tenant account by name or tenant ID.

. From the *Actions* drop-down, select *Remove*.
. Select *OK*.
