---
permalink: admin/generating-self-signed-certificate-for-management-interface.html
sidebar: sidebar
keywords:
summary: 'If strict hostname validation is required, you can use a script to generate the management interface certificate.'
---
= Use a script to generate the management interface certificate
:icons: font
:imagesdir: ../media/

[.lead]
If strict hostname validation is required, you can use a script to generate the management interface certificate.

.What you'll need

* You must have specific access permissions.
* You must have the `Passwords.txt` file.

.About this task

The best practice for a production environment is to use a certificate signed by an external certificate authority.

.Steps

. Obtain the fully qualified domain name (FQDN) of each Admin Node.
. Log in to the primary Admin Node:
 .. Enter the following command: `ssh admin@primary_Admin_Node_IP`
 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.
+
When you are logged in as root, the prompt changes from `$` to `#`.


. Configure StorageGRID with a new self-signed certificate.
+
`$ sudo make-certificate --domains _wildcard-admin-node-fqdn_ --type management`

 ** For `--domains`, use wildcards to represent the fully qualified domain names of all Admin Nodes. For example, `*.ui.storagegrid.example.com` uses the * wildcard to represent `admin1.ui.storagegrid.example.com` and `admin2.ui.storagegrid.example.com`.
 ** Set `--type` to `management` to configure the management interface certificate, which is used by Grid Manager and Tenant Manager.
 ** By default, generated certificates are valid for one year (365 days) and must be recreated before they expire. You can use the `--days` argument to override the default validity period.
+
NOTE: A certificate's validity period begins when `make-certificate` is run. You must ensure the management client is synchronized to the same time source as StorageGRID; otherwise, the client might reject the certificate.


 $ sudo make-certificate --domains *.ui.storagegrid.example.com --type management --days 720
+
The resulting output contains the public certificate needed by your management API client.
. Select and copy the certificate.
+
Include the BEGIN and the END tags in your selection.

. Log out of the command shell. `$ exit`
. Confirm the certificate was configured:
 .. Access the Grid Manager.
 .. Select *CONFIGURATION* > *Security* > *Certificates*
 .. On the *Global* tab, select *Management interface certificate*.
. Configure your management client to use the public certificate you copied. Include the BEGIN and END tags.
