---
permalink: admin/grid-management-api-operations.html
sidebar: sidebar
keywords:
summary: 'The Grid Management API organizes the available API operations into the following sections.'
---
= Grid Management API operations
:icons: font
:imagesdir: ../media/

[.lead]
The Grid Management API organizes the available API operations into the following sections.

* *accounts* -- Operations to manage storage tenant accounts, including creating new accounts and retrieving storage usage for a given account.
* *alarms* -- Operations to list current alarms (legacy system), and return information about the health of the grid, including the current alerts and a summary of node connection states.
* *alert-history* -- Operations on resolved alerts.
* *alert-receivers* -- Operations on alert notification receivers (email).
* *alert-rules* -- Operations on alert rules.
* *alert-silences* -- Operations on alert silences.
* *alerts* -- Operations on alerts.
* *audit* -- Operations to list and update the audit configuration.
* *auth* -- Operations to perform user session authentication.
+
The Grid Management API supports the Bearer Token Authentication Scheme. To sign in, you provide a username and password in the JSON body of the authentication request (that is, `POST /api/v3/authorize`). If the user is successfully authenticated, a security token is returned. This token must be provided in the header of subsequent API requests ("Authorization: Bearer _token_").
+
NOTE: If single sign-on is enabled for the StorageGRID system, you must perform different steps to authenticate. See "`Authenticating in to the API if single sign-on is enabled.`"
+
See "`Protecting against Cross-Site Request Forgery`" for information on improving authentication security.

* *client-certificates* -- Operations to configure client certificates so that StorageGRID can be accessed securely using external monitoring tools.
* *config* -- Operations related to the product release and versions of the Grid Management API. You can list the product release version and the major versions of the Grid Management API supported by that release, and you can disable deprecated versions of the API.
* *deactivated-features* -- Operations to view features that might have been deactivated.
* *dns-servers* -- Operations to list and change configured external DNS servers.
* *endpoint-domain-names* -- Operations to list and change endpoint domain names.
* *erasure-coding* -- Operations on Erasure Coding profiles.
* *expansion* -- Operations on expansion (procedure-level).
* *expansion-nodes* -- Operations on expansion (node-level).
* *expansion-sites* -- Operations on expansion (site-level).
* *grid-networks* -- Operations to list and change the Grid Network List.
* *grid-passwords* -- Operations for grid password management.
* *groups* -- Operations to manage local Grid Administrator Groups and to retrieve federated Grid Administrator Groups from an external LDAP server.
* *identity-source* -- Operations to configure an external identity source and to manually synchronize federated group and user information.
* *ilm* -- Operations on information lifecycle management (ILM).
* *license* -- Operations to retrieve and update the StorageGRID license.
* *logs* -- Operations for collecting and downloading log files.
* *metrics* -- Operations on StorageGRID metrics including instant metric queries at a single point in time and range metric queries over a range of time. The Grid Management API uses the Prometheus systems monitoring tool as the backend data source. For information about constructing Prometheus queries, see the Prometheus web site.
+
NOTE: Metrics that include``_private_`` in their names are intended for internal use only. These metrics are subject to change between StorageGRID releases without notice.

* *node-health* -- Operations on node health status.
* *ntp-servers* -- Operations to list or update external Network Time Protocol (NTP) servers.
* *objects* -- Operations on objects and object metadata.
* *recovery* -- Operations for the recovery procedure.
* *recovery-package* -- Operations to download the Recovery Package.
* *regions* -- Operations to view and create regions.
* *s3-object-lock* -- Operations on global S3 Object Lock settings.
* *server-certificate* -- Operations to view and update Grid Manager server certificates.
* *snmp* -- Operations on the current SNMP configuration.
* *traffic-classes* -- Operations for traffic classification policies.
* *untrusted-client-network* -- Operations on the untrusted Client Network configuration.
* *users* -- Operations to view and manage Grid Manager users.
