---
permalink: admin/guidelines-for-storagegrid-networks.html
sidebar: sidebar
keywords:
summary: 'StorageGRID supports up to three network interfaces per grid node, allowing you to configure the networking for each individual grid node to match your security and access requirements.'
---
= Guidelines for StorageGRID networks
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Grid Manager to configure and manage StorageGRID networks and connections.

See xref:configuring-client-connections.adoc[Configuring S3 and Swift client connections] to learn how to connect S3 or Swift clients.

== About StorageGRID networks
StorageGRID supports up to three network interfaces per grid node, allowing you to configure the networking for each individual grid node to match your security and access requirements.

NOTE: To modify or add a network for a grid node, see xref:../maintain/index.adoc[Maintain & recover]. For more information about network topology, see xref:../network/index.adoc[Networking guidelines].

=== Grid Network

Required. The Grid Network is used for all internal StorageGRID traffic. It provides connectivity between all nodes in the grid, across all sites and subnets.

=== Admin Network

Optional. The Admin Network is typically used for system administration and maintenance. It can also be used for client protocol access. The Admin Network is typically a private network and does not need to be routable between sites.

=== Client Network

Optional. The Client Network is an open network typically used to provide access to S3 and Swift client applications, so the Grid Network can be isolated and secured. The Client Network can communicate with any subnet reachable through the local gateway.

== Guidelines

* Each StorageGRID grid node requires a dedicated network interface, IP address, subnet mask, and gateway for each network it is assigned to.
* A grid node cannot have more than one interface on a network.
* A single gateway, per network, per grid node is supported, and it must be on the same subnet as the node. You can implement more complex routing in the gateway, if required.
* On each node, each network maps to a specific network interface.
+
[cols="1a,1a" options="header"]
|===
| Network| Interface name
a|
Grid
a|
eth0
a|
Admin (optional)
a|
eth1
a|
Client (optional)
a|
eth2
|===

* If the node is connected to a StorageGRID appliance, specific ports are used for each network. For details, see the installation instructions for your appliance.
* The default route is generated automatically, per node. If eth2 is enabled, then 0.0.0.0/0 uses the Client Network on eth2. If eth2 is not enabled, then 0.0.0.0/0 uses the Grid Network on eth0.
* The Client Network does not become operational until the grid node has joined the grid
* The Admin Network can be configured during grid node deployment to allow access to the installation user interface before the grid is fully installed.

