---
permalink: admin/how-ha-groups-are-used.html
sidebar: sidebar
keywords: ha groups, high availability group
summary: 'You can use high availability (HA) groups to provide highly available connections to StorageGRID for object data and for administrative use.'
---
= How are HA groups used?
:icons: font
:imagesdir: ../media/

[.lead]
You can use high availability (HA) groups to provide highly available connections to StorageGRID for object data and for administrative use.

* An HA group can provide highly available administrative connections to the Grid Manager or the Tenant Manager.
* An HA group can provide highly available data connections for S3 and Swift clients.
* An HA group that contains only one interface allows you to provide many VIP addresses and to explicitly set IPv6 addresses.

An HA group can provide high availability only if all nodes included in the group provide the same services. When you create an HA group, add interfaces from the types of nodes that provide the services you require.

* *Admin Nodes*: Include the Load Balancer service and enable access to the Grid Manager or the Tenant Manager.
* *Gateway Nodes*: Include the Load Balancer service and the CLB service (deprecated).

[cols="1a,2a" options="header"]
|===
| Purpose of HA group| Add nodes of this type to the HA group
a|
Access to Grid Manager
a|

* Primary Admin Node (*Primary*)
* Non-primary Admin Nodes

*Note:* The primary Admin Node must be the Primary interface. Some maintenance procedures can only be performed from the primary Admin Node.

a|
Access to Tenant Manager only
a|

* Primary or non-primary Admin Nodes

a|
S3 or Swift client access -- Load Balancer service
a|

* Admin Nodes
* Gateway Nodes

a|S3 client access for xref:../admin/manage-s3-select-for-tenant-accounts.adoc[S3 Select]
a|* SG100 or SG1000 appliances
* VMware-based software nodes

*Note*: HA groups are recommended when using S3 Select, but not required.


a|
S3 or Swift client access -- CLB service

*Note:* The CLB service is deprecated.

a|

* Gateway Nodes

|===

== Limitations of using HA groups with Grid Manager or Tenant Manager

If a Grid Manager or Tenant Manager service fails, HA group failover is not triggered.

If you are signed in to the Grid Manager or the Tenant Manager when failover occurs, you are signed out and must sign in again to resume your task.

Some maintenance procedures cannot be performed when the primary Admin Node is unavailable. During failover, you can use the Grid Manager to monitor your StorageGRID system.

== Limitations of using HA groups with the CLB service

The failure of the CLB service does not trigger failover within the HA group.

NOTE: The CLB service is deprecated.
