---
permalink: admin/managing_archive_nodes.html
sidebar: sidebar
keywords:
summary: 'Optionally, each of your StorageGRID system’s data center sites can be deployed with an Archive Node, which allows you to connect to a targeted external archival storage system, such as Tivoli Storage Manager \(TSM\).'
---
= Managing Archive Nodes
:icons: font
:imagesdir: ../media/

[.lead]
Optionally, each of your StorageGRID system's data center sites can be deployed with an Archive Node, which allows you to connect to a targeted external archival storage system, such as Tivoli Storage Manager (TSM).

After configuring connections to the external target, you can configure the Archive Node to optimize TSM performance, take an Archive Node offline when a TSM server is nearing capacity or unavailable, and configure replication and retrieve settings. You can also set Custom alarms for the Archive Node.

* xref:what_archive_node_is.adoc[What an Archive Node is]
* xref:configuring_archive_node_connections_to_archival_storage.adoc[Configuring Archive Node connections to archival storage]
* xref:setting_custom_alarms_for_archive_node.adoc[Setting Custom alarms for the Archive Node]
* xref:integrating_tivoli_storage_manager.adoc[Integrating Tivoli Storage Manager]
