---
permalink: admin/managing-load-balancing.html
sidebar: sidebar
keywords: 
summary: 'You can use the StorageGRID load balancing functions to handle ingest and retrieval workloads from S3 and Swift clients. Load balancing maximizes speed and connection capacity by distributing the workloads and connections across multiple Storage Nodes.'
---
= Managing load balancing
:icons: font
:imagesdir: ../media/

[.lead]
You can use the StorageGRID load balancing functions to handle ingest and retrieval workloads from S3 and Swift clients. Load balancing maximizes speed and connection capacity by distributing the workloads and connections across multiple Storage Nodes.

You can achieve load balancing in your StorageGRID system in the following ways:

* Use the Load Balancer service, which is installed on Admin Nodes and Gateway Nodes. The Load Balancer service provides Layer 7 load balancing and performs TLS termination of client requests, inspects the requests, and establishes new secure connections to the Storage Nodes. This is the recommended load balancing mechanism.
* Use the Connection Load Balancer (CLB) service, which is installed on Gateway Nodes only. The CLB service provides Layer 4 load balancing and supports link costs.
+
NOTE: The CLB service is deprecated.

* Integrate a third-party load balancer. Contact your NetApp account representative for details.
