---
permalink: admin/managing-load-balancing.html
sidebar: sidebar
keywords: manage load balancing, balance workload, client ingest, client retrieval, distribute connection
summary: 'You can use the StorageGRID load balancing functions to handle ingest and retrieval workloads from S3 and Swift clients. Load balancing maximizes speed and connection capacity by distributing the workloads and connections across multiple Storage Nodes.'
---
= Manage load balancing: Overview
:icons: font
:imagesdir: ../media/

[.lead]
You can use the StorageGRID load balancing functions to handle ingest and retrieval workloads from S3 and Swift clients. Load balancing maximizes speed and connection capacity by distributing the workloads and connections across multiple Storage Nodes.

You can load balance client workloads in the following ways:

* Use the Load Balancer service, which is installed on Admin Nodes and Gateway Nodes. The Load Balancer service provides Layer 7 load balancing and performs TLS termination of client requests, inspects the requests, and establishes new secure connections to the Storage Nodes. This is the recommended load balancing mechanism.
+
See xref:how-load-balancing-works-load-balancer-service.adoc[How load balancing works - Load Balancer service].

* Use the deprecated Connection Load Balancer (CLB) service, which is installed on Gateway Nodes only. The CLB service provides Layer 4 load balancing and supports link costs.
+
See xref:how-load-balancing-works-clb-service.adoc[How load balancing works - CLB service (deprecated)].

* Integrate a third-party load balancer. Contact your NetApp account representative for details.
