---
permalink: admin/manage-s3-select-for-tenant-accounts.html
sidebar: sidebar
keywords: 
summary: 'S3 tenants can issue S3 Select requests to perform SQL queries on individual objects.'
---
= Manage S3 Select for tenant accounts
:icons: font
:imagesdir: ../media/

[.lead]
S3 tenants can issue S3 Select requests to perform SQL queries on individual objects.

S3 Select provides an efficient way to search through large amounts of data without having to deploy a database and associated resources to enable searches. It also reduces the cost and latency of retrieving data.

== What is S3 Select?

S3 Select allows tenants to use SQL statements to filter and retrieve only the data needed from an object. The StorageGRID implementation of S3 Select includes a subset of S3 Select commands and features.

== Considerations and requirements for using S3 Select

StorageGRID requires the following for S3 Select queries:

* Object format must be CSV, or GZIP or BZIP2 compressed files containing a CSV formatted file.
* Tenants must be granted S3 Select ability by the grid administrator. Select *Allow S3 Select* when xref:creating-tenant-account.adoc[creating a tenant] or xref:editing-tenant-account.adoc[editing a tenant].
* The SQL query must be sent to a xref:managing-load-balancing.adoc[StorageGRID load balancer endpoint]. The Admin and Gateway Nodes used by the endpoint must be SG100 or SG1000 appliance nodes or VMware-based software nodes.
* Bare-metal load balancer nodes are not supported.
* SQL queries cannot be sent directly to Storage Nodes.

See the xref:../s3/use-s3-select.adoc[instructions for setting up S3 Select queries].