---
permalink: admin/managing-local-users.html
sidebar: sidebar
keywords:
summary: 'You can create local users and assign them to local admin groups to determine which Grid Manager features these users can access.'
---
= Managing local users
:icons: font
:imagesdir: ../media/

[.lead]
You can create local users and assign them to local admin groups to determine which Grid Manager features these users can access.

The Grid Manager includes one predefined local user, named "`root.`" Although you can add and remove local users, you cannot remove the root user.

NOTE: If single sign-on (SSO) has been enabled, local users cannot sign in to StorageGRID.

* You must be signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You must have specific access permissions.

== Creating a local user

If you have created local admin groups, you can create one or more local users and assign each user to one or more groups. The group's permissions control which Grid Manager features the user can access.

.About this task
You can only create local users, and you can only assign these users to local admin groups. Federated users and federated groups are managed using the external identity source.

.Steps

. Select *Configuration* > *Access Control* > *Admin Users*.
. Click *Create*.
. Enter the user's display name, unique name, and password.
. Assign the user to one or more groups that govern the access permissions.
+
The list of group names is generated from the Groups table.

. Click *Save*.

.Related information

xref:managing-admin-groups.adoc[Managing admin groups]

== Modifying a local user's account

You can modify a local admin user's account to update the user's display name or group membership. You can also temporarily prevent a user from accessing the system.

.About this task
You can edit local users only. Federated user details are automatically synchronized with the external identity source.

.Steps

. Select *Configuration* > *Access Control* > *Admin Users*.
. Select the user you want to edit.
+
If your system includes more than 20 items, you can specify how many rows are shown on each page at one time. You can then use your browser's find feature to search for a specific item in the currently displayed rows.

. Click *Edit*.
. Optionally, make changes to the name or group membership.
. Optionally, to prevent the user from accessing the system temporarily, check *Deny Access*.
. Click *Save*.
+
The new settings are applied the next time the user signs out and then signs back in to the Grid Manager.

== Deleting a local user's account

You can delete accounts for local users that no longer require access to the Grid Manager.

.Steps

. Select *Configuration* > *Access Control* > *Admin Users*.
. Select the local user you want to delete.
+
NOTE: You cannot delete the predefined root local user.
+
If your system includes more than 20 items, you can specify how many rows are shown on each page at one time. You can then use your browser's find feature to search for a specific item in the currently displayed rows.

. Click *Remove*.
. Click *OK*.

== Changing a local user's password

Local users can change their own passwords using the *Change Password* option in the Grid Manager banner. In addition, users who have access to the Admin Users page can change passwords for other local users.

.About this task
You can change passwords for local users only. Federated users must change their own passwords in the external identity source.

.Steps
. Select *Configuration* > *Access Control* > *Admin Users*.
. From the Users page, select the user.
+
If your system includes more than 20 items, you can specify how many rows are shown on each page at one time. You can then use your browser's find feature to search for a specific item in the currently displayed rows.

. Click *Change Password*.
. Enter and confirm the password, and click *Save*.
