---
permalink: admin/migrating_data_into_storagegrid.html
sidebar: sidebar
keywords:
summary: 'You can migrate large amounts of data to the StorageGRID system while simultaneously using the StorageGRID system for day-to-day operations.'
---
= Migrating data into StorageGRID
:icons: font
:imagesdir: ../media/

[.lead]
You can migrate large amounts of data to the StorageGRID system while simultaneously using the StorageGRID system for day-to-day operations.

The following section is a guide to understanding and planning a migration of large amounts of data into the StorageGRID system. It is not a general guide to data migration, and it does not include detailed steps for performing a migration. Follow the guidelines and instructions in this section to ensure that data is migrated efficiently into the StorageGRID system without interfering with day-to-day operations, and that the migrated data is handled appropriately by the StorageGRID system.

* xref:confirming_capacity_of_storagegrid_system.adoc[Confirming capacity of the StorageGRID system]
* xref:determining_ilm_policy_for_migrated_data.adoc[Determining the ILM policy for migrated data]
* xref:impact_of_migration_on_operations.adoc[Impact of migration on operations]
* xref:scheduling_data_migration.adoc[Scheduling data migration]
* xref:monitoring_data_migration.adoc[Monitoring data migration]
* xref:creating_custom_notifications_for_migration_alarms.adoc[Creating custom notifications for migration alarms]
