---
permalink: admin/migrating-data-into-storagegrid.html
sidebar: sidebar
keywords:
summary: 'You can migrate large amounts of data to the StorageGRID system while simultaneously using the StorageGRID system for day-to-day operations.'
---
= Migrating data into StorageGRID
:icons: font
:imagesdir: ../media/

[.lead]
You can migrate large amounts of data to the StorageGRID system while simultaneously using the StorageGRID system for day-to-day operations.

The following section is a guide to understanding and planning a migration of large amounts of data into the StorageGRID system. It is not a general guide to data migration, and it does not include detailed steps for performing a migration. Follow the guidelines and instructions in this section to ensure that data is migrated efficiently into the StorageGRID system without interfering with day-to-day operations, and that the migrated data is handled appropriately by the StorageGRID system.

* xref:confirming-capacity-of-storagegrid-system.adoc[Confirming capacity of the StorageGRID system]
* xref:determining-ilm-policy-for-migrated-data.adoc[Determining the ILM policy for migrated data]
* xref:impact-of-migration-on-operations.adoc[Impact of migration on operations]
* xref:scheduling-data-migration.adoc[Scheduling data migration]
* xref:monitoring-data-migration.adoc[Monitoring data migration]
* xref:creating-custom-notifications-for-migration-alarms.adoc[Creating custom notifications for migration alarms]
