---
permalink: admin/monitoring-data-migration.html
sidebar: sidebar
keywords:
summary: 'Data migration must be monitored and adjusted as necessary to ensure data is placed according to the ILM policy within the required timeframe.'
---
= Monitoring data migration
:icons: font
:imagesdir: ../media/

[.lead]
Data migration must be monitored and adjusted as necessary to ensure data is placed according to the ILM policy within the required timeframe.

This table lists the attributes you must monitor during data migration, and the issues that they represent.

If you use traffic classification policies with rate limits to throttle ingest, you can monitor the observed rate in conjunction with the statistics described in the following table and reduce the limits if necessary.

[cols="1a,2a" options="header"]
|===
| Monitor| Description
a|
Number of objects waiting for ILM evaluation

a|

. Select *Support* > *Tools* > *Grid Topology*.
. Select *_deployment_* > *Overview* > *Main*.
. In the ILM Activity section, monitor the number of objects shown for the following attributes:
 ** *Awaiting - All (XQUZ)*: The total number of objects awaiting ILM evaluation.
 ** *Awaiting - Client (XCQZ)*: The total number of objects awaiting ILM evaluation from client operations (for example, ingest).
. If the number of objects shown for either of these attributes exceeds 100,000, throttle the ingest rate of objects to reduce the load on the StorageGRID system.

a|
Targeted archival system's storage capacity

a|
If the ILM policy saves a copy of the migrated data to a targeted archival storage system (tape or the cloud), monitor the capacity of the targeted archival storage system to ensure that there is sufficient capacity for the migrated data.

a|
*Archive Node* > *ARC* > *Store*
a|
If an alarm for the *Store Failures (ARVF)* attribute is triggered, the targeted archival storage system might have reached capacity. Check the targeted archival storage system and resolve any issues that triggered an alarm.

|===
