---
permalink: admin/networking-and-ports-for-platform-services.html
sidebar: sidebar
keywords: 
summary: 'If you allow an S3 tenant to use platform services, you must configure networking for the grid to ensure that platform services messages can be delivered to their destinations.'
---
= Networking and ports for platform services
:icons: font
:imagesdir: ../media/

[.lead]
If you allow an S3 tenant to use platform services, you must configure networking for the grid to ensure that platform services messages can be delivered to their destinations.

You can enable platform services for an S3 tenant account when you create or update the tenant account. If platform services are enabled, the tenant can create endpoints that serve as a destination for CloudMirror replication, event notifications, or search integration messages from its S3 buckets. These platform services messages are sent from Storage Nodes that run the ADC service to the destination endpoints.

For example, tenants might configure the following types of destination endpoints:

* A locally-hosted Elasticsearch cluster
* A local application that supports receiving Simple Notification Service (SNS) messages
* A locally-hosted S3 bucket on the same or another instance of StorageGRID
* An external endpoint, such as an endpoint on Amazon Web Services.

To ensure that platform services messages can be delivered, you must configure the network or networks containing the ADC Storage Nodes. You must ensure that the following ports can be used to send platform services messages to the destination endpoints.

By default, platform services messages are sent on the following ports:

* *80*: For endpoint URIs that begin with http
* *443*: For endpoint URIs that begin with https

Tenants can specify a different port when they create or edit an endpoint.

NOTE: If a StorageGRID deployment is used as the destination for CloudMirror replication, replication messages might be received on a port other than 80 or 443. Ensure that the port being used for S3 by the destination StorageGRID deployment is specified in the endpoint.

If you use a non-transparent proxy server, you must also configure Storage proxy settings to allow messages to be sent to external endpoints, such as an endpoint on the internet.

.Related information

xref:configuring-storage-proxy-settings.adoc[Configuring Storage proxy settings]

xref:../tenant/index.adoc[Use a tenant account]
