---
permalink: admin/removing-user-or-group-from-cifs-audit-share.html
sidebar: sidebar
keywords:
summary: 'You cannot remove the last user or group permitted to access the audit share.'
---
= Removing a user or group from a CIFS audit share
:icons: font
:imagesdir: ../media/

[.lead]
You cannot remove the last user or group permitted to access the audit share.

.What you'll need

* You must have the `Passwords.txt` file with the root account passwords (available in the SAID package).
* You must have the `Configuration.txt` file (available in the SAID package).

.About this task

Audit export through CIFS/Samba has been deprecated and will be removed in a future StorageGRID release.

.Steps

. Log in to the primary Admin Node:
 .. Enter the following command: `ssh admin@_primary_Admin_Node_IP_`
 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.
+
When you are logged in as root, the prompt changes from `$` to `#`.
. Start the CIFS configuration utility: `config_cifs.rb`
+
----

---------------------------------------------------------------------
| Shares                 | Authentication         | Config          |
---------------------------------------------------------------------
| add-audit-share        | set-authentication     | validate-config |
| enable-disable-share   | set-netbios-name       | help            |
| add-user-to-share      | join-domain            | exit            |
| remove-user-from-share | add-password-server    |                 |
| modify-group           | remove-password-server |                 |
|                        | add-wins-server        |                 |
|                        | remove-wins-server     |                 |
---------------------------------------------------------------------
----

. Start removing a user or group: `remove-user-from-share`
+
A numbered list of available audit shares for the Admin Node is displayed. The audit share is labeled audit-export.

. Enter the number of the audit share: `_audit_share_number_`
. When prompted to remove a user or a group: `user` or `group`
+
A numbered list of users or groups for the audit share is displayed.

. Enter the number corresponding to the user or group you want to remove: `_number_`
+
The audit share is updated, and the user or group is no longer permitted access to the audit share. For example:
+
----
Enabled shares
 1. audit-export
Select the share to change: 1
Remove user or group? [User/group]: User
Valid users for this share
1. audituser
2. newaudituser
Select the user to remove: 1

Removed user "audituser" from share "audit-export".

Press return to continue.
----

. Close the CIFS configuration utility: `exit`
. If the StorageGRID deployment includes Admin Nodes at other sites, disable the audit share at each site as required.
. Log out of each command shell when configuration is complete: `exit`

.Related information

xref:../upgrade/index.adoc[Upgrade software]
