---
permalink: admin/removing-nfs-audit-client-from-audit-share.html
sidebar: sidebar
keywords:
summary: 'NFS audit clients are granted access to an audit share based on their IP address. You can remove an existing audit client by removing its IP address.'
---
= Removing an NFS audit client from the audit share
:icons: font
:imagesdir: ../media/

[.lead]
NFS audit clients are granted access to an audit share based on their IP address. You can remove an existing audit client by removing its IP address.

.What you'll need

* You must have the `Passwords.txt` file with the root/admin account password (available in the SAID package).
* You must have the `Configuration.txt` file (available in the SAID package).

.About this task

You cannot remove the last IP address permitted to access the audit share.

.Steps

. Log in to the primary Admin Node:
 .. Enter the following command: `ssh admin@_primary_Admin_Node_IP_`
 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.
+
When you are logged in as root, the prompt changes from `$` to `#`.
. Start the NFS configuration utility: `config_nfs.rb`
+
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----

. Remove the IP address from the audit share: `remove-ip-from-share`
+
A numbered list of audit shares configured on the server is displayed. The audit share is listed as: `/var/local/audit/export`

. Enter the number corresponding to the audit share: `_audit_share_number_`
+
A numbered list of IP addresses permitted to access the audit share is displayed.

. Enter the number corresponding to the IP address you want to remove.
+
The audit share is updated, and access is no longer permitted from any audit client with this IP address.

. When prompted, press *Enter*.
+
The NFS configuration utility is displayed.

. Close the NFS configuration utility: `exit`
. If your StorageGRID deployment is a multiple data center site deployment with additional Admin Nodes at the other sites, disable these audit shares as required:
 .. Remotely log in to each site's Admin Node:
  ... Enter the following command: `ssh admin@_grid_node_IP_`
  ... Enter the password listed in the `Passwords.txt` file.
  ... Enter the following command to switch to root: `su -`
  ... Enter the password listed in the `Passwords.txt` file.
 .. Repeat these steps to configure the audit shares for each additional Admin Node.
 .. Close the remote secure shell login to the remote Admin Node: `exit`
. Log out of the command shell: `exit`
