---
permalink: admin/restoring-default-server-certificates-for-s3-swift-api-endpoints.html
sidebar: sidebar
keywords:
summary: 'You can revert to using the default S3 and Swift API certificate for S3 and Swift client connections Storage Node, to the deprecated Connection Load Balancer (CLB) service on a Gateway Node, and load balancer endpoints (optional).'
---
= Restore the default S3 and Swift API certificate
:icons: font
:imagesdir: ../media/

[.lead]
You can revert to using the default S3 and Swift API certificate for S3 and Swift client connections Storage Node, to the deprecated Connection Load Balancer (CLB) service on a Gateway Node, and load balancer endpoints (optional).

.Steps

. Select *CONFIGURATION* > *Security* > *Certificates*.
. On the *Global* tab, select *S3 and Swift API certificate*.
. Select *Use default certificate*.
+
When you restore the default S3 and Swift API certificate for the object storage API endpoints, the custom server certificate files you configured are deleted and cannot be recovered from the system. The default S3 and Swift API certificate is used for subsequent new S3 and Swift client connections to a Storage Node, to the deprecated Connection Load Balancer (CLB) service on a Gateway Node, and load balancer endpoints (optional).

. Refresh the page to ensure the web browser is updated.
