---
permalink: admin/reviewing-storagegrid-encryption-methods.html
sidebar: sidebar
keywords:
summary: 'StorageGRID provides a number of options for encrypting data. You should review the available methods to determine which methods meet your data-protection requirements.'
---
= Reviewing StorageGRID encryption methods
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID provides a number of options for encrypting data. You should review the available methods to determine which methods meet your data-protection requirements.

The table provides a high-level summary of the encryption methods available in StorageGRID.

[cols="1a,1a,1a" options="header"]
|===
| Encryption option| How it works| Applies to
a|
Key management server (KMS) in Grid Manager
a|
You configure a key management server for the StorageGRID site (*Configuration* > *System Settings* > *Key Management Server*) and enable node encryption for the appliance. Then, an appliance node connects to the KMS to request a key encryption key (KEK). This key encrypts and decrypts the data encryption key (DEK) on each volume.
a|
Appliance nodes that have *Node Encryption* enabled during installation. All data on the appliance is protected against physical loss or removal from the data center. Can be used with some StorageGRID storage and services appliances.

a|
Drive security in SANtricity System Manager
a|
If the Drive Security feature is enabled for a storage appliance, you can use SANtricity System Manager to create and manage the security key. The key is required to access the data on the secured drives.
a|
Storage appliances that have Full Disk Encryption (FDE) drives or Federal Information Processing Standard (FIPS) drives. All data on the secured drives is protected against physical loss or removal from the data center. Cannot be used with some storage appliances or with any service appliances.

xref:../sg6000/index.adoc[SG6000 storage appliances]

xref:../sg5700/index.adoc[SG5700 storage appliances]

xref:../sg5600/index.adoc[SG5600 storage appliances]

a|
Stored Object Encryption grid option
a|
The *Stored Object Encryption* option can be enabled in the Grid Manager (*Configuration* > *System Settings* > *Grid Options*). When enabled, any new objects that are not encrypted at the bucket level or at the object level are encrypted during ingest.
a|
Newly ingested S3 and Swift object data.Existing stored objects are not encrypted. Object metadata and other sensitive data are not encrypted.

xref:configuring-stored-object-encryption.adoc[Configuring stored object encryption]

a|
S3 bucket encryption
a|
You issue a PUT Bucket encryption request to enable encryption for the bucket. Any new objects that are not encrypted at the object level are encrypted during ingest.
a|
Newly ingested S3 object data only.Encryption must be specified for the bucket. Existing bucket objects are not encrypted. Object metadata and other sensitive data are not encrypted.

xref:../s3/index.adoc[Use S3]

a|
S3 object server-side encryption (SSE)
a|
You issue an S3 request to store an object and include the `x-amz-server-side-encryption` request header.
a|
Newly ingested S3 object data only.Encryption must be specified for the object. Object metadata and other sensitive data are not encrypted.

StorageGRID manages the keys.

xref:../s3/index.adoc[Use S3]

a|
S3 object server-side encryption with customer-provided keys (SSE-C)
a|
You issue an S3 request to store an object and include three request headers.

* `x-amz-server-side-encryption-customer-algorithm`
* `x-amz-server-side-encryption-customer-key`
* `x-amz-server-side-encryption-customer-key-MD5`

a|
Newly ingested S3 object data only.Encryption must be specified for the object. Object metadata and other sensitive data are not encrypted.

Keys are managed outside of StorageGRID.

xref:../s3/index.adoc[Use S3]

a|
External volume or datastore encryption
a|
You use an encryption method outside of StorageGRID to encrypt an entire volume or datastore, if your deployment platform supports it.
a|
All object data, metadata, and system configuration data, assuming every volume or datastore is encrypted.

An external encryption method provides tighter control over encryption algorithms and keys. Can be combined with the other methods listed.

a|
Object encryption outside of StorageGRID
a|
You use an encryption method outside of StorageGRID to encrypt object data and metadata before they are ingested into StorageGRID.
a|
Object data and metadata only (system configuration data is not encrypted).

An external encryption method provides tighter control over encryption algorithms and keys. Can be combined with the other methods listed.

https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingClientSideEncryption.html[Amazon Simple Storage Service - Developer Guide: Protecting data using client-side encryption^]

|===

== Using multiple encryption methods

Depending on your requirements, you can use more than one encryption method at a time. For example:

* You can use a KMS to protect appliance nodes and also use the drive security feature in SANtricity System Manager to "`double encrypt`" data on the self-encrypting drives in the same appliances.
* You can use a KMS to secure data on appliance nodes and also use the Stored Object Encryption grid option to encrypt all objects when they are ingested.

If only a small portion of your objects require encryption, consider controlling encryption at the bucket or individual object level instead. Enabling multiple levels of encryption has an additional performance cost.
