---
permalink: admin/setting-custom-alarms-for-archive-node.html
sidebar: sidebar
keywords: 
summary: 'You should establish Custom alarms for the ARQL and ARRL attributes that are used to monitor the speed and efficiency of object data retrieval from the archival storage system by the Archive Node.'
---
= Setting Custom alarms for the Archive Node
:icons: font
:imagesdir: ../media/

[.lead]
You should establish Custom alarms for the ARQL and ARRL attributes that are used to monitor the speed and efficiency of object data retrieval from the archival storage system by the Archive Node.

* ARQL: Average Queue Length. The average time, in microseconds, that object data is queued for retrieval from the archival storage system.
* ARRL: Average Request Latency. The average time, in microseconds, needed by the Archive Node to retrieve object data from the archival storage system.

The acceptable values for these attributes depend on how the archival storage system is configured and used. (Go to *ARC* > *Retrieve* > *Overview* > *Main*.) The values set for request timeouts and the number of sessions made available for retrieve requests are particularly influential.

After integration is complete, monitor the Archive Node's object data retrievals to establish values for normal retrieval times and queue lengths. Then, create Custom alarms for ARQL and ARRL that will trigger if an abnormal operating condition arises.

.Related information

xref:../monitor/index.adoc[Monitor & troubleshoot]
