---
permalink: admin/storage-node-configuration-settings.html
sidebar: sidebar
keywords:
summary: 'Each Storage Node uses a number of configuration settings and counters. You might need to view the current settings or reset counters to clear alarms \(legacy system\).'
---
= Storage Node configuration settings
:icons: font
:imagesdir: ../media/

[.lead]
Each Storage Node uses a number of configuration settings and counters. You might need to view the current settings or reset counters to clear alarms (legacy system).

IMPORTANT: Except when specifically instructed in documentation, you should consult with technical support before modifying any Storage Node configuration settings. As required, you can reset event counters to clear legacy alarms.

To access a Storage Node's configuration settings and counters:

. Select *Support* > *Tools* > *Grid Topology*.
. Select *_site_* > *_Storage Node_*.
. Expand the Storage Node and select the service or component.
. Select the *Configuration* tab.

The following tables summarize Storage Node configuration settings.

== LDR

[cols="1a,1a,2a" options="header"]
|===
| Attribute Name| Code| Description
a|
HTTP State
a|
HSTE
a|
The current state of the HTTP protocol for S3, Swift, and other internal StorageGRID traffic:

* Offline: No operations are allowed, and any client application that attempts to open an HTTP session to the LDR service receives an error message. Active sessions are gracefully closed.
* Online: Operation continues normally

a|
Auto-Start HTTP
a|
HTAS
a|

* If selected, the state of the system on restart depends on the state of the *LDR* > *Storage* component. If the *LDR* > *Storage* component is Read-only on restart, the HTTP interface is also Read-only. If the *LDR* > *Storage* component is Online, then HTTP is also Online. Otherwise, the HTTP interface remains in the Offline state.
* If not selected, the HTTP interface remains Offline until explicitly enabled.

|===

== LDR > Data Store

[cols="1a,1a,2a" options="header"]
|===
| Attribute Name| Code| Description
a|
Reset Lost Objects Count
a|
RCOR
a|
Reset the counter for the number of lost objects on this service.
|===

== LDR > Storage

[cols="1a,1a,2a" options="header"]
|===
| Attribute Name| Code| Description
a|
Storage State -- Desired
a|
SSDS
a|
A user-configurable setting for the desired state of the storage component. The LDR service reads this value and attempts to match the status indicated by this attribute. The value is persistent across restarts.

For example, you can use this setting to force storage to become read-only even when there is ample available storage space. This can be useful for troubleshooting.

The attribute can take one of the following values:

* Offline: When the desired state is Offline, the LDR service takes the *LDR* > *Storage* component offline.
* Read-only: When the desired state is Read-only, the LDR service moves the storage state to read-only and stops accepting new content. Note that content might continue to be saved to the Storage Node for a short time until open sessions are closed.
* Online: Leave the value at Online during normal system operations. The Storage State -- Current of the storage component will be dynamically set by the service based on the condition of the LDR service, such as the amount of available object storage space. If space is low, the component becomes Read-only.

a|
Health Check Timeout
a|
SHCT
a|
The time limit in seconds within which a health check test must complete in order for a storage volume to be considered healthy. Only change this value when directed to do so by Support.
|===

== LDR > Verification

[cols="1a,1a,2a" options="header"]
|===
| Attribute Name| Code| Description
a|
Reset Missing Objects Count
a|
VCMI
a|
Resets the count of Missing Objects Detected (OMIS). Use only after foreground verification completes. Missing replicated object data is restored automatically by the StorageGRID system.
a|
Verify
a|
FVOV
a|
Select object stores on which to perform foreground verification.
a|
Verification Rate
a|
VPRI
a|
Set the rate at which background verification takes place. See information on configuring the background verification rate.
a|
Reset Corrupt Objects Count
a|
VCCR
a|
Reset the counter for corrupt replicated object data found during background verification. This option can be used to clear the Corrupt Objects Detected (OCOR) alarm condition. For details, see the instructions for monitoring and troubleshooting StorageGRID.
a|
Delete Quarantined Objects
a|
OQRT
a|
Delete corrupt objects from the quarantine directory, reset the count of quarantined objects to zero, and clear the Quarantined Objects Detected (OQRT) alarm. This option is used after corrupt objects have been automatically restored by the StorageGRID system.

If a Lost Objects alarm is triggered, technical support might want to access the quarantined objects. In some cases, quarantined objects might be useful for data recovery or for debugging the underlying issues that caused the corrupt object copies.

|===

== LDR > Erasure Coding

[cols="1a,1a,2a" options="header"]
|===
| Attribute Name| Code| Description
a|
Reset Writes Failure Count
a|
RSWF
a|
Reset the counter for write failures of erasure-coded object data to the Storage Node.
a|
Reset Reads Failure Count
a|
RSRF
a|
Reset the counter for read failures of erasure-coded object data from the Storage Node.
a|
Reset Deletes Failure Count
a|
RSDF
a|
Reset the counter for delete failures of erasure-coded object data from the Storage Node.
a|
Reset Corrupt Copies Detected Count
a|
RSCC
a|
Reset the counter for the number of corrupt copies of erasure-coded object data on the Storage Node.
a|
Reset Corrupt Fragments Detected Count
a|
RSCD
a|
Reset the counter for corrupt fragments of erasure-coded object data on the Storage Node.
a|
Reset Missing Fragments Detected Count
a|
RSMD
a|
Reset the counter for missing fragments of erasure-coded object data on the Storage Node. Use only after foreground verification completes.
|===

== LDR > Replication

[cols="1a,1a,2a" options="header"]
|===
| Attribute Name| Code| Description
a|
Reset Inbound Replication Failure Count
a|
RICR
a|
Reset the counter for inbound replication failures. This can be used to clear the RIRF (Inbound Replication -- Failed) alarm.
a|
Reset Outbound Replication Failure Count
a|
ROCR
a|
Reset the counter for outbound replication failures. This can be used to clear the RORF (Outbound Replications -- Failed) alarm.
a|
Disable Inbound Replication
a|
DSIR
a|
Select to disable inbound replication as part of a maintenance or testing procedure. Leave unchecked during normal operation.

When inbound replication is disabled, objects can be retrieved from the Storage Node for copying to other locations in the StorageGRID system, but objects cannot be copied to this Storage Node from other locations: the LDR service is read-only.

a|
Disable Outbound Replication
a|
DSOR
a|
Select to disable outbound replication (including content requests for HTTP retrievals) as part of a maintenance or testing procedure. Leave unchecked during normal operation.

When outbound replication is disabled, objects can be copied to this Storage Node, but objects cannot be retrieved from the Storage Node to be copied to other locations in the StorageGRID system. The LDR service is write-only.

|===
.Related information

xref:../monitor/index.adoc[Monitor & troubleshoot]
