---
permalink: admin/task_verifying_nfs_audit_integration.html
sidebar: sidebar
keywords: 
summary: 'After you configure an audit share and add an NFS audit client, you can mount the audit client share and verify that the files are available from the audit share.'
---
= Verifying NFS audit integration
:icons: font
:imagesdir: ../media/

[.lead]
After you configure an audit share and add an NFS audit client, you can mount the audit client share and verify that the files are available from the audit share.

. Verify connectivity (or variant for the client system) using the client-side IP address of the Admin Node hosting the AMS service. Enter: `ping IP_address`
+
Verify that the server responds, indicating connectivity.

. Mount the audit read-only share using a command appropriate to the client operating system. A sample Linux command is (enter on one line): `mount -t nfs -o hard,intr Admin_Node_IP_address:/var/local/audit/export myAudit`
+
Use the IP address of the Admin Node hosting the AMS service and the predefined share name for the audit system. The mount point can be any name selected by the client (for example, myAudit in the previous command).

. Verify that the files are available from the audit share. Enter: `ls myAudit /*`
+
where myAudit is the mount point of the audit share. There should be at least one log file listed.
