---
permalink: admin/task_adding_nfs_audit_client_to_audit_share.html
sidebar: sidebar
keywords: 
summary: 'NFS audit clients are granted access to an audit share based on their IP address. Grant access to the audit share to a new NFS audit client by adding its IP address to the audit share.'
---
= Adding an NFS audit client to an audit share
:icons: font
:imagesdir: ../media/

[.lead]
NFS audit clients are granted access to an audit share based on their IP address. Grant access to the audit share to a new NFS audit client by adding its IP address to the audit share.

* You must have the Passwords.txt file with the root/admin account password (available in the SAID package).
* You must have the Configuration.txt file (available in the SAID package).
* The audit client must be using NFS Version 3 (NFSv3).

. Log in to the primary Admin Node:
 .. Enter the following command: `ssh admin@primary_Admin_Node_IP`
 .. Enter the password listed in the Passwords.txt file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the Passwords.txt file.
+
When you are logged in as root, the prompt changes from `$` to `#`.
. Start the NFS configuration utility: `config_nfs.rb`
+
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----

. Enter: `add-ip-to-share`
+
A list of NFS audit shares enabled on the Admin Node is displayed. The audit share is listed as: /var/local/audit/export

. Enter the number of the audit share: `audit_share_number`
. When prompted, enter the audit client's IP address or IP address range for the audit share: `client_IP_address`
+
The audit client is added to the audit share.

. When prompted, press *Enter*.
+
The NFS configuration utility is displayed.

. Repeat from step <<STEP_C031405E18EF422EBCB1DC8C0AC8CD3D,3>> for each audit client that should be added to the audit share.
. Optionally, verify your configuration: `validate-config`
+
The services are checked and displayed.

 .. When prompted, press *Enter*.
+
The NFS configuration utility is displayed.

. Close the NFS configuration utility: `exit`
. If the StorageGRID deployment is a single site, go to step <<STEP_EE192A67A0F941229E4548D20E76E41B,11>>.
+
-- or --
+
Optionally, if the StorageGRID deployment includes Admin Nodes at other sites, enable these audit shares as required:

 .. Remotely log in to a site's Admin Node:
  ... Enter the following command: `ssh admin@grid_node_IP`
  ... Enter the password listed in the Passwords.txt file.
  ... Enter the following command to switch to root: `su -`
  ... Enter the password listed in the Passwords.txt file.
 .. Repeat steps <<STEP_0B2C788AB35347CDB4803E8FB39FA2BF,2>> through <<STEP_0F143B4A033E4CF48D052AAA64EF9C09,9>> to configure the audit shares for each Admin Node.
 .. Close the remote secure shell login to the remote Admin Node: `exit`

. Log out of the command shell: `exit`
