---
permalink: admin/updating-storagegrid-license-information.html
sidebar: sidebar
keywords: storagegrid license, update license, add storage capacity
summary: 'You must update the license information for your StorageGRID system any time the terms of your license change. For example, you must update the license information if you purchase additional storage capacity for your grid.'
---
= Update StorageGRID license information
:icons: font
:imagesdir: ../media/

[.lead]
You must update the license information for your StorageGRID system any time the terms of your license change. For example, you must update the license information if you purchase additional storage capacity for your grid.

.What you'll need

* You have a new license file to apply to your StorageGRID system.
* You have specific access permissions.
* You have the provisioning passphrase.

.Steps

. Select *MAINTENANCE* > *System* > *License*.
. Enter the provisioning passphrase for your StorageGRID system in the *Provisioning Passphrase* text box.
. Select *Browse*.
. In the Open dialog box, locate and select the new license file (`.txt`), and select *Open*.
+
The new license file is validated and displayed.

. Select *Save*.
