---
permalink: admin/using-identity-federation.html
sidebar: sidebar
keywords: how to use identity federation, how to use federated groups with Grid Manager
summary: 'Using identity federation makes setting up groups and users faster, and it allows users to sign in to StorageGRID using familiar credentials.'
---
= Use identity federation
:icons: font
:imagesdir: ../media/

[.lead]
Using identity federation makes setting up groups and users faster, and it allows users to sign in to StorageGRID using familiar credentials.

== Configure identity federation for Grid Manager

You can configure identity federation in the Grid Manager if you want admin groups and users to be managed in another system such as Active Directory, Azure Active Directory (Azure AD), OpenLDAP, or Oracle Directory Server.

.What you'll need
* You are signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You have specific access permissions.
* You are using Active Directory, Azure AD, OpenLDAP, or Oracle Directory Server as the identity provider.
+
NOTE: If you want to use an LDAP v3 service that is not listed, contact technical support.
* If you plan to use OpenLDAP, you must configure the OpenLDAP server. See <<Guidelines for configuring an OpenLDAP server>>.
* If you plan to enable single sign-on (SSO), you have reviewed the xref:requirements-for-sso.adoc[requirements for using single sign-on].
* If you plan to use Transport Layer Security (TLS) for communications with the LDAP server, the identity provider is using TLS 1.2 or 1.3. See xref:supported-ciphers-for-outgoing-tls-connections.adoc[Supported ciphers for outgoing TLS connections].

.About this task
You can configure an identity source for the Grid Manager if you want to import groups from another system such as Active Directory, Azure AD, OpenLDAP, or Oracle Directory Server. You can import the following types of groups:

* Admin groups. The users in admin groups can sign in to the Grid Manager and perform tasks, based on the management permissions assigned to the group.
* Tenant user groups for tenants that do not use their own identity source. Users in tenant groups can sign in to the Tenant Manager and perform tasks, based on the permissions assigned to the group in the Tenant Manager. See xref:creating-tenant-account.adoc[Create tenant account] and xref:../tenant/index.adoc[Use a tenant account] for details.

=== Enter the configuration

. Select *CONFIGURATION* > *Access control* > *Identity federation*.
include::../_include/identity_federation_configure_steps.adoc[]

== Force synchronization with the identity source
include::../_include/identity_federation_force_sync_steps.adoc[]

== Disable identity federation
include::../_include/identity_federation_disable_steps.adoc[]

== Guidelines for configuring an OpenLDAP server
include::../_include/identity_federation_openldap_guidelines.adoc[]
