---
permalink: admin/using-grid-management-api.html
sidebar: sidebar
keywords: use the Grid Management API, private API
summary: 'You can perform system management tasks using the Grid Management REST API instead of the Grid Manager user interface. For example, you might want to use the API to automate operations or to create multiple entities, such as users, more quickly.'
---
= Use the Grid Management API
:icons: font
:imagesdir: ../media/

[.lead]
You can perform system management tasks using the Grid Management REST API instead of the Grid Manager user interface. For example, you might want to use the API to automate operations or to create multiple entities, such as users, more quickly.

The Grid Management API uses the Swagger open source API platform. Swagger provides an intuitive user interface that allows developers and non-developers to perform real-time operations in StorageGRID with the API.

== Top-level resources

The Grid Management API provides the following top-level resources:

* `/grid`: Access is restricted to Grid Manager users and is based on the configured group permissions.
* `/org`: Access is restricted to users who belong to a local or federated LDAP group for a tenant account. For details, see xref:../tenant/index.adoc[Use a tenant account].
* `/private`: Access is restricted to Grid Manager users and is based on the configured group permissions. The private APIs are subject to change without notice. StorageGRID private endpoints also ignore the API version of the request. 


