---
permalink: admin/what-is-autosupport.html
sidebar: sidebar
keywords: autosupport, technical support, storagegrid health, system status, active iq
summary: 'The AutoSupport feature enables your StorageGRID system to send health and status messages to technical support.'
---
= What is AutoSupport?
:icons: font
:imagesdir: ../media/

[.lead]
The AutoSupport feature enables your StorageGRID system to send health and status messages to technical support. 

Using AutoSupport can significantly speed problem determination and resolution. Technical support can also monitor the storage needs of your system and help you determine if you need to add new nodes or sites. Optionally, you can configure AutoSupport messages to be sent to one additional destination.

== Information included in AutoSupport messages

include::../_include/autosupport-message-info.adoc[]

== What is Active IQ?

include::../_include/autosupport-activeiq.adoc[]

== Protocols for sending AutoSupport messages

You can choose one of three protocols for sending AutoSupport messages:

* HTTPS
* HTTP
* SMTP

If you send AutoSupport messages using HTTPS or HTTP, you can configure a non-transparent proxy server between Admin Nodes and technical support.

If you use SMTP as the protocol for AutoSupport messages, you must configure an SMTP mail server.

== AutoSupport options

You can use any combination of the following options to send AutoSupport messages to technical support:

* *Weekly*: Automatically send AutoSupport messages once per week. Default setting: Enabled.
* *Event-triggered*: Automatically send AutoSupport messages every hour or when significant system events occur. Default setting: Enabled.
* *On Demand*: Allow technical support to request that your StorageGRID system send AutoSupport messages automatically, which is useful when they are actively working an issue (requires HTTPS AutoSupport transmission protocol). Default setting: Disabled.
* *User-triggered*: Manually send AutoSupport messages at any time.

.Related information

https://mysupport.netapp.com/site/global/dashboard[NetApp Support^]
