---
permalink: admin/what-arc-service-is.html
sidebar: sidebar
keywords: 
summary: 'The Archive Node’s Archive \(ARC\) service provides the management interface you can use to configure connections to external archival storage, such as tape through TSM middleware.'
---
= What the ARC service is
:icons: font
:imagesdir: ../media/

[.lead]
The Archive Node's Archive (ARC) service provides the management interface you can use to configure connections to external archival storage, such as tape through TSM middleware.

It is the ARC service that interacts with an external archival storage system, sending object data for near-line storage and performing retrievals when a client application requests an archived object. When a client application requests an archived object, a Storage Node requests the object data from the ARC service. The ARC service makes a request to the external archival storage system, which retrieves the requested object data and sends it to the ARC service. The ARC service verifies the object data and forwards it to the Storage Node, which in turn returns the object to the requesting client application.

Requests for object data archived to tape through TSM middleware are managed for efficiency of retrievals. Requests can be ordered so that objects stored in sequential order on tape are requested in that same sequential order. Requests are then queued for submission to the storage device. Depending upon the archival device, multiple requests for objects on different volumes can be processed simultaneously.
