---
permalink: s3/benefits_of_active_idle_and_concurrent_http_connections.html
sidebar: sidebar
keywords:
summary: 'How you configure HTTP connections can impact the performance of the StorageGRID system. Configurations differ depending on whether the HTTP connection is active or idle or you have concurrent multiple connections.'
---
= Benefits of active, idle, and concurrent HTTP connections
:icons: font
:imagesdir: ../media/

[.lead]
How you configure HTTP connections can impact the performance of the StorageGRID system. Configurations differ depending on whether the HTTP connection is active or idle or you have concurrent multiple connections.

You can identify the performance benefits for the following types of HTTP connections:

* Idle HTTP connections
* Active HTTP connections
* Concurrent HTTP connections

* xref:benefits_of_keeping_idle_http_connections_open.adoc[Benefits of keeping idle HTTP connections open]
* xref:benefits_of_active_http_connections.adoc[Benefits of active HTTP connections]
* xref:benefits_of_concurrent_http_connections.adoc[Benefits of concurrent HTTP connections]
* xref:separation_of_http_connection_pools_for_read_and_write_operations.adoc[Separation of HTTP connection pools for read and write operations]
