---
permalink: s3/changes_to_s3_rest_api_support.html
sidebar: sidebar
keywords:
summary: 'You should be aware of changes to the StorageGRID system’s support for the S3 REST API.'
---
= Changes to S3 REST API support
:icons: font
:imagesdir: ../media/

[.lead]
You should be aware of changes to the StorageGRID system's support for the S3 REST API.

[options="header"]
|===
| Release| Comments
a|
11.5
a|

* Added support for managing bucket encryption.
* Added support for S3 Object Lock and deprecated legacy Compliance requests.
* Added support for using DELETE Multiple Objects on versioned buckets.
* The `Content-MD5` request header is now correctly supported.

a|
11.4
a|

* Added support for DELETE Bucket tagging, GET Bucket tagging, and PUT Bucket tagging. Cost allocation tags are not supported.
* For buckets created in StorageGRID 11.4, restricting object key names to meet performance best practices is no longer required.
* Added support for bucket notifications on the `s3:ObjectRestore:Post` event type.
* AWS size limits for multipart parts are now enforced. Each part in a multipart upload must be between 5 MiB and 5 GiB. The last part can be smaller than 5 MiB.
* Added support for TLS 1.3, and updated list of supported TLS cipher suites.
* The CLB service is deprecated.

a|
11.3
a|

* Added support for server-side encryption of object data with customer-provided keys (SSE-C).
* Added support for DELETE, GET, and PUT Bucket lifecycle operations (Expiration action only) and for the `x-amz-expiration` response header.
* Updated PUT Object, PUT Object - Copy, and Multipart Upload to describe the impact of ILM rules that use synchronous placement at ingest.
* Updated list of supported TLS cipher suites. TLS 1.1 ciphers are no longer supported.

a|
11.2
a|
Added support for POST Object restore for use with Cloud Storage Pools. Added support for using the AWS syntax for ARN, policy condition keys, and policy variables in group and bucket policies. Existing group and bucket policies that use the StorageGRID syntax will continue to be supported.

*Note:* Uses of ARN/URN in other configuration JSON/XML, including those used in custom StorageGRID features, have not changed.

a|
11.1
a|
Added support for Cross-Origin Resource Sharing (CORS), HTTP for S3 client connections to grid nodes, and compliance settings on buckets.
a|
11.0
a|
Added support for configuring platform services (CloudMirror replication, notifications, and Elasticsearch search integration) for buckets. Also added support for object tagging location constraints for buckets, and the Available consistency control setting.
a|
10.4
a|
Added support for ILM scanning changes to versioning, Endpoint Domain Names page updates, conditions and variables in policies, policy examples, and the PutOverwriteObject permission.
a|
10.3
a|
Added support for versioning.
a|
10.2
a|
Added support for group and bucket access policies, and for multipart copy (Upload Part - Copy).
a|
10.1
a|
Added support for multipart upload, virtual hosted-style requests, and v4 authentication.
a|
10.0
a|
Initial support of the S3 REST API by the StorageGRID system.The currently supported version of the _Simple Storage Service API Reference_ is 2006-03-01.

|===
