---
permalink: s3/get-object.html
sidebar: sidebar
keywords:
summary: 'You can use the S3 GET Object request to retrieve an object from an S3 bucket.'
---
= GET Object
:icons: font
:imagesdir: ../media/

[.lead]
You can use the S3 GET Object request to retrieve an object from an S3 bucket.

== partNumber request parameter is not supported

The `partNumber` request parameter is not supported for GET Object requests. You cannot perform a GET request to retrieve a specific part of a multipart object. A 501 Not Implemented error is returned with the following message:

----
GET Object by partNumber is not implemented
----

== Request headers for server-side encryption with customer-provided encryption keys (SSE-C)

Use all three of the headers if the object is encrypted with a unique key that you provided.

* `x-amz-server-side-encryption-customer-algorithm`: Specify `AES256`.
* `x-amz-server-side-encryption-customer-key`: Specify your encryption key for the object.
* `x-amz-server-side-encryption-customer-key-MD5`: Specify the MD5 digest of the object's encryption key.

IMPORTANT: The encryption keys you provide are never stored. If you lose an encryption key, you lose the corresponding object. Before using customer-provided keys to secure object data, review the considerations in "`Using server-side encryption.`"

== UTF-8 characters in user metadata

StorageGRID does not parse or interpret escaped UTF-8 characters in user-defined metadata. GET requests for an object with escaped UTF-8 characters in user-defined metadata do not return the `x-amz-missing-meta` header if the key name or value includes unprintable characters.

== Unsupported request header

The following request header is not supported and returns `XNotImplemented`:

* `x-amz-website-redirect-location`

== Versioning

If a `versionId` subresource is not specified, the operation fetches the most recent version of the object in a versioned bucket. If the current version of the object is a delete marker, a "`Not Found`" status is returned with the `x-amz-delete-marker` response header set to `true`.

== Behavior of GET Object for Cloud Storage Pool objects

If an object has been stored in a Cloud Storage Pool (see the instructions for managing objects with information lifecycle management), the behavior of a GET Object request depends on the state of the object. See "`HEAD Object`" for more details.

NOTE: If an object is stored in a Cloud Storage Pool and one or more copies of the object also exist on the grid, GET Object requests will attempt to retrieve data from the grid, before retrieving it from the Cloud Storage Pool.

[options="header"]
|===
| State of object| Behavior of GET Object
a|
Object ingested into StorageGRID but not yet evaluated by ILM, or object stored in a traditional storage pool or using erasure coding
a|
`200 OK`

A copy of the object is retrieved.

a|
Object in Cloud Storage Pool but not yet transitioned to a non-retrievable state

a|
`200 OK`

A copy of the object is retrieved.

a|
Object transitioned to a non-retrievable state

a|
`403 Forbidden`, `InvalidObjectState`

Use a POST Object restore request to restore the object to a retrievable state.

a|
Object in process of being restored from a non-retrievable state

a|
`403 Forbidden`, `InvalidObjectState`

Wait for the POST Object restore request to complete.

a|
Object fully restored to the Cloud Storage Pool

a|
`200 OK`

A copy of the object is retrieved.

|===

== Multipart or segmented objects in a Cloud Storage Pool

If you uploaded a multipart object or if StorageGRID split a large object into segments, StorageGRID determines whether the object is available in the Cloud Storage Pool by sampling a subset of the object's parts or segments. In some cases, a GET Object request might incorrectly return `200 OK` when some parts of the object have already been transitioned to a non-retrievable state or when some parts of the object have not yet been restored.

In these cases:

* The GET Object request might return some data but stop midway through the transfer.
* A subsequent GET Object request might return `403 Forbidden`.

.Related information

xref:using-server-side-encryption.adoc[Using server-side encryption]

xref:../ilm/index.adoc[Manage objects with ILM]

xref:post-object-restore.adoc[POST Object restore]

xref:s3-operations-tracked-in-audit-logs.adoc[S3 operations tracked in the audit logs]
