---
permalink: s3/how-storagegrid-ilm-rules-manage-objects.html
sidebar: sidebar
keywords: 
summary: 'The grid administrator creates information lifecycle management \(ILM\) rules to manage object data ingested into the StorageGRID system from S3 REST API client applications. These rules are then added to the ILM policy to determine how and where object data is stored over time.'
---
= How StorageGRID ILM rules manage objects
:icons: font
:imagesdir: ../media/

[.lead]
The grid administrator creates information lifecycle management (ILM) rules to manage object data ingested into the StorageGRID system from S3 REST API client applications. These rules are then added to the ILM policy to determine how and where object data is stored over time.

ILM settings determine the following aspects of an object:

* *Geography*
+
The location of an object's data, either within the StorageGRID system (storage pool) or in a Cloud Storage Pool.

* *Storage grade*
+
The type of storage used to store object data: for example flash or spinning disk.

* *Loss protection*
+
How many copies are made and the types of copies that are created: replication, erasure coding, or both.

* *Retention*
+
The changes over time to how an object's data is managed, where it is stored, and how it is protected from loss.

* *Protection during ingest*
+
The method used to protect object data during ingest: synchronous placement (using the Balanced or Strict options for Ingest Behavior), or making interim copies (using the Dual commit option).

ILM rules can filter and select objects. For objects ingested using S3, ILM rules can filter objects based on the following metadata:

* Tenant Account
* Bucket Name
* Ingest Time
* Key
* Last Access Time
+
NOTE: By default, updates to last access time are disabled for all S3 buckets. If your StorageGRID system includes an ILM rule that uses the Last Access Time option, you must enable updates to last access time for the S3 buckets specified in that rule. You can enable last access time updates using the PUT Bucket last access time request, the *S3* > *Buckets* > *Configure Last Access Time* check box in the Tenant Manager, or using the Tenant Management API. When enabling last access time updates, be aware that StorageGRID performance might be reduced, especially in systems with small objects.

* Location Constraint
* Object Size
* User Metadata
* Object Tag

For more information about ILM, see the instructions for managing objects with information lifecycle management.

.Related information

xref:../tenant/index.adoc[Use a tenant account]

xref:../ilm/index.adoc[Manage objects with ILM]

xref:storagegrid-s3-rest-api-operations.adoc[PUT Bucket last access time request]
