---
permalink: s3/operations_on_objects.html
sidebar: sidebar
keywords: bucket, buckets, operations on buckets
summary: 'This section describes how the StorageGRID system implements S3 REST API operations for objects.'
---
= Operations on objects
:icons: font
:imagesdir: ../media/

[.lead]
This section describes how the StorageGRID system implements S3 REST API operations for objects.

* xref:get_object.adoc[GET Object]
* xref:head_object.adoc[HEAD Object]
* xref:post_object_restore.adoc[POST Object restore]
* xref:put_object.adoc[PUT Object]
* xref:put_object_copy.adoc[PUT Object - Copy]

The following conditions apply to all object operations:

* StorageGRID consistency controls are supported by all operations on objects, with the exception of the following:
 ** GET Object ACL
 ** `OPTIONS /`
 ** PUT Object legal hold
 ** PUT Object retention
* Conflicting client requests, such as two clients writing to the same key, are resolved on a "`latest-wins`" basis. The timing for the "`latest-wins`"evaluation is based on when the StorageGRID system completes a given request, and not on when S3 clients begin an operation.
* All objects in a StorageGRID bucket are owned by the bucket owner, including objects created by an anonymous user, or by another account.
* Data objects ingested to the StorageGRID system through Swift cannot be accessed through S3.

The following table describes how StorageGRID implements S3 REST API object operations.

[options="header"]
|===
| Operation| Implementation
a|
DELETE Object
a|
Multi-Factor Authentication (MFA) and the response header `x-amz-mfa` are not supported.

When processing a DELETE Object request, StorageGRID attempts to immediately remove all copies of the object from all stored locations. If successful, StorageGRID returns a response to the client immediately. If all copies cannot be removed within 30 seconds (for example, because a location is temporarily unavailable), StorageGRID queues the copies for removal and then indicates success to the client.

*Versioning*

To remove a specific version, the requestor must be the bucket owner and use the `versionId` subresource. Using this subresource permanently deletes the version. If the `versionId` corresponds to a delete marker, the response header `x-amz-delete-marker` is returned set to `true`.

* If an object is deleted without the `versionId` subresource on a version enabled bucket, it results in the generation of a delete marker. The `versionId` for the delete marker is returned using the `x-amz-version-id` response header, and the `x-amz-delete-marker` response header is returned set to `true`.
* If an object is deleted without the `versionId` subresource on a version suspended bucket, it results in a permanent deletion of an already existing 'null' version or a 'null' delete marker, and the generation of a new 'null' delete marker. The `x-amz-delete-marker` response header is returned set to `true`.

*Note*: In certain cases, multiple delete markers might exist for an object.

a|
DELETE Multiple Objects
a|
Multi-Factor Authentication (MFA) and the response header `x-amz-mfa` are not supported.

Multiple objects can be deleted in the same request message.

a|
DELETE Object tagging
a|
Uses the `tagging` subresource to remove all tags from an object. Implemented with all Amazon S3 REST API behavior.

*Versioning*

If the `versionId` query parameter is not specified in the request, the operation deletes all tags from the most recent version of the object in a versioned bucket. If the current version of the object is a delete marker, a "`MethodNotAllowed`" status is returned with the `x-amz-delete-marker` response header set to `true`.

a|
GET Object
a|
xref:get_object.adoc[GET Object]

a|
GET Object ACL
a|
If the necessary access credentials are provided for the account, the operation returns a positive response and the ID, DisplayName, and Permission of the object owner, indicating that the owner has full access to the object.

a|
GET Object legal hold
a|
xref:s3_rest_api_supported_operations_and_limitations.adoc[Using S3 Object Lock]
a|
GET Object retention
a|
xref:s3_rest_api_supported_operations_and_limitations.adoc[Using S3 Object Lock]
a|
GET Object tagging
a|
Uses the `tagging` subresource to return all tags for an object. Implemented with all Amazon S3 REST API behavior

*Versioning*

If the `versionId` query parameter is not specified in the request, the operation returns all tags from the most recent version of the object in a versioned bucket. If the current version of the object is a delete marker, a "`MethodNotAllowed`" status is returned with the `x-amz-delete-marker` response header set to `true`.

a|
HEAD Object
a|
xref:head_object.adoc[HEAD Object]

a|
POST Object restore
a|
xref:post_object_restore.adoc[POST Object restore]

a|
PUT Object
a|
xref:put_object.adoc[PUT Object]

a|
PUT Object - Copy
a|
xref:put_object_copy.adoc[PUT Object - Copy]

a|
PUT Object legal hold
a|
xref:s3_rest_api_supported_operations_and_limitations.adoc[Using S3 Object Lock]
a|
PUT Object retention
a|
xref:s3_rest_api_supported_operations_and_limitations.adoc[Using S3 Object Lock]
a|
PUT Object tagging
a|
Uses the `tagging` subresource to add a set of tags to an existing object. Implemented with all Amazon S3 REST API behavior

*Tag updates and ingest behavior*

When you use PUT Object tagging to update an object's tags, StorageGRID does not re-ingest the object. This means that the option for Ingest Behavior specified in the matching ILM rule is not used. Any changes to object placement that are triggered by the update are made when ILM is re-evaluated by normal background ILM processes.

This means that if the ILM rule uses the Strict option for ingest behavior, no action is taken if the required object placements cannot be made (for example, because a newly required location is unavailable). The updated object retains its current placement until the required placement is possible.

*Resolving conflicts*

Conflicting client requests, such as two clients writing to the same key, are resolved on a "`latest-wins`" basis. The timing for the "`latest-wins`"evaluation is based on when the StorageGRID system completes a given request, and not on when S3 clients begin an operation.

*Versioning*

If the `versionId` query parameter is not specified in the request, the operation add tags to the most recent version of the object in a versioned bucket. If the current version of the object is a delete marker, a "`MethodNotAllowed`" status is returned with the `x-amz-delete-marker` response header set to `true`.

|===

== Using S3 Object Lock

[.lead]
If the global S3 Object Lock setting is enabled for your StorageGRID system, you can create buckets with S3 Object Lock enabled and then specify retain-until-date and legal hold settings for each object version you add to that bucket.

S3 Object Lock allows you to specify object-level settings to prevent objects from being deleted or overwritten for a fixed amount of time or indefinitely.

The StorageGRID S3 Object Lock feature provides a single retention mode that is equivalent to the Amazon S3 compliance mode. By default, a protected object version cannot be overwritten or deleted by any user. The StorageGRID S3 Object Lock feature does not support a governance mode, and it does not allow users with special permissions to bypass retention settings or to delete protected objects.

=== Enabling S3 Object Lock for a bucket

If the global S3 Object Lock setting is enabled for your StorageGRID system, you can optionally enable S3 Object Lock when you create each bucket. You can use either of these methods:

* Create the bucket using the Tenant Manager.
+
xref:../tenant/index.adoc[Use a tenant account]

* Create the bucket using a PUT Bucket request with the x-amz-bucket-object-lock_enabled request header.
+
xref:s3_rest_api_supported_operations_and_limitations.adoc[Operations on buckets]

You cannot add or disable S3 Object Lock after the bucket is created. S3 Object Lock requires bucket versioning, which is enabled automatically when you create the bucket.

A bucket with S3 Object Lock enabled can contain a combination of objects with and without S3 Object Lock settings. StorageGRID does not support default retention for the objects in S3 Object Lock buckets, so the PUT Object Lock Configuration bucket operation is not supported.

=== Determining if S3 Object Lock is enabled for a bucket

To determine if S3 Object Lock is enabled, use the GET Object Lock Configuration request.

xref:s3_rest_api_supported_operations_and_limitations.adoc[Operations on buckets]

=== Creating an object with S3 Object Lock settings

To specify S3 Object Lock settings when adding an object version to a bucket that has S3 Object Lock enabled, issue a PUT Object, PUT Object - Copy, or Initiate Multipart Upload request. Use the following request headers.

NOTE: You must enable S3 Object Lock when you create a bucket. You cannot add or disable S3 Object Lock after a bucket is created.

* `x-amz-object-lock-mode`, which must be COMPLIANCE (case sensitive).
+
NOTE: If you specify `x-amz-object-lock-mode`, you must also specify `x-amz-object-lock-retain-until-date`.

* `x-amz-object-lock-retain-until-date`
 ** The retain-until-date value must be in the format `2020-08-10T21:46:00Z`. Fractional seconds are allowed, but only 3 decimal digits are preserved (milliseconds precision). Other ISO 8601 formats are not allowed.
 ** The retain-until-date must be in the future.
* `x-amz-object-lock-legal-hold`
+
If legal hold is ON (case-sensitive), the object is placed under a legal hold. If legal hold is OFF, no legal hold is placed. Any other value results in a 400 Bad Request (InvalidArgument) error.

If you use any of these request headers, be aware of these restrictions:

* The `Content-MD5` request header is required if any `x-amz-object-lock-*` request header is present in the PUT Object request. `Content-MD5` is not required for PUT Object - Copy or Initiate Multipart Upload.
* If the bucket does not have S3 Object Lock enabled and a `x-amz-object-lock-*` request header is present, a 400 Bad Request (InvalidRequest) error is returned.
* The PUT Object request supports the use of `x-amz-storage-class: REDUCED_REDUNDANCY` to match AWS behavior. However, when an object is ingested into a bucket with S3 Object Lock enabled, StorageGRID will always perform a dual-commit ingest.
* A subsequent GET or HEAD Object version response will include the headers `x-amz-object-lock-mode`, `x-amz-object-lock-retain-until-date`, and `x-amz-object-lock-legal-hold`, if configured and if the request sender has the correct `s3:Get*` permissions.
* A subsequent DELETE Object version or DELETE Objects versions request will fail if it is before the retain-until-date or if a legal hold is on.

=== Updating S3 Object Lock settings

If you need to update the legal hold or retention settings for an existing object version, you can perform the following object subresource operations:

* `PUT Object legal-hold`
+
If the new legal-hold value is ON, the object is placed under a legal hold. If the legal-hold value is OFF, the legal hold is lifted.

* `PUT Object retention`
 ** The mode value must be COMPLIANCE (case sensitive).
 ** The retain-until-date value must be in the format `2020-08-10T21:46:00Z`. Fractional seconds are allowed, but only 3 decimal digits are preserved (milliseconds precision). Other ISO 8601 formats are not allowed.
 ** If an object version has an existing retain-until-date, you can only increase it. The new value must be in the future.

.Related information

xref:../ilm/index.adoc[Manage objects with ILM]

xref:../tenant/index.adoc[Use a tenant account]

xref:put_object.adoc[PUT Object]

xref:put_object_copy.adoc[PUT Object - Copy]

xref:s3_rest_api_supported_operations_and_limitations.adoc[Initiate Multipart Upload]

xref:object_versioning.adoc[Object versioning]

xref:consistency_controls.adoc[Consistency controls]

xref:s3_operations_tracked_in_audit_logs.adoc[S3 operations tracked in the audit logs]

https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html[Amazon Simple Storage Service User Guide: Using S3 Object Lock]
