---
permalink: s3/operations_on_the_service.html
sidebar: sidebar
keywords: operations, service, operations on the service
summary: 'The StorageGRID system supports operations on the service.'
---
= Operations on the service
:icons: font
:imagesdir: ../media/

[.lead]
The StorageGRID system supports the following operations on the service.

[options="header"]
|===
| Operation| Implementation
a|
GET Service
a|
Implemented with all Amazon S3 REST API behavior.
a|
GET Storage Usage
a|
The GET Storage Usage request tells you the total amount of storage in use by an account, and for each bucket associated with the account. This is an operation on the service with a path of / and a custom query parameter (`?x-ntap-sg-usage`) added.
a|
OPTIONS /
a|
Client applications can issue `OPTIONS /` requests to the S3 port on a Storage Node, without providing S3 authentication credentials, to determine whether the Storage Node is available. You can use this request for monitoring, or to allow external load balancers to identify when a Storage Node is down.
|===
.Related information

xref:storagegrid_s3_rest_api_operations.adoc[GET Storage Usage request]
