---
permalink: s3/storagegrid-s3-rest-api-operations.html
sidebar: sidebar
keywords: S3 REST API, S3 operations
summary: 'There are operations added on to the S3 REST API that are specific to StorageGRID system.'
---
= StorageGRID S3 REST API operations
:icons: font
:imagesdir: ../media/

[.lead]
There are operations added on to the S3 REST API that are specific to StorageGRID system.

* xref:../s3/get-bucket-consistency-request.adoc[GET Bucket consistency request]

+
The GET Bucket consistency request allows you to determine the consistency level being applied to a particular bucket.

* xref:../s3/put-bucket-consistency-request.adoc[PUT Bucket consistency request]

+
The PUT Bucket consistency request allows you to specify the consistency level to apply to operations performed on a bucket.

* xref:../s3/get-bucket-last-access-time-request.adoc[GET Bucket last access time request]

+
The GET Bucket last access time request allows you to determine if last access time updates are enabled or disabled for individual buckets.

* xref:../s3/put-bucket-last-access-time-request.adoc[PUT Bucket last access time request]

+
The PUT Bucket last access time request allows you to enable or disable last access time updates for individual buckets. Disabling last access time updates improves performance, and is the default setting for all buckets created with version 10.3.0, or later.

* xref:../s3/delete-bucket-metadata-notification-configuration-request.adoc[DELETE Bucket metadata notification configuration request]

+
The DELETE Bucket metadata notification configuration request allows you to disable the search integration service for individual buckets by deleting the configuration XML.

* xref:../s3/get-bucket-metadata-notification-configuration-request.adoc[GET Bucket metadata notification configuration request]

+
The GET Bucket metadata notification configuration request allows you to retrieve the configuration XML used to configure search integration for individual buckets.

* xref:../s3/put-bucket-metadata-notification-configuration-request.adoc[PUT Bucket metadata notification configuration request]

+
The PUT Bucket metadata notification configuration request allows you to enable the search integration service for individual buckets. The metadata notification configuration XML that you supply in the request body specifies the objects whose metadata is sent to the destination search index.

* xref:../s3/get-storage-usage-request.adoc[GET Storage Usage request]

+
The GET Storage Usage request tells you the total amount of storage in use by an account, and for each bucket associated with the account.

The amount of storage used by an account and its buckets can be obtained by a modified GET Service request with the `x-ntap-sg-usage` query parameter. Bucket storage usage is tracked separately from the PUT and DELETE requests processed by the system. There might be some delay before the usage values match the expected values based on the processing of requests, particularly if the system is under heavy load.

By default, StorageGRID attempts to retrieve usage information using strong-global consistency. If strong-global consistency cannot be achieved, StorageGRID attempts to retrieve the usage information at a strong-site consistency.

You have the s3:ListAllMyBuckets permission, or be account root, to complete this operation.

=== Request example

[subs="specialcharacters,quotes"]
----
GET /?x-ntap-sg-usage HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----

=== Response example

This example shows an account that has four objects and 12 bytes of data in two buckets. Each bucket contains two objects and six bytes of data.

----
HTTP/1.1 200 OK
Date: Sat, 29 Nov 2015 00:49:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/10.2.0
x-amz-request-id: 727237123
Content-Length: 427
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<UsageResult xmlns="http://s3.storagegrid.com/doc/2015-02-01">
<CalculationTime>2014-11-19T05:30:11.000000Z</CalculationTime>
<ObjectCount>4</ObjectCount>
<DataBytes>12</DataBytes>
<Buckets>
<Bucket>
<Name>bucket1</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
<Bucket>
<Name>bucket2</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
</Buckets>
</UsageResult>
----

=== Versioning

Every object version stored will contribute to the `ObjectCount` and `DataBytes` values in the response. Delete markers are not added to the `ObjectCount` total.

.Related information

xref:consistency-controls.adoc[Consistency controls]

== Deprecated bucket requests for legacy Compliance

You might need to use the StorageGRID S3 REST API to manage buckets that were created using the legacy Compliance feature.

=== Compliance feature deprecated

The StorageGRID Compliance feature that was available in previous StorageGRID versions is deprecated and has been replaced by S3 Object Lock.

If you previously enabled the global Compliance setting, the global S3 Object Lock setting is enabled in StorageGRID 11.6. You can no longer create new buckets with Compliance enabled; however, as required, you can use the StorageGRID S3 REST API to manage any existing legacy Compliant buckets.

* xref:s3-rest-api-supported-operations-and-limitations.adoc[Use S3 Object Lock]

* xref:../ilm/index.adoc[Manage objects with ILM]

* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5[NetApp Knowledge Base: How to manage legacy Compliant buckets in StorageGRID 11.5]

[[deprecated-put-bucket-request-modifications-for-compliance]]
=== Deprecated: PUT Bucket with compliance settings

The SGCompliance XML element is deprecated. Previously, you could include this StorageGRID custom element in the optional XML request body of PUT Bucket requests to create a Compliant bucket.

IMPORTANT: The StorageGRID Compliance feature that was available in previous StorageGRID versions is deprecated and has been replaced by S3 Object Lock.

xref:s3-rest-api-supported-operations-and-limitations.adoc[Use S3 Object Lock]

xref:../ilm/index.adoc[Manage objects with ILM]

https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5[NetApp Knowledge Base: How to manage legacy Compliant buckets in StorageGRID 11.5]

You can no longer create new buckets with Compliance enabled. The following error message is returned if you attempt to use the PUT Bucket request modifications for compliance to create a new Compliant bucket:

----
The Compliance feature is deprecated.
Contact your StorageGRID administrator if you need to create new Compliant buckets.
----

.Related information

xref:../ilm/index.adoc[Manage objects with ILM]

xref:../tenant/index.adoc[Use tenant account]

[[deprecated-get-bucket-compliance-request]]
=== Deprecated: GET Bucket compliance request

The GET Bucket compliance request is deprecated. However, you can continue to use this request to determine the compliance settings currently in effect for an existing legacy Compliant bucket.

IMPORTANT: The StorageGRID Compliance feature that was available in previous StorageGRID versions is deprecated and has been replaced by S3 Object Lock.

xref:s3-rest-api-supported-operations-and-limitations.adoc[Use S3 Object Lock]

xref:../ilm/index.adoc[Manage objects with ILM]

https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5[NetApp Knowledge Base: How to manage legacy Compliant buckets in StorageGRID 11.5]

You have the s3:GetBucketCompliance permission, or be account root, to complete this operation.

==== Request example

This example request allows you to determine the compliance settings for the bucket named `mybucket`.

[subs="specialcharacters,quotes"]
----
GET /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----

==== Response example

In the response XML, `<SGCompliance>` lists the compliance settings in effect for the bucket. This example response shows the compliance settings for a bucket in which each object will be retained for one year (525,600 minutes), starting from when the object is ingested into the grid. There is currently no legal hold on this bucket. Each object will be automatically deleted after one year.

[subs="specialcharacters,quotes"]
----
HTTP/1.1 200 OK
Date: _date_
Connection: _connection_
Server: StorageGRID/11.1.0
x-amz-request-id: _request ID_
Content-Length: _length_
Content-Type: application/xml

<SGCompliance>
  <RetentionPeriodMinutes>525600</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----

[options="header"]
|===
| Name| Description
a|
RetentionPeriodMinutes
a|
The length of the retention period for objects added to this bucket, in minutes. The retention period starts when the object is ingested into the grid.
a|
LegalHold
a|

* True: This bucket is currently under a legal hold. Objects in this bucket cannot be deleted until the legal hold is lifted, even if their retention period has expired.
* False: This bucket is not currently under a legal hold. Objects in this bucket can be deleted when their retention period expires.

a|
AutoDelete
a|

* True: The objects in this bucket will be deleted automatically when their retention period expires, unless the bucket is under a legal hold.
* False: The objects in this bucket will not be deleted automatically when the retention period expires. You must delete these objects manually if you need to delete them.

|===

==== Error responses

If the bucket was not created to be compliant, the HTTP status code for the response is `404 Not Found`, with an S3 error code of `XNoSuchBucketCompliance`.

.Related information

xref:../ilm/index.adoc[Manage objects with ILM]

xref:../tenant/index.adoc[Use tenant account]

[[deprecated-put-bucket-compliance-request]]
=== Deprecated: PUT Bucket compliance request

The PUT Bucket compliance request is deprecated. However, you can continue to use this request to modify the compliance settings for an existing legacy Compliant bucket. For example, you can place an existing bucket on legal hold or increase its retention period.

IMPORTANT: The StorageGRID Compliance feature that was available in previous StorageGRID versions is deprecated and has been replaced by S3 Object Lock.

xref:s3-rest-api-supported-operations-and-limitations.adoc[Use S3 Object Lock]

xref:../ilm/index.adoc[Manage objects with ILM]

https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5[NetApp Knowledge Base: How to manage legacy Compliant buckets in StorageGRID 11.5]

You have the s3:PutBucketCompliance permission, or be account root, to complete this operation.

You must specify a value for every field of the compliance settings when issuing a PUT Bucket compliance request.

==== Request example

This example request modifies the compliance settings for the bucket named `mybucket`. In this example, objects in `mybucket` will now be retained for two years (1,051,200 minutes) instead of one year, starting from when the object is ingested into the grid. There is no legal hold on this bucket. Each object will be automatically deleted after two years.

[subs="specialcharacters,quotes"]
----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization name_
Host: _host_
Content-Length: 152

<SGCompliance>
  <RetentionPeriodMinutes>1051200</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----

[options="header"]
|===
| Name| Description
a|
RetentionPeriodMinutes
a|
The length of the retention period for objects added to this bucket, in minutes. The retention period starts when the object is ingested into the grid.

*Attention:* When specifying a new value for RetentionPeriodMinutes, you must specify a value that is equal to or greater than the bucket's current retention period. After the bucket's retention period is set, you cannot decrease that value; you can only increase it.

a|
LegalHold
a|

* True: This bucket is currently under a legal hold. Objects in this bucket cannot be deleted until the legal hold is lifted, even if their retention period has expired.
* False: This bucket is not currently under a legal hold. Objects in this bucket can be deleted when their retention period expires.

a|
AutoDelete
a|

* True: The objects in this bucket will be deleted automatically when their retention period expires, unless the bucket is under a legal hold.
* False: The objects in this bucket will not be deleted automatically when the retention period expires. You must delete these objects manually if you need to delete them.

|===

==== Consistency level for compliance settings

When you update the compliance settings for an S3 bucket with a PUT Bucket compliance request, StorageGRID attempts to update the bucket's metadata across the grid. By default, StorageGRID uses the *strong-global* consistency level to guarantee that all data center sites and all Storage Nodes that contain bucket metadata have read-after-write consistency for the changed compliance settings.

If StorageGRID cannot achieve the *strong-global* consistency level because a data center site or multiple Storage Nodes at a site are unavailable, the HTTP status code for the response is `503 Service Unavailable.`

If you receive this response, you must contact the grid administrator to ensure that the required storage services are made available as soon as possible. If the grid administrator is unable to make enough of the Storage Nodes at each site available, technical support might direct you to retry the failed request by forcing the *strong-site* consistency level.

IMPORTANT: Never force the *strong-site* consistency level for PUT bucket compliance unless you have been directed to do so by technical support and unless you understand the potential consequences of using this level.

When the consistency level is reduced to *strong-site*, StorageGRID guarantees that updated compliance settings will have read-after-write consistency only for client requests within a site. This means that the StorageGRID system might temporarily have multiple, inconsistent settings for this bucket until all sites and Storage Nodes are available. The inconsistent settings can result in unexpected and undesired behavior. For example, if you are placing a bucket under a legal hold and you force a lower consistency level, the bucket's previous compliance settings (that is, legal hold off) might continue to be in effect at some data center sites. As a result, objects that you think are on legal hold might be deleted when their retention period expires, either by the user or by AutoDelete, if enabled.

To force the use of the *strong-site* consistency level, reissue the PUT Bucket compliance request and include the `Consistency-Control` HTTP request header, as follows:

----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Consistency-Control: strong-site
----

==== Error responses

* If the bucket was not created to be compliant, the HTTP status code for the response is `404 Not Found`.
* If `RetentionPeriodMinutes` in the request is less than the bucket's current retention period, the HTTP status code is `400 Bad Request`.

.Related information

xref:storagegrid-s3-rest-api-operations.adoc[Deprecated: PUT Bucket request modifications for compliance]

xref:../tenant/index.adoc[Use tenant account]
