---
permalink: s3/use-s3-select.html
sidebar: sidebar
keywords: use S3 Select, S3 Select
summary: 'StorageGRID supports the following AWS S3 Select clauses, data types, operators, and reserved keywords for the SELECT Object content command.'
---
= Use S3 Select
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID supports the following AWS S3 Select clauses, data types, and operators for the xref:select-object-content.adoc[SelectObjectContent command].

NOTE: Any items not listed are not supported.

For syntax, see xref:select-object-content.adoc[SelectObjectContent]. For more information about S3 Select, see the https://docs.aws.amazon.com/AmazonS3/latest/userguide/selecting-content-from-objects.html[AWS documentation for S3 Select^].

Only tenant accounts that have S3 Select enabled can issue SelectObjectContent queries. See the xref:../admin/manage-s3-select-for-tenant-accounts.adoc[considerations and requirements for using S3 Select].

== Clauses

* SELECT list
* FROM clause
* WHERE clause
* LIMIT clause

== Data types

* bool
* integer
* string
* float
* decimal, numeric
* timestamp

== Operators

=== Logical operators

* AND
* NOT
* OR

=== Comparison operators

* <
* >
* &lt;=
* &gt;=
* =
* =
* <>
* !=
* BETWEEN
* IN

=== Pattern matching operators

* LIKE
* _
* %

=== Unitary operators

* IS NULL
* IS NOT NULL

=== Math operators

* +
* -
* *
* /
* %

StorageGRID follows the AWS S3 Select operator precedence.

== Aggregate functions

* AVG()
* COUNT(*)
* MAX()
* MIN()
* SUM()

== Conditional functions

* CASE
* COALESCE
* NULLIF

== Conversion functions

* CAST (for supported datatype)

== Date functions

* DATE_ADD
* DATE_DIFF
* EXTRACT
* TO_STRING
* TO_TIMESTAMP
* UTCNOW

== String functions

* CHAR_LENGTH, CHARACTER_LENGTH
* LOWER
* SUBSTRING
* TRIM
* UPPER