---
permalink: monitor/alarms-that-generate-snmp-notifications.html
sidebar: sidebar
keywords: alarms, monitor alarms, snmp notification, snmp
summary: 'The following table lists the legacy alarms that generate SNMP notifications. Unlike alerts, not all alarms generate SNMP notifications. Only the alarms listed generate SNMP notifications and only at the indicated severity or higher.'
---
= Alarms that generate SNMP notifications (legacy system)
:icons: font
:imagesdir: ../media/

[.lead]
The following table lists the legacy alarms that generate SNMP notifications. Unlike alerts, not all alarms generate SNMP notifications. Only the alarms listed generate SNMP notifications and only at the indicated severity or higher.

NOTE: While the legacy alarm system continues to be supported, the alert system offers significant benefits and is easier to use.

[options="header"]
|===
| Code| Name| Severity
a|
ACMS
a|
Available Metadata Services
a|
Critical
a|
AITE
a|
Retrieve State
a|
Minor
a|
AITU
a|
Retrieve Status
a|
Major
a|
AMQS
a|
Audit Messages Queued
a|
Notice
a|
AOTE
a|
Store State
a|
Minor
a|
AOTU
a|
Store Status
a|
Major
a|
AROQ
a|
Objects Queued
a|
Minor
a|
ARRF
a|
Request Failures
a|
Major
a|
ARRV
a|
Verification Failures
a|
Major
a|
ARVF
a|
Store Failures
a|
Major
a|
ASXP
a|
Audit Shares
a|
Minor
a|
AUMA
a|
AMS Status
a|
Minor
a|
AUXS
a|
Audit Export Status
a|
Minor
a|
BTOF
a|
Offset
a|
Notice
a|
CAHP
a|
Java Heap Usage Percent
a|
Major
a|
CAQH
a|
Number Available Destinations
a|
Notice
a|
CASA
a|
Data Store Status
a|
Major
a|
CDLP
a|
Metadata Used Space (Percent)
a|
Major
a|
CLBE
a|
CLB State
a|
Critical
a|
DNST
a|
DNS Status
a|
Critical
a|
ECST
a|
Verification Status
a|
Major
a|
HSTE
a|
HTTP State
a|
Major
a|
HTAS
a|
Auto-Start HTTP
a|
Notice
a|
LOST
a|
Lost Objects
a|
Major
a|
MINQ
a|
E-mail Notifications Queued
a|
Notice
a|
MINS
a|
E-mail Notifications Status
a|
Minor
a|
NANG
a|
Network Auto Negotiate Setting
a|
Notice
a|
NDUP
a|
Network Duplex Setting
a|
Minor
a|
NLNK
a|
Network Link Detect
a|
Minor
a|
NRER
a|
Receive Errors
a|
Notice
a|
NSPD
a|
Speed
a|
Notice
a|
NTER
a|
Transmit Errors
a|
Notice
a|
NTFQ
a|
NTP Frequency Offset
a|
Minor
a|
NTLK
a|
NTP Lock
a|
Minor
a|
NTOF
a|
NTP Time Offset
a|
Minor
a|
NTSJ
a|
Chosen Time Source Jitter
a|
Minor
a|
NTSU
a|
NTP Status
a|
Major
a|
OPST
a|
Overall Power Status
a|
Major
a|
ORSU
a|
Outbound Replication Status
a|
Notice
a|
PSAS
a|
Power Supply A Status
a|
Major
a|
PSBS
a|
Power Supply B Status
a|
Major
a|
RDTE
a|
Tivoli Storage Manager State
a|
Notice
a|
RDTU
a|
Tivoli Storage Manager Status
a|
Major
a|
SAVP
a|
Total Usable Space (Percent)
a|
Notice
a|
SHLH
a|
Health
a|
Notice
a|
SLSA
a|
CPU Load Average
a|
Notice
a|
SMTT
a|
Total Events
a|
Notice
a|
SNST
a|
Status
a|

a|
SOSS
a|
Storage Operating System Status
a|
Notice
a|
SSTS
a|
Storage Status
a|
Notice
a|
SVST
a|
Status
a|
Notice
a|
TMEM
a|
Installed Memory
a|
Minor
a|
UMEM
a|
Available Memory
a|
Minor
a|
VMST
a|
Status
a|
Minor
a|
VPRI
a|
Verification Priority
a|
Notice
a|
VSTU
a|
Object Verification Status
a|
Notice
|===
