---
permalink: monitor/applying-hotfixes-or-upgrading-software-if-necessary.html
sidebar: sidebar
keywords: hotfix, software upgrade, apply hotfix
summary: 'If a hotfix or a new version of StorageGRID software is available, you should assess whether the update is appropriate for your system, and install it if required.'
---
= Applying hotfixes or upgrading software if necessary
:icons: font
:imagesdir: ../media/

[.lead]
If a hotfix or a new version of StorageGRID software is available, you should assess whether the update is appropriate for your system, and install it if required.

.About this task
StorageGRID hotfixes contain software changes that are made available outside of a feature or patch release. The same changes are included in a future release.

.Steps
. Go to the NetApp Downloads page for StorageGRID.
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads: StorageGRID]

. Select the down arrow for the *Type/Select Version* field to see a list of the updates that are available to download:
 ** *StorageGRID software versions*: 11._x.y_
 ** *StorageGRID hotfixes*: 11._x.y.z_
. Review the changes that are included in the update:
 .. Select the version from the pull-down menu, and click *Go*.
 .. Sign in using the username and password for your NetApp account.
 .. Read the End User License Agreement, select the check box, and then select *Accept & Continue*.
+
The downloads page for the version you selected appears.
. Learn about the changes included in the software version or hotfix.
 ** For a new software version, see the "`What's new`" topic in the instructions for upgrading StorageGRID.
 ** For a hotfix, download the README file for a summary of the changes included in the hotfix.
. If you decide a software update is required, locate the instructions before proceeding.
 ** For a new software version, carefully follow the instructions for upgrading StorageGRID.
 ** For a hotfix, locate the hotfix procedure in the recovery and maintenance instructions

*Related information*

xref:../upgrade/index.adoc[Upgrade software]

xref:../maintain/index.adoc[Maintain & recover]
