---
permalink: monitor/commonly-used-prometheus-metrics.html
sidebar: sidebar
keywords: prometheus, Prometheus metrics, metrics
summary: 'The Prometheus service on Admin Nodes collects time series metrics from the services on all nodes. While Prometheus collects more than a thousand metrics, a relatively small number are required to monitor the most critical StorageGRID operations.'
---
= Commonly used Prometheus metrics
:icons: font
:imagesdir: ../media/

[.lead]
The Prometheus service on Admin Nodes collects time series metrics from the services on all nodes. While Prometheus collects more than a thousand metrics, a relatively small number are required to monitor the most critical StorageGRID operations.

Metrics are stored on each Admin Node until the space reserved for Prometheus data is full. When the `/var/local/mysql_ibdata/` volume reaches capacity, the oldest metrics are deleted first.

To obtain the complete list of metrics, use the Grid Management API.

. From the top of the Grid Manager, select the help icon and select *API Documentation*.
. Locate the *metrics* operations.
. Execute the `GET /grid/metric-names` operation.
. Download the results.

The following table lists the most commonly used Prometheus metrics. You can refer to this list to better understand the conditions in the default alert rules or to construct the conditions for custom alert rules. 

NOTE: Metrics that include _private_ in their names are intended for internal use only and are subject to change between StorageGRID releases without notice.



[options="header"]
|===
| Prometheus metric| Description
a|
alertmanager_notifications_failed_total
a|
The total number of failed alert notifications.
a|
node_filesystem_avail_bytes
a|
The amount of filesystem space available to non-root users in bytes.
a|
node_memory_MemAvailable_bytes
a|
Memory information field MemAvailable_bytes.
a|
node_network_carrier
a|
Carrier value of /sys/class/net/<iface>.
a|
node_network_receive_errs_total
a|
Network device statistic receive_errs.
a|
node_network_transmit_errs_total
a|
Network device statistic transmit_errs.
a|
storagegrid_administratively_down
a|
The node is not connected to the grid for an expected reason. For example, the node, or services on the node, has been gracefully shut down, the node is rebooting, or the software is being upgraded.
a|
storagegrid_appliance_compute_controller_hardware_status
a|
The status of the compute controller hardware in an appliance.
a|
storagegrid_appliance_failed_disks
a|
For the storage controller in an appliance, the number of drives that are not optimal.
a|
storagegrid_appliance_storage_controller_hardware_status
a|
The overall status of the storage controller hardware in an appliance.
a|
storagegrid_content_buckets_and_containers
a|
The total number of S3 buckets and Swift containers known by this Storage Node.
a|
storagegrid_content_objects
a|
The total number of S3 and Swift data objects known by this Storage Node. Count is valid only for data objects created by client applications that interface with the system through S3 or Swift.
a|
storagegrid_content_objects_lost
a|
The total number of objects this service detects as missing from the StorageGRID system. Action should be taken to determine the cause of the loss and if recovery is possible.

xref:troubleshooting-lost-and-missing-object-data.adoc[Troubleshoot lost and missing object data]

a|
storagegrid_http_sessions_incoming_attempted
a|
The total number of HTTP sessions that have been attempted to a Storage Node.
a|
storagegrid_http_sessions_incoming_currently_established
a|
The number of HTTP sessions that are currently active (open) on the Storage Node.
a|
storagegrid_http_sessions_incoming_failed
a|
The total number of HTTP sessions that failed to complete successfully, either due to a malformed HTTP request or a failure while processing an operation.
a|
storagegrid_http_sessions_incoming_successful
a|
The total number of HTTP sessions that have completed successfully.
a|
storagegrid_ilm_awaiting_background_objects
a|
The total number of objects on this node awaiting ILM evaluation from the scan.
a|
storagegrid_ilm_awaiting_client_evaluation_objects_per_second
a|
The current rate at which objects are evaluated against the ILM policy on this node.
a|
storagegrid_ilm_awaiting_client_objects
a|
The total number of objects on this node awaiting ILM evaluation from client operations (for example, ingest).
a|
storagegrid_ilm_awaiting_total_objects
a|
The total number of objects awaiting ILM evaluation.
a|
storagegrid_ilm_scan_objects_per_second
a|
The rate at which objects owned by this node are scanned and queued for ILM.
a|
storagegrid_ilm_scan_period_estimated_minutes
a|
The estimated time to complete a full ILM scan on this node.

*Note:* A full scan does not guarantee that ILM has been applied to all objects owned by this node.
a|
storagegrid_load_balancer_endpoint_cert_expiry_time
a|
The expiration time of the load balancer endpoint certificate in seconds since the epoch.
a|
storagegrid_metadata_queries_average_latency_milliseconds
a|
The average time required to run a query against the metadata store through this service.
a|
storagegrid_network_received_bytes
a|
The total amount of data received since installation.
a|
storagegrid_network_transmitted_bytes
a|
The total amount of data sent since installation.
a|
storagegrid_node_cpu_utilization_percentage
a|
The percentage of available CPU time currently being used by this service. Indicates how busy the service is. The amount of available CPU time depends on the number of CPUs for the server.
a|
storagegrid_ntp_chosen_time_source_offset_milliseconds
a|
Systematic offset of time provided by a chosen time source. Offset is introduced when the delay to reach a time source is not equal to the time required for the time source to reach the NTP client.
a|
storagegrid_ntp_locked
a|
The node is not locked to a network time protocol (NTP) server.
a|
storagegrid_s3_data_transfers_bytes_ingested
a|
The total amount of data ingested from S3 clients to this Storage Node since the attribute was last reset.
a|
storagegrid_s3_data_transfers_bytes_retrieved
a|
The total amount of data retrieved by S3 clients from this Storage Node since the attribute was last reset.
a|
storagegrid_s3_operations_failed
a|
The total number of failed S3 operations (HTTP status codes 4xx and 5xx), excluding those caused by S3 authorization failure.
a|
storagegrid_s3_operations_successful
a|
The total number of successful S3 operations (HTTP status code 2xx).
a|
storagegrid_s3_operations_unauthorized
a|
The total number of failed S3 operations that are the result of an authorization failure.
a|
storagegrid_servercertificate_management_interface_cert_expiry_days
a|
The number of days before the Management Interface certificate expires.
a|
storagegrid_servercertificate_storage_api_endpoints_cert_expiry_days
a|
The number of days before the Object Storage API certificate expires.
a|
storagegrid_service_cpu_seconds
a|
The cumulative amount of time that the CPU has been used by this service since installation.
a|
storagegrid_service_memory_usage_bytes
a|
The amount of memory (RAM) currently in use by this service. This value is identical to that displayed by the Linux top utility as RES.
a|
storagegrid_service_network_received_bytes
a|
The total amount of data received by this service since installation.
a|
storagegrid_service_network_transmitted_bytes
a|
The total amount of data sent by this service.
a|
storagegrid_service_restarts
a|
The total number of times the service has been restarted.
a|
storagegrid_service_runtime_seconds
a|
The total amount of time that the service has been running since installation.
a|
storagegrid_service_uptime_seconds
a|
The total amount of time the service has been running since it was last restarted.
a|
storagegrid_storage_state_current
a|
The current state of the storage services. Attribute values are:

* 10 = Offline
* 15 = Maintenance
* 20 = Read-only
* 30 = Online

a|
storagegrid_storage_status
a|
The current status of the storage services. Attribute values are:

* 0 = No Errors
* 10 = In Transition
* 20 = Insufficient Free Space
* 30 = Volume(s) Unavailable
* 40 = Error

a|
storagegrid_storage_utilization_metadata_bytes
a|
An estimate of the total size of replicated and erasure coded object data on the Storage Node.
a|
storagegrid_storage_utilization_metadata_allowed_bytes
a|
The total space on volume 0 of each Storage Node that is allowed for object metadata. This value is always less than the actual space reserved for metadata on a node, because a portion of the reserved space is required for essential database operations (such as compaction and repair) and future hardware and software upgrades.The allowed space for object metadata controls overall object capacity.

a|
storagegrid_storage_utilization_metadata_bytes
a|
The amount of object metadata on storage volume 0, in bytes.
// a|storagegrid_storage_utilization_metadata_reserved_bytes
// a|The total space on volume 0 of each Storage Node that is actually reserved for object metadata. For any given Storage Node, the actual reserved space for metadata depends on the size of volume 0 for the node and the system-wide Metadata Reserved Space setting.
a|
storagegrid_storage_utilization_total_space_bytes
a|
The total amount of storage space allocated to all object stores.
a|
storagegrid_storage_utilization_usable_space_bytes
a|
The total amount of object storage space remaining. Calculated by adding together the amount of available space for all object stores on the Storage Node.
a|
storagegrid_swift_data_transfers_bytes_ingested
a|
The total amount of data ingested from Swift clients to this Storage Node since the attribute was last reset.
a|
storagegrid_swift_data_transfers_bytes_retrieved
a|
The total amount of data retrieved by Swift clients from this Storage Node since the attribute was last reset.
a|
storagegrid_swift_operations_failed
a|
The total number of failed Swift operations (HTTP status codes 4xx and 5xx), excluding those caused by Swift authorization failure.
a|
storagegrid_swift_operations_successful
a|
The total number of successful Swift operations (HTTP status code 2xx).
a|
storagegrid_swift_operations_unauthorized
a|
The total number of failed Swift operations that are the result of an authorization failure (HTTP status codes 401, 403, 405).
a|
storagegrid_tenant_usage_data_bytes
a|
The logical size of all objects for the tenant.
a|
storagegrid_tenant_usage_object_count
a|
The number of objects for the tenant.
a|
storagegrid_tenant_usage_quota_bytes
a|
The maximum amount of logical space available for the tenant's objects. If a quota metric is not provided, an unlimited amount of space is available.
|===
