---
permalink: monitor/deployment-and-maintenance-logs.html
sidebar: sidebar
keywords: deployment, logs, Maintenance
summary: 'You can use the deployment and maintenance logs to troubleshoot issues.'
---
= Deployment and maintenance logs
:icons: font
:imagesdir: ../media/

[.lead]
You can use the deployment and maintenance logs to troubleshoot issues.

[options="header"]
|===
| File name| Notes| Found on
a|
`/var/local/log/install.log`
a|
Created during software installation. Contains a record of the installation events.
a|
All nodes
a|
`/var/local/log/expansion-progress.log`
a|
Created during expansion operations. Contains a record of the expansion events.
a|
Storage Nodes
a|
`/var/local/log/gdu-server.log`
a|
Created by the GDU service. Contains events related to provisioning and maintenance procedures managed by the primary Admin Node.
a|
Primary Admin Node
a|
`/var/local/log/send_admin_hw.log`
a|
Created during installation. Contains debugging information related to a node's communications with the primary Admin Node.
a|
All nodes
a|
`/var/local/log/upgrade.log`
a|
Created during software upgrade. Contains a record of the software update events.
a|
All nodes
|===
