---
permalink: monitor/disabling-alert-rules.html
sidebar: sidebar
keywords: how to disable alert rules, how to remove a custom alert rule
summary: 'You can change the enabled/disabled state for a default or custom alert rule.'
---
= Disable alert rules
:icons: font
:imagesdir: ../media/

[.lead]
You can change the enabled/disabled state for a default or custom alert rule.

.What you'll need
* You are signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You have the Manage Alerts or Root Access permission.

.About this task
When an alert rule is disabled, its expressions are not evaluated and no alerts are triggered.

IMPORTANT: In general, disabling a default alert rule is not recommended. If an alert rule is disabled, you might not detect an underlying problem until it prevents a critical operation from completing.

.Steps
. Select *ALERTS* > *Rules*.
+
The Alert Rules page appears.

. Select the radio button for the alert rule you want to disable or enable.
. Select *Edit rule*.
+
The Edit Rule dialog box appears.

. Select or unselect the *Enabled* check box to determine if this alert rule is currently enabled.
+
If an alert rule is disabled, its expressions are not evaluated and no alerts are triggered.
+
NOTE: If you disable the alert rule for a current alert, you must wait a few minutes for the alert to no longer display as an active alert.

. Select *Save*.
+
*Disabled* appears in the *Status* column.