---
permalink: monitor/generating-charts.html
sidebar: sidebar
keywords: charts, generating
summary: 'Charts display a graphical representation of attribute data values. You can report on a data center site, grid node, component, or service.'
---
= Generating charts
:icons: font
:imagesdir: ../media/

[.lead]
Charts display a graphical representation of attribute data values. You can report on a data center site, grid node, component, or service.

.What you'll need
* You must be signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You must have specific access permissions.

.Steps
. Select *Support* > *Tools* > *Grid Topology*.
. Select *_grid node_* > *_component or service_* > *Reports* > *Charts*.
. Select the attribute to report on from the *Attribute* drop-down list.
. To force the Y-axis to start at zero, deselect the *Vertical Scaling* check box.
. To show values at full precision, select the *Raw Data* check box, or to round values to a maximum of three decimal places (for example, for attributes reported as percentages), deselect the *Raw Data* check box.
. Select the time period to report on from the *Quick Query* drop-down list.
+
Select the Custom Query option to select a specific time range.
+
The chart appears after a few moments. Allow several minutes for tabulation of long time ranges.

. If you selected Custom Query, customize the time period for the chart by entering the *Start Date* and *End Date*.
+
Use the format `_YYYY/MM/DDHH:MM:SS_` in local time. Leading zeros are required to match the format. For example, 2017/4/6 7:30:00 fails validation. The correct format is: 2017/04/06 07:30:00.

. Click *Update*.
+
A chart is generated after a few moments. Allow several minutes for tabulation of long time ranges. Depending on the length of time set for the query, either a raw text report or aggregate text report is displayed.

. If you want to print the chart, right-click and select *Print*, and modify any necessary printer settings and click *Print*.
