---
permalink: monitor/generating_text_reports.html
sidebar: sidebar
keywords: 
summary: 'Text reports display a textual representation of attribute data values that have been processed by the NMS service. You can report on a data center site, grid node, component, or service.'
---
= Generating text reports
:icons: font
:imagesdir: ../media/

[.lead]
Text reports display a textual representation of attribute data values that have been processed by the NMS service. You can report on a data center site, grid node, component, or service.

* You must be signed in to the Grid Manager using a supported browser.
* You must have specific access permissions.

For attribute data that is expected to be continuously changing, this attribute data is sampled by the NMS service (at the source) at regular intervals. For attribute data that changes infrequently (for example, data based on events such as state or status changes), an attribute value is sent to the NMS service when the value changes.

The type of report displayed depends on the configured time period. By default, aggregate text reports are generated for time periods longer than one week.

Gray text indicates the service was administratively down during the time it was sampled. Blue text indicates the service was in an unknown state.

. Select *Support* > *Tools* > *Grid Topology*.
. Select *grid node* > *component or service* > *Reports* > *Text*.
. Select the attribute to report on from the *Attribute* drop-down list.
. Select the number of results per page from the *Results per Page* drop-down list.
. To round values to a maximum of three decimal places (for example, for attributes reported as percentages), unselect the *Raw Data* check box.
. Select the time period to report on from the *Quick Query* drop-down list.
+
Select the Custom Query option to select a specific time range.
+
The report appears after a few moments. Allow several minutes for tabulation of long time ranges.

. If you selected Custom Query, you need to customize the time period to report on by entering the *Start Date* and *End Date*.
+
Use the format YYYY/MM/DDHH:MM:SS in local time. Leading zeros are required to match the format. For example, 2017/4/6 7:30:00 fails validation. The correct format is: 2017/04/06 07:30:00.

. Click *Update*.
+
A text report is generated after a few moments. Allow several minutes for tabulation of long time ranges. Depending on the length of time set for the query, either a raw text report or aggregate text report is displayed.

. If you want to print the report, right-click and select *Print*, and modify any necessary printer settings and click *Print*.
