---
permalink: monitor/information-you-should-monitor-regularly.html
sidebar: sidebar
keywords: monitor, monitoring, StorageGRID,
summary: 'StorageGRID is a fault-tolerant, distributed storage system that is designed to continue operating even when errors occur, or when nodes or sites are unavailable. You must proactively monitor system health, workloads, and usage statistics so that you can take action to address potential issues before they affect the grid’s efficiency or availability.'
---
= Information you should monitor regularly
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID is a fault-tolerant, distributed storage system that is designed to continue operating even when errors occur, or when nodes or sites are unavailable. You must proactively monitor system health, workloads, and usage statistics so that you can take action to address potential issues before they affect the grid's efficiency or availability.

A busy system generates large amounts of information. This section provides guidance about the most important information to monitor on an ongoing basis. This section contains the following sub-sections:

* xref:monitoring-system-health.adoc[Monitoring system health]
* xref:monitoring-storage-capacity.adoc[Monitoring storage capacity]
* xref:monitoring-information-lifecycle-management.adoc[Monitoring information lifecycle management]
* xref:monitoring-performance-networking-and-system-resources.adoc[Monitoring performance, networking, and system resources]
* xref:monitoring-tenant-activity.adoc[Monitoring tenant activity]
* xref:monitoring-archival-capacity.adoc[Monitoring archival capacity]
* xref:monitoring-load-balancing-operations.adoc[Monitoring load balancing operations]
* xref:applying-hotfixes-or-upgrading-software-if-necessary.adoc[Applying hotfixes or upgrading software if necessary]

[options="header"]
|===
| What to monitor| Frequency
a|
The system health data shown on the Grid Manager DashboardNote if anything has changed from the previous day.

a|
Daily
a|
Rate at which Storage Node object and metadata capacity is being consumed
a|
Weekly
a|
Information lifecycle management operations
a|
Weekly
a|
Performance, networking, and system resources:

* Query latency
* Connectivity and networking
* Node-level resources

a|
Weekly
a|
Tenant activity
a|
Weekly
a|
Capacity of the external archival storage system
a|
Weekly
a|
Load balancing operations
a|
After the initial configuration and after any configuration changes
a|
Availability of software hotfixes and software upgrades
a|
Monthly
|===
