---
permalink: monitor/information-you-should-monitor-regularly.html
sidebar: sidebar
keywords: monitor, monitoring, StorageGRID,
summary: 'StorageGRID is a fault-tolerant, distributed storage system that is designed to continue operating even when errors occur, or when nodes or sites are unavailable. You must proactively monitor system health, workloads, and usage statistics so that you can take action to address potential issues before they affect the grid’s efficiency or availability.'
---
= Information you should monitor regularly
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID is a fault-tolerant, distributed storage system that is designed to continue operating even when errors occur, or when nodes or sites are unavailable. You must proactively monitor system health, workloads, and usage statistics so that you can take action to address potential issues before they affect the grid's efficiency or availability.

A busy system generates large amounts of information. This section provides guidance about the most important information to monitor on an ongoing basis.

[cols="2a,1a" options="header"]
|===
| What to monitor| Frequency

|The xref:monitoring-system-health.adoc[system health data] shown on the Grid Manager Dashboard. Note if anything has changed from the previous day.
|Daily

|Rate at which xref:monitoring-storage-capacity.adoc[Storage Node object and metadata capacity] is being consumed
|Weekly

|xref:monitoring-information-lifecycle-management.adoc[Information lifecycle management operations]
|Weekly

|xref:monitoring-performance-networking-and-system-resources.adoc[Performance, networking, and system resources]:

* Query latency
* Connectivity and networking
* Node-level resources
|Weekly

|xref:monitoring-tenant-activity.adoc[Tenant activity]
|Weekly

|xref:monitoring-archival-capacity.adoc[Capacity of the external archival storage system]
|Weekly

|xref:monitoring-load-balancing-operations.adoc[Load balancing operations]
|After the initial configuration and after any configuration changes

|xref:applying-hotfixes-or-upgrading-software-if-necessary.adoc[Availability of software hotfixes and software upgrades]
|Monthly
|===
