---
permalink: monitor/logs-for-third-party-software.html
sidebar: sidebar
keywords: troubleshooting, logs
summary: 'You can use the third-party software logs to troubleshoot issues.'
---
= Logs for third-party software
:icons: font
:imagesdir: ../media/

[.lead]
You can use the third-party software logs to troubleshoot issues.

[cols="1a,2a,3a,1a" options="header"]
|===
| Category| File name| Notes| Found on

|Archiving
m|/var/local/log/dsierror.log
|Error information for TSM Client APIs.
|Archive Nodes

|MySQL
m|
/var/local/log/mysql.err
/var/local/log/mysql-slow.log
|Log files generated by MySQL.

The file `mysql.err` captures database errors and events such as startups and shutdowns.

The file `mysql-slow.log` (the slow query log) captures the SQL statements that took more than 10 seconds to execute.
|Admin Nodes

|Operating system
m|/var/local/log/messages
|This directory contains log files for the operating system. The errors contained in these logs are also displayed in the Grid Manager. Select *SUPPORT* > *Tools* > *Grid topology*. Then select *Topology* > *_Site_* > *_Node_* > *SSM* > *Events*.
|All nodes

|NTP
m|
/var/local/log/ntp.log
/var/lib/ntp/var/log/ntpstats/
|
`/var/local/log/ntp.log` contains the log file for NTP error messages.

The `/var/lib/ntp/var/log/ntpstats/` directory contains NTP timing statistics.

`loopstats` records loop filter statistics information.

`peerstats` records peer statistics information.
|All nodes

|Samba
m|/var/local/log/samba/
|The Samba log directory includes a log file for each Samba process (smb, nmb, and winbind) and every client hostname/IP.
|Admin Node configured to export the audit share over CIFS
|===
