---
permalink: monitor/monitoring-storage-capacity.html
sidebar: sidebar
keywords: 
summary: 'You must monitor the total usable space available on Storage Nodes to ensure that the StorageGRID system does not run out of storage space for objects or for object metadata.'
---
= Monitoring storage capacity
:icons: font
:imagesdir: ../media/

[.lead]
You must monitor the total usable space available on Storage Nodes to ensure that the StorageGRID system does not run out of storage space for objects or for object metadata.

StorageGRID stores object data and object metadata separately, and reserves a specific amount of space for a distributed Cassandra database that contains object metadata. Monitor the total amount of space consumed for objects and for object metadata, as well as trends in the amount of space consumed for each. This will enable you to plan ahead for the addition of nodes and avoid any service outages.

You can view storage capacity information for the entire grid, for each site, and for each Storage Node in your StorageGRID system.

.Related information

xref:viewing-storage-tab.adoc[Viewing the Storage tab]
