---
permalink: monitor/monitoring-load-balancing-operations.html
sidebar: sidebar
keywords: load balancing, monitoring
summary: 'If you are using a load balancer to manage client connections to StorageGRID, you should monitor load balancing operations after you configure the system initially and after you make any configuration changes or perform an expansion.'
---
= Monitor load balancing operations
:icons: font
:imagesdir: ../media/

[.lead]
If you are using a load balancer to manage client connections to StorageGRID, you should monitor load balancing operations after you configure the system initially and after you make any configuration changes or perform an expansion.

.What you'll need
* You must be signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You must have specific access permissions.

.About this task
You can use the Load Balancer service on Admin Nodes or Gateway Nodes, an external third-party load balancer, or the CLB service on Gateway Nodes to distribute client requests across multiple Storage Nodes.

NOTE: The CLB service is deprecated.

After configuring load balancing, you should confirm that object ingest and retrieval operations are being evenly distributed across Storage Nodes. Evenly distributed requests ensure that StorageGRID remains responsive to client requests under load and can help maintain client performance.

If you configured a high availability (HA) group of Gateway Nodes or Admin Nodes in active-backup mode, only one node in the group actively distributes client requests.

See the section on configuring client connections in the instructions for administering StorageGRID.

.Steps
. If S3 or Swift clients connect using the Load Balancer service, check that Admin Nodes or Gateway Nodes are actively distributing traffic as you expect:
 .. Select *NODES*.
 .. Select a Gateway Node or Admin Node.
 .. On the *Overview* tab, check if a node interface is in an HA group and if the node interface has the role of Master.
+
Nodes with the role of Master and nodes that are not in an HA group should be actively distributing requests to clients.

 .. For each node that should be actively distributing client requests, select the *Load Balancer* tab.
 .. Review the chart of Load Balancer Request Traffic for the last week to ensure that the node has been actively distributing requests.
+
Nodes in an active-backup HA group might take the Backup role from time to time. During that time the nodes do not distribute client requests.

 .. Review the chart of Load Balancer Incoming Request Rate for the last week to review the object throughput of the node.
 .. Repeat these steps for each Admin Node or Gateway Node in the StorageGRID system.
 .. Optionally, use traffic classification policies to view a more detailed breakdown of traffic being served by the Load Balancer service.
. If S3 or Swift clients connect using the CLB service (deprecated), perform the following checks:
 .. Select *NODES*.
 .. Select a Gateway Node.
 .. On the *Overview* tab, check if a node interface is in an HA group, and if the node interface has the role of Master.
+
Nodes with the role of Master and nodes that are not in an HA group should be actively distributing requests to clients.

 .. For each Gateway Node that should be actively distributing client requests, select *SUPPORT* > *Tools* > *Grid topology*.
 .. Select *_Gateway Node_* > *CLB* > *HTTP* > *Overview* > *Main*.
 .. Review the number of *Incoming Sessions - Established* to verify that the Gateway Node has been actively handling requests.
. Verify that these requests are being evenly distributed to Storage Nodes.
 .. Select *_Storage Node_* > *LDR* > *HTTP*.
 .. Review the number of *Currently Established incoming Sessions*.
 .. Repeat for each Storage Node in the grid.
+
The number of sessions should be roughly equal across all Storage Nodes.

.Related information

xref:../admin/index.adoc[Administer StorageGRID]

xref:viewing-load-balancer-tab.adoc[View the Load Balancer tab]
