---
permalink: monitor/monitoring-put-and-get-performance.html
sidebar: sidebar
keywords: put, get, performance
summary: 'You can monitor the performance of certain operations, such as object store and retrieve, to help identify changes that might require further investigation.'
---
= Monitoring PUT and GET performance
:icons: font
:imagesdir: ../media/

[.lead]
You can monitor the performance of certain operations, such as object store and retrieve, to help identify changes that might require further investigation.

.About this task
To monitor PUT and GET performance, you can run S3 and Swift commands directly from a workstation or by using the open-source S3tester application. Using these methods allows you to assess performance independently of factors that are external to StorageGRID, such as issues with a client application or issues with an external network.

When performing tests of PUT and GET operations, use the following guidelines:

* Use object sizes comparable to the objects that you typically ingest into your grid.
* Perform operations against both local and remote sites.

Messages in the audit log indicate the total time required to run certain operations. For example, to determine the total processing time for an S3 GET request, you can review the value of the TIME attribute in the SGET audit message. You can also find the TIME attribute in the audit messages for the following operations:

* *S3*: DELETE, GET, HEAD, Metadata Updated, POST, PUT
* *Swift*: DELETE, GET, HEAD, PUT

When analyzing results, look at the average time required to satisfy a request, as well as the overall throughput that you can achieve. Repeat the same tests regularly and record the results, so that you can identify trends that may require investigation.

* You can download S3tester from github:https://github.com/s3tester

.Related information

xref:../audit/index.adoc[Review audit logs]
