---
permalink: monitor/reference_logs_for_third_party_software.html
sidebar: sidebar
keywords: 
summary: 'You can use the third-party software logs to troubleshoot issues.'
---
= Logs for third-party software
:icons: font
:imagesdir: ../media/

[.lead]
You can use the third-party software logs to troubleshoot issues.

|===
| Category| File name| Notes| Found on
a|
apache2 logs
a|
/var/local/log/apache2/access.log /var/local/log/apache2/error.log

/var/local/log/apache2/other_vhosts_access.log

a|
Log files for apache2.
a|
Admin Nodes
a|
Archiving
a|
/var/local/log/dsierror.log
a|
Error information for TSM Client APIs.
a|
Archive Nodes
a|
MySQL
a|
/var/local/log/mysql.err /var/local/log/mysql-slow.log

a|
Log files generated by MySQL.

The file mysql.err captures database errors and events such as startups and shutdowns.

The file mysql-slow.log (the slow query log) captures the SQL statements that took more than 10 seconds to execute.

a|
Admin Nodes
a|
Operating system
a|
/var/local/log/messages
a|
This directory contains log files for the operating system. The errors contained in these logs are also displayed in the Grid Manager. Select *Support* > *Tools* > *Grid Topology*. Then select *Topology* > *Site* > *Node* > *SSM* > *Events*.
a|
All nodes
a|
NTP
a|
/var/local/log/ntp.log
a|
Log file for NTP error messages.
a|
All nodes
a|
/var/lib/ntp/var/log/ntpstats/
a|
The directory that contains NTP timing statistics.

loopstats records loop filter statistics information.

peerstats records peer statistics information.

a|
Samba
a|
/var/local/log/samba/
a|
The Samba log directory includes a log file for each Samba process (smb, nmb, and winbind) and every client hostname/IP.
a|
Admin Node configured to export the audit share over CIFS
|===
