---
permalink: monitor/reviewing-audit-messages.html
sidebar: sidebar
keywords: 
summary: 'Audit messages can help you get a better understanding of the detailed operations of your StorageGRID system. You can use audit logs to troubleshoot issues and to evaluate performance.'
---
= Reviewing audit messages
:icons: font
:imagesdir: ../media/

[.lead]
Audit messages can help you get a better understanding of the detailed operations of your StorageGRID system. You can use audit logs to troubleshoot issues and to evaluate performance.

During normal system operation, all StorageGRID services generate audit messages, as follows:

* System audit messages are related to the auditing system itself, grid node states, system-wide task activity, and service backup operations.
* Object storage audit messages are related to the storage and management of objects within StorageGRID, including object storage and retrievals, grid-node to grid-node transfers, and verifications.
* Client read and write audit messages are logged when an S3 or Swift client application makes a request to create, modify, or retrieve an object.
* Management audit messages log user requests to the Management API.

Each Admin Node stores audit messages in text files. The audit share contains the active file (audit.log) as well as compressed audit logs from previous days.

For easy access to audit logs, you can configure client access to the audit share for both NFS and CIFS (deprecated). You can also access audit log files directly from the command line of the Admin Node.

For details on the audit log file, the format of audit messages, the types of audit messages, and the tools available to analyze audit messages, see the instructions for audit messages. To learn how to configure audit client access, see the instructions for administering StorageGRID.

.Related information

xref:../audit/index.adoc[Review audit logs]

xref:../admin/index.adoc[Administer StorageGRID]
