---
permalink: monitor/troubleshooting-delivery-platform-services-messages.html
sidebar: sidebar
keywords:
summary: 'The Total Events (SMTT) alarm is triggered in the Grid Manager if a platform service message is delivered to an destination that cannot accept the data.'
---

= Troubleshooting delivery of platform services messages (SMTT alarm)
:experimental:
:icons: font
:imagesdir: ../media/


[.lead]
The Total Events (SMTT) alarm is triggered in the Grid Manager if a platform service message is delivered to an destination that cannot accept the data.

.About this task
For example, an S3 multipart upload can succeed even though the associated replication or notification message cannot be delivered to the configured endpoint. Or, a message for CloudMirror replication can fail to be delivered if the metadata is too long.

The SMTT alarm contains a Last Event message that says, `Failed to publish notifications for _bucket-name object key_` for the last object whose notification failed.

For additional information about troubleshooting platform services, see the instructions for administering StorageGRID. You might need to access the tenant from the Tenant Manager to debug a platform service error.

.Steps
. To view the alarm, select *Nodes* > *_site_* > *_grid node_* > *Events*.
. View Last Event at the top of the table.
+
Event messages are also listed in `/var/local/log/bycast-err.log`.

. Follow the guidance provided in the SMTT alarm contents to correct the issue.
. Click *Reset event counts*.
. Notify the tenant of the objects whose platform services messages have not been delivered.
. Instruct the tenant to trigger the failed replication or notification by updating the object's metadata or tags.

.Related information

xref:../admin/index.adoc[Administer StorageGRID]

xref:../tenant/index.adoc[Use a tenant account]

xref:logs-files-reference.adoc[Log files reference]

xref:resetting-event-counts.adoc[Resetting event counts]
