---
permalink: monitor/using-task-tab-to-reboot-grid-node.html
sidebar: sidebar
keywords: task tab
summary: 'The Task tab allows you to reboot the selected node. The Task tab is shown for all nodes.'
---
= Use the Task tab to reboot a grid node
:icons: font
:imagesdir: ../media/

[.lead]
The Task tab allows you to reboot the selected node. The Task tab is shown for all nodes.

.What you'll need
* You are signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You have the Maintenance or Root access permission.
* You have the provisioning passphrase.

.About this task
You can use the Task tab to reboot a node. For appliance nodes, you can also use the Task tab to place the appliance into maintenance mode.

* Rebooting a grid node from the Task tab issues the reboot command on the target node. When you reboot a node, the node shuts down and restarts. All services are restarted automatically.
+
If you plan to reboot a Storage Node, note the following:

 ** If an ILM rule specifies an ingest behavior of Dual commit or the rule specifies Balanced and it is not possible to immediately create all required copies, StorageGRID immediately commits any newly ingested objects to two Storage Nodes on the same site and evaluates ILM later. If you want to reboot two or more Storage Nodes on a given site, you might not be able to access these objects for the duration of the reboot.
 ** To ensure you can access all objects while a Storage Node is rebooting, stop ingesting objects at a site for approximately one hour before rebooting the node.

* You might need to put a StorageGRID appliance into maintenance mode to perform certain procedures, such as changing the link configuration or replacing a storage controller. For instructions, see the hardware installation and maintenance instructions for the appliance.
+
NOTE: In rare instances, placing a StorageGRID appliance into maintenance mode might make the appliance unavailable for remote access.

include::../_include/rebooting-grid-node-from-grid-manager-steps.adoc[] 

.Related information

xref:../sg6000/index.adoc[SG6000 storage appliances]

xref:../sg5700/index.adoc[SG5700 storage appliances]

xref:../sg5600/index.adoc[SG5600 storage appliances]

xref:../sg100-1000/index.adoc[SG100 and SG1000 services appliances]
