---
permalink: monitor/using-snmp-monitoring.html
sidebar: sidebar
keywords: snmp, monitoring
summary: 'If you want to monitor StorageGRID using the Simple Network Management Protocol \(SNMP\), you must configure the SNMP agent that is included with StorageGRID.'
---
= Using SNMP monitoring
:icons: font
:imagesdir: ../media/

[.lead]
If you want to monitor StorageGRID using the Simple Network Management Protocol (SNMP), you must configure the SNMP agent that is included with StorageGRID.

* xref:configuring-snmp-agent.adoc[Configuring the SNMP agent]
* xref:updating-snmp-agent.adoc[Updating the SNMP agent]

== Capabilities

Each StorageGRID node runs an SNMP agent, or daemon, that provides a management information base (MIB). The StorageGRID MIB contains table and notification definitions for alerts and alarms. The MIB also contains system description information such as platform and model number for each node. Each StorageGRID node also supports a subset of MIB-II objects.

Initially, SNMP is disabled on all nodes. When you configure the SNMP agent, all StorageGRID nodes receive the same configuration.

The StorageGRID SNMP agent supports all three versions of the SNMP protocol. It provides read-only MIB access for queries, and it can send two types of event-driven notifications to a management system:

* *Traps* are notifications sent by the SNMP agent that do not require acknowledgment by the management system. Traps serve to notify the management system that something has happened within StorageGRID, such as an alert being triggered.
+
Traps are supported in all three versions of SNMP.

* *Informs* are similar to traps, but they require acknowledgment by the management system. If the SNMP agent does not receive an acknowledgment within a certain amount of time, it resends the inform until an acknowledgment is received or the maximum retry value has been reached.
+
Informs are supported in SNMPv2c and SNMPv3.

Trap and inform notifications are sent in the following cases:

* A default or custom alert is triggered at any severity level. To suppress SNMP notifications for an alert, you must configure a silence for the alert. Alert notifications are sent by whichever Admin Node is configured to be the preferred sender.
* Certain alarms (legacy system) are triggered at specified severity levels or higher.
+
NOTE: SNMP notifications are not sent for every alarm or every alarm severity.

== SNMP version support

The table provides a high-level summary of what is supported for each SNMP version.

[options="header"]
|===
|  | SNMPv1| SNMPv2c| SNMPv3
a|
Queries
a|
Read-only MIB queries
a|
Read-only MIB queries
a|
Read-only MIB queries
a|
Query authentication
a|
Community string
a|
Community string
a|
User-based Security Model (USM) user
a|
Notifications
a|
Traps only
a|
Traps and informs
a|
Traps and informs
a|
Notification authentication
a|
Default trap community or a custom community string for each trap destination
a|
Default trap community or a custom community string for each trap destination
a|
USM user for each trap destination
|===

== Limitations

* StorageGRID supports read-only MIB access. Read-write access is not supported.
* All nodes in the grid receive the same configuration.
* SNMPv3: StorageGRID does not support the Transport Support Mode (TSM).
* SNMPv3: The only authentication protocol supported is SHA (HMAC-SHA-96).
* SNMPv3: The only privacy protocol supported is AES.

== Accessing the MIB

You can access the MIB definition file at the following location on any StorageGRID node:

/usr/share/snmp/mibs/NETAPP-STORAGEGRID-MIB.txt

.Related information

xref:alerts-reference.adoc[Alerts reference]

xref:alarms-reference.adoc[Alarms reference (legacy system)]

xref:alarms-that-generate-snmp-notifications.adoc[Alarms that generate SNMP notifications (legacy system)]

xref:managing-alerts.adoc[Silencing alert notifications]
