---
permalink: maintain/adding_donotstart_file_for_service.html
sidebar: sidebar
keywords:
summary: 'You can prevent an individual service from starting by adding a DoNotStart file to that service’s directory on a grid node.'
---
= Adding a DoNotStart file for a service
:icons: font
:imagesdir: ../media/

[.lead]
You can prevent an individual service from starting by adding a DoNotStart file to that service's directory on a grid node.

.What you'll need

You must have the `Passwords.txt` file.

.Steps

. Log in to the grid node:
 .. Enter the following command: `ssh admin@_grid_node_IP_`
 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.

+
When you are logged in as root, the prompt changes from `$` to `#`.
. Add a DoNotStart file: `touch /etc/sv/_service_/DoNotStart`
+
where `service` is the name of the service to be prevented from starting. For example,
+
----
touch /etc/sv/ldr/DoNotStart
----
+
A DoNotStart file is created. No file content is needed.
+
When Server Manager or the grid node is restarted, Server Manager restarts, but the service does not.

. Log out of the command shell: `exit`
