---
permalink: maintain/all-node-types-replacing-linux-node.html
sidebar: sidebar
keywords:
summary: 'If a failure requires that you deploy one or more new physical or virtual hosts or reinstall Linux on an existing host, you must deploy and configure the replacement host before you can recover the grid node. This procedure is one step of the grid node recovery process for all types of grid nodes.'
---
= All grid node types: Replacing a Linux node
:icons: font
:imagesdir: ../media/

[.lead]
If a failure requires that you deploy one or more new physical or virtual hosts or reinstall Linux on an existing host, you must deploy and configure the replacement host before you can recover the grid node. This procedure is one step of the grid node recovery process for all types of grid nodes.

"`Linux`" refers to a Red Hat速 Enterprise Linux速, Ubuntu速, CentOS, or Debian速 deployment. Use the NetApp Interoperability Matrix Tool to get a list of supported versions.

This procedure is only performed as one step in the process of recovering software-based Storage Nodes, primary or non-primary Admin Nodes, Gateway Nodes, or Archive Nodes. The steps are identical regardless of the type of grid node you are recovering.

If more than one grid node is hosted on a physical or virtual Linux host, you can recover the grid nodes in any order. However, recovering a primary Admin Node first, if present, prevents the recovery of other grid nodes from stalling as they try to contact the primary Admin Node to register for recovery.

. xref:deploying-new-linux-hosts.adoc[Deploying new Linux hosts]
. xref:restoring-existing-nodes.adoc[Restoring grid nodes to the host]
. link:whats_next_performing_additional_recovery_steps_if_required.adoc[What's next: Performing additional recovery steps, if required]

.Related information

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
