---
permalink: maintain/all_node_types_replacing_vmware_node.html
sidebar: sidebar
keywords: 
summary: 'When you recover a failed StorageGRID node that was hosted on VMware, you must remove the failed node and deploy a recovery node.'
---
= All grid node types: Replacing a VMware node
:icons: font
:imagesdir: ../media/

[.lead]
When you recover a failed StorageGRID node that was hosted on VMware, you must remove the failed node and deploy a recovery node.

You must have determined that the virtual machine cannot be restored, and must be replaced.

You use the VMware vSphere Web Client to first remove the virtual machine associated with the failed grid node. Then, you can deploy a new virtual machine.

This procedure is only one step in the grid node recovery process. The node removal and deployment procedure is the same for all VMware nodes, including Admin Nodes, Storage Nodes, Gateway Nodes, and Archive Nodes.

. Log in to VMware vSphere Web Client.
. Navigate to the failed grid node virtual machine.
. Make a note of all of the information required to deploy the recovery node.
 .. Right-click the virtual machine, select the *Edit Settings* tab, and note the settings in use.
 .. Select the *vApp Options* tab to view and record the grid node network settings.
. If the failed grid node is a Storage Node, determine if any of the virtual hard disks used for data storage are undamaged and preserve them for reattachment to the recovered grid node.
. Power off the virtual machine.
. Select *Actions* > *All vCenter Actions* > *Delete from Disk* to delete the virtual machine.
. Deploy a new virtual machine to be the replacement node, and connect it to one or more StorageGRID networks.
+
When you deploy the node, you can optionally remap node ports or increase CPU or memory settings.
+
NOTE: After deploying the new node, you can add new virtual disks according to your storage requirements, reattach any virtual hard disks preserved from the previously removed failed grid node, or both.
+
For instructions:
+
http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-install-vmw/home.html[VMware installation] > Deploying a StorageGRID node as a virtual machine

. Complete the node recovery procedure, based on the type of node you are recovering.
+
|===
| Type of node| Go to
a|
Primary Admin Node
a|
xref:configuring_replacement_primary_admin_node.adoc[Configuring the replacement primary Admin Node]
a|
Non-primary Admin Node
a|
xref:selecting_start_recovery_to_configure_non_primary_admin_node.adoc[Selecting Start Recovery to configure a non-primary Admin Node]
a|
Gateway Node
a|
xref:selecting_start_recovery_to_configure_gateway_node.adoc[Selecting Start Recovery to configure a Gateway Node]
a|
Storage Node
a|
xref:selecting_start_recovery_to_configure_storage_node.adoc[Selecting Start Recovery to configure a Storage Node]
a|
Archive Node
a|
link:selecting_start_recovery_to_configure_archive_node.md#[Selecting Start Recovery to configure an Archive Node]
|===
