---
permalink: maintain/checking-storage-state-after-recovering-sga.html
sidebar: sidebar
keywords: storagegrid, recovery, node recovery, storage state
summary: 'After recovering an appliance Storage Node, you must verify that the desired state of the appliance Storage Node is set to online and ensure that the state will be online by default whenever the Storage Node server is restarted.'
---
= Check storage state after recovering appliance Storage Node
:icons: font
:imagesdir: ../media/

[.lead]
After recovering an appliance Storage Node, you must verify that the desired state of the appliance Storage Node is set to online and ensure that the state will be online by default whenever the Storage Node server is restarted.

.What you'll need

* You must be signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* The Storage Node has been recovered, and data recovery is complete.

.Steps

. Select *SUPPORT* > *Tools* > *Grid topology*.
. Check the values of *Recovered Storage Node* > *LDR* > *Storage* > *Storage State -- Desired* and *Storage State -- Current*.
+
The value of both attributes should be Online.

. If the Storage State -- Desired is set to Read-only, complete the following steps:
 .. Click the *Configuration* tab.
 .. From the *Storage State -- Desired* drop-down list, select *Online*.
 .. Click *Apply Changes*.
 .. Click the *Overview* tab and confirm that the values of *Storage State -- Desired* and *Storage State -- Current* are updated to Online.
