---
permalink: maintain/concept_selecting_a_node_recovery_procedure.html
sidebar: sidebar
keywords: 
summary: 'You must select the correct recovery procedure for the type of node that has failed.'
---
= Selecting a node recovery procedure
:icons: font
:imagesdir: ../media/

[.lead]
You must select the correct recovery procedure for the type of node that has failed.

|===
| Grid node| Recovery procedure
a|
More than one Storage Node
a|
Contact technical support. If more than one Storage Node has failed, technical support must assist with recovery to prevent database inconsistencies that could lead to data loss. A site recovery procedure might be required.

xref:concept_how_site_recovery_is_performed_by_technical_support.adoc[How site recovery is performed by technical support].

a|
A single Storage Node
a|
The Storage Node recovery procedure depends on the type and duration of the failure.xref:concept_recovering_from_storage_node_failures.adoc[Recovering from Storage Node failures]

a|
Admin Node
a|
The Admin Node procedure depends on whether you need to recover the primary Admin Node or a non-primary Admin Node.xref:task_recovering_from_admin_node_failures.adoc[Recovering from Admin Node failures]

a|
Gateway Node
a|
xref:task_recovering_from_gateway_node_failures.adoc[Recovering from Gateway Node failures].
a|
Archive Node
a|
xref:task_recovering_from_archive_node_failures.adoc[Recovering from Archive Node failures].
|===
*Note:* If a server that is hosting more than one grid node fails, you can recover the nodes in any order. However, if the failed server is hosting the primary Admin Node, you must recover that node first. Recovering the primary Admin Node first prevents other node recoveries from halting as they wait to contact the primary Admin Node.
