---
permalink: maintain/configuring-ip-addresses.html
sidebar: sidebar
keywords: storagegrid, ip address, configure ip address, configuring ip address, network configuration, network configure, network configuring
summary: 'You can perform network configuration by configuring IP addresses for grid nodes using the Change IP tool.'
---
= Configure IP addresses
:icons: font
:imagesdir: ../media/

[.lead]
You can perform network configuration by configuring IP addresses for grid nodes using the Change IP tool.

You must use the Change IP tool to make most changes to the networking configuration that was initially set during grid deployment. Manual changes using standard Linux networking commands and files might not propagate to all StorageGRID services, and might not persist across upgrades, reboots, or node recovery procedures.

NOTE: If you want to change the Grid Network IP address for all nodes in the grid, use the xref:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.adoc[special procedure for grid-wide changes].

NOTE: If you are making changes to the Grid Network Subnet List only, use the Grid Manager to add or change the network configuration. Otherwise, use the Change IP tool if the Grid Manager is inaccessible due to a network configuration issue, or you are performing both a Grid Network routing change and other network changes at the same time.

IMPORTANT: The IP change procedure can be a disruptive procedure. Parts of the grid might be unavailable until the new configuration is applied.

*Ethernet interfaces*

The IP address assigned to eth0 is always the grid node's Grid Network IP address. The IP address assigned to eth1 is always the grid node's Admin Network IP address. The IP address assigned to eth2 is always the grid node's Client Network IP address.

Note that on some platforms, such as StorageGRID appliances, eth0, eth1, and eth2 might be aggregate interfaces composed of subordinate bridges or bonds of physical or VLAN interfaces. On these platforms, the *SSM* > *Resources* tab might show the Grid, Admin, and Client Network IP address assigned to other interfaces in addition to eth0, eth1, or eth2.

*DHCP*

You can only set up DHCP during the deployment phase. You cannot set up DHCP during configuration. You must use the IP address change procedures if you want to change IP addresses, subnet masks, and default gateways for a grid node. Using the Change IP tool will cause DHCP addresses to become static.

*High availability (HA) groups*

* If a Client network interface is contained in an HA group, you cannot change the Client network IP address for that interface to an address that is outside of the subnet configured for the HA group.
* You cannot change the Client Network IP address to the value of an existing virtual IP address assigned to an HA group configured on the Client Network interface.
* If a Grid network interface is contained in an HA group, you cannot change the Grid network IP address for that interface to an address that is outside of the subnet configured for the HA group.
* You cannot change the Grid Network IP address to the value of an existing virtual IP address assigned to an HA group configured on the Grid Network interface.
