---
permalink: maintain/configuring-dns-servers.html
sidebar: sidebar
keywords: storagegrid, dns, configuring dns, configure dns, domain name system
summary: 'You can add, remove, and update domain name system \(DNS\) servers, so that you can use fully qualified domain name \(FQDN\) hostnames rather than IP addresses.'
---
= Configure DNS servers
:icons: font
:imagesdir: ../media/

[.lead]
You can add, remove, and update domain name system (DNS) servers, so that you can use fully qualified domain name (FQDN) hostnames rather than IP addresses.

.What you'll need

* You must be signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You must have the Maintenance or Root Access permission.
* You must have the IP addresses of the DNS servers to configure.

Specifying DNS server information allows you to use fully qualified domain name (FQDN) hostnames rather than IP addresses for email or SNMP notifications and AutoSupport. Specifying at least two DNS servers is recommended.

IMPORTANT: Provide between two to six IP addresses for DNS servers. In general, select DNS servers that each site can access locally in the event of network islanding. This is to ensure an islanded site continues to have access to the DNS service. After configuring the grid-wide DNS server list, you can xref:modifying-dns-configuration-for-single-grid-node.adoc[further customize the DNS server list for each node].

If the DNS server information is omitted or incorrectly configured, a DNST alarm is triggered on each grid node's SSM service. The alarm clears when DNS is configured correctly and the new server information has reached all grid nodes.

.Steps

. Select *MAINTENANCE* > *Network* > *DNS servers*.
. In the Servers section, add update, or remove DNS server entries, as necessary.
+
The best practice is to specify at least two DNS servers per site. You can specify up to six DNS servers.

. Click *Save*.
