---
permalink: maintain/configuring-ntp-servers.html
sidebar: sidebar
keywords: storagegrid, ntp, ntp server, configure ntp, configuring ntp
summary: 'You can add, update, or remove network time protocol \(NTP\) servers to ensure that data is synchronized accurately between grid nodes in your StorageGRID system.'
---
= Configure NTP servers
:icons: font
:imagesdir: ../media/

[.lead]
You can add, update, or remove network time protocol (NTP) servers to ensure that data is synchronized accurately between grid nodes in your StorageGRID system.

.What you'll need

* You must be signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You must have the Maintenance or Root Access permission.
* You must have the provisioning passphrase.
* You must have the IPv4 addresses of the NTP servers to configure.

.About this task

The StorageGRID system uses the network time protocol (NTP) to synchronize time between all grid nodes in the grid.

At each site, at least two nodes in the StorageGRID system are assigned the primary NTP role. They synchronize to a suggested minimum of four, and a maximum of six, external time sources and with each other. Every node in the StorageGRID system that is not a primary NTP node acts as an NTP client and synchronizes with these primary NTP nodes.

The external NTP servers connect to the nodes to which you previously assigned Primary NTP roles. For this reason, specifying at least two nodes with Primary NTP roles is recommended.

IMPORTANT: Make sure that at least two nodes at each site can access at least four external NTP sources. If only one node at a site can reach the NTP sources, timing issues will occur if that node goes down. In addition, designating two nodes per site as primary NTP sources ensures accurate timing if a site is isolated from the rest of the grid.

The specified external NTP servers must use the NTP protocol. You must specify NTP server references of Stratum 3 or better to prevent issues with time drift.

NOTE: When specifying the external NTP source for a production-level StorageGRID installation, do not use the Windows Time (W32Time) service on a version of Windows earlier than Windows Server 2016. The time service on earlier versions of Windows is not sufficiently accurate and is not supported by Microsoft for use in high-accuracy environments, such as StorageGRID.

https://support.microsoft.com/en-us/help/939322/support-boundary-to-configure-the-windows-time-service-for-high-accura[Support boundary to configure the Windows Time service for high-accuracy environments^]

If you encounter problems with the stability or availability of the NTP servers originally specified during installation, you can update the list of external NTP sources that the StorageGRID system uses by adding additional servers, or updating or removing existing servers.

.Steps

. Select *MAINTENANCE* > *Network* > *NTP servers*.
. In the Servers section, add update, or remove NTP server entries, as necessary.
+
You should include at least 4 NTP servers, and you can specify up to 6 servers.

. In the *Provisioning Passphrase* text box, enter the provisioning passphrase for your StorageGRID system and click *Save*.
+
The status of the procedure is displayed at the top of the page. The page is disabled until the configuration updates are complete.
+
IMPORTANT: If all of your NTP servers fail the connection test after you save the new NTP servers, do not proceed. Contact technical support.
