---
permalink: maintain/consolidating-storage-nodes.html
sidebar: sidebar
keywords: storagegrid, storage node, consolidate storage node, consolidating storage node
summary: 'You can consolidate Storage Nodes to reduce the Storage Node count for a site or deployment while increasing storage capacity.'
---
= Consolidate Storage Nodes
:icons: font
:imagesdir: ../media/

[.lead]
You can consolidate Storage Nodes to reduce the Storage Node count for a site or deployment while increasing storage capacity.

When you consolidate Storage Nodes, you expand the StorageGRID system to add new, larger capacity Storage Nodes and then decommission the old, smaller capacity Storage Nodes. During the decommission procedure, objects are migrated from the old Storage Nodes to the new Storage Nodes.

NOTE: If you are consolidating older and smaller appliances with new models or larger capacity appliances, you many use the node clone feature or the node clone procedure and the decommission procedure if you are not doing a one-to-one replacement.  

For example, you might add two new, larger capacity Storage Nodes to replace three older Storage Nodes. You would first use the expansion procedure to add the two new, larger Storage Nodes, and then use the decommission procedure to remove the three old, smaller capacity Storage Nodes.

By adding new capacity before removing existing Storage Nodes, you ensure a more balanced distribution of data across the StorageGRID system. You also reduce the possibility that an existing Storage Node might be pushed beyond the storage watermark level.

.Related information

xref:../expand/index.adoc[Expand your grid]
