---
permalink: maintain/considerations-for-applying-hotfix.html
sidebar: sidebar
keywords: storagegrid, hotfix
summary: 'When you apply a hotfix, a cumulative series of software updates is applied to the nodes in your StorageGRID system.'
---
= Considerations for applying a hotfix
:icons: font
:imagesdir: ../media/

[.lead]
When you apply a hotfix, a cumulative series of software updates is applied to the nodes in your StorageGRID system.

You cannot apply a StorageGRID hotfix when another maintenance procedure is running. For example, you cannot apply a hotfix while a decommission, expansion, or recovery procedure is running.

NOTE: If a node or site decommission procedure is paused, you can safely apply a hotfix. In addition, you might be able to apply a hotfix during the final stages of a StorageGRID upgrade procedure. See the instructions for upgrading StorageGRID software for details.

After you upload the hotfix in the Grid Manager, the hotfix is applied automatically to the primary Admin Node. Then, you can approve the application of the hotfix to the rest of the nodes in your StorageGRID system.

If a hotfix fails to be applied to one or more nodes, the reason for the failure appears in the Details column of the hotfix progress table. You must resolve whatever issues caused the failures and then retry the entire process. Nodes with a previously successful application of the hotfix will be skipped in subsequent applications. You can safely retry the hotfix process as many times as required until all nodes have been updated. The hotfix must be successfully installed on all grid nodes in order for the application to be complete.

While grid nodes are updated with the new hotfix version, the actual changes in a hotfix might only affect specific services on specific types of nodes. For example, a hotfix might only affect the LDR service on Storage Nodes.

== How hotfixes are applied for recovery and expansion

After a hotfix has been applied to your grid, the primary Admin Node automatically installs the same hotfix version to any nodes restored by recovery operations or added in an expansion.

However, if you need to recover the primary Admin Node, you must manually install the correct StorageGRID release and then apply the hotfix. The final StorageGRID version of the primary Admin Node must match the version of the other nodes in the grid.

The following example illustrates how to apply a hotfix when recovering the primary Admin Node:

. Assume the grid is running a StorageGRID 11._A.B_ version with the latest hotfix. The "`grid version`" is 11._A.B.y_.
. The primary Admin Node fails.
. You redeploy the primary Admin Node using StorageGRID 11._A.B_, and perform the recovery procedure.
+
NOTE: As required to match the grid version, you can use a minor release when deploying the node; you do not need to deploy the major release first.

. You then apply hotfix 11._A.B.y_ to the primary Admin Node.

.Related information

xref:configuring-replacement-primary-admin-node.adoc[Configuring the replacement primary Admin Node]
