---
permalink: maintain/downloading-recovery-package.html
sidebar: sidebar
keywords: storagegrid, recovery package
summary: 'The Recovery Package file allows you to restore the StorageGRID system if a failure occurs.'
---
= Download Recovery Package
:icons: font
:imagesdir: ../media/

[.lead]
The Recovery Package file allows you to restore the StorageGRID system if a failure occurs.

.What you'll need

* You must be signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You must have the provisioning passphrase.
* You must have specific access permissions.

Download the current Recovery Package file before making grid topology changes to the StorageGRID system or before upgrading software. Then, download a new copy of the Recovery Package after making grid topology changes or after upgrading software.

.Steps

. Select *MAINTENANCE* > *System* > *Recovery package*.
. Enter the provisioning passphrase, and select *Start Download*.
+
The download starts immediately.

. When the download completes:
 .. Open the `.zip` file.
 .. Confirm it includes a gpt-backup directory and an inner `.zip` file.
 .. Extract the inner `.zip` file.
 .. Confirm you can open the `Passwords.txt` file.
. Copy the downloaded Recovery Package file (`.zip`) to two safe, secure, and separate locations.
+
IMPORTANT: The Recovery Package file must be secured because it contains encryption keys and passwords that can be used to obtain data from the StorageGRID system.

.Related information

xref:../admin/index.adoc[Administer StorageGRID]
