---
permalink: maintain/downloading-hotfix-file.html
sidebar: sidebar
keywords: storagegrid, hotfix, download
summary: 'You must download the hotfix file before you can apply the hotfix.'
---
= Downloading the hotfix file
:icons: font
:imagesdir: ../media/

[.lead]
You must download the hotfix file before you can apply the hotfix.

.Steps

. Go to the NetApp Downloads page for StorageGRID.
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads: StorageGRID]

. Select the down arrow under *Available Software* to see a list of hotfixes that are available to download.
+
NOTE: Hotfix file versions have the form: 11.4__.x.y__.

. Review the changes that are included in the update.
+
NOTE: If you have just recovered the primary Admin Node and you need to apply a hotfix, select the same hotfix version that is installed on the other grid nodes.

 .. Select the hotfix version you want to download, and select *Go*.
 .. Sign in using the username and password for your NetApp account.
 .. Read and accept the End User License Agreement.
+
The download page for the version you selected appears.

 .. Download the hotfix `readme.txt` file to view a summary of the changes included in the hotfix.

. Select the download button for the hotfix, and save the file.
+
NOTE: Do not change the name of this file.
+
NOTE: If you are using a macOS device, the hotfix file might be automatically saved as a `.txt` file. If it is, you must rename the file without the `.txt` extension.

. Select a location for the download, and select *Save*.

.Related information

xref:configuring-replacement-primary-admin-node.adoc[Configuring the replacement primary Admin Node]
