---
permalink: maintain/gathering-required-materials-for-grid-node-recovery.html
sidebar: sidebar
keywords: storagegrid, recovery, grid node recovery, node recovery
summary: 'Before performing maintenance procedures, you must ensure you have the necessary materials to recover a failed grid node.'
---
= Gather required materials for grid node recovery
:icons: font
:imagesdir: ../media/

[.lead]
Before performing maintenance procedures, you must ensure you have the necessary materials to recover a failed grid node.

[cols="1a,2a" options="header"]
|===
| Item| Notes
|StorageGRID installation archive
|If you need to recover a grid node, you need to <<download-and-extract-install-files-recover,download the StorageGRID installation files>> for your platform.

*Note:* You do not need to download files if you are recovering failed storage volumes on a Storage Node.

|Service laptop
|The service laptop must have the following:

* Network port
* SSH client (for example, PuTTY)
* xref:../admin/web-browser-requirements.adoc[Supported web browser]

|Recovery Package `.zip` file
|Obtain a copy of the most recent Recovery Package `.zip` file:
`sgws-recovery-package-_id-revision_.zip`

The contents of the `.zip` file are updated each time the system is modified. You are directed to store the most recent version of the Recovery Package in a secure location after making such changes. Use the most recent copy to recover from grid failures.

If the primary Admin Node is operating normally, you can download the Recovery Package from the Grid Manager. Select *MAINTENANCE* > *System* > *Recovery package*.

If you cannot access the Grid Manager, you can find encrypted copies of the Recovery Package on some Storage Nodes that contain the ADC service. On each Storage Node, examine this location for the Recovery Package: `/var/local/install/sgws-recovery-package-_grid-id_-_revision_.zip.gpg` Use the Recovery Package with the highest revision number.

|`Passwords.txt` file
|Contains the passwords required to access grid nodes on the command line. Included in the Recovery Package.

|Provisioning passphrase
|The passphrase is created and documented when the StorageGRID system is first installed. The provisioning passphrase is not in the `Passwords.txt` file.

|Current documentation for your platform
|Go to the platform vendor's website for documentation.

For the current supported versions of your platform, see the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].

|===

.[[download-and-extract-install-files-recover]]
== Download and extract StorageGRID installation files

Download the software and extract the files, unless you are xref:recovering-from-storage-node-failures.adoc[recovering failed storage volumes on a Storage Node].

You must use the version of StorageGRID that is currently running on the grid.

.Steps

. Determine which version of the software is currently installed. From the top of the Grid Manager, select the help icon and select *About*.
. Go to the https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads page for StorageGRID].
. Select the version of StorageGRID that is currently running on the grid.
+
StorageGRID software versions have this format: `11.x.y`.

. Sign in with the username and password for your NetApp account.
. Read the End User License Agreement, select the check box, and then select *Accept & Continue*.
. In the *Install StorageGRID* column of the download page, select the `.tgz` or `.zip` file for your platform.
+
The version shown in the installation archive file must match the version of the software that is currently installed.
+
Use the `.zip` file if you are running Windows.
+
[cols="1a,2a" options="header"]
|===
| Platform| Installation archive

|Red Hat Enterprise Linux or CentOS
m|
include::../_include/installation-archives-rhel.adoc[]

|Ubuntu or Debian or Appliances
m|
include::../_include/installation-archives-ubuntu.adoc[]

|VMware
m|
include::../_include/installation-archives-vmware.adoc[]

|===

. Download and extract the archive file.
. Follow the appropriate step for your platform to choose the files you need, based on your platform and which grid nodes you need to recover.
+
The paths listed in the step for each platform are relative to the top-level directory installed by the archive file.

. If you are recovering a xref:../rhel/index.adoc[Red Hat Enterprise Linux or CentOS system], select the appropriate files.
+
include::../_include/installation-files-rhel.adoc[]

[start=10]
. If you are recovering an xref:../ubuntu/index.adoc[Ubuntu or Debian system], select the appropriate files.
+
include::../_include/installation-files-ubuntu.adoc[]

[start=11]
. If you are recovering a xref:../vmware/index.adoc[VMware system], select the appropriate files.
+
include::../_include/installation-files-vmware.adoc[]

[start=12]
. If you are recovering a StorageGRID appliance-based system, select the appropriate files.
+
include::../_include/installation-files-appliance.adoc[]
