---
permalink: maintain/gathering-required-materials-site-decom.html
sidebar: sidebar
keywords: storagegrid, decommission
summary: 'Before you decommission a site, you must obtain the following materials.'
---
= Gather required materials
:icons: font
:imagesdir: ../media/

[.lead]
Before you decommission a site, you must obtain the following materials.

|===
| Item| Notes
a|
Recovery Package `.zip` file
a|
You must download the most recent Recovery Package `.zip` file (`sgws-recovery-package-id-revision.zip`). You can use the Recovery Package file to restore the system if a failure occurs.
a|
`Passwords.txt` file
a|
This file contains the passwords required to access grid nodes on the command line and is included in the Recovery Package.
a|
Provisioning passphrase
a|
The passphrase is created and documented when the StorageGRID system is first installed. The provisioning passphrase is not in the `Passwords.txt` file.
a|
Description of StorageGRID system's topology before decommissioning
a|
If available, obtain any documentation that describes the system's current topology.
|===
.Related information

xref:../admin/web-browser-requirements.adoc[Web browser requirements]

xref:downloading-recovery-package.adoc[Download the Recovery Package]
