---
permalink: maintain/grid-node-procedures.html
sidebar: sidebar
keywords: storagegrid, grid node procedure
summary: 'You might need to perform procedures on a specific grid node. While you can perform a few of these procedures from Grid Manager, most of the procedures require you to access Server Manager from the node’s command line.'
---
= Grid node procedures
:icons: font
:imagesdir: ../media/

[.lead]
You might need to perform procedures on a specific grid node. While you can perform a few of these procedures from Grid Manager, most of the procedures require you to access Server Manager from the node's command line.

Server Manager runs on every grid node to supervise the starting and stopping of services and to ensure that services gracefully join and leave the StorageGRID system. Server Manager also monitors the services on every grid node and will automatically attempt to restart any services that report faults.

IMPORTANT: You should access Server Manager only if technical support has directed you to do so.

NOTE: You must close the current command shell session and log out after you are finished with Server Manager. Enter: `exit`

.Choices

* xref:viewing-server-manager-status-and-version.adoc[View Server Manager status and version]
* xref:viewing-current-status-of-all-services.adoc[View current status of all services]
* xref:starting-server-manager-and-all-services.adoc[Start Server Manager and all services]
* xref:restarting-server-manager-and-all-services.adoc[Restart Server Manager and all services]
* xref:stopping-server-manager-and-all-services.adoc[Stop Server Manager and all services]
* xref:viewing-current-status-of-service.adoc[View current status of service]
* xref:stopping-service.adoc[Stop service]
* xref:placing-appliance-into-maintenance-mode.adoc[Place appliance into maintenance mode]
* xref:forcing-service-to-terminate.adoc[Force service to terminate]
* xref:starting-or-restarting-service.adoc[Start or restart service]
* xref:removing-port-remaps.adoc[Remove port remaps]
* xref:removing-port-remaps-on-bare-metal-hosts.adoc[Remove port remaps on bare metal hosts]
* xref:rebooting-grid-node.adoc[Reboot grid node]
* xref:shutting-down-grid-node.adoc[Shut down grid node]
* xref:powering-down-host.adoc[Power down host]
* xref:powering-off-and-on-all-nodes-in-grid.adoc[Power off and on all nodes in grid]
* xref:using-donotstart-file.adoc[Use a DoNotStart file]
* xref:troubleshooting-server-manager.adoc[Troubleshoot Server Manager]
