---
permalink: maintain/grid-node-procedures.html
sidebar: sidebar
keywords: storagegrid, grid node procedure
summary: 'You might need to perform procedures on a specific grid node. While you can perform a few of these procedures from Grid Manager, most of the procedures require you to access Server Manager from the node’s command line.'
---
= Grid node procedures
:icons: font
:imagesdir: ../media/

[.lead]
You might need to perform procedures on a specific grid node. While you can perform a few of these procedures from Grid Manager, most of the procedures require you to access Server Manager from the node's command line.

Server Manager runs on every grid node to supervise the starting and stopping of services and to ensure that services gracefully join and leave the StorageGRID system. Server Manager also monitors the services on every grid node and will automatically attempt to restart any services that report faults.

IMPORTANT: You should access Server Manager only if technical support has directed you to do so.

NOTE: You must close the current command shell session and log out after you are finished with Server Manager. Enter: `exit`
