---
permalink: maintain/how-your-system-is-affected-when-you-apply-hotfix.html
sidebar: sidebar
keywords: storagegrid, hotfix
summary: 'You must understand how your StorageGRID system will be affected when you apply a hotfix.'
---
= How your system is affected when you apply a hotfix
:icons: font
:imagesdir: ../media/

[.lead]
You must understand how your StorageGRID system will be affected when you apply a hotfix.

== Client applications might experience short-term disruptions

The StorageGRID system can ingest and retrieve data from client applications throughout the hotfix process; however, client connections to individual Gateway Nodes or Storage Nodes might be disrupted temporarily if the hotfix needs to restart services on those nodes. Connectivity will be restored after the hotfix process completes and services resume on the individual nodes.

You might need to schedule downtime to apply a hotfix if loss of connectivity for a short period is not acceptable. You can use selective approval to schedule when certain nodes are updated.

NOTE: You can use multiple gateways and high availability (HA) groups to provide automatic failover during the hotfix process. To configure high availability groups, see the instructions for administering StorageGRID.

== Alerts and SNMP notifications might be triggered

Alerts and SNMP notifications might be triggered when services are restarted and when the StorageGRID system is operating as a mixed-version environment (some grid nodes running an earlier version, while others have been upgraded to a later version). In general, these alerts and notifications will clear when the hotfix completes.

== Configuration changes are restricted

When applying a hotfix to StorageGRID:

* Do not make any grid configuration changes (for example, specifying Grid Network subnets or approving pending grid nodes) until the hotfix has been applied to all nodes.
* Do not update the ILM configuration until the hotfix has been applied to all nodes.
