---
permalink: maintain/installing-services-appliance-platform-change-only.html
sidebar: sidebar
keywords: storagegrid, recover services appliance, recover appliance, recovering appliance, recovering services appliance, install services appliance, installing services appliance, services appliance
summary: 'When you are recovering a failed grid node that was hosted on VMware or a Linux host and you are using an SG100 or SG1000 services appliance for the replacement node, you must first install the new appliance hardware using the same node name as the failed node.'
---
= Installing a services appliance (platform change only)
:icons: font
:imagesdir: ../media/

[.lead]
When you are recovering a failed grid node that was hosted on VMware or a Linux host and you are using an SG100 or SG1000 services appliance for the replacement node, you must first install the new appliance hardware using the same node name as the failed node.

You must have the following information about the failed node:

* *Node name*: You must install the services appliance using the same node name as the failed node.
* *IP addresses*: You can assign the services appliance the same IP addresses as the failed node, which is the preferred option, or you can select a new unused IP address on each network.

Perform this procedure only if you are recovering a failed node that was hosted on VMware or Linux and are replacing it with a node hosted on a services appliance.

. Follow the instructions for installing a new SG100 or SG1000 services appliance.
. When prompted for a node name, use the node name of the failed node.

.Related information

xref:../sg100-1000/index.adoc[SG100 & SG1000 services appliances]
