---
permalink: maintain/introduction-to-storagegrid-recovery-and-maintenance.html
sidebar: sidebar
keywords: storagegrid, recovery, maintenance
summary: 'The recovery and maintenance procedures for StorageGRID include applying a software hotfix, recovering grid nodes, recovering a failed site, decommissioning grid nodes or an entire site, performing network maintenance, performing host-level and middleware maintenance procedures, and performing grid node procedures.'
---
= Introduction to StorageGRID recovery and maintenance
:icons: font
:imagesdir: ../media/

[.lead]
The recovery and maintenance procedures for StorageGRID include applying a software hotfix, recovering grid nodes, recovering a failed site, decommissioning grid nodes or an entire site, performing network maintenance, performing host-level and middleware maintenance procedures, and performing grid node procedures.

All recovery and maintenance activities require a broad understanding of the StorageGRID system. You should review your StorageGRID system's topology to ensure that you understand the grid configuration.

You must follow all instructions exactly and heed all warnings.

Maintenance procedures not described are not supported or require a services engagement.

For hardware procedures, see the installation and maintenance instructions for your StorageGRID appliance.

NOTE: "`Linux`" refers to a Red Hat速 Enterprise Linux速, Ubuntu速, CentOS, or Debian速 deployment. Use the NetApp Interoperability Matrix Tool to get a list of supported versions.

.Related information

xref:../primer/index.adoc[Grid primer]

xref:../network/index.adoc[Network guidelines]

xref:../admin/index.adoc[Administer StorageGRID]

xref:../sg100-1000/index.adoc[SG100 & SG1000 services appliances]

xref:../sg6000/index.adoc[SG6000 storage appliances]

xref:../sg5700/index.adoc[SG5700 storage appliances]

xref:../sg5600/index.adoc[SG5600 storage appliances]

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
