---
permalink: maintain/introduction_to_storagegrid_recovery_and_maintenance.html
sidebar: sidebar
keywords: 
summary: 'The recovery and maintenance procedures for StorageGRID include applying a software hotfix, recovering grid nodes, recovering a failed site, decommissioning grid nodes or an entire site, performing network maintenance, performing host-level and middleware maintenance procedures, and performing grid node procedures.'
---
= Introduction to StorageGRID recovery and maintenance
:icons: font
:imagesdir: ../media/

[.lead]
The recovery and maintenance procedures for StorageGRID include applying a software hotfix, recovering grid nodes, recovering a failed site, decommissioning grid nodes or an entire site, performing network maintenance, performing host-level and middleware maintenance procedures, and performing grid node procedures.

All recovery and maintenance activities require a broad understanding of the StorageGRID system. You should review your StorageGRID system's topology to ensure that you understand the grid configuration.

You must follow all instructions exactly and heed all warnings.

Maintenance procedures not described are not supported or require a services engagement.

For hardware procedures, see the installation and maintenance instructions for your StorageGRID appliance.

NOTE: "`Linux`" refers to a Red Hat速 Enterprise Linux速, Ubuntu速, CentOS, or Debian速 deployment. Use the NetApp Interoperability Matrix Tool to get a list of supported versions.

.Related information

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-primer/home.html[Grid primer]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-network/home.html[StorageGRID networking guidelines]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-admin/home.html[Administering StorageGRID]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sga-install-sg1000/home.html[SG100 and SG1000 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sga-install-sg6000/home.html[SG6000 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sga-install-sg5700/home.html[SG5700 appliance installation and maintenance]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-app-install/home.html[SG5600 appliance installation and maintenance]

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
