---
permalink: maintain/linux-importing-node-on-target-host.html
sidebar: sidebar
keywords: storagegrid, recover, linux, import node, importing node, target host
summary: 'After exporting the node from the source host, you import and validate the node on the target Linux host. Validation confirms that the node has access to the same block storage and network interface devices as it had on the source host.'
---
= Linux: Importing the node on the target host
:icons: font
:imagesdir: ../media/

[.lead]
After exporting the node from the source host, you import and validate the node on the target Linux host. Validation confirms that the node has access to the same block storage and network interface devices as it had on the source host.

Run the following command on the target Linux host.

. Import the node on the target host.
+
----
sudo storagegrid node import /dev/mapper/sgws-dc1-s3-var-local
----
+
`Finished importing node DC1-S3 from /dev/mapper/sgws-dc1-s3-var-local.`
+
`You should run 'storagegrid node validate DC1-S3'`

. Validate the node configuration on the new host.
+
----
sudo storagegrid node validate DC1-S3
----
+
`+Confirming existence of node DC1-S3... PASSED+`
+
`+Checking configuration file /etc/storagegrid/nodes/DC1-S3.conf for node DC1-S3... PASSED+`
+
`+Checking for duplication of unique values... PASSED+`

. If any validation errors occur, address them before starting the migrated node.
+
For troubleshooting information, see the StorageGRID installation instructions for your Linux operating system.

.Related information

xref:../rhel/index.adoc[Install Red Hat Enterprise Linux or CentOS]

xref:../ubuntu/index.adoc[Install Ubuntu or Debian]
