---
permalink: maintain/linux-adding-interfaces-to-existing-node.html
sidebar: sidebar
keywords: add interfaces, add client network interface, add admin network interface
summary: 'Use these steps to add an interface on the Admin Network or the Client Network to a Linux node after it has been installed.'
---
= Linux: Add Admin or Client interfaces to an existing node
:icons: font
:imagesdir: ../media/

[.lead]
Use these steps to add an interface on the Admin Network or the Client Network to a Linux node after it has been installed.

If you did not configure ADMIN_NETWORK_TARGET or CLIENT_NETWORK_TARGET in the node configuration file on the Linux host during installation, use this procedure to add the interface. For more information about the node configuration file, see the instructions for your Linux operating system:

* xref:../rhel/index.adoc[Install Red Hat Enterprise Linux or CentOS]

* xref:../ubuntu/index.adoc[Install Ubuntu or Debian]

You perform this procedure on the Linux server hosting the node that needs the new network assignment, not inside the node. This procedure only adds the interface to the node; a validation error occurs if you attempt to specify any other network parameters.

To provide addressing information, you must use the Change IP tool. See xref:changing-nodes-network-configuration.adoc[Change node network configuration].

.Steps

. Log in to the Linux server hosting the node.
. Edit the node configuration file: `/etc/storagegrid/nodes/_node-name_.conf`.
+
IMPORTANT: Do not specify any other network parameters, or a validation error will result.

 .. Add an entry for the new network target. For example:
+
`CLIENT_NETWORK_TARGET = bond0.3206`

.. Optional: Add an entry for the MAC address. For example:
+
`CLIENT_NETWORK_MAC = aa:57:61:07:ea:5c`

. Run the node validate command:
+
`sudo storagegrid node validate _node-name_`

. Resolve all validation errors.

. Run the node reload command:
+
`sudo storagegrid node reload _node-name_`
