---
permalink: maintain/modifying_dns_configuration_for_single_grid_node.html
sidebar: sidebar
keywords: 
summary: 'Rather than configure the Domain Name System \(DNS\) globally for the entire deployment, you can run a script to configure DNS differently for each grid node.'
---
= Modifying the DNS configuration for a single grid node
:icons: font
:imagesdir: ../media/

[.lead]
Rather than configure the Domain Name System (DNS) globally for the entire deployment, you can run a script to configure DNS differently for each grid node.

In general, you should use the *Maintenance* > *Network* > *DNS Servers* option on the Grid Manager to configure DNS servers. Only use the following script if you need to use different DNS servers for different grid nodes.

. Log in to the primary Admin Node:
 .. Enter the following command: `ssh admin@primary_Admin_Node_IP`
 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.
+
When you are logged in as root, the prompt changes from `$` to `#`.

 .. Add the SSH private key to the SSH agent. Enter: `ssh-add`
 .. Enter the SSH Access Password listed in the `Passwords.txt` file.
. Log in to the node you want to update with a custom DNS configuration: `ssh node_IP_address`
. Run the DNS setup script: `setup_resolv.rb.`
+
The script responds with the list of supported commands.
+
----
Tool to modify external name servers

available commands:
  add search <domain>
               add a specified domain to search list
               e.g.> add search netapp.com
  remove search <domain>
               remove a specified domain from list
               e.g.> remove search netapp.com
  add nameserver <ip>
               add a specified IP address to the name server list
               e.g.> add nameserver 192.0.2.65
  remove nameserver <ip>
               remove a specified IP address from list
               e.g.> remove nameserver 192.0.2.65
  remove nameserver all
               remove all nameservers from list
  save         write configuration to disk and quit
  abort        quit without saving changes
  help         display this help message


Current list of name servers:
    192.0.2.64
Name servers inherited from global DNS configuration:
    192.0.2.126
    192.0.2.127
Current list of search entries:
    netapp.com

Enter command [add search <domain>|remove search <domain>|add nameserver <ip>]
              [remove nameserver <ip>|remove nameserver all|save|abort|help]
----

. Add the IPv4 address of a server that provides domain name service for your network: `add nameserver IP_address`
. Repeat the `add nameserver` command to add name servers.
. Follow instructions as prompted for other commands.
. Save your changes and exit the application: `save`
. Close the command shell on the server: `exit`
. Repeat steps <<STEP2,#STEP2>> through <<STEP_00BE2CF27ECD4BB393988C20F2F5A5BA,#STEP_00BE2CF27ECD4BB393988C20F2F5A5BA>> for each grid node.
. When you no longer require passwordless access to other servers, remove the private key from the SSH agent. Enter: `ssh-add -D`
