---
permalink: maintain/rebooting-grid-node-from-command-shell.html
sidebar: sidebar
keywords: storagegrid, recover, reboot node, command shell reboot
summary: 'If you need to monitor the reboot operation more closely or if you are unable to access the Grid Manager, you can log into the grid node and run the Server Manager reboot command from the command shell.'
---
= Rebooting a grid node from the command shell
:icons: font
:imagesdir: ../media/

[.lead]
If you need to monitor the reboot operation more closely or if you are unable to access the Grid Manager, you can log into the grid node and run the Server Manager reboot command from the command shell.

You must have the `Passwords.txt` file.

. Log in to the grid node:
 .. Enter the following command: `ssh admin@_grid_node_IP_`
 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.

+
When you are logged in as root, the prompt changes from `$` to `#`.
. Optionally, stop services: `service servermanager stop`
+
Stopping services is an optional, but recommended step. Services can take up to 15 minutes to shut down, and you might want to log in to the system remotely to monitor the shutdown process before you reboot the node in the next step.

. Reboot the grid node: `reboot`
. Log out of the command shell: `exit`
