---
permalink: maintain/recovering_nodes_that_fail_to_start_normally.html
sidebar: sidebar
keywords:
summary: 'If a StorageGRID node does not rejoin the grid normally and does not show up as recoverable, it may be corrupted. You can force the node into recovery mode.'
---
= Recovering nodes that fail to start normally
:icons: font
:imagesdir: ../media/

[.lead]
If a StorageGRID node does not rejoin the grid normally and does not show up as recoverable, it may be corrupted. You can force the node into recovery mode.

To force the node into recovery mode:

----
sudo storagegrid node force-recovery <node-name>
----

TIP: Before issuing this command, confirm that the node's network configuration is correct; it may have failed to rejoin the grid due to incorrect network interface mappings or an incorrect Grid Network IP address or gateway.

IMPORTANT: After issuing the `storagegrid node force-recovery node-name` command, you must perform additional recovery steps for `<node-name>`.

.Related information

xref:whats_next_performing_additional_recovery_steps_if_required.adoc[What's next: Performing additional recovery steps, if required]
