---
permalink: maintain/recovering-nodes-that-fail-to-start-normally.html
sidebar: sidebar
keywords: storagegrid, recover, node did not start, node fail to start
summary: 'If a StorageGRID node does not rejoin the grid normally and does not show up as recoverable, it may be corrupted. You can force the node into recovery mode.'
---
= Recovering nodes that fail to start normally
:icons: font
:imagesdir: ../media/

[.lead]
If a StorageGRID node does not rejoin the grid normally and does not show up as recoverable, it may be corrupted. You can force the node into recovery mode.

To force the node into recovery mode:

`sudo storagegrid node force-recovery _node-name_`

TIP: Before issuing this command, confirm that the node's network configuration is correct; it may have failed to rejoin the grid due to incorrect network interface mappings or an incorrect Grid Network IP address or gateway.

IMPORTANT: After issuing the `storagegrid node force-recovery _node-name_` command, you must perform additional recovery steps for _node-name_.

.Related information

xref:whats-next-performing-additional-recovery-steps-if-required.adoc[What's next: Performing additional recovery steps, if required]
