---
permalink: maintain/recovering-from-non-primary-admin-node-failures.html
sidebar: sidebar
keywords: storagegrid, recover, non-primary admin node failure
summary: 'You must complete the following tasks to recover from a non-primary Admin Node failure. One Admin Node hosts the Configuration Management Node \(CMN\) service and is known as the primary Admin Node. Although you can have multiple Admin Nodes, each StorageGRID system includes only one primary Admin Node. All other Admin Nodes are non-primary Admin Nodes.'
---
= Recover from non-primary Admin Node failures
:icons: font
:imagesdir: ../media/

[.lead]
You must complete the following tasks to recover from a non-primary Admin Node failure. One Admin Node hosts the Configuration Management Node (CMN) service and is known as the primary Admin Node. Although you can have multiple Admin Nodes, each StorageGRID system includes only one primary Admin Node. All other Admin Nodes are non-primary Admin Nodes.

.Related information

xref:../sg100-1000/index.adoc[SG100 & SG1000 services appliances]

.Steps

* xref:copying-audit-logs-from-failed-non-primary-admin-node.adoc[Copy audit logs from failed non-primary Admin Node]
* xref:replacing-non-primary-admin-node.adoc[Replace non-primary Admin Node]
* xref:selecting-start-recovery-to-configure-non-primary-admin-node.adoc[Select Start Recovery to configure non-primary Admin Node]
* xref:restoring-audit-log-on-recovered-non-primary-admin-node.adoc[Restore audit log on recovered non-primary Admin Node]
* xref:resetting-preferred-sender-on-recovered-non-primary-admin-node.adoc[Reset preferred sender on recovered non-primary Admin Node]
* xref:restoring-admin-node-database-non-primary-admin-node.adoc[Restore Admin Node database when recovering non-primary Admin Node]
* xref:restoring-prometheus-metrics-non-primary-admin-node.adoc[Restore Prometheus metrics when recovering non-primary Admin Node]
