---
permalink: maintain/removing_port_remaps.html
sidebar: sidebar
keywords: 
summary: 'If you want to configure an endpoint for the Load Balancer service, and you want to use a port that has already been configured as the Mapped-To Port of a port remap, you must first remove the existing port remap, or the endpoint will not be effective. You must run a script on each Admin Node and Gateway Node that has conflicting remapped ports to remove all of the node’s port remaps.'
---
= Removing port remaps
:icons: font
:imagesdir: ../media/

[.lead]
If you want to configure an endpoint for the Load Balancer service, and you want to use a port that has already been configured as the Mapped-To Port of a port remap, you must first remove the existing port remap, or the endpoint will not be effective. You must run a script on each Admin Node and Gateway Node that has conflicting remapped ports to remove all of the node's port remaps.

CAUTION:

This procedure removes all port remaps. If you need to keep some of the remaps, contact technical support.

For information about configuring load balancer endpoints, see the instructions for administering StorageGRID.

IMPORTANT: If the port remap provides client access, the client should be reconfigured to use a different port configured as an load balancer endpoint if possible, to avoid loss of service, Otherwise, removing the port mapping will result in loss of client access and should be scheduled appropriately.

IMPORTANT: This procedure does not work for a StorageGRID system deployed as a container on bare metal hosts. See the instructions for removing port remaps on bare metal hosts.

. Log in to the node.
 .. Enter the following command: `ssh -p 8022 admin@node_IP`
+
Port 8022 is the SSH port of the base OS, while port 22 is the SSH port of the Docker container running StorageGRID.

 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.
+
When you are logged in as root, the prompt changes from `$` to `#`.
. Run the following script:``remove-port-remap.sh``
. Reboot the node.
+
Follow the instructions for rebooting a grid node.

. Repeat these steps on each Admin Node and Gateway Node that has conflicting remapped ports.

.Related information

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-admin/home.html[Administering StorageGRID]

xref:rebooting_grid_node.adoc[Rebooting a grid node]

xref:removing_port_remaps_on_bare_metal_hosts.adoc[Removing port remaps on bare metal hosts]
