---
permalink: maintain/replacing-gateway-node.html
sidebar: sidebar
keywords: storagegrid, recover, replace gateway node, replacing gateway node
summary: 'You can replace a failed Gateway Node with a Gateway Node running on the same physical or virtual hardware, or you can replace a Gateway Node running on VMware or a Linux host with a Gateway Node hosted on a services appliance.'
---
= Replacing a Gateway Node
:icons: font
:imagesdir: ../media/

[.lead]
You can replace a failed Gateway Node with a Gateway Node running on the same physical or virtual hardware, or you can replace a Gateway Node running on VMware or a Linux host with a Gateway Node hosted on a services appliance.

The node replacement procedure you must follow depends on which platform will be used by the replacement node. After you complete the node replacement procedure (which is suitable for all node types), that procedure will direct you to the next step for Gateway Node recovery.

[cols="1a,2a" options="header"]
|===
| Replacement platform| Procedure
|VMware
|xref:all-node-types-replacing-vmware-node.adoc[Replacing a VMware node]

|Linux
|xref:all-node-types-replacing-linux-node.adoc[Replacing a Linux node]

|SG100 and SG1000 services appliances
|xref:replacing-failed-node-with-services-appliance.adoc[Replacing a services appliance]

|OpenStack
|NetApp-provided virtual machine disk files and scripts for OpenStack are no longer supported for recovery operations. If you need to recover a node running in an OpenStack deployment, download the files for your Linux operating system. Then, follow the procedure for replacing a Linux node.
|===
