---
permalink: maintain/replacing-failed-node-with-services-appliance.html
sidebar: sidebar
keywords: storagegrid, recover, replace failed node, services appliance
summary: 'You can use an SG100 or SG1000 services appliance to recover a failed Gateway Node, a failed non-primary Admin Node, or a failed primary Admin Node that was hosted on VMware, a Linux host, or a services appliance. This procedure is one step of the grid node recovery procedure.'
---
= Replacing a failed node with a services appliance
:icons: font
:imagesdir: ../media/

[.lead]
You can use an SG100 or SG1000 services appliance to recover a failed Gateway Node, a failed non-primary Admin Node, or a failed primary Admin Node that was hosted on VMware, a Linux host, or a services appliance. This procedure is one step of the grid node recovery procedure.

.What you'll need

* You must have determined that one of the following situations is true:
 ** The virtual machine hosting the node cannot be restored.
 ** The physical or virtual Linux host for the grid node has failed, and must be replaced.
 ** The services appliance hosting the grid node must be replaced.
* You must make sure that the StorageGRID Appliance Installer version on the services appliance matches the software version of your StorageGRID system, as described in hardware installation and maintenance for verifying and upgrading the StorageGRID Appliance Installer version.
+
xref:../sg100-1000/index.adoc[SG100 & SG1000 services appliances]

IMPORTANT: Do not deploy both an SG100 and an SG1000 service appliance in the same site. Unpredictable performance might result.

.About this task

You can use an SG100 or SG1000 services appliance to recover a failed grid node in the following cases:

* The failed node was hosted on VMware or Linux (platform change)
* The failed node was hosted on a services appliance (platform replacement)

.Steps

* xref:installing-services-appliance-platform-change-only.adoc[Installing a services appliance (platform change only)]
* xref:preparing-appliance-for-reinstallation-platform-replacement-only.adoc[Preparing an appliance for reinstallation (platform replacement only)]
* xref:starting-software-installation-on-services-appliance-recovery.adoc[Starting software installation on a services appliance]
* xref:monitoring-services-appliance-installation.adoc[Monitoring services appliance installation]
