---
permalink: maintain/resetting-preferred-sender-on-recovered-non-primary-admin-node.html
sidebar: sidebar
keywords: storagegrid, recover, non-primary admin node, reset preferred sender, resetting preferred sender
summary: 'If the non-primary Admin Node you are recovering is currently set as the preferred sender of alert notifications, alarm notifications, and AutoSupport messages, you must reconfigure this setting in the StorageGRID system.'
---
= Reset preferred sender on recovered non-primary Admin Node
:icons: font
:imagesdir: ../media/

[.lead]
If the non-primary Admin Node you are recovering is currently set as the preferred sender of alert notifications, alarm notifications, and AutoSupport messages, you must reconfigure this setting in the StorageGRID system.

.What you'll need

* You must be signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You must have specific access permissions.
* The recovered Admin Node must be installed and running.

.Steps

. Select *CONFIGURATION* > *System* > *Display options*.
. Select the recovered Admin Node from the *Preferred Sender* drop-down list.
. Click *Apply Changes*.

.Related information

xref:../admin/index.adoc[Administer StorageGRID]
