---
permalink: maintain/restoring-audit-log-on-recovered-primary-admin-node.html
sidebar: sidebar
keywords: storagegrid, recover, restore audit log, primary admin node
summary: 'If you were able to preserve the audit log from the failed primary Admin Node, you can copy it to the primary Admin Node you are recovering.'
---
= Restoring the audit log on the recovered primary Admin Node
:icons: font
:imagesdir: ../media/

[.lead]
If you were able to preserve the audit log from the failed primary Admin Node, you can copy it to the primary Admin Node you are recovering.

* The recovered Admin Node must be installed and running.
* You must have copied the audit logs to another location after the original Admin Node failed.

If an Admin Node fails, audit logs saved to that Admin Node are potentially lost. It might be possible to preserve data from loss by copying audit logs from the failed Admin Node and then restoring these audit logs to the recovered Admin Node. Depending on the failure, it might not be possible to copy audit logs from the failed Admin Node. In that case, if the deployment has more than one Admin Node, you can recover audit logs from another Admin Node as audit logs are replicated to all Admin Nodes.

If there is only one Admin Node and the audit log cannot be copied from the failed node, the recovered Admin Node starts recording events to the audit log as if the installation is new.

You must recover an Admin Node as soon as possible to restore logging functionality.

. Log in to the recovered Admin Node:
 .. Enter the following command: `ssh admin@recovery_Admin_Node_IP`
 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.

+
After you are logged in as root, the prompt changes from `$` to `#`.
. Check which audit files have been preserved: `cd /var/local/audit/export`
. Copy the preserved audit log files to the recovered Admin Node: `scp admin@_grid_node_IP_:/var/local/tmp/saved-audit-logs/YYYY* .`
+
When prompted, enter the password for admin.

. For security, delete the audit logs from the failed grid node after verifying that they have been copied successfully to the recovered Admin Node.
. Update the user and group settings of the audit log files on the recovered Admin Node: `chown ams-user:bycast *`
. Log out as root: `exit`

You must also restore any pre-existing client access to the audit share. For more information, see the instructions for administering StorageGRID.

.Related information

xref:../admin/index.adoc[Administer StorageGRID]
