---
permalink: maintain/restoring-admin-node-database-non-primary-admin-node.html
sidebar: sidebar
keywords: storagegrid, recover, restore admin node database, restore database, non-primary admin node
summary: 'If you want to retain the historical information about attributes, alarms, and alerts on a non-primary Admin Node that has failed, you can restore the Admin Node database from the primary Admin Node.'
---
= Restoring the Admin Node database when recovering a non-primary Admin Node
:icons: font
:imagesdir: ../media/

[.lead]
If you want to retain the historical information about attributes, alarms, and alerts on a non-primary Admin Node that has failed, you can restore the Admin Node database from the primary Admin Node.

* The recovered Admin Node must be installed and running.
* The StorageGRID system must include at least two Admin Nodes.
* You must have the `Passwords.txt` file.
* You must have the provisioning passphrase.

If an Admin Node fails, the historical information stored in its Admin Node database is lost. This database includes the following information:

* Alert history
* Alarm history
* Historical attribute data, which is used in the charts and text reports available from the *Support* > *Tools* > *Grid Topology* page.

When you recover an Admin Node, the software installation process creates an empty Admin Node database on the recovered node. However, the new database only includes information for servers and services that are currently part of the system or added later.

If you restored a non-primary Admin Node, you can restore the historical information by copying the Admin Node database from the primary Admin Node (the _source Admin Node_) to the recovered node.

NOTE: Copying the Admin Node database might take several hours. Some Grid Manager features will be unavailable while services are stopped on the source node.

. Log in to the source Admin Node:
 .. Enter the following command: `ssh admin@_grid_node_IP_`
 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.
. Run the following command from the source Admin Node. Then, enter the provisioning passphrase if prompted. `recover-access-points`
. From the source Admin Node, stop the MI service: `service mi stop`
. From the source Admin Node, stop the Management Application Program Interface (mgmt-api) service: `service mgmt-api stop`
. Complete the following steps on the recovered Admin Node:
 .. Log in to the recovered Admin Node:
  ... Enter the following command: `ssh admin@_grid_node_IP_`
  ... Enter the password listed in the `Passwords.txt` file.
  ... Enter the following command to switch to root: `su -`
  ... Enter the password listed in the `Passwords.txt` file.
 .. Stop the MI service: `service mi stop`
 .. Stop the mgmt-api service: `service mgmt-api stop`
 .. Add the SSH private key to the SSH agent. Enter:``ssh-add``
 .. Enter the SSH Access Password listed in the `Passwords.txt` file.
 .. Copy the database from the source Admin Node to the recovered Admin Node: `/usr/local/mi/bin/mi-clone-db.sh Source_Admin_Node_IP`
 .. When prompted, confirm that you want to overwrite the MI database on the recovered Admin Node.
+
The database and its historical data are copied to the recovered Admin Node. When the copy operation is done, the script starts the recovered Admin Node.

 .. When you no longer require passwordless access to other servers, remove the private key from the SSH agent. Enter:``ssh-add -D``
. Restart the services on the source Admin Node: `service servermanager start`
