---
permalink: maintain/reviewing-ilm-policy-and-storage-configuration.html
sidebar: sidebar
keywords: storagegrid, restore, ilm policy, storage configuration
summary: 'If you plan to decommission a Storage Node, you should review your StorageGRID system’s ILM policy before starting the decommissioning process.'
---
= Reviewing the ILM policy and storage configuration
:icons: font
:imagesdir: ../media/

[.lead]
If you plan to decommission a Storage Node, you should review your StorageGRID system's ILM policy before starting the decommissioning process.

During decommissioning, all object data is migrated from the decommissioned Storage Node to other Storage Nodes.

NOTE: The ILM policy you have _during_ the decommission will be the one used _after_ the decommission. You must ensure this policy meets your data requirements both before you start the decommission and after the decommission is complete.

You should review the rules in the active ILM policy to ensure that the StorageGRID system will continue to have enough capacity of the correct type and in the correct locations to accommodate the decommissioning of a Storage Node.

Consider the following:

* Will it be possible for ILM evaluation services to copy object data such that ILM rules are satisfied?
* What happens if a site becomes temporarily unavailable while decommissioning is in progress? Can additional copies be made in an alternate location?
* How will the decommissioning process affect the final distribution of content? As described in "`Consolidating Storage Nodes,`" you should add new Storage Nodes before decommissioning old ones. If you add a larger replacement Storage Node after decommissioning a smaller Storage Node, the old Storage Nodes could be close to capacity and the new Storage Node could have almost no content. Most write operations for new object data would then be directed at the new Storage Node, reducing the overall efficiency of system operations.
* Will the system, at all times, include enough Storage Nodes to satisfy the active ILM policy?
+
NOTE: An ILM policy that cannot be satisfied will lead to backlogs and alarms, and can halt operation of the StorageGRID system.

Verify that the proposed topology that will result from the decommissioning process satisfies the ILM policy by assessing the factors listed in the table.

[cols="1a,2a" options="header"]
|===
| Area to assess| Notes
|Available capacity
|Will there be enough storage capacity to accommodate all of the object data stored in the StorageGRID system, including the permanent copies of object data currently stored on the Storage Node to be decommissioned?Will there be enough capacity to handle the anticipated growth in stored object data for a reasonable interval of time after decommissioning is complete?

|Location of storage
|If enough capacity remains in the StorageGRID system as a whole, is the capacity in the right locations to satisfy the StorageGRID system's business rules?

|Storage type
|Will there be enough storage of the appropriate type after decommissioning is complete? For example, ILM rules might dictate that content be moved from one type of storage to another as content ages. If so, you must ensure that enough storage of the appropriate type is available in the final configuration of the StorageGRID system.
|===

.Related information

xref:consolidating-storage-nodes.adoc[Consolidating Storage Nodes]

xref:../ilm/index.adoc[Manage objects with ILM]

xref:../expand/index.adoc[Expand your grid]
