---
permalink: maintain/service-with-error-state.html
sidebar: sidebar
keywords: storagegrid, recover, service error state, error, error state
summary: 'If you detect that a service has entered an error state, attempt to restart the service.'
---
= Service with an error state
:icons: font
:imagesdir: ../media/

[.lead]
If you detect that a service has entered an error state, attempt to restart the service.

.What you'll need

You must have the `Passwords.txt` file.

.About this task

Server Manager monitors services and restarts any that have stopped unexpectedly. If a service fails, Server Manager attempts to restart it. If there are three failed attempts to start a service within five minutes, the service enters an error state. Server Manager does not attempt another restart.

.Steps

. Log in to the grid node:
 .. Enter the following command: `ssh admin@_grid_node_IP_`
 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.

+
When you are logged in as root, the prompt changes from `$` to `#`.
. Confirm the error state of the service: `service _servicename_ status`
+
For example:
+
----
service ldr status
----
+
If the service is in an error state, the following message is returned: `_servicename_ in error state`. For example:
+
----
ldr in error state
----
+
NOTE: If the service status is `disabled`, see the instructions for removing a DoNotStart file for a service.

. Attempt to remove the error state by restarting the service: `service _servicename_ restart`
+
If the service fails to restart, contact technical support.

. Log out of the command shell: `exit`

.Related information

xref:removing-donotstart-file-for-service.adoc[Removing a DoNotStart file for a service]
