---
permalink: maintain/shutting-down-grid-node.html
sidebar: sidebar
keywords: storagegrid, recover, node shutdown, shut down node, node shut down
summary: 'You can shut down a grid node from the node’s command shell.'
---
= Shut down grid node
:icons: font
:imagesdir: ../media/

[.lead]
You can shut down a grid node from the node's command shell.

.What you'll need

* You must have the `Passwords.txt` file.

.About this task

Before performing this procedure, review these considerations:

* In general, you should not shut down more than one node at a time to avoid disruptions.
* Do not shut down a node during a maintenance procedure unless explicitly instructed to do so by the documentation or by technical support.
* The shutdown process is based on where the node is installed, as follows:
 ** Shutting down a VMware node shuts down the virtual machine.
 ** Shutting down a Linux node shuts down the container.
 ** Shutting down a StorageGRID appliance node shuts down the compute controller.
* If you plan to shut down more than one Storage Node at a site, stop ingesting objects at that site for approximately one hour before shutting down the nodes.
+
If any ILM rule uses the *Dual commit* ingest option (or if a rule uses the *Balanced* option and all required copies cannot be created immediately), StorageGRID immediately commits any newly ingested objects to two Storage Nodes on the same site and evaluates ILM later. If more than one Storage Node at a site is shut down, you might not be able to access newly ingested objects for the duration of the shutdown. Write operations might also fail if too few Storage Nodes remain available at the site.

.Steps

. Log in to the grid node:
 .. Enter the following command: `ssh admin@_grid_node_IP_`
 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.

+
When you are logged in as root, the prompt changes from `$` to `#`.
. Stop all services: `service servermanager stop`
+
Services can take up to 15 minutes to shut down, and you might want to log in to the system remotely to monitor the shutdown process.
. If the node is running on a VMware virtual machine or it is an appliance node, issue the shutdown command: `shutdown -h now`
+
Perform this step regardless of the outcome of the `service servermanager stop` command.
+
NOTE: After you issue the `shutdown -h now` command on an appliance node, you must power cycle the appliance to restart the node.
+
For the appliance, this command shuts down the controller, but the appliance is still powered on. You must complete the next step.

. If you are powering down an appliance node:
 ** For the SG100 or SG1000 services appliance
  ... Turn off the power to the appliance.
  ... Wait for the blue power LED to turn off.
 ** For the SG6000 appliance
  ... Wait for the green Cache Active LED on the back of the storage controllers to turn off.
+
This LED is on when cached data needs to be written to the drives. You must wait for this LED to turn off before you turn off power.

  ... Turn off the power to the appliance, and wait for the blue power LED to turn off.
 ** For the SG5700 appliance
  ... Wait for the green Cache Active LED on the back of the storage controller to turn off.
+
This LED is on when cached data needs to be written to the drives. You must wait for this LED to turn off before you turn off power.

  ... Turn off the power to the appliance, and wait for all LED and seven-segment display activity to stop.

.Related information

xref:../admin/index.adoc[Administer StorageGRID]
