---
permalink: maintain/shutting-down-grid-node.html
sidebar: sidebar
keywords: storagegrid, recover, node shutdown, shut down node, node shut down
summary: 'You can shut down a grid node from the node’s command shell.'
---
= Shutting down a grid node
:icons: font
:imagesdir: ../media/

[.lead]
You can shut down a grid node from the node's command shell.

.What you'll need

* You must have the `Passwords.txt` file.

.About this task

Before performing this procedure, review these considerations:

* In general, you should not shut down more than one node at a time to avoid disruptions.
* Do not shut down a node during a maintenance procedure unless explicitly instructed to do so by the documentation or by technical support.
* The shutdown process is based on where the node is installed, as follows:
 ** Shutting down a VMware node shuts down the virtual machine.
 ** Shutting down a Linux node shuts down the container.
 ** Shutting down a StorageGRID appliance node shuts down the compute controller.
* If you plan to shut down Storage Nodes, note the following:
 ** If an ILM rule specifies an ingest behavior of Dual commit or the rule specifies Balanced and it is not possible to immediately create all required copies, StorageGRID immediately commits any newly ingested objects to two Storage Nodes on the same site and evaluates ILM later. If you want to shut down two or more Storage Nodes on a given site, you might not be able to access these objects for the duration of the shutdown.
 ** To ensure you can access all objects when a Storage Node is shut down, stop ingesting objects at a site for approximately one hour before shutting down the node.

.Steps

. Log in to the grid node:
 .. Enter the following command: `ssh admin@_grid_node_IP_`
 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.

+
When you are logged in as root, the prompt changes from `$` to `#`.
. Stop all services: `service servermanager stop`
+
Services can take up to 15 minutes to shut down, and you might want to log in to the system remotely to monitor the shutdown process.

. Log out of the command shell: `exit`

After being shut down you can power off the grid node.

xref:powering-down-host.adoc[Powering down a host]

.Related information

xref:../admin/index.adoc[Administer StorageGRID]
