---
permalink: maintain/storagegrid_hotfix_procedure.html
sidebar: sidebar
keywords:
summary: 'You might need to apply a hotfix to your StorageGRID system if issues with the software are detected and resolved between feature releases.'
---
= StorageGRID hotfix procedure
:icons: font
:imagesdir: ../media/

[.lead]
You might need to apply a hotfix to your StorageGRID system if issues with the software are detected and resolved between feature releases.

StorageGRID hotfixes contain software changes that are made available outside of a feature or patch release. The same changes are included in a future release. In addition, each hotfix release contains a roll-up of all previous hotfixes within the feature or patch release.

* xref:considerations_for_applying_hotfix.adoc[Considerations for applying a hotfix]

* xref:how_your_system_is_affected_when_you_apply_hotfix.adoc[How your system is affected when you apply a hotfix]

* xref:obtaining_required_materials_for_hotfix.adoc[Obtaining the required materials for a hotfix]

* xref:downloading_hotfix_file.adoc[Downloading the hotfix file]

* xref:checking_systems_condition_before_applying_hotfix.adoc[Checking the system's condition before applying a hotfix]

* xref:applying_hotfix.adoc[Applying the hotfix]
