---
permalink: maintain/storagegrid-hotfix-procedure.html
sidebar: sidebar
keywords:
summary: 'You might need to apply a hotfix to your StorageGRID system if issues with the software are detected and resolved between feature releases.'
---
= StorageGRID hotfix procedure
:icons: font
:imagesdir: ../media/

[.lead]
You might need to apply a hotfix to your StorageGRID system if issues with the software are detected and resolved between feature releases.

StorageGRID hotfixes contain software changes that are made available outside of a feature or patch release. The same changes are included in a future release. In addition, each hotfix release contains a roll-up of all previous hotfixes within the feature or patch release.

* xref:considerations-for-applying-hotfix.adoc[Considerations for applying a hotfix]

* xref:how-your-system-is-affected-when-you-apply-hotfix.adoc[How your system is affected when you apply a hotfix]

* xref:obtaining-required-materials-for-hotfix.adoc[Obtaining the required materials for a hotfix]

* xref:downloading-hotfix-file.adoc[Downloading the hotfix file]

* xref:checking-systems-condition-before-applying-hotfix.adoc[Checking the system's condition before applying a hotfix]

* xref:applying-hotfix.adoc[Applying the hotfix]
