---
permalink: maintain/task_stopping_server_manager_and_all_services.html
sidebar: sidebar
keywords: 
summary: 'Server Manager is intended to run at all times, but you might need to stop Server Manager and all services running on a grid node.'
---
= Stopping Server Manager and all services
:icons: font
:imagesdir: ../media/

[.lead]
Server Manager is intended to run at all times, but you might need to stop Server Manager and all services running on a grid node.

You must have the Passwords.txt file.

The only scenario that requires you to stop Server Manager while keeping the operating system running is when you need to integrate Server Manager to other services. If there is a requirement to stop the Server Manager for servicing of the hardware or reconfiguration of the server, the entire server should be halted.

. Log in to the grid node:
 .. Enter the following command: `ssh admin@grid_node_IP`
 .. Enter the password listed in the Passwords.txt file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the Passwords.txt file.

+
When you are logged in as root, the prompt changes from `$` to `#`.
. Stop Server manager and all services running on the grid node: `service servermanager stop`
+
Server Manager and all services running on the grid node are gracefully terminated. Services can take up to 15 minutes to shut down.

. Log out of the command shell: `exit`
