---
permalink: maintain/task_resetting_archive_node_connection_to_the_cloud.html
sidebar: sidebar
keywords: 
summary: 'After you recover an Archive Node that targets the cloud through the S3 API, you need to modify configuration settings to reset connections. An Outbound Replication Status \(ORSU\) alarm is triggered if the Archive Node is unable to retrieve object data.'
---
= Resetting Archive Node connection to the cloud
:icons: font
:imagesdir: ../media/

[.lead]
After you recover an Archive Node that targets the cloud through the S3 API, you need to modify configuration settings to reset connections. An Outbound Replication Status (ORSU) alarm is triggered if the Archive Node is unable to retrieve object data.

NOTE: If your Archive Node connects to external storage through TSM middleware, then the node resets itself automatically and you do not need to reconfigure.

You must be signed in to the Grid Manager using a supported browser.

. Select *Support* > *Tools* > *Grid Topology*.
. Select *Archive Node* > *ARC* > *Target*.
. Edit the *Access Key* field by entering an incorrect value and click *Apply Changes*.
. Edit the *Access Key* field by entering the correct value and click *Apply Changes*.
