---
permalink: maintain/task_starting_or_restarting_a_service.html
sidebar: sidebar
keywords: 
summary: 'You might need to start a service that has been stopped, or you might need to stop and restart a service.'
---
= Starting or restarting a service
:icons: font
:imagesdir: ../media/

[.lead]
You might need to start a service that has been stopped, or you might need to stop and restart a service.

You must have the Passwords.txt file.

. Log in to the grid node:
 .. Enter the following command: `ssh admin@grid_node_IP`
 .. Enter the password listed in the Passwords.txt file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the Passwords.txt file.

+
When you are logged in as root, the prompt changes from `$` to `#`.
. Decide which command to issue, based on whether the service is currently running or stopped.
 ** If the service is currently stopped, use the start command to start the service manually: `service servicename start`
+
For example:
+
----
service ldr start
----

 ** If the service is currently running, use the restart command to stop the service and then restart it: `service servicename restart`
+
For example:
+
----
service ldr restart
----
+
NOTE: Using the restart command is the same as using the stop command followed by the start command. You can issue restart even if the service is currently stopped.
. Log out of the command shell: `exit`
