---
permalink: maintain/task_replacing_the_storage_node.html
sidebar: sidebar
keywords: 
summary: 'If the system drive has failed, you must first replace the Storage Node.'
---
= Replacing the Storage Node
:icons: font
:imagesdir: ../media/

[.lead]
If the system drive has failed, you must first replace the Storage Node.

You must select the node replacement procedure for your platform. The steps to replace a node are the same for all types of grid nodes.

NOTE: This procedure applies to software-based Storage Nodes only. You must follow a different procedure to recover an appliance Storage Node.

xref:task_recovering_a_storagegrid_appliance_storage_node.adoc[Recovering a StorageGRID appliance Storage Node]

*Linux:* If you are not sure if your system drive has failed, follow the instructions to replace the node to determine which recovery steps are required.

|===
| Platform| Procedure
a|
VMware
a|
xref:task_all_node_types_replacing_a_vmware_node.adoc[Replacing a VMware node]
a|
Linux
a|
xref:task_all_node_types_replacing_a_linux_node.adoc[Replacing a Linux node]
a|
OpenStack
a|
NetApp-provided virtual machine disk files and scripts for OpenStack are no longer supported for recovery operations. If you need to recover a node running in an OpenStack deployment, download the files for your Linux operating system. Then, follow the procedure for replacing a Linux node.

|===
