---
permalink: maintain/task_linux_adding_interfaces_to_an_existing_node.html
sidebar: sidebar
keywords: 
summary: 'If you want to add an interface to a Linux-based node that you did not install initially, you must use this procedure.'
---
= Linux: Adding interfaces to an existing node
:icons: font
:imagesdir: ../media/

[.lead]
If you want to add an interface to a Linux-based node that you did not install initially, you must use this procedure.

If you did not configure ADMIN_NETWORK_TARGET or CLIENT_NETWORK_TARGET in the node configuration file on the Linux host during installation, use this procedure to add the interface. For more information about the node configuration file, see the StorageGRID installation instructions for your Linux operating system.

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-install-rhel/home.html[Red Hat Enterprise Linux or CentOS installation]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-install-ub/home.html[Ubuntu or Debian installation]

You perform this procedure on the Linux server hosting the node that needs the new network assignment, not inside the node. This procedure only adds the interface to the node; a validation error occurs if you attempt to specify any other network parameters.

To provide addressing information, you must use the Change IP tool. See the information about changing a node's network configuration.

xref:task_changing_a_node_s_network_configuration.adoc[Changing a node's network configuration]

. Log in to the Linux server hosting the node that needs the new network assignment.
. Edit the node configuration file at /etc/storagegrid/nodes/<node-name>.conf.
+
IMPORTANT: Do not specify any other network parameters, or a validation error will result.

 .. Add the new network target.
+
----
CLIENT_NETWORK_TARGET = bond0.3206
----

 .. Optional: Add a MAC address.
+
----
CLIENT_NETWORK_MAC = aa:57:61:07:ea:5c
----

. Run the node validate command: `sudo storagegrid node validate <node-name\>`
. Resolve all validation errors.
. Run the node reload command: `sudo storagegrid node reload <node-name\>`

*Related information*

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-install-rhel/home.html[Red Hat Enterprise Linux or CentOS installation]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-install-ub/home.html[Ubuntu or Debian installation]

xref:task_changing_a_node_s_network_configuration.adoc[Changing a node's network configuration]
