---
permalink: maintain/viewing-server-manager-status-and-version.html
sidebar: sidebar
keywords: storagegrid, recover, server manager, status, version
summary: 'For each grid node, you can view the current status and version of Server Manager running on that grid node. You can also obtain the current status of all services running on that grid node.'
---
= Viewing Server Manager status and version
:icons: font
:imagesdir: ../media/

[.lead]
For each grid node, you can view the current status and version of Server Manager running on that grid node. You can also obtain the current status of all services running on that grid node.

.What you'll need

You must have the `Passwords.txt` file.

.Steps

. Log in to the grid node:
 .. Enter the following command: `ssh admin@_grid_node_IP_`
 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.

+
When you are logged in as root, the prompt changes from `$` to `#`.
. View the current status of Server Manager running on the grid node: `*service servermanager status*`
+
The current status of Server Manager running on the grid node is reported (running or not). If Server Manager's status is `running`, the time it has been running since last it was started is listed. For example:
+
----
servermanager running for 1d, 13h, 0m, 30s
----
+
This status is the equivalent of the status shown in the header of the local console display.

. View the current version of Server Manager running on a grid node: `*service servermanager version*`
+
The current version is listed. For example:
+
----
11.1.0-20180425.1905.39c9493
----

. Log out of the command shell: `*exit*`
