---
permalink: primer/storagegrid_attributes.html
sidebar: sidebar
keywords:
summary: 'Attributes report values and statuses for many of the functions of the StorageGRID system. Attribute values are available for each grid node, each site, and the entire grid.'
---
= StorageGRID attributes
:icons: font
:imagesdir: ../media/

[.lead]
Attributes report values and statuses for many of the functions of the StorageGRID system. Attribute values are available for each grid node, each site, and the entire grid.

StorageGRID attributes are used in a number of places in the Grid Manager:

* *Nodes page*: Many of the values shown on the Nodes page are StorageGRID attributes. (Prometheus metrics are also shown on the Nodes pages.)
* *Alarms*: When attributes reach defined threshold values, StorageGRID alarms (legacy system) are triggered at specific severity levels.
* *Grid Topology tree*: Attribute values are shown in the Grid Topology tree (*Support* > *Tools* > *Grid Topology*).
* *Events*: System events occur when certain attributes record an error or fault condition for a node, including errors such as network errors.

== Attribute values

Attributes are reported on a best-effort basis and are approximately correct. Attribute updates can be lost under some circumstances, such as the crash of a service or the failure and rebuild of a grid node.

In addition, propagation delays might slow the reporting of attributes. Updated values for most attributes are sent to the StorageGRID system at fixed intervals. It can take several minutes before an update is visible in the system, and two attributes that change more or less simultaneously can be reported at slightly different times.

.Related information

xref:../monitor/index.adoc[Monitor & troubleshoot]
