---
permalink: primer/tabs_for_nodes_page.html
sidebar: sidebar
keywords:
summary: 'The tabs at the top of the Nodes page are based on what you select from the tree at the left.'
---
= Tabs for the Nodes page
:icons: font
:imagesdir: ../media/

[.lead]
The tabs at the top of the Nodes page are based on what you select from the tree at the left.

[cols="1a,2a,1a" options="header"]
|===
| Tab name| Description| Included for
a|
Overview
a|

* Provides basic information about each node.
* Shows any current, unacknowledged alarms affecting the node.

a|
All nodes
a|
Hardware
a|

* Displays CPU utilization and memory usage for each node
* For appliance nodes, provides additional hardware information.

a|
All nodes
a|
Network
a|
Displays a graph showing the network traffic received and sent across the network interfaces.
a|
All nodes, each site, and the entire grid
a|
Storage
a|

* Provides details for the disk devices and volumes on each node.
* For Storage Nodes, each site, and the entire grid, includes graphs showing object data storage and metadata storage used over time.

a|
All nodes, each site, and the entire grid
a|
Events
a|
Displays a count of any system error or fault event, including errors such as network errors.
a|
All nodes
a|
Objects
a|

* Provides information about S3 and Swift ingest and retrieve rates.
* For Storage Nodes, provides object counts and information about metadata store queries and background verification.

a|
Storage Nodes, each site, and the entire grid
a|
ILM
a|
Provides information about Information Lifecycle Management (ILM) operations.

* For Storage Nodes, provides details about ILM evaluation and background verification for erasure coded objects.
* For each site and the entire grid, shows a graph of the ILM queue over time.
* For the entire grid, provides the estimated time to complete a full ILM scan of all objects.

a|
Storage Nodes, each site, and the entire grid
a|
Load Balancer
a|
Includes performance and diagnostic graphs related to the Load Balancer service.

* For each site, provides an aggregate summary of the statistics for all nodes at that site.
* For the entire grid, provides an aggregate summary of the statistics for all sites.

a|
Admin Nodes and Gateway Nodes, each site, and the entire grid
a|
Platform Services
a|
Provides information about any S3 platform service operations at a site.
a|
Each site
a|
SANtricity System Manager
a|
Provides access to SANtricity System Manager. From SANtricity System Manager, you can review hardware diagnostic and environmental information for the storage controller, as well as issues related to the drives.
a|
Storage appliance nodes

*Note:* The SANtricity System Manager tab will not appear if the controller firmware on the storage appliance is less than 8.70.

|===
