---
permalink: primer/using-snmp-monitoring.html
sidebar: sidebar
keywords: snmp, simple network management protocol, agent, trap, inform, mib
summary: 'If you want to monitor StorageGRID using the Simple Network Management Protocol \(SNMP\), you can use the Grid Manager to configure the SNMP agent.'
---
= Use SNMP monitoring
:icons: font
:imagesdir: ../media/

[.lead]
If you want to monitor StorageGRID using the Simple Network Management Protocol (SNMP), you can use the Grid Manager to configure the SNMP agent.

Each StorageGRID node runs an SNMP agent, or daemon, that provides a management information base (MIB). The StorageGRID MIB contains table and notification definitions for alerts and alarms. Each StorageGRID node also supports a subset of MIB-II objects.

Initially, SNMP is disabled on all nodes. When you configure the SNMP agent, all StorageGRID nodes receive the same configuration.

The StorageGRID SNMP agent supports all three versions of the SNMP protocol. The agent provides read-only MIB access for queries, and it can send two types of event-driven notifications to a management system:

* *Traps* are notifications sent by the SNMP agent that do not require acknowledgment by the management system. Traps serve to notify the management system that something has happened within StorageGRID, such as an alert being triggered. Traps are supported in all three versions of SNMP.
* *Informs* are similar to traps, but they require acknowledgment by the management system. If the SNMP agent does not receive an acknowledgment within a certain amount of time, it resends the inform until an acknowledgment is received or the maximum retry value has been reached. Informs are supported in SNMPv2c and SNMPv3.

Trap and inform notifications are sent in the following cases:

* A default or custom alert is triggered at any severity level. To suppress SNMP notifications for an alert, you must configure a silence for the alert. Alert notifications are sent by whichever Admin Node is configured to be the preferred sender.
* Certain alarms (legacy system) are triggered at specified severity levels or higher.
+
NOTE: SNMP notifications are not sent for every alarm or every alarm severity.

*Related information*

* xref:../monitor/index.adoc[Monitor and troubleshoot]
