---
permalink: sg5700/configuring-storagegrid-connections.html
sidebar: sidebar
keywords: storagegrid, sg5700, storage node, storage appliance, storagegrid connections, connections, configure, setup, set up
summary: 'Before you can deploy a StorageGRID appliance as a Storage Node in a StorageGRID grid, you must configure the connections between the appliance and the networks you plan to use. You can configure networking by browsing to the StorageGRID Appliance Installer, which is included on the E5700SG controller \(the compute controller in the appliance\).'
---
= Configuring StorageGRID connections
:icons: font
:imagesdir: ../media/

[.lead]
Before you can deploy a StorageGRID appliance as a Storage Node in a StorageGRID grid, you must configure the connections between the appliance and the networks you plan to use. You can configure networking by browsing to the StorageGRID Appliance Installer, which is included on the E5700SG controller (the compute controller in the appliance).

.Steps

* xref:accessing-storagegrid-appliance-installer-sg5700.adoc[Accessing the StorageGRID Appliance Installer]
* xref:verifying-and-upgrading-storagegrid-appliance-installer-version.adoc[Verifying and upgrading the StorageGRID Appliance Installer version]
* xref:configuring-network-links-sg5700.adoc[Configuring network links (SG5700)]
* xref:setting-ip-configuration-sg5700.adoc[Setting the IP configuration]
* xref:verifying-network-connections.adoc[Verifying network connections]
* xref:verifying-port-level-network-connections.adoc[Verifying port-level network connections]
