---
permalink: sg5700/configuring_hardware_sg5712_60.html
sidebar: sidebar
keywords: storagegrid, sg5700, storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking
summary: 'After applying power to the appliance, you must configure SANtricity System Manager, which is the software you will use to monitor the hardware. You must also configure the network connections that will be used by StorageGRID.'
---
= Configuring the hardware
:icons: font
:imagesdir: ../media/

[.lead]
After applying power to the appliance, you must configure SANtricity System Manager, which is the software you will use to monitor the hardware. You must also configure the network connections that will be used by StorageGRID.

.Steps

* xref:configuring_storagegrid_connections.adoc[Configuring StorageGRID connections]
* xref:accessing_and_configuring_santricity_system_manager.adoc[Accessing and Configuring SANtricity System Manager]
* xref:optional_enabling_node_encryption.adoc[Optional: Enabling node encryption]
* xref:optional_changing_raid_mode_sg5760_only.adoc[Optional: Changing the RAID mode (SG5760 only)]
* xref:optional_remapping_network_ports_for_appliance_sg5600_and_sg5700.adoc[Optional: Remapping network ports for the appliance]
