---
permalink: sg5700/connecting_power_cords_and_applying_power_sg5700.html
sidebar: sidebar
keywords:
summary: 'When you apply power to the appliance, both controllers boot up.'
---
= Connecting power cords and applying power (SG5700)
:icons: font
:imagesdir: ../media/

[.lead]
When you apply power to the appliance, both controllers boot up.

.What you'll need

Both appliance power switches must be off before connecting power.

CAUTION: *Risk of electrical shock* -- Before connecting the power cords, make sure that the two power switches on the appliance are off.

.Steps

. Confirm that the two power switches on the appliance are off.
. Connect the two power cords to the appliance.
. Connect the two power cords to different power distribution units (PDUs) in the cabinet or rack.
. Turn on the two power switches on the appliance.
 ** Do not turn off the power switches during the power-on process.
 ** The fans are very loud when they first start up. The loud noise during start-up is normal.
. After the controllers have booted up, check their seven-segment displays.
