---
permalink: sg5700/gathering-installation-information-sg5700.html
sidebar: sidebar
keywords: storagegrid, sg5700, storage node, storage appliance, install, information, site, pre-install, preparing, prepare, preinstall, info, preparation
summary: 'As you install and configure the StorageGRID appliance, you must make decisions and gather information about Ethernet switch ports, IP addresses, and port and network bond modes.'
---
= Gathering installation information (SG5700)
:icons: font
:imagesdir: ../media/

[.lead]
As you install and configure the StorageGRID appliance, you must make decisions and gather information about Ethernet switch ports, IP addresses, and port and network bond modes.

.About this task

You can use the following tables to record the required information for each network you connect to the appliance. These values are required to install and configure the hardware.

== Information needed to connect to SANtricity System Manager on the E2800 controller

You must connect the E2800 controller to the management network you will use for SANtricity System Manager.

[options="header"]
|===
| Information needed| Your value
a|
Ethernet switch port you will connect to management port 1
a|

a|
MAC address for management port 1 (printed on a label near port P1)
a|

a|
DHCP-assigned IP address for management port 1, if available after power on

*Note:* If the network you will connect to the E2800 controller includes a DHCP server, the network administrator can use the MAC address to determine the IP address that was assigned by the DHCP server.

a|

a|
Speed and duplex mode

*Note:* You must make sure the Ethernet switch for the SANtricity System Manager management network is set to autonegotiate.

a|
Must be:

* Autonegotiate (default)

a|
IP address format
a|
Choose one:

* IPv4
* IPv6

a|
Static IP address you plan to use for the appliance on the management network
a|
For IPv4:

* IPv4 address:
* Subnet mask:
* Gateway:

For IPv6:

* IPv6 address:
* Routable IP address:
* E2800 controller router IP address:
|===

== Information needed to connect the E5700SG controller to the Admin Network

The Admin Network for StorageGRID is an optional network, used for system administration and maintenance. The appliance connects to the Admin Network using the 1-GbE management ports on the E5700SG controller.

[options="header"]
|===
| Information needed| Your value
a|
Admin Network enabled
a|
Choose one:

* No
* Yes (default)

a|
Network bond mode
a|
Choose one:

* Independent
* Active-Backup

a|
Switch port for port 1
a|

a|
Switch port for port 2 (Active-Backup network bond mode only)
a|

a|
DHCP-assigned IP address for management port 1, if available after power on

*Note:* If the Admin Network includes a DHCP server, the E5700SG controller displays the DHCP-assigned IP address on its seven-segment display after it boots up. You can also determine the DHCP-assigned IP address by using the MAC address to look up the assigned IP.

a|

* IPv4 address (CIDR):
* Gateway:

a|
Static IP address you plan to use for the appliance Storage Node on the Admin Network

*Note:* If your network does not have a gateway, specify the same static IPv4 address for the gateway.

a|

* IPv4 address (CIDR):
* Gateway:

a|
Admin Network subnets (CIDR)
a|
|===

== Information needed to connect and configure the 10/25-GbE ports on the E5700SG controller

The four 10/25-GbE ports on the E5700SG controller connect to the StorageGRID Grid Network and Client Network.

NOTE: See "10/25-GbE port connections for the E5700SG controller" for more information about the options for these ports.

[options="header"]
|===
| Information needed| Your value
a|
Link speed

*Note:* If you select 25 GbE, you must install SPF28 transceivers. Auto-negotiation is not supported, so you must also configure the ports and the connected switches for 25GbE.

a|
Choose one:

* 10 GbE (default)
* 25 GbE

a|
Port bond mode

a|
Choose one:

* Fixed (default)
* Aggregate

a|
Switch port for port 1 (Client Network)

a|

a|
Switch port for port 2 (Grid Network)

a|

a|
Switch port for port 3 (Client Network)

a|

a|
Switch port for port 4 (Grid Network)

a|

|===

== Information needed to connect the E5700SG controller to the Grid Network

The Grid Network for StorageGRID is a required network, used for all internal StorageGRID traffic. The appliance connects to the Grid Network using the 10/25-GbE ports on the E5700SG controller.

NOTE: See "10/25-GbE port connections for the E5700SG controller" for more information about the options for
these ports.

[options="header"]
|===
| Information needed| Your value
a|
Network bond mode
a|
Choose one:

* Active-Backup (default)
* LACP (802.3ad)

a|
VLAN tagging enabled
a|
Choose one:

* No (default)
* Yes

a|
VLAN tag(if VLAN tagging is enabled)

a|
Enter a value between 0 and 4095:
a|
DHCP-assigned IP address for the Grid Network, if available after power on

*Note:* If the Grid Network includes a DHCP server, the E5700SG controller displays the DHCP-assigned IP address for the Grid Network on its seven-segment display after it boots up.

a|

* IPv4 address (CIDR):
* Gateway:

a|
Static IP address you plan to use for the appliance Storage Node on the Grid Network

*Note:* If your network does not have a gateway, specify the same static IPv4 address for the gateway.

a|

* IPv4 address (CIDR):
* Gateway:

a|
Grid Network subnets (CIDR)

*Note:* If the Client Network is not enabled, the default route on the controller will use the gateway specified here.

a|

|===

== Information needed to connect the E5700SG controller to the Client Network

The Client Network for StorageGRID is an optional network, typically used to provide client protocol access to the grid. The appliance connects to the Client Network using the 10/25-GbE ports on the E5700SG controller.

NOTE: See "10/25-GbE port connections for the E5700SG controller" for more information about the options for
these ports.

[options="header"]
|===
| Information needed| Your value
a|
Client Network enabled
a|
Choose one:

* No (default)
* Yes

a|
Network bond mode
a|
Choose one:

* Active-Backup (default)
* LACP (802.3ad)

a|
VLAN tagging enabled
a|
Choose one:

* No (default)
* Yes

a|
VLAN tag

(if VLAN tagging is enabled)

a|
Enter a value between 0 and 4095:
a|
DHCP-assigned IP address for the Client Network, if available after power on
a|

* IPv4 address (CIDR):
* Gateway:

a|
Static IP address you plan to use for the appliance Storage Node on the Client Network

*Note:* If the Client Network is enabled, the default route on the controller will use the gateway specified here.

a|

* IPv4 address (CIDR):
* Gateway:

|===
.Related information

xref:reviewing-appliance-network-connections-sg5700.adoc[Reviewing appliance network connections]

xref:port-bond-modes-for-e5700sg-controller-ports.adoc[Port bond modes for E5700SG controller ports]

xref:configuring-hardware-sg5712-60.adoc[Configuring the hardware]
