---
permalink: sg5700/gathering_installation_information_sg5700.html
sidebar: sidebar
keywords: 
summary: 'As you install and configure the StorageGRID appliance, you must make decisions and gather information about Ethernet switch ports, IP addresses, and port and network bond modes.'
---
= Gathering installation information (SG5700)
:icons: font
:imagesdir: ../media/

[.lead]
As you install and configure the StorageGRID appliance, you must make decisions and gather information about Ethernet switch ports, IP addresses, and port and network bond modes.

.About this task

You can use the following tables to record the required information for each network you connect to the appliance. These values are required to install and configure the hardware.

[options="header"]
|===
| Information needed| Your value
a|
Ethernet switch port you will connect to management port 1
a|
 
a|
MAC address for management port 1 (printed on a label near port P1)
a|
 
a|
DHCP-assigned IP address for management port 1, if available after power on
+
*Note:* If the network you will connect to the E2800 controller includes a DHCP server, the network administrator can use the MAC address to determine the IP address that was assigned by the DHCP server.

a|
 
a|
Speed and duplex mode
+
*Note:* You must make sure the Ethernet switch for the SANtricity System Manager management network is set to autonegotiate.

a|
Must be:

* Autonegotiate (default)

a|
IP address format
a|
Choose one:

* IPv4
* IPv6

a|
Static IP address you plan to use for the appliance on the management network
a|
For IPv4:

* IPv4 address:
* Subnet mask:
* Gateway:

For IPv6:

* IPv6 address:
* Routable IP address:
* E2800 controller router IP address:

[options="header"]
|===
|===
| Information needed| Your value
a|
Admin Network enabled
a|
Choose one:

* No
* Yes (default)

a|
Network bond mode
a|
Choose one:

* Independent
* Active-Backup

a|
Switch port for port 1
a|
 
a|
Switch port for port 2 (Active-Backup network bond mode only)
a|
 
a|
DHCP-assigned IP address for management port 1, if available after power on 
+
*Note:* If the Admin Network includes a DHCP server, the E5700SG controller displays the DHCP-assigned IP address on its seven-segment display after it boots up. You can also determine the DHCP-assigned IP address by using the MAC address to look up the assigned IP.

a|

* IPv4 address (CIDR):
* Gateway:

a|
Static IP address you plan to use for the appliance Storage Node on the Admin Network
+
*Note:* If your network does not have a gateway, specify the same static IPv4 address for the gateway.

a|

* IPv4 address (CIDR):
* Gateway:

a|
Admin Network subnets (CIDR)
a|
 
|===
|===
| Information needed| Your value
a|
Link speed

NOTE: If you select 25 GbE, you must install SPF28 transceivers. Auto-negotiation is not supported, so you must also configure the ports and the connected switches for 25GbE.

a|
Choose one:

* 10 GbE (default)
* 25 GbE

a|
Port bond mode

a|
Choose one:

* Fixed (default)
* Aggregate

a|
Switch port for port 1 (Client Network)

a|
 
a|
Switch port for port 2 (Grid Network)

a|
 
a|
Switch port for port 3 (Client Network)

a|
 
a|
Switch port for port 4 (Grid Network)

a|
 
|===
|===
| Information needed| Your value
a|
Network bond mode
a|
Choose one:

* Active-Backup (default)
* LACP (802.3ad)

a|
VLAN tagging enabled
a|
Choose one:

* No (default)
* Yes

a|
VLAN tag(if VLAN tagging is enabled)

a|
Enter a value between 0 and 4095:
a|
DHCP-assigned IP address for the Grid Network, if available after power on
+
*Note:* If the Grid Network includes a DHCP server, the E5700SG controller displays the DHCP-assigned IP address for the Grid Network on its seven-segment display after it boots up.

a|

* IPv4 address (CIDR):
* Gateway:

a|
Static IP address you plan to use for the appliance Storage Node on the Grid Network
+
*Note:* If your network does not have a gateway, specify the same static IPv4 address for the gateway.

a|

* IPv4 address (CIDR):
* Gateway:

a|
Grid Network subnets (CIDR)
+
*Note:* If the Client Network is not enabled, the default route on the controller will use the gateway specified here.

a|
 
|===
|===
| Information needed| Your value
a|
Client Network enabled
a|
Choose one:

* No (default)
* Yes

a|
Network bond mode
a|
Choose one:

* Active-Backup (default)
* LACP (802.3ad)

a|
VLAN tagging enabled
a|
Choose one:

* No (default)
* Yes

a|
VLAN tag(if VLAN tagging is enabled)

a|
Enter a value between 0 and 4095:
a|
DHCP-assigned IP address for the Client Network, if available after power on
a|

* IPv4 address (CIDR):
* Gateway:

a|
Static IP address you plan to use for the appliance Storage Node on the Client Network 
+
*Note:* If the Client Network is enabled, the default route on the controller will use the gateway specified here.

a|

* IPv4 address (CIDR):
* Gateway:

|===
.Related information

xref:reviewing_appliance_network_connections_sg5700.adoc[Reviewing appliance network connections]

xref:port_bond_modes_for_e5700sg_controller_ports.adoc[Port bond modes for E5700SG controller ports]

xref:configuring_hardware_sg5712_60.adoc[Configuring the hardware]
