---
permalink: sg5700/maintaining-sg5700-appliance.html
sidebar: sidebar
keywords: storagegrid, sg5700, storage node, storage appliance, maintain, maintaining, hardware, procedures, tasks
summary: 'You might need to upgrade the SANtricity OS Software on the E2800 controller, change the Ethernet link configuration of the E5700SG controller, replace the E2800 controller or the E5700SG controller, or replace specific components. The procedures in this section assume that the appliance has already been deployed as a Storage Node in a StorageGRID system.'
---
= Maintain SG5700 appliance
:icons: font
:imagesdir: ../media/

[.lead]
You might need to upgrade the SANtricity OS Software on the E2800 controller, change the Ethernet link configuration of the E5700SG controller, replace the E2800 controller or the E5700SG controller, or replace specific components. The procedures in this section assume that the appliance has already been deployed as a Storage Node in a StorageGRID system.

.Steps

* xref:placing-appliance-into-maintenance-mode.adoc[Place appliance into maintenance mode]
* xref:upgrading-santricity-os-on-storage-controller.adoc[Upgrade SANtricity OS on the storage controller]
* xref:upgrading-drive-firmware-using-santricity-system-manager.adoc[Upgrade drive firmware using SANtricity System Manager]
* xref:replacing-e2800-controller.adoc[Replace E2800 controller]
* xref:replacing-e5700sg-controller.adoc[Replace E5700SG controller]
* xref:replacing-other-hardware-components-sg5700.adoc[Replace other hardware components]
* xref:changing-link-configuration-of-e5700sg-controller.adoc[Change link configuration of the E5700SG controller]
* xref:changing-mtu-setting.adoc[Change MTU setting]
* xref:checking-dns-server-configuration.adoc[Check DNS server configuration]
* xref:monitoring-node-encryption-in-maintenance-mode.adoc[Monitor node encryption in maintenance mode (SG5700)]
