---
permalink: sg5700/maintaining_sg5700_appliance.html
sidebar: sidebar
keywords: storagegrid, sg5700, storage node, storage appliance, maintain, maintaining, hardware, procedures, tasks
summary: 'You might need to upgrade the SANtricity OS Software on the E2800 controller, change the Ethernet link configuration of the E5700SG controller, replace the E2800 controller or the E5700SG controller, or replace specific components. The procedures in this section assume that the appliance has already been deployed as a Storage Node in a StorageGRID system.'
---
= Maintaining the SG5700 appliance
:icons: font
:imagesdir: ../media/

[.lead]
You might need to upgrade the SANtricity OS Software on the E2800 controller, change the Ethernet link configuration of the E5700SG controller, replace the E2800 controller or the E5700SG controller, or replace specific components. The procedures in this section assume that the appliance has already been deployed as a Storage Node in a StorageGRID system.

.Steps

* xref:placing_appliance_into_maintenance_mode.adoc[Placing an appliance into maintenance mode]
* xref:upgrading_santricity_os_on_storage_controller.adoc[Upgrading SANtricity OS on the storage controller]
maintenance mode]
* xref:upgrading_drive_firmware_using_santricity_system_manager.adoc[Upgrading drive firmware using SANtricity System Manager]
* xref:replacing_e2800_controller.adoc[Replacing the E2800 controller]
* xref:replacing_e5700sg_controller.adoc[Replacing the E5700SG controller]
* xref:replacing_other_hardware_components_sg5700.adoc[Replacing other hardware components]
* xref:changing_link_configuration_of_e5700sg_controller.adoc[Changing the link configuration of the E5700SG controller]
* xref:changing_mtu_setting.adoc[Changing the MTU setting]
* xref:checking_dns_server_configuration.adoc[Checking the DNS server configuration]
* xref:monitoring_node_encryption_in_maintenance_mode.adoc[Monitoring node encryption in maintenance mode]
