---
permalink: sg5700/preparing-site-sg5700.html
sidebar: sidebar
keywords: storagegrid, sg5700, storage node, storage appliance, install, installation, site prep, site preparating, preparing site, site requirements, requirements, site, dimensions, weight, weights, temperature, humidity, altitude, airflow, heat, wiring, power, grounding, facility
summary: 'Before installing the appliance, you must make sure that the site and the cabinet or rack you plan to use meet the specifications for a StorageGRID appliance.'
---
= Preparing the site (SG5700)
:icons: font
:imagesdir: ../media/

[.lead]
Before installing the appliance, you must make sure that the site and the cabinet or rack you plan to use meet the specifications for a StorageGRID appliance.

.Steps

. Confirm that the site meets the requirements for temperature, humidity, altitude range, airflow, heat dissipation, wiring, power, and grounding. See the NetApp Hardware Universe for more information.
. If you are installing the SG5760 model, confirm that your location provides 240-volt AC power.
. Obtain a 19-inch (48.3-cm) cabinet or rack to fit shelves of this size (without cables):
+
[options="header"]
|===
| Appliance model| Height| Width| Depth| Maximum weight
a|
SG5712

(12 drives)
a|
3.41 in.

(8.68 cm)
a|
17.6 in.

(44.7 cm)
a|
21.1 in.

(53.6 cm)
a|
63.9 lb

(29.0 kg)
a|
SG5760

(60 drives)
a|
6.87 in.

(17.46 cm)
a|
17.66 in.

(44.86 cm)
a|
38.25 in.

(97.16 cm)
a|
250 lb.

(113 kg)

|===

. Install any required network switches. See the NetApp Interoperability Matrix Tool for compatibility information.

.Related information

https://hwu.netapp.com[NetApp Hardware Universe^]

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]
