---
permalink: sg5700/replacing-e5700sg-controller.html
sidebar: sidebar
keywords: storagegrid, sg5700, storage node, storage appliance, Replacing, replace, E5700sg, controller, remove, removing, removal, install, installing, installation
summary: 'You might need to replace the E5700SG controller if it is not functioning optimally or if it has failed.'
---
= Replacing the E5700SG controller
:icons: font
:imagesdir: ../media/

[.lead]
You might need to replace the E5700SG controller if it is not functioning optimally or if it has failed.

.What you'll need

* You have a replacement controller with the same part number as the controller you are replacing.
* You have downloaded the E-Series instructions for replacing a failed E5700 controller.
+
IMPORTANT: Use the E-Series instructions for reference only if you need more details to perform a specific step. Do not rely on the E-Series instructions to replace a controller in the StorageGRID appliance, because the procedures are not the same. For example, the E-Series instructions for the E5700 controller describe how to remove the battery and the host interface card (HIC) from a failed controller and install them in a replacement controller. These steps do not apply to the E5700SG controller.

* You have labels to identify each cable that is connected to the controller.
* The appliance has been placed maintenance mode.
+
xref:placing-appliance-into-maintenance-mode.adoc[Placing an appliance into maintenance mode]

.About this task

The appliance Storage Node will not be accessible when you replace the controller. If the E5700SG controller is functioning sufficiently, you can perform a controlled shutdown at the start of this procedure.

NOTE: If you are replacing the controller before installing StorageGRID software, you might not be able to access the StorageGRID Appliance Installer immediately after completing this procedure. While you can access the StorageGRID Appliance Installer from other hosts on the same subnet as the appliance, you cannot access it from hosts on other subnets. This condition should resolve itself within 15 minutes (when any ARP cache entries for the original controller time out), or you can clear the condition immediately by purging any old ARP cache entries manually from the local router or gateway.

.Steps

. When the appliance has been placed maintenance mode, shut down the E5700SG controller.
 .. Log in to the grid node:
  ... Enter the following command: `ssh admin@_grid_node_IP_`
  ... Enter the password listed in the `Passwords.txt` file.
  ... Enter the following command to switch to root: `su -`
  ... Enter the password listed in the `Passwords.txt` file.
+
When you are logged in as root, the prompt changes from `$` to `#`.
 .. Shut down the E5700SG controller: +
`*shutdown -h now*`
 .. Wait for any data in cache memory to be written to the drives.
+
The green Cache Active LED on the back of the E2800 controller is on when cached data needs to be written to the drives. You must wait for this LED to turn off.
. Turn off the power.
 .. From the home page of SANtricity System Manager, select *View Operations in Progress*.
 .. Confirm that all operations have completed.
 .. Turn off both power switches on the appliance.
 .. Wait for all LEDs to turn off.
. If the StorageGRID networks attached to the controller use DHCP servers:
 .. Note the MAC addresses for the ports on the replacement controller (located on labels on the controller).
 .. Ask your network administrator to update the IP address settings for the original controller to reflect the MAC addresses for the replacement controller.
+
IMPORTANT: You must ensure that the IP addresses for the original controller have been updated before you apply power to the replacement controller. Otherwise, the controller will obtain new DHCP IP addresses when it boots up and might not be able to reconnect to StorageGRID. This step applies to all StorageGRID networks that are attached to the controller.
. Remove the controller from the appliance:
 .. Put on an ESD wristband or take other antistatic precautions.
 .. Label the cables and then disconnect the cables and SFPs.
+
IMPORTANT: To prevent degraded performance, do not twist, fold, pinch, or step on the cables.

 .. Release the controller from the appliance by squeezing the latch on the cam handle until it releases, and then open the cam handle to the right.
 .. Using two hands and the cam handle, slide the controller out of the appliance.
+
IMPORTANT: Always use two hands to support the weight of the controller.
. Install the replacement controller into the appliance.
 .. Turn the controller over, so that the removable cover faces down.
 .. With the cam handle in the open position, slide the controller all the way into the appliance.
 .. Move the cam handle to the left to lock the controller in place.
 .. Replace the cables and SFPs.
. Power on the appliance, and monitor the controller LEDs and seven-segment displays.
+
After the controllers have successfully booted up, the seven-segment displays should show the following:

 ** E2800 controller:
+
The final state is `99`.

 ** E5700SG controller:
+
The final state is `HA`.

. Confirm that the appliance Storage Node appears in the Grid Manager and that no alarms appear.

.Related information

http://mysupport.netapp.com/info/web/ECMP1658252.html[NetApp E-Series Systems Documentation Site^]
