---
permalink: sg5700/replacing-other-hardware-components-sg5700.html
sidebar: sidebar
keywords: storagegrid, sg5700, storage node, storage appliance, Replacing, replace, hardware, components, remove, removing, removal, install, installing, installation, controller battery, battery, drive, fan, power supply
summary: 'You might need to replace a controller battery, drive, fan, or power supply, in the StorageGRID appliance.'
---
= Replacing other hardware components
:icons: font
:imagesdir: ../media/

[.lead]
You might need to replace a controller battery, drive, fan, or power supply, in the StorageGRID appliance.

.What you'll need

* You have the E-Series hardware replacement procedure.
* The appliance has been placed maintenance mode if the component replacement procedure requires that you shut down the appliance.
+
xref:placing-appliance-into-maintenance-mode.adoc[Placing an appliance into maintenance mode]

.About this task

To replace the battery in the E2800 controller, see the instructions in these instructions for replacing the E2800 controller. Those instructions describe how to remove the controller from the appliance, remove the battery from the controller, install the battery, and replace the controller.

To replace a drive, power-fan canister, fan canister, power canister, or drive drawer in the appliance, access the E-Series procedures for maintaining E2800 hardware.

== SG5712 component replacement instructions

[options="header"]
|===
| FRU| See E-Series instructions for
a|
Drive
a|
Replacing a drive in E2800 12-drive or 24-drive shelves
a|
Power-fan canister
a|
Replacing a power-fan canister in E2800 shelves
|===

== SG5760 component replacement instructions

[options="header"]
|===
| FRU| See E-Series instructions for
a|
Drive
a|
Replacing a drive in E2860 shelves
a|
Power canister
a|
Replacing a power canister in E2860 shelves
a|
Fan canister
a|
Replacing a fan canister in E2860 shelves
a|
Drive drawer
a|
Replacing a drive drawer in E2860 shelves
|===
.Related information

xref:replacing-e2800-controller.adoc[Replacing the E2800 controller]

http://mysupport.netapp.com/info/web/ECMP1658252.html[NetApp E-Series Systems Documentation Site^]
