---
permalink: sg5700/upgrading-santricity-os-on-storage-controller.html
sidebar: sidebar
keywords: storagegrid, sg5700, storage node, storage appliance, controller, storage controller, upgrade, upgrading, SANtricity OS, SANtricity
summary: 'To ensure optimal functioning of the storage controller, you must upgrade to the latest maintenance release of the SANtricity OS that is qualified for your StorageGRID appliance. Consult the NetApp Interoperability Matrix Tool \(IMT\) to determine which version you should be using. If you need assistance, contact technical support.'
---
= Upgrading SANtricity OS on the storage controller
:icons: font
:imagesdir: ../media/

[.lead]
To ensure optimal functioning of the storage controller, you must upgrade to the latest maintenance release of the SANtricity OS that is qualified for your StorageGRID appliance. Consult the NetApp Interoperability Matrix Tool (IMT) to determine which version you should be using. If you need assistance, contact technical support.

* If the storage controller is using SANtricity OS 08.42.20.00 (11.42) or newer, use the Grid Manager to perform the upgrade.
+
xref:upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg5700.adoc[Upgrading SANtricity OS on the storage controllers using the Grid Manager]

* If the storage controller is using a SANtricity OS version older than 08.42.20.00 (11.42), use maintenance mode to perform the upgrade.
+
xref:upgrading-santricity-os-on-e2800-controller-using-maintenance-mode.adoc[Upgrading SANtricity OS on the E2800 controller using maintenance mode]

.Related information

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]

https://mysupport.netapp.com/site/products/all/details/eseries-santricityos/downloads-tab[NetApp Downloads: SANtricity OS^]

xref:../monitor/index.adoc[Monitor & troubleshoot]
