---
permalink: expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html
sidebar: sidebar
keywords: grid node, node, site, add, adding, expand, expansion
summary: 'You can follow this procedure to add grid nodes to existing sites or to add a new site, but you cannot perform both types of expansion at the same time.'
---
= Add grid nodes to an existing site or adding a new site
:icons: font
:imagesdir: ../media/

[.lead]
You can follow this procedure to add grid nodes to existing sites or to add a new site, but you cannot perform both types of expansion at the same time.

.What you'll need

* You must have root or maintenance permissions. For details, see information about controlling system access with administration user accounts and groups.
* All existing nodes in the grid must be up and running across all sites.
* Any previous expansion, upgrade, decommissioning, or recovery procedures must be complete.
+
NOTE: You are prevented from starting an expansion while another expansion, upgrade, recovery, or active decommission procedure is in progress. However, if necessary, you can pause a decommission procedure to start an expansion.

.Steps

. xref:updating-subnets-for-grid-network.adoc[Update subnets for the Grid Network]
. xref:deploying-new-grid-nodes.adoc[Deploy new grid nodes]
. xref:performing-expansion.adoc[Perform the expansion]
