---
permalink: expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html
sidebar: sidebar
keywords: grid node, add node, add site, expand, expansion
summary: 'You can follow this procedure to add grid nodes to existing sites or to add a new site, but you cannot perform both types of expansion at the same time.'
---
= Add grid nodes to existing site or add new site
:icons: font
:imagesdir: ../media/

[.lead]
You can follow this procedure to add grid nodes to existing sites or to add a new site, but you cannot perform both types of expansion at the same time.

.What you'll need

* You have the Root access or Maintenance permission.
* All existing nodes in the grid are up and running across all sites.
* Any previous expansion, upgrade, decommissioning, or recovery procedures are complete.
+
NOTE: You are prevented from starting an expansion while another expansion, upgrade, recovery, or active decommission procedure is in progress. However, if necessary, you can pause a decommission procedure to start an expansion.

.Steps

. xref:updating-subnets-for-grid-network.adoc[Update subnets for Grid Network].
. xref:deploying-new-grid-nodes.adoc[Deploy new grid nodes].
. xref:performing-expansion.adoc[Perform expansion].
