---
permalink: expand/adding-storage-capacity-for-replicated-objects.html
sidebar: sidebar
keywords: replication, replicated, copies, capacity, storage nodes, expand, expansion
summary: 'If the information lifecycle management \(ILM\) policy for your deployment includes a rule that creates replicated copies of objects, you must consider how much storage to add and where to add the new storage volumes or Storage Nodes.'
---
= Add storage capacity for replicated objects
:icons: font
:imagesdir: ../media/

[.lead]
If the information lifecycle management (ILM) policy for your deployment includes a rule that creates replicated copies of objects, you must consider how much storage to add and where to add the new storage volumes or Storage Nodes. 

For guidance on where to add additional storage, examine the ILM rules that create replicated copies. If ILM rules create two or more object copies, plan to add storage in each location where object copies are made. As a simple example, if you have a two-site grid and an ILM rule that creates one object copy at each site, you must add storage to each site to increase the overall object capacity of the grid. See the instructions for xref:../ilm/index.adoc[managing objects with information lifecycle management].

For performance reasons, you should attempt to keep storage capacity and compute power balanced across sites. So, for this example, you should add the same number of Storage Nodes to each site or additional storage volumes at each site.

If you have a more complex ILM policy that includes rules that place objects in different locations based on criteria such as bucket name, or rules that change object locations over time, your analysis of where storage is required for the expansion will be similar, but more complex.

Charting how quickly overall storage capacity is being consumed can help you understand how much storage to add in the expansion, and when the additional storage space will be required. You can use the Grid Manager to monitor and chart storage capacity as described in the instructions for xref:../monitor/index.adoc[monitoring and troubleshooting StorageGRID].

When planning the timing of an expansion, remember to consider how long it might take to procure and install additional storage.
