---
permalink: expand/adding-grid-nodes-to-add-capabilities.html
sidebar: sidebar
keywords: grid nodes, expand, expansion, site, add
summary: 'You can add redundancy or additional capabilities to a StorageGRID system by adding new grid nodes to existing sites.'
---
= Add grid nodes to add capabilities to your system
:icons: font
:imagesdir: ../media/

[.lead]
You can add redundancy or additional capabilities to a StorageGRID system by adding new grid nodes to existing sites.

For example, you might choose to add additional Gateway Nodes to support the creation of High Availability groups of Gateway Nodes, or you might add an Admin Node at a remote site to permit monitoring using a local node.

You can add one or more of the following types of nodes to one or more existing sites in a single expansion operation:

* Non-primary Admin Nodes
* Storage Nodes
* Gateway Nodes
* Archive Nodes

When preparing to add grid nodes, be aware of the following limitations:

* The primary Admin Node is deployed during the initial installation. You cannot add a primary Admin Node during an expansion.
* You can add Storage Nodes and other types of nodes in the same expansion.
* When adding Storage Nodes, you must carefully plan the number and location of the new nodes. See xref:../expand/guidelines-for-adding-object-capacity.adoc[Guidelines for adding object capacity].
* If you are adding Archive Nodes, note that each Archive Node only supports tape through Tivoli Storage Manager (TSM) middleware.
* If the *New Node Client Network Default* option is set to *Untrusted* on the Untrusted Client Networks page, client applications that connect to expansion nodes using the Client Network must connect using a load balancer endpoint port (*CONFIGURATION* > *Network* > *Untrusted Client Networks*). See the instructions for xref:../admin/index.adoc[administering StorageGRID] to change the setting for the new node and to configure load balancer endpoints. 
