---
permalink: expand/adding-storage-capacity.html
sidebar: sidebar
keywords: storage, capacity, add, adding, expand, expansion, full storage node
summary: 'When existing Storage Nodes become full, you must increase the storage capacity of your StorageGRID system.'
---
= Add storage capacity
:icons: font
:imagesdir: ../media/

[.lead]
When existing Storage Nodes become full, you must increase the storage capacity of your StorageGRID system.

To increase storage capacity, you must first understand where data is stored currently and then add capacity in all required locations. For example, if you currently store copies of object data at several sites, you might need to increase the storage capacity of each site.

* xref:guidelines-for-adding-object-capacity.adoc[Guidelines for adding object capacity]
* xref:adding-storage-capacity-for-replicated-objects.adoc[Add storage capacity for replicated objects]
* xref:adding-storage-capacity-for-erasure-coded-objects.adoc[Add storage capacity for erasure-coded objects]
* xref:considerations-for-rebalancing-erasure-coded-data.adoc[Considerations for rebalancing erasure-coded data]
