---
permalink: expand/contacting-technical-support.html
sidebar: sidebar
keywords: contact technical support
summary: 'If you encounter errors during the grid expansion process that you are unable to resolve, or if a grid task fails, contact technical support.'
---
= Contact technical support
:icons: font
:imagesdir: ../media/

[.lead]
If you encounter errors during the grid expansion process that you are unable to resolve, or if a grid task fails, contact technical support.

.About this task

When you contact technical support, you must provide the required log files to assist in troubleshooting the errors you are encountering.

.Steps
. Connect to the expansion node that has experienced failures:
 .. Enter the following command:``ssh -p 8022 admin@_grid_node_IP_``
+
NOTE: Port 8022 is the SSH port of the base OS, while port 22 is the SSH port of the container engine running StorageGRID.

 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.

+
Once you are logged in as root, the prompt changes from `$` to `#`.
. Depending on the stage the installation reached, retrieve any of the following logs that are available on the grid node:
+
[cols="1a,2a" options="header"]

|===
| Platform| Logs
a|
VMware

a|
* `/var/log/daemon.log`
* `/var/log/storagegrid/daemon.log`
* `/var/log/storagegrid/nodes/<node-name>.log`

a|
Linux

a|
* `/var/log/storagegrid/daemon.log`
* `/etc/storagegrid/nodes/<node-name>.conf` (for each failed node)
* `/var/log/storagegrid/nodes/<node-name>.log` (for each failed node; might not exist)

+
|===
