---
permalink: expand/contacting_technical_support.html
sidebar: sidebar
keywords: 
summary: 'If you encounter errors during the grid expansion process that you are unable to resolve, or if a grid task fails, contact technical support.'
---
= Contacting technical support
:icons: font
:imagesdir: ../media/

[.lead]
If you encounter errors during the grid expansion process that you are unable to resolve, or if a grid task fails, contact technical support.

When you contact technical support, you must provide the required log files to assist in troubleshooting the errors you are encountering.

. Connect to the expansion node that has experienced failures:
 .. Enter the following command:``ssh -p 8022 admin@grid_node_IP``
+
NOTE: Port 8022 is the SSH port of the base OS, while port 22 is the SSH port of the Docker container running StorageGRID.

 .. Enter the password listed in the Passwords.txt file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the Passwords.txt file.

+
Once you are logged in as root, the prompt changes from `$` to `#`.
. Depending on the stage the installation reached, retrieve any of the following logs that are available on the grid node:
+
|===
| Platform| Logs
a|
VMware
a|

 ** /var/log/daemon.log
 ** /var/log/storagegrid/daemon.log
 ** /var/log/storagegrid/nodes/<node-name>.log

a|
Linux
a|

 ** /var/log/storagegrid/daemon.log
 ** /etc/storagegrid/nodes/<node-name>.conf (for each failed node)
 ** /var/log/storagegrid/nodes/<node-name>.log (for each failed node; might not exist)

+
|===
