---
permalink: expand/copying_audit_logs.html
sidebar: sidebar
keywords: copy audit log, Admin Node expansion,
summary: 'When you add a new Admin Node through an expansion procedure, its AMS service only logs events and actions that occur after it joins the system. You can copy audit logs from a previously installed Admin Node to the new expansion Admin Node so that it is in sync with the rest of the StorageGRID system.'
---
= Copy audit logs
:icons: font
:imagesdir: ../media/

[.lead]
When you add a new Admin Node through an expansion procedure, its AMS service only logs events and actions that occur after it joins the system. You can copy audit logs from a previously installed Admin Node to the new expansion Admin Node so that it is in sync with the rest of the StorageGRID system.

.What you'll need

* You must have completed the required expansion steps to add an Admin Node.
* You must have the `Passwords.txt` file.

.About this task

To make the historical audit messages from other Admin Nodes available on the expansion Admin Node, you must copy the audit log files manually from the primary Admin Node, or another existing Admin Node, to the expansion Admin Node.

.Steps

. Log in to the primary Admin Node:
 .. Enter the following command: `ssh _admin@_primary_Admin_Node_IP_`
 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.
+
When you are logged in as root, the prompt changes from `$` to `#`.
. Stop the AMS service to prevent it from creating a new file: `service ams stop`

. Rename the `audit.log` file to ensure that it does not overwrite the file on the expansion Admin Node you are copying it to:
+
`cd /var/local/audit/export` +
`ls -l` +
`mv audit.log _new_name_.txt`
. Copy all audit log files to the expansion Admin Node:
+
`scp -p * _IP_address_:/var/local/audit/export`

. If prompted for the passphrase for `/root/.ssh/id_rsa`, enter the SSH Access Password for the Primary Admin Node listed in the `Passwords.txt` file.

. Restore the original `audit.log` file:
+
`mv _new_name_.txt audit.log`

. Start the AMS service:
+
`service ams start`
. Log out from the server:
+
`exit`
. Log in to the expansion Admin Node:
 .. Enter the following command: `ssh admin@_expansion_Admin_Node_IP_`
 .. Enter the password listed in the `Passwords.txt` file.
 .. Enter the following command to switch to root: `su -`
 .. Enter the password listed in the `Passwords.txt` file.
+
When you are logged in as root, the prompt changes from `$` to `#`.
. Update the user and group settings for the audit log files:
+
`cd /var/local/audit/export` +
`chown ams-user:bycast *`

. Log out from the server:
+
`exit`
