---
permalink: expand/guidelines-for-adding-object-capacity.html
sidebar: sidebar
keywords: adding storage capacity, guidelines
summary: 'You can expand the object storage capacity of your StorageGRID system by adding storage volumes to existing Storage Nodes or by adding new Storage Nodes to existing sites. You must add storage capacity in a way that meets the requirements of your information lifecycle management \(ILM\) policy.'
---
= Guidelines for adding object capacity
:icons: font
:imagesdir: ../media/

[.lead]
You can expand the object storage capacity of your StorageGRID system by adding storage volumes to existing Storage Nodes or by adding new Storage Nodes to existing sites. You must add storage capacity in a way that meets the requirements of your information lifecycle management (ILM) policy.

== Guidelines for adding storage volumes

Before adding storage volumes to existing Storage Nodes, review the following guidelines and limitations:

* You must examine your current ILM rules to determine where and when to add storage volumes to increase the storage available for replicated or erasure-coded objects. See the instructions for managing objects with information lifecycle management.
* You cannot increase the metadata capacity of your system by adding storage volumes because object metadata is stored only on volume 0.
* Each software-based Storage Node can support a maximum of 16 storage volumes. If you need to add capacity beyond that, you must add new Storage Nodes.
* You can add one or two expansion shelves to each SG6060 appliance. Each expansion shelf adds 16 storage volumes. With both expansion shelves installed, the SG6060 can support a total of 48 storage volumes.
* You cannot add storage volumes to any other storage appliance.
* You cannot increase the size of an existing storage volume.
* You cannot add storage volumes to a Storage Node at the same time you are performing a system upgrade, recovery operation, or another expansion.

After you have decided to add storage volumes and have determined which Storage Nodes you must expand to satisfy your ILM policy, follow the instructions for your type of Storage Node:

* To add expansion shelves to an SG6060 storage appliance, see the instructions for SG6000 appliance installation and maintenance.
+
xref:../sg6000/index.adoc[SG6000 storage appliances]

* For a software-based node, follow the instructions for adding storage volumes to Storage Nodes.
+
xref:adding-storage-volumes-to-storage-nodes.adoc[Adding storage volumes to Storage Nodes]

== Guidelines for adding Storage Nodes

Before adding Storage Nodes to existing sites, review the following guidelines and limitations:

* You must examine your current ILM rules to determine where and when to add Storage Nodes to increase the storage available for replicated or erasure-coded objects.
* You should not add more than 10 Storage Nodes in a single expansion procedure.
* You can add Storage Nodes to more than one site in a single expansion procedure.
* You can add Storage Nodes and other types of nodes in a single expansion procedure.
* Before starting the expansion procedure, you must confirm that all data-repair operations performed as part of a recovery are complete. See the steps for checking data repair jobs in the recovery and maintenance instructions.
* If you need to remove Storage Nodes before or after performing an expansion, you should not decommission more than 10 Storage Nodes in a single Decommission Node procedure.

== Guidelines for the ADC service on Storage Nodes

When configuring the expansion, you must choose whether to include the Administrative Domain Controller (ADC) service on each new Storage Node. The ADC service keeps track of the location and availability of grid services.

* The StorageGRID system requires a quorum of ADC services to be available at each site and at all times.
+
NOTE: Learn about the ADC quorum in the recovery and maintenance instructions.

* At least three Storage Nodes at each site must include the ADC service.
* Adding the ADC service to every Storage Node is not recommended. Including too many ADC services can cause slowdowns due to the increased amount of communication between nodes.
* A single grid should not have more than 48 Storage Nodes with the ADC service. This is equivalent to 16 sites with three ADC services at each site.
* In general, when you select the *ADC Service* setting for a new node, you should select *Automatic*. Select *Yes* only if the new node will replace another Storage Node that includes the ADC service. Because you cannot decommission a Storage Node if too few ADC services would remain, this ensures that a new ADC service is available before the old service is removed.
* You cannot add the ADC service to a node after it is deployed.

*Related information*

xref:../ilm/index.adoc[Manage objects with ILM]

xref:../sg6000/index.adoc[SG6000 storage appliances]

xref:adding-storage-volumes-to-storage-nodes.adoc[Adding storage volumes to Storage Nodes]

xref:../maintain/index.adoc[Maintain & recover]

xref:performing-expansion.adoc[Performing the expansion]
