---
permalink: expand/index.html
sidebar: sidebar
keywords:
summary: 'Use these instructions to expand the capacity or capabilities of your StorageGRID system without interrupting system operations.'
---
= Expand your grid: Overview
:icons: font
:imagesdir: ../media/

[.lead]
Use these instructions to expand the capacity or capabilities of your StorageGRID system without interrupting system operations.

== About these instructions

These instructions describe how to perform a StorageGRID expansion to add storage volumes to Storage Nodes, new grid nodes to an existing site, or an entire new site. 

The number, type, and location of the nodes you will add depends on the reason for the expansion. For example, you might want to increase storage capacity, add metadata capacity, add redundancy or new capabilities, or add a new site. 

These instructions are for technical personnel who will be configuring and supporting a StorageGRID system after it has been installed.

== Before you begin

* You have a general understanding of the StorageGRID system. 
