---
permalink: expand/preparing-for-expansion.html
sidebar: sidebar
keywords: expand, expansion, planning
summary: 'You must prepare for the StorageGRID expansion by obtaining required materials and installing and configuring any new hardware and networks.'
---
= Prepare for an expansion
:icons: font
:imagesdir: ../media/

[.lead]
You must prepare for the StorageGRID expansion by obtaining required materials and installing and configuring any new hardware and networks.

== Gather required materials

Before you perform an expansion operation, you must gather the materials listed in the following table.

[cols="1a,2a" options="header"]
|===
| Item| Notes

|StorageGRID installation archive
|If you are adding new grid nodes or a new site, you must download and extract the StorageGRID installation archive. You must use the same version that is currently running on the grid.

For details, see the instructions for xref:downloading-and-extracting-storagegrid-installation-files.adoc[downloading and extracting the StorageGRID installation files].

*Note:* You do not need to download files if you are adding new storage volumes to existing Storage Nodes or installing a new StorageGRID appliance.

|Service laptop
|The service laptop must meet the following requirements:

* Network port
* SSH client (for example, PuTTY)
* xref:../admin/web-browser-requirements.adoc[Supported web browser]

|Provisioning passphrase
|The passphrase is created and documented when the StorageGRID system is first installed. The provisioning passphrase is not in the `Passwords.txt` file.

|StorageGRID documentation
|
* xref:../admin/index.adoc[Administer StorageGRID]
* xref:../release-notes/index.adoc[Release notes]
* Installation instructions for your platform
** xref:../rhel/index.adoc[Install Red Hat Enterprise Linux or CentOS]
** xref:../ubuntu/index.adoc[Install Ubuntu or Debian]
** xref:../vmware/index.adoc[Install VMware]

|Current documentation for your platform
|For supported versions, see the https://mysupport.netapp.com/matrix[Interoperability Matrix].

|===

== Download and extract the StorageGRID installation files

Before you can add new grid nodes or a new site, you must download the appropriate StorageGRID installation archive and extract the files.

.About this task

You must perform expansion operations using the version of StorageGRID that is currently running on the grid.

.Steps

. Go to the NetApp Downloads page for StorageGRID.
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads: StorageGRID^]

. Select the version of StorageGRID that is currently running on the grid.
. Sign in with the username and password for your NetApp account.
. Read the End User License Agreement, select the check box, and then select *Accept & Continue*.
. In the *Install StorageGRID* column of the download page, select the `.tgz` or `.zip` file for your platform.
+
The version shown in the installation archive file must match the version of the software that is currently installed.
+
Use the `.zip` file if you are running Windows on the service laptop.
+
[cols="1a,2a" options="header"]
|===
| Platform| Installation archive

|Red Hat Enterprise Linux or CentOS
m|
StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip

StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz

|Ubuntu or Debian and Appliance
m|
StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip

StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz

|VMware
m|
StorageGRID-Webscale-_version_-VMware-_uniqueID_.zip

StorageGRID-Webscale-_version_-VMware-_uniqueID_.tgz

|OpenStack/other Hypervisor
|To expand an existing deployment on OpenStack, you must deploy a virtual machine running one of the supported Linux distributions listed above and follow the appropriate instructions for Linux.

|===

. Download and extract the archive file.
. Follow the appropriate step for your platform to choose the files you need, based on your platform, planned grid topology, and how you will expand your StorageGRID system.
+
The paths listed in the step for each platform are relative to the top-level directory installed by the archive file.

. If you are expanding a Red Hat Enterprise Linux or CentOS system, select the appropriate files.
+

include::../_include/installation-files-rhel.adoc[]

. If you are expanding an Ubuntu or Debian system, select the appropriate files.
+
include::../_include/installation-files-ubuntu.adoc[]

. If you are expanding a VMware system, select the appropriate files.
+
include::../_include/installation-files-vmware.adoc[]

. If you are expanding a StorageGRID appliance-based system, select the appropriate files.
+
[cols="1a,1a" options="header"]
|===
| Path and file name| Description

m|./debs/storagegrid-webscale-images-version-SHA.deb
|
DEB package for installing the StorageGRID node images on your appliances.

m|./debs/storagegrid-webscale-images-version-SHA.deb.md5
|
Checksum of the DEB installation package used by the StorageGRID Appliance Installer to validate that the package is intact after upload.
|===
NOTE: For appliance installation, these files are only required if you need to avoid network traffic. The appliance can download the required files from the primary Admin Node.

== Verify hardware and networking

Before you begin the expansion of your StorageGRID system, you must ensure that you have installed and configured the necessary hardware to support the new grid nodes or new site.

For information about supported versions, see the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].

You must also verify network connectivity between servers at the site, and confirm that the primary Admin Node can communicate with all expansion servers that are intended to host the StorageGRID system.

If you are performing an expansion activity that includes adding a new subnet, you must xref:updating-subnets-for-grid-network.adoc[add the new Grid subnet] before you start the expansion procedure.

Do not use network address translation (NAT) on the Grid Network between grid nodes or between StorageGRID sites. When you use private IPv4 addresses for the Grid Network, those addresses must be directly routable from every grid node at every site. As required, however, you can use NAT between external clients and grid nodes, such as to provide a public IP address for a Gateway Node. Using NAT to bridge a public network segment is supported only when you employ a tunneling application that is transparent to all nodes in the grid, meaning the grid nodes require no knowledge of public IP addresses.



