---
permalink: expand/task_preparing_for_expansion.html
sidebar: sidebar
keywords: 
summary: ''
---
= Preparing for an expansion
:icons: font
:imagesdir: ../media/

[.lead]
You must prepare for the StorageGRID expansion by obtaining required materials and installing and configuring any new hardware and networks.

== Gathering required materials

[.lead]
Before you perform an expansion operation, you must gather the materials listed in the following table.

|===
| Item| Notes
a|
StorageGRID installation archive

a|
If you are adding new grid nodes or a new site, you must download and extract the StorageGRID installation archive. You must use the same version that is currently running on the grid. For details, see the instructions for downloading and extracting the StorageGRID installation files.

NOTE: You do not need to download files if you are adding new storage volumes to existing Storage Nodes or installing a new StorageGRID appliance.

a|
Service laptop
a|
The service laptop must meet the following requirements:

* Network port
* SSH client (for example, PuTTY)
* Supported browser

a|
Provisioning passphrase
a|
The passphrase is created and documented when the StorageGRID system is first installed. The provisioning passphrase is not in the Passwords.txt file.

a|
StorageGRID documentation
a|

* _Administering StorageGRID_
* _StorageGRID Release Notes_
* Installation instructions for your platform

a|
Current documentation for your platform
a|
For supported versions, see the Interoperability Matrix.

|===
*Related information*

link:task_preparing_for_expansion.md#[Web browser requirements]

link:task_preparing_for_expansion.md#[Downloading and extracting the StorageGRID installation files]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-admin/home.html[Administering StorageGRID]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-rn/home.html[StorageGRID release notes]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-install-vmw/home.html[VMware installation]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-install-rhel/home.html[Red Hat Enterprise Linux or CentOS installation]

http://docs.netapp.com/sgws-115/topic/com.netapp.doc.sg-install-ub/home.html[Ubuntu or Debian installation]

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

=== Web browser requirements

[.lead]
You must use a supported web browser.

|===
| Web browser| Minimum supported version
a|
Google Chrome
a|
87
a|
Microsoft Edge
a|
87
a|
Mozilla Firefox
a|
84
|===
You should set the browser window to a recommended width.

|===
| Browser width| Pixels
a|
Minimum
a|
1024
a|
Optimum
a|
1280
|===

== Downloading and extracting the StorageGRID installation files

[.lead]
Before you can add new grid nodes or a new site, you must download the appropriate StorageGRID installation archive and extract the files.

You must perform expansion operations using the version of StorageGRID that is currently running on the grid.

. Go to the NetApp Downloads page for StorageGRID.
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads: StorageGRID]

. Select the version of StorageGRID that is currently running on the grid.
. Sign in with the username and password for your NetApp account.
. Read the End User License Agreement, select the check box, and then select *Accept & Continue*.
. In the *Install StorageGRID* column of the download page, select the .tgz or .zip file for your platform.
+
The version shown in the installation archive file must match the version of the software that is currently installed.
+
Use the .zip file if you are running Windows on the service laptop.
+
|===
| Platform| Installation archive
a|
VMware
a|

 ** StorageGRID-Webscale-version-VMware-uniqueID.zip
 ** StorageGRID-Webscale-version-VMware-uniqueID.tgz

a|
Red Hat Enterprise Linux or CentOS
a|

 ** StorageGRID-Webscale-version-RPM-uniqueID.zip
 ** StorageGRID-Webscale-version-RPM-uniqueID.tgz

a|
    Ubuntu or Debian
+
and
+
Appliance
a|

 ** StorageGRID-Webscale-version-DEB-uniqueID.zip
 ** StorageGRID-Webscale-version-DEB-uniqueID.tgz

a|
OpenStack/other Hypervisor
a|
    To expand an existing deployment on OpenStack, you must deploy a virtual machine running one of the supported Linux distributions listed above and follow the appropriate instructions for Linux.
+
|===

. Download and extract the archive file.
. Follow the appropriate step for your platform to choose the files you need, based on your platform, planned grid topology, and how you will expand your StorageGRID system.
+
The paths listed in the step for each platform are relative to the top-level directory installed by the archive file.

. If you are expanding a VMware system, select the appropriate files.
+
|===
| Path and file name| Description
a|
./vsphere/README
a|
A text file that describes all of the files contained in the StorageGRID download file.
a|
./vsphere/NLF000000.txt
a|
A free license that does not provide any support entitlement for the product.
a|
./vsphere/NetApp-SG-version-SHA.vmdk
a|
The virtual machine disk file that is used as a template for creating grid node virtual machines.
a|
    ./vsphere/vsphere-primary-admin.ovf
+
./vsphere/vsphere-primary-admin.mf
a|
The Open Virtualization Format template file (.ovf) and manifest file (.mf) for deploying the primary Admin Node.
a|
    ./vsphere/vsphere-non-primary-admin.ovf
+
./vsphere/vsphere-non-primary-admin.mf
a|
The template file (.ovf) and manifest file (.mf) for deploying non-primary Admin Nodes.
a|
    ./vsphere/vsphere-archive.ovf
+
./vsphere/vsphere-archive.mf
a|
The template file (.ovf) and manifest file (.mf) for deploying Archive Nodes.
a|
    ./vsphere/vsphere-gateway.ovf
+
./vsphere/vsphere-gateway.mf
a|
The template file (.ovf) and manifest file (.mf) for deploying Gateway Nodes.
a|
    ./vsphere/vsphere-storage.ovf
+
./vsphere/vsphere-storage.mf
a|
The template file (.ovf) and manifest file (.mf) for deploying virtual machine-based Storage Nodes.
a|
*Deployment scripting tool*
a|
*Description*
a|
./vsphere/deploy-vsphere-ovftool.sh
a|
A Bash shell script used to automate the deployment of virtual grid nodes.
a|
./vsphere/deploy-vsphere-ovftool-sample.ini
a|
A sample configuration file for use with the deploy-vsphere-ovftool.sh script.
a|
./vsphere/configure-storagegrid.py
a|
A Python script used to automate the configuration of a StorageGRID system.
a|
./vsphere/configure-sga.py
a|
A Python script used to automate the configuration of StorageGRID appliances.
a|
./vsphere/storagegrid-ssoauth.py
a|
An example Python script that you can use to sign in to the Grid Management API when single sign-on is enabled.
a|
./vsphere/configure-storagegrid.sample.json
a|
A sample configuration file for use with the configure-storagegrid.py script.
a|
./vsphere/configure-storagegrid.blank.json
a|
A blank configuration file for use with the configure-storagegrid.py script.
|===

. If you are expanding a Red Hat Enterprise Linux or CentOS system, select the appropriate files.
+
|===
| Path and file name| Description
a|
./rpms/README
a|
A text file that describes all of the files contained in the StorageGRID download file.
a|
./rpms/NLF000000.txt
a|
A free license that does not provide any support entitlement for the product.
a|
./rpms/StorageGRID-Webscale-Images-version-SHA.rpm
a|
RPM package for installing the StorageGRID node images on your RHEL or CentOS hosts.
a|
./rpms/StorageGRID-Webscale-Service-version-SHA.rpm
a|
RPM package for installing the StorageGRID host service on your RHEL or CentOS hosts.
a|
*Deployment scripting tool*
a|
*Description*
a|
./rpms/configure-storagegrid.py
a|
A Python script used to automate the configuration of a StorageGRID system.
a|
./rpms/configure-sga.py
a|
A Python script used to automate the configuration of StorageGRID appliances.
a|
./rpms/configure-storagegrid.sample.json
a|
A sample configuration file for use with the configure-storagegrid.py script.
a|
./rpms/storagegrid-ssoauth.py
a|
An example Python script that you can use to sign in to the Grid Management API when single sign-on is enabled.
a|
./rpms/configure-storagegrid.blank.json
a|
A blank configuration file for use with the configure-storagegrid.py script.
a|
./rpms/extras/ansible
a|
Example Ansible role and playbook for configuring RHEL or CentOS hosts for StorageGRID container deployment. You can customize the role or playbook as necessary.
|===

. If you are expanding an Ubuntu or Debian system, select the appropriate files.
+
|===
| Path and file name| Description
a|
./debs/README
a|
A text file that describes all of the files contained in the StorageGRID download file.
a|
./debs/NLF000000.txt
a|
A non-production NetApp License File that you can use for testing and proof of concept deployments.
a|
./debs/storagegrid-webscale-images-version-SHA.deb
a|
DEB package for installing the StorageGRID node images on Ubuntu or Debian hosts.
a|
./debs/storagegrid-webscale-images-version-SHA.deb.md5
a|
MD5 checksum for the file /debs/storagegrid-webscale-images-version-SHA.deb.
a|
./debs/storagegrid-webscale-service-version-SHA.deb
a|
DEB package for installing the StorageGRID host service on Ubuntu or Debian hosts.
a|
*Deployment scripting tool*
a|
*Description*
a|
./debs/configure-storagegrid.py
a|
A Python script used to automate the configuration of a StorageGRID system.
a|
./debs/configure-sga.py
a|
A Python script used to automate the configuration of StorageGRID appliances.
a|
./debs/storagegrid-ssoauth.py
a|
An example Python script that you can use to sign in to the Grid Management API when single sign-on is enabled.
a|
./debs/configure-storagegrid.sample.json
a|
A sample configuration file for use with the configure-storagegrid.py script.
a|
./debs/configure-storagegrid.blank.json
a|
A blank configuration file for use with the configure-storagegrid.py script.
a|
./debs/extras/ansible
a|
Example Ansible role and playbook for configuring Ubuntu or Debian hosts for StorageGRID container deployment. You can customize the role or playbook as necessary.
|===

. If you are expanding a StorageGRID appliance-based system, select the appropriate files.
+
|===
| Path and file name| Description
a|
./debs/storagegrid-webscale-images-version-SHA.deb
a|
DEB package for installing the StorageGRID node images on your appliances.
a|
./debs/storagegrid-webscale-images-version-SHA.deb.md5
a|
Checksum of the DEB installation package used by the StorageGRID Appliance Installer to validate that the package is intact after upload.
|===
*Note:* For appliance installation, these files are only required if you need to avoid network traffic. The appliance can download the required files from the primary Admin Node.

== Verifying hardware and networking

[.lead]
Before you begin the expansion of your StorageGRID system, you must ensure that you have installed and configured the necessary hardware to support the new grid nodes or new site.

For information about supported versions, see the Interoperability Matrix.

You must also verify network connectivity between servers at the site, and confirm that the primary Admin Node can communicate with all expansion servers that are intended to host the StorageGRID system.

If you are performing an expansion activity that includes adding a new subnet, you must add the new Grid subnet before you start the expansion procedure.

Do not use network address translation (NAT) on the Grid Network between grid nodes or between StorageGRID sites. When you use private IPv4 addresses for the Grid Network, those addresses must be directly routable from every grid node at every site. As required, however, you can use NAT between external clients and grid nodes, such as to provide a public IP address for a Gateway Node. Using NAT to bridge a public network segment is supported only when you employ a tunneling application that is transparent to all nodes in the grid, meaning the grid nodes require no knowledge of public IP addresses.

*Related information*

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

xref:task_updating_subnets_for_the_grid_network.adoc[Updating subnets for the Grid Network]
