---
permalink: expand/vmware-adding-storage-volumes-to-storage-node.html
sidebar: sidebar
keywords: expand, expansion, storage node, add storage volumes, VMware
summary: 'If a Storage Node includes fewer than 16 storage volumes, you can increase its capacity by using VMware vSphere to add volumes.'
---
= VMware: Add storage volumes to Storage Node
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
If a Storage Node includes fewer than 16 storage volumes, you can increase its capacity by using VMware vSphere to add volumes.

.What you'll need
* You have access to the instructions for installing StorageGRID for VMware deployments.
** xref:../vmware/index.adoc[Install VMware]

* You have the `Passwords.txt` file.
* You have specific access permissions.

IMPORTANT: Do not attempt to add storage volumes to a Storage Node while a software upgrade, recovery procedure, or another expansion procedure is active.

.About this task

The Storage Node is unavailable for a brief time when you add storage volumes. You should perform this procedure on one Storage Node at a time to avoid impacting client-facing grid services.

.Steps

. If necessary, install new storage hardware and create new VMware datastores.
. Add one or more hard disks to the virtual machine for use as storage (object stores).
 .. Open VMware vSphere Client.
 .. Edit the virtual machine settings to add one or more additional hard disks.

+
The hard disks are typically configured as Virtual Machine Disks (VMDKs). VMDKs are more commonly used and are easier to manage, while RDMs may provide better performance for workloads that use larger object sizes (for example, greater than 100 MB). For more information about adding hard disks to virtual machines, see the VMware vSphere documentation.
. Restart the virtual machine by using the *Restart Guest OS* option in the VMware vSphere Client, or by entering the following command in an ssh session to the virtual machine:``sudo reboot``
+
NOTE: Do not use *Power Off* or *Reset* to restart the virtual machine.

. Configure the new storage for use by the Storage Node:
 .. Log in to the grid node:
  ... Enter the following command: `ssh admin@_grid_node_IP_`
  ... Enter the password listed in the `Passwords.txt` file.
  ... Enter the following command to switch to root: `su -`
  ... Enter the password listed in the `Passwords.txt` file.
When you are logged in as root, the prompt changes from `$` to `#`.
 .. Configure the new storage volumes:
+
`sudo add_rangedbs.rb`
+
This script finds any new storage volumes and prompts you to format them.

 .. Enter *y* to accept the formatting.
 .. If any of the volumes have previously been formatted, decide if you want to reformat them.
  *** Enter *y* to reformat.
  *** Enter *n* to skip reformatting.

 .. When asked, enter *y* to stop storage services.
+
The storage services are stopped, and the `setup_rangedbs.sh` script runs automatically. After the volumes are ready for use as rangedbs, the services start again.
. Check that the services start correctly:
 .. View a listing of the status of all services on the server:
+
`sudo storagegrid-status`
+
The status is updated automatically.

 .. Wait until all services are Running or Verified.
 .. Exit the status screen:
+
`Ctrl+C`
. Verify that the Storage Node is online:
 .. Sign in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
 .. Select *SUPPORT* > *Tools* > *Grid topology*.
 .. Select *_site_* > *_Storage Node_* > *LDR* > *Storage*.
 .. Select the *Configuration* tab and then the *Main* tab.
 .. If the *Storage State - Desired* drop-down list is set to Read-only or Offline, select *Online*.
 .. Select *Apply Changes*.
. To see the new object stores:
 .. Select *NODES* > *_site_* > *_Storage Node_* > *Storage*.
 .. View the details in the *Object Stores* table.

.Result
You can use the expanded capacity of the Storage Nodes to save object data.


