---
permalink: ilm/comparing_s3_object_lock_to_legacy_compliance.html
sidebar: sidebar
keywords:
summary: ''
---
= Comparing S3 Object Lock to legacy Compliance
:icons: font
:imagesdir: ../media/

[.lead]
The S3 Object Lock feature in StorageGRID 11.5 replaces the Compliance feature that was available in previous StorageGRID versions. Because the new S3 Object Lock feature conforms to Amazon S3 requirements, it deprecates the proprietary StorageGRID Compliance feature, which is now referred to as "`legacy Compliance.`"

If you previously enabled the global Compliance setting, the new global S3 Object Lock setting is enabled automatically when you upgrade to StorageGRID 11.5. Tenant users will no longer be able to create new buckets with Compliance enabled in StorageGRID 11.5; however, as required, tenant users can continue to use and manage any existing legacy Compliant buckets, which includes performing the following tasks:

* Ingesting new objects into an existing bucket that has legacy Compliance enabled.
* Increasing the retention period of an existing bucket that has legacy Compliance enabled.
* Changing the auto-delete setting for an existing bucket that has legacy Compliance enabled.
* Placing a legal hold on an existing bucket that has legacy Compliance enabled.
* Lifting a legal hold.

https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5[NetApp Knowledge Base: How to manage legacy Compliant buckets in StorageGRID 11.5^]

If you used the legacy Compliance feature in a previous version of StorageGRID, refer to the following table to learn how it compares to the S3 Object Lock feature in StorageGRID.

[cols="1a,1a,1a" options="header"]
|===
|  | S3 Object Lock (new)| Compliance (legacy)
a|
How is the feature enabled globally?
a|
From the Grid Manager, select *Configuration* > *System Settings* > *S3 Object Lock*.
a|
No longer supported.

*Note:* If you previously enabled the global Compliance setting,the global S3 Object Lock setting will be enabled automatically when you upgrade to StorageGRID 11.5.

a|
How is the feature enabled for a bucket?
a|
Users must enable S3 Object Lock when creating a new bucket using the Tenant Manager, the Tenant Management API, or the S3 REST API.
a|
Users can no longer create new buckets with Compliance enabled; however, they can continue to add new objects to existing Compliant buckets.
a|
Is bucket versioning supported?
a|
Yes. Bucket versioning is required and is enabled automatically when S3 Object Lock is enabled for the bucket.
a|
No. The legacy Compliance feature does not allow bucket versioning.
a|
How is object retention set?
a|
Users can set a retain-until-date for each object version.
a|
Users must set a retention period for the entire bucket. The retention period applies to all objects in the bucket.
a|
Can a bucket have default settings for retention and legal hold?
a|
No. StorageGRID buckets that have S3 Object Lock enabled do not have a default retention period. Instead, you can specify a retain-until-date for each object version.
a|
Yes
a|
Can the retention period be changed?
a|
The retain-until-date for an object version can be increased but never decreased.
a|
The bucket's retention period can be increased but never decreased.
a|
Where is legal hold controlled?
a|
Users can place a legal hold or lift a legal hold for any object version in the bucket.
a|
A legal hold is placed on the bucket and affects all objects in the bucket.
a|
When can objects be deleted?
a|
An object version can be deleted after the retain-until-date is reached, assuming the object is not under legal hold.
a|
An object can be deleted after the retention period expires, assuming the bucket is not under legal hold. Objects can be deleted automatically or manually.
a|
Is bucket lifecycle configuration supported?
a|
Yes
a|
No
|===
