---
permalink: ilm/configuring_erasure_coding_profiles.html
sidebar: sidebar
keywords: 
summary: 'You configure Erasure Coding profiles by associating a storage pool with an erasure-coding scheme, such as 6+3. Then, when you configure the placement instructions for an ILM rule, you can select the Erasure Coding profile. If an object matches the rule, data and parity fragments are created and distributed to the storage locations in the storage pool according to the erasure-coding scheme.'
---
= Configuring Erasure Coding profiles
:icons: font
:imagesdir: ../media/

[.lead]
You configure Erasure Coding profiles by associating a storage pool with an erasure-coding scheme, such as 6+3. Then, when you configure the placement instructions for an ILM rule, you can select the Erasure Coding profile. If an object matches the rule, data and parity fragments are created and distributed to the storage locations in the storage pool according to the erasure-coding scheme.

.Related information

xref:what_erasure_coding_schemes_are.adoc[What erasure-coding schemes are]

xref:configuring_storage_pools.adoc[Configuring storage pools]

xref:creating_ilm_rule.adoc[Creating an ILM rule]

xref:what_erasure_coding_is.adoc[What erasure coding is]

xref:advantages_disadvantages_of_ingest_options.adoc[Advantages, disadvantages, and limitations of the data-protection options]
