---
permalink: ilm/configuring-storage-pools.html
sidebar: sidebar
keywords: what is a storage pool, guidelines for storage pools
summary: 'When defining an ILM rule, you use storage pools to specify where objects are stored. Before creating a storage pool, you must review the storage pool guidelines.'
---
= Configuring storage pools
:icons: font
:imagesdir: ../media/

[.lead]
When defining an ILM rule, you use storage pools to specify where objects are stored. Before creating a storage pool, you must review the storage pool guidelines.

* xref:what-storage-pool-is.adoc[What a storage pool is]
* xref:guidelines-for-creating-storage-pools.adoc[Guidelines for creating storage pools]
* xref:using-multiple-storage-pools-for-cross-site-replication.adoc[Use multiple storage pools for cross-site replication]
* xref:using-storage-pool-as-temporary-location-deprecated.adoc[Use a storage pool as a temporary location (deprecated)]
* xref:creating-storage-pool.adoc[Create a storage pool]
* xref:viewing-storage-pool-details.adoc[View storage pool details]
* xref:editing-storage-pool.adoc[Edit a storage pool]
* xref:removing-storage-pool.adoc[Remove a storage pool]
