---
permalink: ilm/guidelines-for-creating-storage-pools.html
sidebar: sidebar
keywords: 
summary: 'When configuring and using storage pools, follow these guidelines.'
---
= Guidelines for creating storage pools
:icons: font
:imagesdir: ../media/

[.lead]
When configuring and using storage pools, follow these guidelines.

== Guidelines for all storage pools

* StorageGRID includes a default storage pool, All Storage Nodes, that uses the default site, All Sites, and the default storage grade, All Storage Nodes. The All Storage Nodes storage pool is automatically updated whenever you add new data center sites.
+
NOTE: Using the All Storage Nodes storage pool or the All Sites site is not recommended because these items are automatically updated to include any new sites you add in an expansion, which might not be the behavior you want. Before using the All Storage Nodes storage pool or the default site, carefully review the guidelines for replicated and erasure-coded copies.

* Keep storage pool configurations as simple as possible. Do not create more storage pools than necessary.
* Create storage pools with as many nodes as possible. Each storage pool should contain two or more nodes. A storage pool with insufficient nodes can cause ILM backlogs if a node becomes unavailable.
* Avoid creating or using storage pools that overlap (contain one or more of the same nodes). If storage pools overlap, more than one copy of object data might be saved on the same node.

== Guidelines for storage pools used for replicated copies

* Create a different storage pool for each site. Then, specify one or more site-specific storage pools in the placement instructions for each rule. Using a storage pool for each site ensures that replicated object copies are placed exactly where you expect (for example, one copy of every object at each site for site-loss protection).
* If you add a site in an expansion, create a new storage pool for the new site. Then, update ILM rules to control which objects are stored on the new site.
* In general, do not use the default storage pool, All Storage Nodes, or any storage pool that includes the default site, All Sites.

== Guidelines for storage pools used for erasure-coded copies

* You cannot use Archive Nodes for erasure-coded data.
* The number of Storage Nodes and sites contained in the storage pool determine which erasure-coding schemes are available.
* If a storage pool includes only two sites, you cannot use that storage pool for erasure coding. No erasure-coding schemes are available for a storage pool that has two sites.
* In general, do not use the default storage pool, All Storage Nodes, or any storage pool that includes the default site, All Sites in any Erasure Coding profile.
+
NOTE: If your grid includes only one site, you are prevented from using the All Storage Nodes storage pool or the All Sites default site in an Erasure Coding profile. This behavior prevents the Erasure Coding profile from becoming invalid if a second site is added.

* If you have high throughput requirements, creating a storage pool that includes multiple sites is not recommended if the network latency between sites is greater than 100 ms. As latency increases, the rate at which StorageGRID can create, place, and retrieve object fragments decreases sharply due to the decrease in TCP network throughput. The decrease in throughput affects the maximum achievable rates of object ingest and retrieval (when Strict or Balanced are selected as the Ingest Behavior) or could lead to ILM queue backlogs (when Dual Commit is selected as the Ingest Behavior).
* If possible, a storage pool should include more than the minimum number of Storage Nodes required for the erasure-coding scheme you select. For example, if you use a 6+3 erasure-coding scheme, you must have at least nine Storage Nodes. However, having at least one additional Storage Node per site is recommended.
* Distribute Storage Nodes across sites as evenly as possible. For example, to support a 6+3 erasure-coding scheme, configure a storage pool that includes at least three Storage Nodes at three sites.

== Guidelines for storage pools used for archived copies

* You cannot create a storage pool that includes both Storage Nodes and Archive Nodes. Archived copies require a storage pool that only includes Archive Nodes.
* When using a storage pool that includes Archive Nodes, you should also maintain at least one replicated or erasure-coded copy on a storage pool that includes Storage Nodes.
* If the global S3 Object Lock setting is enabled and you are creating a compliant ILM rule, you cannot use a storage pool that includes Archive Nodes. See the instructions for managing objects with S3 Object Lock.
* If an Archive Node's Target Type is Cloud Tiering - Simple Storage Service (S3), the Archive Node must be in its own storage pool. See the instructions for administering StorageGRID.

.Related information

xref:what-replication-is.adoc[What replication is]

xref:what-erasure-coding-is.adoc[What erasure coding is]

xref:what-erasure-coding-schemes-are.adoc[What erasure-coding schemes are]

xref:using-multiple-storage-pools-for-cross-site-replication.adoc[Using multiple storage pools for cross-site replication]

xref:using-storage-pool-as-temporary-location-deprecated.adoc[Using a storage pool as a temporary location (deprecated)]

xref:managing-objects-with-s3-object-lock.adoc[Managing objects with S3 Object Lock]

xref:../admin/index.adoc[Administer StorageGRID]
