---
permalink: ilm/how-objects-are-ingested.html
sidebar: sidebar
keywords: 
summary: 'StorageGRID protects objects during ingest either by performing synchronous placement or by performing dual commit, as specified in the ILM rule that matches the objects.'
---
= How objects are ingested
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID protects objects during ingest either by performing synchronous placement or by performing dual commit, as specified in the ILM rule that matches the objects.

When an S3 or Swift client stores an object to the grid, StorageGRID ingests the object using one of these two methods:

* *Synchronous placement*: StorageGRID immediately creates all object copies that are needed to meet ILM requirements. StorageGRID sends an "`ingest successful`" message to the client when all copies are created.
+
If StorageGRID cannot immediately create all object copies (for example, because a required location is temporarily unavailable), it either sends an "`ingest failed`" message to the client, or it falls back to creating interim object copies and evaluating ILM later, depending on the choice you made when you created the ILM rule.

* *Dual commit*: StorageGRID immediately creates two interim copies of the object, each on a different Storage Node, and sends an "`ingest successful`" message to the client. StorageGRID then queues the object for ILM evaluation.
+
When StorageGRID performs the ILM evaluation, it first checks to see if the interim copies satisfy the placement instructions in the ILM rule. For example, the two interim copies might satisfy the instructions in a two-copy ILM rule, but they would not satisfy the instructions in an erasure-coding rule. If the interim copies do not satisfy the ILM instructions, StorageGRID creates new object copies and deletes any interim copies that are not needed.
+
If StorageGRID cannot create two interim copies (for example, if a network issue prevents the second copy from being made), StorageGRID does not retry. Ingest fails.
+
NOTE: S3 or Swift clients can specify that StorageGRID create a single interim copy at ingest by specifying `REDUCED_REDUNDANCY` for the storage class. See the instructions for implementing an S3 or Swift client for more information.

By default, StorageGRID uses synchronous placement to protect objects during ingest.

.Related information

xref:data-protection-options-for-ingest.adoc[Data-protection options for ingest]

xref:../s3/index.adoc[Use S3]

xref:../swift/index.adoc[Use Swift]
