---
permalink: ilm/using-cloud-storage-pools.html
sidebar: sidebar
keywords:
summary: 'You can use Cloud Storage Pools to move StorageGRID objects to an external storage location, such as S3 Glacier or Microsoft Azure Blob storage. Moving objects outside of the grid lets you take advantage of a low-cost storage tier for long-term archive.'
---
= Using Cloud Storage Pools
:icons: font
:imagesdir: ../media/

[.lead]
You can use Cloud Storage Pools to move StorageGRID objects to an external storage location, such as S3 Glacier or Microsoft Azure Blob storage. Moving objects outside of the grid lets you take advantage of a low-cost storage tier for long-term archive.


* xref:what-cloud-storage-pool-is.adoc[What a Cloud Storage Pool is]
*  xref:lifecycle-of-cloud-storage-pool-object.adoc[Lifecycle of a Cloud Storage Pool object]
* xref:when-to-use-cloud-storage-pools.adoc[When to use Cloud Storage Pools]
* xref:considerations-for-cloud-storage-pools.adoc[Considerations for Cloud Storage Pools]
* xref:comparing-cloud-storage-pools-to-cloudmirror-replication.adoc[Comparing Cloud Storage Pools and CloudMirror replication]
* xref:creating-cloud-storage-pool.adoc[Creating a Cloud Storage Pool]
* xref:editing-cloud-storage-pool.adoc[Editing a Cloud Storage Pool]
* xref:removing-cloud-storage-pool.adoc[Removing a Cloud Storage Pool]
* xref:troubleshooting-cloud-storage-pools.adoc[Troubleshooting Cloud Storage Pools]
