---
permalink: ilm/using-last-access-time-in-ilm-rules.html
sidebar: sidebar
keywords:
summary: 'You can use Last Access Time as the reference time in an ILM rule. For example, you might want to leave objects that have been viewed in the last three months on local Storage Nodes, while moving objects that have not been viewed as recently to an off-site location. You can also use Last Access Time as an advanced filter if you want an ILM rule to apply only to objects that were last accessed on a specific date.'
---
= Using Last Access Time in ILM rules
:icons: font
:imagesdir: ../media/

[.lead]
You can use Last Access Time as the reference time in an ILM rule. For example, you might want to leave objects that have been viewed in the last three months on local Storage Nodes, while moving objects that have not been viewed as recently to an off-site location. You can also use Last Access Time as an advanced filter if you want an ILM rule to apply only to objects that were last accessed on a specific date.

.About this task

Before using Last Access Time in an ILM rule, review the following considerations:

* When using Last Access Time as a reference time, be aware that changing the Last Access Time for an object does not trigger an immediate ILM evaluation. Instead, the object's placements are assessed and the object is moved as required when background ILM evaluates the object. This could take two weeks or more after the object is accessed.
+
Take this latency into account when creating ILM rules based on Last Access Time and avoid placements that use short time periods (less than one month).

* When using Last Access Time as an advanced filter or as a reference time, you must enable last access time updates for S3 buckets. You can use the Tenant Manager or the Tenant Management API.
+
NOTE: Last access time updates are always enabled for Swift containers, but are disabled by default for S3 buckets.
+
IMPORTANT: Be aware that enabling last access time updates can reduce performance, especially in systems with small objects. The performance impact occurs because StorageGRID must update the objects with new timestamps every time the objects are retrieved.

The following table summarizes whether the Last Access Time is updated for all objects in the bucket for different types of requests.
[cols="1a,1a,1a" options="header"]
|===
| Type of request| Whether Last Access Time is updated when last access time updates are disabled| Whether Last Access Time is updated when last access time updates are enabled
a|
Request to retrieve an object, its access control list, or its metadata
a|
No
a|
Yes
a|
Request to update an object's metadata
a|
Yes
a|
Yes
a|
Request to copy an object from one bucket to another
a|

* No, for the source copy
* Yes, for the destination copy

a|

* Yes, for the source copy
* Yes, for the destination copy

a|
Request to complete a multipart upload
a|
Yes, for the assembled object
a|
Yes, for the assembled object
|===
.Related information

xref:../s3/index.adoc[Use S3]

xref:../tenant/index.adoc[Use a tenant account]
