---
permalink: fabricpool/creating-ha-group-for-fabricpool.html
sidebar: sidebar
keywords: fabricPool, high availability group, HA group, create, creating, virtual IP, VIP, preferred master, backup interface
summary: 'When configuring StorageGRID for use with FabricPool, you can optionally create one or more high availability \(HA\) groups. An HA group consists of one or more network interfaces on Admin Nodes, Gateway Nodes, or both.'
---
= Create a high availability (HA) group for FabricPool
:icons: font
:imagesdir: ../media/

[.lead]
When configuring StorageGRID for use with FabricPool, you can optionally create one or more high availability (HA) groups. An HA group consists of one or more network interfaces on Admin Nodes, Gateway Nodes, or both.

.What you'll need
* You are signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You have the Root Access permission.
* If you plan to use a VLAN, you have created the VLAN interface. See xref:../admin/configure-vlan-interfaces.adoc[Configure VLAN interfaces].

.About this task
Each HA group uses virtual IP addresses (VIPs) to provide highly available access to the shared services on the associated nodes.

For details about this task, see xref:../admin/managing-high-availability-groups.adoc[Manage high availability groups].

.Steps
. Select *CONFIGURATION* > *Network* > *High availability groups*.
. Select *Create*.
. Enter a unique name and optionally a description.
. Select one or more interfaces to add to this HA group.
+
Use the column headers to sort the rows, or enter a search term to locate interfaces more quickly.

. Determine the Primary interface and any backup interfaces for this HA group.
+
Drag and drop rows to change the values in the *Priority order* column.
+
The first interface in the list is the Primary interface. The Primary interface is the active interface unless a failure occurs.
+
If the HA group includes more than one interface and the active interface fails, the VIP addresses move to the first backup interface in the priority order. If that interface fails, the VIP addresses move to the next backup interface, and so on. When failures are resolved, the VIP addresses move back to highest priority interface available.

. Specify the VIP subnet in CIDR notation&#8212;an IPv4 address followed by a slash and the subnet length (0-32).
+
The network address must not have any host bits set. For example, `192.16.0.0/22`.

. Optionally, if the ONTAP IP addresses used to access StorageGRID are not on the same subnet as the StorageGRID VIP addresses, enter the StorageGRID VIP local gateway IP address. The local gateway IP address must be within the VIP subnet.

. Enter one or more virtual IP addresses for the HA group. You can add up to 10 IP addresses. All VIPs must be within the VIP subnet.
+
You must provide at least one IPv4 address. Optionally, you can specify additional IPv4 and IPv6 addresses.

. Select *Create HA group* and then select *Finish*.
