---
permalink: fabricpool/creating-ha-group-for-fabricpool.html
sidebar: sidebar
keywords: fabricPool, high availability group, HA group, create, creating, virtual IP, VIP, preferred master, backup interface
summary: 'When configuring StorageGRID for use with FabricPool, you can optionally create one or more high availability \(HA\) groups. An HA group consists of one or more network interfaces on Admin Nodes, Gateway Nodes, or both.'
---
= Create a high availability (HA) group for FabricPool
:icons: font
:imagesdir: ../media/

[.lead]
When configuring StorageGRID for use with FabricPool, you can optionally create one or more high availability (HA) groups. An HA group consists of one or more network interfaces on Admin Nodes, Gateway Nodes, or both.

.What you'll need
* You are signed in to the Grid Manager using a xref:../admin/web-browser-requirements.adoc[supported web browser].
* You have the Root Access permission.
* If you plan to use a VLAN, you have created the VLAN interface. See xref:../admin/configure-vlan-interfaces.adoc[Configure VLAN interfaces].

.About this task
Each HA group uses virtual IP addresses (VIPs) to provide highly available access to the shared services on the associated nodes.

For details about this task, see xref:../admin/managing-high-availability-groups.adoc[Manage high availability groups].

.Steps
. Select *CONFIGURATION* > *Network* > *High availability groups*.
. Select *Create*.
. Enter a unique name and optionally enter a description.
. Select one or more interfaces to add to this HA group.
+
Use the column headers to sort the rows, or enter a search term to locate interfaces more quickly.

. Determine the Primary interface and any Backup (failover) interfaces for this HA group.
+
Drag and drop rows to change the values in the *Failover order* column.
+
The first interface in the list is the Primary interface. The Primary interface is the active interface unless a failure occurs.
+
If the HA group includes more than one interface and the Primary interface fails, the VIP addresses move to the first Backup interface in the failover order. If that interface fails, the VIP addresses move to the next Backup interface, and so on.

. If the virtual IP addresses for this HA group are on a different subnet than the ones used by the FabricPool client, specify the gateway for the VIP subnet.
+
Enter the gateway using CIDR notation: an IPv4 address followed by a slash and the subnet length (0-32). For example, `192.16.2.1/22`.
+
The FabricPool client will use this gateway to access the virtual IP addresses.
+
NOTE: Do not specify the the broadcast or network address of the VIP subnet.

. Enter one or more virtual IP addresses for the HA group. You can add up to 10 IP addresses.
+
You must provide at least one IPv4 address. Optionally, you can specify additional IPv4 and IPv6 addresses.
+
NOTE: If you specified a value for *Gateway CIDR*, all VIPs must be in the same subnet as the gateway

. Select *Save* and then select *Finish*.
