---
permalink: fabricpool/example_ilm_policy_for_fabricpool_data.html
sidebar: sidebar
keywords: fabricPool, ilm, information lifecycle management, ILM policy, example
summary: 'Use this simple example policy as a starting point for your own ILM rules and policy.'
---
= Example ILM policy for FabricPool data
:icons: font
:imagesdir: ../media/

[.lead]
Use this simple example policy as a starting point for your own ILM rules and policy.

This example assumes you are designing the ILM rules and an ILM policy for a StorageGRID system that has four Storage Nodes at a single data center in Denver, Colorado. The FabricPool data in this example uses a bucket named `fabricpool-bucket`.

[CAUTION]
====
The following ILM rules and policy are only examples. There are many ways to configure ILM rules. Before activating a new policy, simulate the proposed policy to confirm it will work as intended to protect content from loss.

To learn more: xref:../ilm/index.adoc[Manage objects with ILM]
====

.Steps
. Create a storage pool named *DEN*. Select the Denver site.
. Create an Erasure Coding profile named *2 plus 1*. Select the 2+1 erasure-coding scheme and the *DEN* storage pool.
. Create an ILM rule that applies only to the data in `fabricpool-bucket`. This example rule creates erasure-coded copies.
+

[cols="1a,1a" options="header"]
|===
| Rule definition| Example value

|Rule Name
|2 plus 1 erasure coding for FabricPool data

|Bucket Name
|`fabricpool-bucket`

You could also filter on the FabricPool tenant account.

|Advanced Filtering
|Object Size (MB) greater than 0.2 MB.

*Note:* FabricPool only writes 4 MB objects, but you must add an Object Size filter because this rule uses erasure coding.

|Reference Time
|Ingest Time

|Placement
|From day 0 store forever

|Type
|Erasure coded

|Location
|DEN (2 plus 1)

|Ingest Behavior
|Balanced
|===

. Create an ILM rule that will create two replicated copies of any objects not matched by the first rule. Do not select a basic filter (tenant account or bucket name) or any advanced filters.
+

[cols="1a,1a" options="header"]
|===
| Rule definition| Example value
|
Rule Name
|
Two replicated copies
|
Bucket Name
|
_none_
|
Advanced Filtering
|
_none_
|
Reference Time
|
Ingest Time
|
Placement
|
From day 0 store forever
|
Type
|
Replicated
|
Location
|
DEN
|
Copies
|
2
|
Ingest Behavior
|
Balanced
|===

. Create a proposed ILM policy and select the two rules. Because the replication rule does not use any filters, it can be the default (last) rule for the policy.
. Ingest test objects into the grid.
. Simulate the policy with the test objects to verify the behavior.
. Activate the policy.

When this policy is activated, StorageGRID places object data as follows:

* The data tiered from FabricPool in `fabricpool-bucket` will be erasure coded using the 2+1 erasure-coding scheme. Two data fragments and one parity fragment will be placed on three different Storage Nodes.
* All objects in all other buckets will be replicated. Two copies will be created and placed on two different Storage Nodes.
* The erasure-coded and replicated copies will be maintained in StorageGRID until they are deleted by the S3 client. StorageGRID ILM will never delete these items.
