---
permalink: fabricpool/other-best-practices-for-storagegrid-and-fabricpool.html
sidebar: sidebar
keywords: fabricPool, best practices, encryption, compressions, tiering, AFF, consistency
summary: 'When configuring a StorageGRID system for use with FabricPool, you should avoid setting global options that might affect how your data is saved.'
---
= Other best practices for StorageGRID and FabricPool
:icons: font
:imagesdir: ../media/

[.lead]
When configuring a StorageGRID system for use with FabricPool, you should avoid setting global options that might affect how your data is saved.

== Object encryption

When configuring StorageGRID, you can optionally enable the global *Stored Object Encryption* setting if data encryption is required for other StorageGRID clients (*CONFIGURATION* > *System* > *Grid options*). The data that is tiered from FabricPool to StorageGRID is already encrypted, so enabling the StorageGRID setting is not required. Client-side encryption keys are owned by ONTAP.

== Object compression

When configuring StorageGRID, do not enable the global *Compress Stored Objects* setting (*CONFIGURATION* > *System* > *Grid options*). The data that is tiered from FabricPool to StorageGRID is already compressed. Enabling *Compress Stored Objects* will not further reduce an object's size.

== Consistency level

For FabricPool buckets, the recommended bucket consistency level is "`read-after-new-write.`" The "`available`" consistency level is not recommended. See xref:../tenant/changing-consistency-level.adoc[Change the consistency level].

== FabricPool tiering

If the StorageGRID node uses storage assigned from a NetApp AFF system, confirm that the volume does not have a FabricPool tiering policy enabled. For example, if a StorageGRID node is running on a VMware host, ensure the volume backing the datastore for the StorageGRID node does not have a FabricPool tiering policy enabled. Disabling FabricPool tiering for volumes used with StorageGRID nodes simplifies troubleshooting and storage operations.

IMPORTANT: Never use FabricPool to tier any data related to StorageGRID back to StorageGRID itself. Tiering StorageGRID data back to StorageGRID increases troubleshooting and operational complexity.
